Step1 - [1단계 - 인수 테스트 기반 리팩터링]
next-step/atdd-subway-service pull request #11
Opened 2021-01-02 15:45 UTC by jhhj424

안녕하세요! 이번 `인수 테스트 기반 ATDD` 미션을 통해 인사 드리게 된 신지호 입니다.

이번 첫 Step에서는 기존 코드에 대한 리팩터링을 진행했는데요, 이전 과제에서 진행했던 내용이랑 비슷한 점이 많아서 조금은 수월하게 할 수 있었던 것 같습니다. (저만의 착각 일지도..?) ㅎㅎ

먼저 인수 테스트 코드를 시나리오식으로 한벌 작성하고, 나머지는 분리하게 될 `Sections` 클래스에 대한 단위 테스트로 검증하였습니다.

이렇게 진행하다보니 `Sections` 의 내용이 좀 많아지긴 했는데.. 오히려 가독성 측면에서 더 악영향이 있을수도 있을까요??
기능들은 확실하게 몰아서 `Sections`에 위임했지만 이로인해 `Sections`만 너무 커지게 된 게 아닐까 하는 의문도 들었습니다.

---

이번 우테캠pro 과정을 진행하면 할수록 TC에 매력에 푹 빠지게 되네요, 이번 리팩터링 경험을 통해서 더 느꼈습니다.
믿을만한 TC가 있으니 기능 개발이나, 리팩터링에 부담이 전혀 없어지게 되더라구요 👍
아주 좋은 경험들을 하고있는 것 같습니다!!

어쨌든 주저리주저리 했는데.. 이번 미션도 잘 부탁드리고! 앞으로도 잘 부탁드리겠습니다 :)
새해 복 많이 받으시고, 올해에는 이루고 싶으신 모든 것들을 이루셨으면 좋겠습니다😁

2021-01-03 04:57 UTC, kang-hyungu requested changes
안녕하세요 지호님, 리뷰어 강현구입니다 👋 
1단계 미션 구현 잘 하셨어요 👍 
Sections가 조금 복잡한데 좀더 코드를 다듬어보면 좋을 것 같네요
관련해서 피드백 남겼으니 참고해서 수정해보시고 리뷰 재요청주세요
궁금한 점은 dm 주시거나 코멘트 남겨주세요

2021-01-03 04:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            if (!nextLineStation.isPresent()) {
객체지향 생활 체조
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.

2021-01-03 04:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Station findDownStation(Station downStation) {
addUpLineStation 메서드랑 거의 기능이 비슷하지 않나요?
중복을 제거할 방법 없을까요?

2021-01-03 04:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Station downStation = findUpStation();
메서드명은 UpStation인데 변수명은 downStation이네요
상행역을 찾는 메서드인데 하행역을 반환한건가요?
협업하는 개발자 입장에서는 코드를 다 파악해야 어떤 의도로 작성된 코드인지 알 수 있겠네요

2021-01-03 04:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (!stations.isEmpty() && stations.stream().noneMatch(it -> it == section.getUpStation()) &&
if 조건이 복잡합니다
stream을 private 메서드로 빼는게 좋겠네요

2021-01-03 13:51 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public List<StationResponse> ofStationResponse() {
앗..!! 그렇군요 ㅠㅠ 지켜지지 못했네요.. 너무 정신없이 코드를 작성한 듯 싶기도 합니다 :(

이 경우엔 해당 로직이 서비스에 있어도 괜찮은 정도인가요??

2021-01-03 13:57 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Line.java
>      public Line() {
Entity의 기본 생성자는 protected로 해서 최대한 숨겨라👍 해당 코드에서 놓쳤네요. 명심하겠습니다! :)

2021-01-03 14:43 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Line.java
>  public class Line extends BaseEntity {
이상하게도 getter를 끌어올리는 습관이 들어버렸나보네요 ㅠ :(
고치도록 노력하겠습니다!! getter는 아래로, 주요 기능을 위로! 

피드백 감사합니다👍

2021-01-03 15:05 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private Sections sections = new Sections();
혹시 현재 코드에서 -> `생성자에서 객체를 할당` 방식으로 변경시 이점들은 어떤 것들이 있을까요??! ㅠㅠ

2021-01-03 15:16 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (getSections().isEmpty()) {
1번에 대한 내용으로는 저는 항상 내부에서도 getter를 사용했었는데.. 좋은 방향은 아니었나보군요!! 

2번 내용은 제가 알지못했던 지식이라 새로이 배울 수 있었습니다.

피드백 감사합니다 :)

2021-01-03 15:29 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Station downStation = findUpStation();
그렇네요, 이해하는데 오히려 헷갈리게 명명이 된 듯 싶습니다. 전체적인 흐름이 보이도록 리팩터링 진행하겠습니다!!
감사합니다😁

2021-01-03 15:34 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (!stations.isEmpty() && stations.stream().noneMatch(it -> it == section.getUpStation()) &&
넵, 현재 코드는 가독성이 매우 좋지 못하네요, Stream 부분은 각각의 메서드로 기능이 드러나도록 명명해서 분리 진행하겠습니다!👍

2021-01-03 16:02 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            if (!nextLineStation.isPresent()) {
break 문을 걸려다 보니 2 단계의 들여쓰기가 되었네요 ㅠ 
해당 로직은 if() 에 따른 break 를 걸지 않으면서 비즈니스 요구사항을 만족하도록 변경하였습니다 :)

2021-01-03 16:03 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Station findDownStation(Station downStation) {
해당 로직은 변경하였고, 서로 다른 Station을 호출(up, down)하는 부분을 제외하고는 중복을 제거하였습니다 :)

2021-01-03 16:05 UTC, jhhj424 commented
ㅎㅎ 항상 제가 생각하기에는 괜찮아 보였던 코드도 리뷰를 받고나면 알게되는 실수 사항, 지켜지지 못한 원칙들이 많은 것 같네요😭
현구님의 피드백을 통해 한번 더 생각할 수 있었고, 다음에는 조금 더 생각하고 작성할 수 있겠네요👍

문의 사항은 DM으로 남겨뒀습니다!! 일단은 현구님의 피드백 사항에 맞춰서 리팩터링 진행하였고, PR 보내도록 하겠습니다 ㅎㅎ

앞으로도 꼼꼼한 리뷰 부탁드리겠습니다!! 감사합니다 :)

2021-01-03 17:20 UTC, jhhj424 commented
ㅎㅎ 항상 제가 생각하기에는 괜찮아 보였던 코드도 리뷰를 받고나면 알게되는 실수 사항, 지켜지지 못한 원칙들이 많은 것 같네요😭
현구님의 피드백을 통해 한번 더 생각할 수 있었고, 다음에는 조금 더 생각하고 작성할 수 있겠네요👍

문의 사항은 DM으로 남겨뒀습니다!! 일단은 현구님의 피드백 사항에 맞춰서 리팩터링 진행하였고, PR 보내도록 하겠습니다 ㅎㅎ

앞으로도 꼼꼼한 리뷰 부탁드리겠습니다!! 감사합니다 :)

2021-01-04 01:33 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public List<StationResponse> ofStationResponse() {
각 역할에 맞는 레이어로 분리만 하면 서비스나 dto에서 처리하나 문제 없어 보입니다

2021-01-04 01:34 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (getSections().isEmpty()) {
getter에 혹시라도 다른 로직이 추가되면 if절에 영향을 미칠 수 있으니 의도한 값을 직접 처리하는게 좋습니다

2021-01-04 01:36 UTC, kang-hyungu approved these changes
지호님 피드백 반영 잘 하셨어요 👏 
다음 단계 진행을 위해 pr은 머지 처리할게요
수고하셨습니다

2021-01-04 01:36 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        List<StationResponse> stations = StationResponse.ofStationResponses(persistLine.getStations());
클래스명이 StationResponse라서 of에 반복해서 적어줄 필요는 없어보이네요

2021-01-04 01:36 UTC, merged

2021-01-04 13:55 UTC, jhhj424 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        List<StationResponse> stations = StationResponse.ofStationResponses(persistLine.getStations());
List를 반환해서, StationResponse`s`라고 명명을 했는데, 괜찮은 부분이었나 보네요 :) ㅎㅎ
다음부터는 현구님의 피드백 사항 반영해서 작성해보겠습니다😊