[Step4] - 요금 조회 리뷰 요청드립니다.
next-step/atdd-subway-service pull request #13
Opened 2021-01-03 14:44 UTC by ccf05017

안녕하세요, 우아한테크캠프 Pro 수강생 조범진입니다 :)

4단계 요금 조회 구현 완료해서 리뷰 요청드립니다.
다음과 같은 방식으로 구현했습니다.
- 최단 경로상의 거리를 기반으로 거리 요금을 계산한다.
- 최단 경로상의 역 경로를 기반으로 각 역들이 어느 노선에 속해있는지 추적한다.
- 추적된 노선별로 환승 여부를 파악한다.
- 파악된 환승 노선들의 요금을 계산하고 거리 요금에 합산한다.
- 로그인한 사용자의 나이에 따른 할인 정책을 적용하고 최종 요금을 계산한다.

지금까지 미션 중 가장 어려운 미션이었던 것 같습니다 ㅜ
그 중에서도 환승 노선의 추가금을 부여하는 부분이 가장 어려웠습니다.
요구사항에는 없었지만, 예시를 만들던 중 아래 그림과 같은 상황이 발생하는 걸 확인하고 이를 해결하기 위한 로직이 좀 많아졌습니다.
![노선도질문](https://user-images.githubusercontent.com/30560659/103481269-409d4980-4e1d-11eb-8b94-e19d97b3fea1.jpg)

해당 부분에 대해서는 강의자인 `브라운`에게 질문을 드렸고, 구현하고 싶다면 구현해도 되지만 기존 과제 요구사항은 아니기 때문에 넘어가도 된다고 답변 받았습니다.
저는 이미 저걸 염두하고 설계를 하고 있어서... 결국 저 경로를 처리할 수 있도록 구현을 완료했습니다 ㅜㅜㅜㅜ
뭔가 괜한 삽을 판 것 같기도 하지만 개인적으로 좀 더 그래도 공부할 수 있는 기회가 된 것 같아 좋았습니다 :)

다만, 리뷰어님께서 저 부분 때문에 리뷰하시기 좀 복잡하실 수 있지 않을까 걱정이 되네요.. ㅜ
혹시 리뷰하시다가 '너무 이상한 코드다!'라거나 '이걸 도대체 왜 굳이 이렇게 한거지!' 싶은 부분 있다면 가감 없는 리뷰 부탁드립니다.
그 외에도 미숙한 부분에 대한 많은 피드백 부탁드립니다.

이번 미션도 잘 부탁드립니다 :) 감사합니다.

2021-01-04 03:27 UTC, seok-2-o requested changes
많은 고민을 해주신 만큼 매우 잘 구현해주셨네요. 💯 
구현에 있어서는 딱히 코멘트 드릴 부분이 없네요.
소소한 피드백과 질문 몇 가지 남겨놓았습니다 :)

해당 부분 확인하시고 수정 혹은 코멘트 달아주세요.

2021-01-04 03:27 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        List<Long> stationIds = getStations().stream().map(Station::getId).collect(Collectors.toList());
```suggestion
        List<Long> stationIds = getStations().stream()
        .map(Station::getId)
        .collect(Collectors.toList());
```

행위 단위로 내려쓰는것이 가독성 및 디버깅에 유리한점이 많은것 같아요.

2021-01-04 03:27 UTC, seok-2-o commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
> +                new LineRequest("신분당선", "bg-red-600", 강남역.getId(), 양재역.getId(), 10, BigDecimal.ZERO))
생략하면 ZERO  로 초기화하는건 어떤가요 ? 
빈번하게 발생할 수 있을 것 같아요.

2021-01-04 03:27 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        return discountPolicy.applyDiscount(fee);
요금정보가 객체로 민들어진다면 

할인혜택등의 정보를 담을 수 있을 것 같아요.

어떻게 생각하시나요 ?

2021-01-04 03:27 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        BigDecimal fee = distanceFee.add(transferFee);
shortestPath 에 조금 더 정보를 추가한다면 
shortestPath.getFee(loginMember) 와 같은꼴로 캡슐화 할 수 있을 것 같은데
어떻게 생각하시나요 ?

도메인이 아니라 서비스에서 계산 해야하는 이유가 꼭 있을까요 ? 🤔

2021-01-04 03:27 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/adapters/SafeLineAdapter.java
> +        return new LineOfStationInPaths(lineOfStationInPaths);
```suggestion
        return List<LineOfStationInPath> lineOfStationInPaths = stationIds.stream()
                .map(it -> parseLineToLineOfStationInPath(lines, it))
                .collect(collectingAndTehn(Collectors.toList(), LineOfStationInPaths::new));
```

2021-01-04 03:27 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/adapters/SafeLineAdapter.java
> +        return new LineOfStationInPath(lineWithExtraFees);
```suggestion
        return lines.stream()
                .filter(line -> line.isBelongedStation(stationId))
                .map(belongedLine -> new LineWithExtraFee(belongedLine.getId(), belongedLine.getExtraFee()))
                .collect(collectingAndTehn(Collectors.toList(), LineOfStationInPath::new))
```

2021-01-04 03:31 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/AgeDiscountPolicy.java
> +        BigDecimal discountConstantValue = fee.subtract(BigDecimal.valueOf(350));
마지막 부분에 급하게 끼워넣다가 리팩토링이 덜 됐네요 ㅜ 확인 감사합니다

2021-01-04 03:33 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/AgeDiscountPolicy.java
> +        return AgeDiscountPolicy.NONE;
저도 이 부분은 switch case가 더 낫다고 생각합니다 ㅎㅎ
다만, 저도 switch case를 가능한 안쓰려고 해서 이렇게 표현했습니다.

2021-01-04 03:35 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private BigDecimal extraFee;
음.. 일단 아래 코멘트 주신 노선 생성 시 노선 환승 추가요금이 null인 경우의 기본값 필요 코멘트와 연결하면 두가지 장점이 있을 것 같습니다.
- 음수로 노선 환승 추가금을 생성할 수 없도록 안전하게 포장
- 노선 환승 요금이 null인 요청을 받았을 경우 기본적으로 BigDecimal.ZERO로 리턴해서 생성

이것만으로도 장점이 꾀 있는 것 같습니다 ㅎㅎ 피드백 반영 진행하겠습니다.

2021-01-04 03:36 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/SuperLongDistanceFee.java
> +    private static final BigDecimal DEFAULT_FEE = BigDecimal.valueOf(2050);
으... 이 부분이 확실히 오해의 소지가 많은 숫자네요 ㅜ

LongDistanceFee는 50km까지만 계산하기 때문에 SuperLongDistance부터는 LongDistanceFee의 최대값을 기본을 깔고 간다는 의미로 계산했습니다. 요 매직넘버를 상수로 추출하거나 매직넘버 계산 과정을 메서드로 좀 더 의미있게 추출해서 가독성 높여보겠습니다.

2021-01-04 03:37 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DefaultDistanceFee.java
> +        return BigDecimal.valueOf(1250L);
이번에 매직넘버가 많네요 ㅜ 수정 진행하겠습니다.

2021-01-04 03:38 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
ㅎㅎ.. 과제여서 좀 더 다양한 방법을 연습해보고 싶었습니다.

말씀주신대로 AgeDiscountPolicy처럼 ENUM으로 추상화시키는 게 훨씬 응집도 높게 코드 표현이 가능하고 코드양 자체도 훨씬 적을 것 같습니다. 피드백 반영 진행하겠습니다.

2021-01-04 03:38 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        List<Long> stationIds = getStations().stream().map(Station::getId).collect(Collectors.toList());
으... 죄송합니다 급하게 막 쓰면서 놓친 부분이 되게 많네요 ㅜ 수정 진행하겠습니다.

2021-01-04 03:39 UTC, ccf05017 commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
> +                new LineRequest("신분당선", "bg-red-600", 강남역.getId(), 양재역.getId(), 10, BigDecimal.ZERO))
위의 노선의 extraFee를 래핑하는 과정에서 함께 처리하겠습니다.

2021-01-04 03:40 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        return discountPolicy.applyDiscount(fee);
오... 발견못햇던 오브젝트네요. 말씀주신 방법대로 하면 가독성이 많이 올라갈 것 같습니다.

도메인 서비스에서 도메인 로직이 좀 늘어지고 있는 느낌이었는데 이걸 정리해주는 역할도 만들어줄 수 있을 것 같아요 ㅎㅎ

2021-01-04 03:43 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        BigDecimal fee = distanceFee.add(transferFee);
요 부분은 도메인 서비스를 염두에 두고 만들었습니다.

제가 알고있는 도메인 서비스의 정의는 `두가지의 Aggregate가 모여서 도메인 로직을 진행하는 경우`였습니다.
현재 DDD가 아니지만, 혼자 나름 긋고 있던 선은 Path / Line을 서로 다른 도메인의 Aggregate Root로 염두하고 있었습니다. 이 때문에 Path, Line이 모여서 진행되는 도메인 로직인 Fee 계산은 `도메인 서비스에서 진행되야 되지 않나`라고 생각해서 이렇게 구현했습니다 ㅎㅎ

제가 도메인 서비스에 대해 잘못 이해하고 있거나, 다른 의견이 있으시다면 추가적인 피드백 부탁드립니다 :D

P.S. 생각해보니 제가 말씀드린 기준대로라면 ShortestPath를 계산하는 부분도 도메인 서비스로 빠져야 될 것 같네요 ㅎㅎ.. 일단 이 부분도 도메인 서비스로 추출해서 리팩토링 진행한 버전으로 피드백 반영 진행하겠습니다. 보시고 이상하면 추가적인 코멘트 부탁드립니다.

2021-01-04 03:44 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/adapters/SafeLineAdapter.java
> +        return new LineOfStationInPath(lineWithExtraFees);
이렇게 쓸 수 있네요.. 피드백 감사합니다 ㅎㅎ

2021-01-04 12:18 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/AgeDiscountPolicy.java
> +        return AgeDiscountPolicy.NONE;
이 부분은 리팩토링 중 case 구문 숫자가 여러개 들어가는 게 더 가독성이 떨어지는 것 같아서 메서드 추출로 해결했습니다.

2021-01-04 12:47 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
음..... 이 부분은 Enum으로 리팩토링을 진행하던 중이었는데 약간 애매한 부분이 있어서 보류했습니다.

Enum으로 구현하게 될 경우 알맞는 오브젝트를 찾기 위해 find 메서드에 distance를 전달하고,
해당 오브젝트 정책에 기반해서 최종적인 요금을 구할 때(calculate 메서드 사용) 다시 똑같은 distance를 넘겨야 구현이 되더라구요.

구현하면서 뭔가 같은 값을 여러번 다른 메서드에 전달하는 게 어색하기도 하고 오히려 해당 값 자체가 포장되야되는 상황이 아닌가 하는 생각이 들었습니다. 그래서 일단 지금 형태로 유지하려 합니다.

리뷰어님께서는 어떻게 생각하시는지 의견 한번 더 들려주시면 감사하겠습니다!

구현하던 코드 중 일부는 다음과 같습니다
```java
public static DistanceFee2 find(final Integer distance) {
        if (isDefault(distance)) {
            return DEFAULT;
        }
        if (isLong(distance)) {
            return LONG_DISTANCE;
        }
        if (isSuperLong(distance)) {
            return SUPER_LONG_DISTANCE;
        }
        throw new InvalidFeeDistanceException("유효하지 않은 거리입니다.");
    }

    public BigDecimal calculate(Integer distance) {
        if (needExtraFee) {
            // 이 부분 계산을 위해 오브젝트를 찾을 때 사용한 distance를 똑같이 해당 메서드에 다시 넘겨줘야 하는 것 같습니다.
            // Enum의 경우 상수 오브젝트의 개념이라 이런 식으로 값을 여러번 전달하지 않고 전달해둘 방법이 생각 안나네요 ㅜ 
            Integer fee = (int) (Math.ceil((distance - MIN_DISTANCE - 1) / 5) + 1) * 100;
            return DEFAULT_FEE.add(BigDecimal.valueOf(fee));
        }
        return DEFAULT_FEE;
    }
```

2021-01-04 13:48 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/SuperLongDistanceFee.java
> +    private static final BigDecimal DEFAULT_FEE = BigDecimal.valueOf(2050);
46~50km 의 운임이군요 2050 이군요.
LongDistanceFee 를 활용해보는건 어떻게 생각하시나요 ㅎㅎ?

요금 정책이 바뀌었을때  쉽게 대처할 수 있을 것 같아요

LongDistanceFee 는 DefaultDistanceFee를 이용할수도 있겠네요.

2021-01-04 13:51 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        BigDecimal fee = distanceFee.add(transferFee);
해당 부분에 대한 리팩토링을 진행하면서 코드양이 꾀 많이 늘어난다는 걸 느꼈고 '이걸 할만큼 가치가 있을까?'에 대해서 다시한번 생각해봤습니다.

그러면서 '왜 Aggregate 루트 여러개를 도메인 서비스에서 묶어서 처리할까?'에 대해 고민해봤습니다. 제가 나름대로 내린 결론은 '도메인 로직이 서비스에 지나치게 드러나는 걸 방지하기 위해'라고 생각했습니다.
이런 관점에서 볼 때 현재 ShortestPath라는 도메인을 추상화한 오브젝트가 있는 상태에서 굳이 도메인 서비스를 따로 빼면서까지 계산이 복잡해질 필요가 없지 않나 생각이 들더라구요 ㅎㅎ

그래서 결국 리뷰어님께서 제안주신 대로 도메인 서비스를 없애고 ShortestPath에서 기존 FeeCalculatorService의 역할을 일부 수행하도록 리팩토링을 진행했습니다.

이 형태로 가면 ShortestPath 안에 도메인 로직을 넣고 서비스 레이어에서는 도메인에 필요한 정보를 Adapter를 통해 다른 도메인에서 불러와서 주입해주는 형태로 각 레이어의 역할을 크게 해치지 않고 수행이 가능한 것 같습니다 :)

2021-01-04 13:52 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
```
    public static BigDecimal calculate(Integer distance) {
        return find(distnace).expression.apply(distnace);
    }
```

위처럼 구현 하면 안될까요?

2021-01-04 13:53 UTC, ccf05017 commented
리뷰어님 덕분에 Stream의 새로운 사용법을 익히는 등의 기술적인 부분부터 DDD의 사용 목적에 대해 다시 생각해보는 좋은 시간을 보낼 수 있었습니다 :)

리뷰주신 내용 나름대로 반영 진행해봤습니다. 보시고 부족한 부분 있으면 다시 피드백 부탁드립니다! 감사합니다 ㅎㅎ

2021-01-04 14:58 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요 👍 

코멘트 달아주신부분에 제가 생각하는 코드 남겨 놓았으니 확인 부탁드릴게요.

미션내내 너무 잘해주셔서 많은 이야기를 못해본 것 같아 아쉽습니다. 
1~3 스탭 미션도 오늘 같았으면 정말 좋을 것 같다는 아쉬움이 남네요.

그런 의미에서 미션은 종료되었지만 앞으로도 궁금한점이나 어려운점 있다면 편하게 연락주세요.

다음 미션도 꼭 좋은 모습으로 완주하시기라 믿습니다.🔥
감사합니다.

2021-01-04 14:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
음 저렇게 색깔 있는 코드는 어떻게 넣는건가요 ?-?
제가 enum 으로 구현한 요금 계산기는

```
    enum BillingStrategy {
        SHORT (distance -> 1250),
        MEDIUM(distance ->
                SHORT.expression.apply(Constants.SHORT_MAX_DISTANCE)
                + (int) (Math.ceil((distance - Constants.SHORT_MAX_DISTANCE - 1) / 5) + 1) * 100),
        LONG(distance ->
                MEDIUM.expression.apply(Constants.MEDIUM_MAX_DISTANCE)
                + (int) (Math.ceil((distance - Constants.MEDIUM_MAX_DISTANCE - 1) / 8) + 1) * 100);


        private static class Constants {
            public static final int SHORT_MAX_DISTANCE = 10;
            public static final int MEDIUM_MAX_DISTANCE = 50;
        }

        private final Function<Integer, Integer> expression;

        BillingStrategy(Function<Integer, Integer> expression) {
            this.expression = expression;
        }

        public static int calculate(int age) {
            return find(age).expression.apply(age);
        }

        private static  BillingStrategy find(int age) {
            if(age <= Constants.SHORT_MAX_DISTANCE) {
                return SHORT;
            }
            if(age <= Constants.MEDIUM_MAX_DISTANCE) {
                return MEDIUM;
            }
            return LONG;
        }
    }
```

위와 같은 느낌입니다.

2021-01-04 14:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
하다보니까...
```
    public int calculate(int distance) {
        int fee = 1250;
        if((distance -= 10)> 0) {
            fee += (int) (Math.ceil((distance - 1) / 5) + 1) * 100;
        }
        if((distance -= 40)> 0) {
            fee +=  (int) (Math.ceil((distance - 1) / 8) + 1) * 100;
        }
        return fee;
    }
```

위처럼 하고싶은 충동도 느끼네요.

2021-01-04 14:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        BigDecimal totalFee = distanceFee.add(transferFee);
이친구들은 Fee를 사용하지 않을 이유가 있을까요?

2021-01-04 14:59 UTC, merged

2021-01-05 00:36 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/SuperLongDistanceFee.java
> +    private static final BigDecimal DEFAULT_FEE = BigDecimal.valueOf(2050);
음..? 그러네요.. 이미 잘 계산된 오브젝트가 있는데 이걸 활용하는 게 가독성이나 코드 중복 제거로 보나 두 방면 모두로 이득일 거 같습니다.

2021-01-05 00:40 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
오.. 제가 너무 메서드 역할을 잘게 쪼개서만 생각했던 것 같네요 ㅎㅎ

이 부분에서 정확히 원하는 건 결국 거리에 따라 '요금'이 계산되는 걸 원하니까 찾는 동작을 따로 빼지 않고 계산의 중간과정으로 찾은 뒤 계산하도록 구현하면 Enum으로 구현하고 가독성도 높일 수 있는 것 같습니다.

두번째 제안 주신 코드는 완전 깔끔하게 구현 가능하네요 ㅎㅎㅎㅎ.. 하지만 지극히 개인적인 이유로 저렇게 코드에 수식이 많으면 제 머리로 나중에 다시 코드 봤을 때 이해하는데 한참 걸리더라구요 -_-;; '어 이거 왜 이렇게 짰지.....'하면서 한참 고민해서 개인적으로 수식을 메서드로 빼서 의미를 어느정도 추론 가능하게 넣는 형태의 코드를 선호합니다 ㅎㅎ 이건 그냥 제 능력의 한계상 나타나는 선호 스타일입니다 ㅜ 저도 저렇게 짧고 간단한 코드로 명확하게 개발할 수 있도록 노력해 보겠습니다 ㅎㅎ

2021-01-05 00:43 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/fee/distanceFee/DistanceFeeSelector.java
> +public class DistanceFeeSelector {
아 그리고 말씀주신 색 들어가는 부분은 그 코드 블록 넣는 그 기호 뭐라고 하는지 이름이 기억이 안나네요 ㅎㅎㅎㅎ..
그 옆에 사용하실 언어명을 적어주시면 해당 언어의 문법에 따라 색을 넣어주더라구요 ㅎㅎ
예를 들면
```
  // ```java
  // {내용}
  // ```
```  
요런 식으로 써주시면 됩니당 ㅎㅎ 웬만큼 잘 알려진 언어는 다 지원되는 것 같더라구요. 무엇보다 json도 표현됩니다! ㅎ.ㅎ

2021-01-05 00:48 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/AgeDiscountPolicy.java
> +    private static final BigDecimal DEFAULT_DISCOUNT_FEE = BigDecimal.valueOf(350);
분명 권장받은 일은 '영어 사전과 유의어 사전을 찾아보면서 정확한 변수명을 지어라'이지만.......
이렇게 변수명을 지으면 나중에 제가 제 코드 보면서 영어사전 찾을 때가 생기더라구요 ㅋㅋㅋㅋㅋ
그래서 콩글리시를 선호하긴합니다 ㅎㅎㅎ..

사실 말씀주신 저 변수명도 의미를 생각했다기보단 정말 말 그대로 `기본할인금액`을 영어로 옮긴 형태입니다 ㅎㅎ
하지만 이건 제가 만들었으니까 알아보는거지 처음보는 분 입장에선 일종의 넌센스로 보일 수 있을것 같네요.

저 외에 다른 사람도 읽고 쓰는 코드라 생각해야 하고 그런 관점에서 볼 땐 제가 불편해도 정확한 단어로 써야 저 외의 다른 팀원들도 영어사전을 찾고 정확한 뜻으로 코드를 읽을 수 있지 않나 생각이 듭니다 ㅎㅎ 오늘부터 영어사전 다시 열심히 찾아야 될 거 같아요 ㅎㅎ

2021-01-05 00:49 UTC, ccf05017 commented on src/main/java/nextstep/subway/path/domain/FeeCalculatorService.java
> +        BigDecimal totalFee = distanceFee.add(transferFee);
요거슨..... 급하게 하다가 빼먹었네요 ㅜㅜㅜㅜㅜㅜ

굉장히 덤벙거리는 성격이라 조심한다고 조심하는데도 자꾸 이런 디테일한 부분을 놓칩니다 ㅜ
조언 감사드립니다! ㅎㅎ