🚀 1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #162
Opened 2021-06-20 19:35 UTC by mskangg

안녕하세요! 리뷰어님 :)
인수 테스트 기반 TDD 미션을 진행할 강민수 라고 합니다. 😁

이번 미션엔 Outside In 방식을 사용하여 UI -> Service -> Domain 순으로 테스트 코드를 작성하여 리팩토링을 진행했습니다!
도메인 객체를 리팩토링 할 때에는 Inside Out 방식을 사용하여 예외 케이스까지 리팩토링하였습니다.
확실히 인수테스트를 통합하여 관리하니 비즈니스 흐름이 한눈에 보이는 것 같아 장점이 많아보였습니다.
기존 코드는 중복되는 테스트도 많았고 오히려 비즈니스를 이해하기 힘든 부분도 있었는데 통합하여 관리하다보니 흐름을 이해할 수 있는 인수테스트가 되어 깔끔해진 것 같아요 😁
그리고 테스트코드로 방어하고 리펙터링을 진행해보니 테스트코드는 역시 필수라는 것을 다시 한번 상기시키게 된 미션이었습니다 :)

그럼 리뷰 부탁드립니다.
감사합니다 😁

2021-06-21 14:12 UTC, tearight approved these changes
안녕하세요, 이번 미션을 함께 진행하게 된 리뷰어 한수빈입니다.
코멘트 남겼으니 확인 부탁드립니다.

2021-06-21 14:12 UTC, tearight commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +    @DisplayName("지하철 노선을 관리")
전체적인 시나리오 테스트를 작성해주셨네요.👍

2021-06-21 14:12 UTC, tearight commented on src/test/java/nextstep/subway/line/application/LineCommandServiceTest.java
> +    private LineRepository lineRepository;
나중에 응용서비스에 대한 테스트를 작성하실 때 통합테스트로도 작성해보시는걸 추천드립니다.
응용 계층은 구조상 구현된 인프라가 모이는 곳이라 통합테스트가 가능한 영역입니다.
인수테스트, Controller 테스트는 API 응답에 대해 집중적으로 본다면, 응용서비스는 return 이외에도 내부적인 동작을 볼 수 있는 곳이지요. 가장 큰 예로는 캐시저장소와 DB 저장소에 동시에 저장하는 경우 캐시 저장소에 저장이 되었는지도 검증할 수 있겠네요.

2021-06-21 14:12 UTC, tearight commented on src/test/java/nextstep/subway/line/application/LineCommandServiceTest.java
> +    private LineRepository lineRepository;
응용서비스는 로직보다는 도메인과 인프라의 조합의 경우가 많기 때문에 통합테스트가 더 넓은 커버리지를 가집니다.

2021-06-21 14:13 UTC, tearight requested changes
안녕하세요, 이번 미션을 함께 진행하게 된 리뷰어 한수빈입니다.
코멘트 남겼으니 확인 부탁드립니다.

2021-06-21 18:21 UTC, mskangg commented on src/main/java/nextstep/subway/line/application/LineCommandService.java
> +        persistLine.update(lineUpdateRequest.toLine());
음.. 미션의 요구사항인 `비즈니스 로직을 도메인 객체로 이관한다`에 집중해서 내부 로직에 대해 소홀히하였네요..!
말씀해주신 코드 봐보니 쓸데없는 객체를 생성하여 넘겨주고있네요.. 영속화된 엔티티의 값을 수정함에 있어 객체를 생성할 필욘 없는데 말이죠..
수정완료했습니다. 😁

2021-06-21 18:31 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    private int distance;
현재 소속된 팀에선 `@Column name`을 추가하는 필드는 변수명과 다를시에만 추가하게 하고있습니다.
이렇게 하는 이유는 엔티티에 과도한 에노테이션을 달게되면 엔티티 클래스의 비즈니스 코드의 집중도를 떨어뜨리기도 하고 변수명과 다른 필드를 가진 곳에만 `@Column`을 달게되면 한눈에 볼 수 있는 장점이 있기 때문입니다.
그럼에도 전체적으로 `@Column` 을 다는 패턴을 사용하면 멤버 필드를 변경함에 있어 보다 자유롭게 진행할 수 있는 장점이 있기에 서로 장단이 있다고 생각합니다.
그런데 지금 @Column을 붙이고 아무행위도 하지 않았네요..
수정하겠습니다. 😅

2021-06-21 18:51 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    private int distance;
현재 소속된 팀에선 `@Column name`을 추가하는 필드는 변수명과 다를시에만 추가하게 하고있습니다.
이렇게 하는 이유는 엔티티에 과도한 에노테이션을 달게되면 엔티티 클래스의 비즈니스 코드의 집중도를 떨어뜨리기도 하고 변수명과 다른 필드를 가진 곳에만 `@Column`을 달게되면 한눈에 볼 수 있는 장점이 있기 때문입니다.
그럼에도 전체적으로 `@Column` 을 다는 패턴을 사용하면 멤버 필드의 변수명을 변경함에 있어 보다 자유롭게 진행할 수 있는 장점이 있기에 서로 장단이 있다고 생각합니다.
그런데 지금 밸류타입의 필드접근방식을 사용하기 위해 `@Column`을 붙이고는 아무 값도 달지 않았네요..
수정하겠습니다. 😅

2021-06-21 19:12 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    }
제가 어이없는 실수를 저질러버렸네요.. 😂
일반적인 값 타입은 `Call By Value`로 이뤄져있기 때문에 내값을 변경한다고해서 복사해간 값은 변경되지 않습니다.
하지만 값 객체는 값을 래핑한 객체로 객체이기 때문에 `Call By Reference` 입니다.
그러므로 어느 한쪽이 변경되면, 복사된 모든 값객체에 영향을 미치게 하기 때문에 불변되어야 합니다.
수정하였습니다. 😭

2021-06-21 19:23 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    }
음.. `10 minus 5 is 5. 10빼기 5는 5이다.` 라는 표현을 하고싶어 `minus`로 칭했습니다. `diff`는 다름, 변경, 차이의 뜻을 갖고있기에 숫자를 뺀다라기보단 다르다의 느낌으로 다가오는데 `diff`가 더 어울리릴 것 같은 이유에 대해서 추가 설명해주시면 감사하겠습니다! 😁

2021-06-21 19:31 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Section.java
> +        return upStation == station;
앗.. 위에 말씀드린것처럼 비즈니스 로직을 옮기는거에 초점을 맞춰서 보느라 내부로직에 신경을 못썼네요.. 😭😭
수정하였습니다!

2021-06-21 19:31 UTC, mskangg commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +    @DisplayName("지하철 노선을 관리")
감사합니다. 😁

2021-06-21 19:38 UTC, mskangg commented on src/test/java/nextstep/subway/line/application/LineCommandServiceTest.java
> +    private LineRepository lineRepository;
좋은 피드백 감사합니다!
캐시저장소에 저장이 되어있는지 검증.. 👍 
인수테스트에선 해당 응답이 캐시에서 왔는지 DB에서 왔는지 검증하기 어려우니 응용서비스에서 해야하는 테스트겠네요!
감사합니다. 💯

2021-06-22 10:58 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    }
이건 다시 보니까 민수님 생각이 맞는 것 같습니다. 그대로 진행해주시면 될 것 같습니다.

2021-06-22 11:00 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    private int distance;
column name 에 대한 유지보수성을 어느정도 인지하고 계시니 그대로 진행하셔도 괜찮을 것 같습니다. :+1:
혹시나 이런 사실을 모르시는 분이 있을까해서 가이드를 드리려고 이런 피드백을 드리곤 합니다.

2021-06-22 11:01 UTC, tearight approved these changes
피드백 잘 반영해주셨네요. :+1: 다음 단계 진행해주세요.

2021-06-22 11:01 UTC, merged