[Step1] 1단계 - 인수 테스트 기반 리팩터링 코드리뷰 요청드립니다!!
next-step/atdd-subway-service pull request #199
Opened 2021-06-25 12:04 UTC by Lee-Chungsun

안녕하세요 리뷰어님 반가워요!😊

이제 절반이 넘는 리뷰어님을 뵙네요!!
개인 적으로 이번 미션이 제일 재밌는 것 같아요 ( 바로 전 미션 때문에 거의 2주를 고생해서 그런지..😒)

Mock 테스트도 처음부터 해본 건 처음 이었는데 생각보다 개념이 쉽고 단위테스트에 편리한 것 같아요.
코드 리펙터링 하면서 거의 2~30줄 되는 레거시 메서드를 여러개 한번에 다 지우는 과정도 속 시원했습니다,

이번 미션 잘 부탁드리겠습니다!!🙏🙏🙏

2021-06-26 05:55 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
간단한 피드백 몇 개 남겼으니 확인을 부탁 드리겠습니다.

2021-06-26 05:55 UTC, wheejuni commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +                .orElse(null);
`.orElse()` 로 `null` 을 리턴한다면 옵셔널 클래스를 사용하는 의미가 없습니다...
예외를 던지거나, 분기 처리가 이뤄져야할 것 같습니다.

2021-06-26 05:55 UTC, wheejuni commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +                .anyMatch(it -> it.isUpFinalSection(newSection));
람다 표현식 내에서 `it` 을 쓰는 것은 코틀린의 컨벤션으로 알고 있는데요.

2021-06-26 05:55 UTC, wheejuni commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +        }
`sections.stream()` 한 뒤에 `.filter()` 혹은 `.forEach()` 문으로 리팩토링 가능하지 않을까요?

2021-06-26 06:42 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/common/Excetion/LineNotFoundException.java
> +    public static final String NOT_REGISTERED_LINE = "등록되지 않은 노선입니다.";
앗,, public 으로 되었던 것을 확인을 못 했네요,, 단축키로 하다보니 당연히 private 일 거라 생각했었는데,
슈퍼생성자에 넣었습니다! ☺☺

2021-06-26 06:53 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/line/collection/Distance.java
> +    private final int distance;
static final , final 개행으로 구분하겠습니다!😊

2021-06-26 07:17 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +                .orElse(null);
맞는 것 같습니다,, null이면 null을 리턴한다는 게 잘 못된 구현이네요!
로직 의미에 맞게 nonMatch로 변경해주었습니다!
전에도 orElse(null)로 구현한게 몇 개 있었는데 쓰지 않겠습니다~!
감사합니다😀😀

2021-06-26 08:29 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +                .anyMatch(it -> it.isUpFinalSection(newSection));
it 이 코틀린 컨벤션이었군요!
가독성이 좋게 section 으로 변경해주었습니다!!

2021-06-26 11:07 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +        }
넵!! 리펙토링 가능해서 적용완료했습니다!
계속 결과값이 나올때까지 찾는다라는 생각으로 while을 썻던 것같은데,,
size가 조건이 걸리면 stream으로 충분했는데 잘 못 생각한 것 같네요😑

2021-06-26 11:49 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +        }
리팩토링 적용했습니다!
결과값이 나올 때까지 루프를 돌린다는 생각만 가지고 while을 적용했던 것 같은데,
 sections size 만큼 루프 실행 조건이 들어가면서 왜 while을 썼는지,, 놓친부분 이었습니다,
 감사합니다~!😀

2021-06-26 11:52 UTC, Lee-Chungsun commented on src/main/java/nextstep/subway/line/collection/Sections.java
> +                .orElse(null);
src/main/java/nextstep/subway/line/collection/Sections.java

2021-06-27 00:25 UTC, wheejuni approved these changes
빠르게 피드백 잘 반영해 주셨습니다. 💯 수고하셨습니다.

2021-06-27 00:25 UTC, wheejuni commented on src/main/java/nextstep/subway/common/Excetion/LineNotFoundException.java
> +        super("등록되지 않은 노선입니다.");
👍

2021-06-27 00:25 UTC, merged