[3단계 - 인증을 통한 기능 구현] 리뷰 요청드립니다!
next-step/atdd-subway-service pull request #202
Opened 2021-06-25 13:50 UTC by itdar

안녕하세요, 용근님. 리뷰 요청 드립니다!
- 토큰 발급
- 토큰을 통한 내정보 확인
- 토큰을 통한 나의 즐겨찾기 확인
앞의 단계들과 마찬가지로, 인수테스트케이스 작성 후 사이사이 테스트케이스 작성하며 구현했습니다.
리뷰 부탁드립니다. 감사합니다!

2021-06-25 14:37 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :) 
확인 부탁드려요.

2021-06-25 14:37 UTC, kingbbode commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        return favoriteRepository.findById(id).orElseThrow(RuntimeException::new);
RuntimeException 은 500 에러로 처리가 됩니다. 500 응답은 서버에서 처리에 실패하였을 때의 응답으로 서버의 문제를 이야기합니다. 그런데 의도하신 예외들은 서버의 문제가 아닌, 사용자 요청에 대한 문제인 것으로 보여요. 이런 경우 4xx 대역의 에러를 사용합니다.

스프링의 예외 핸들러가 어떻게 구현되어 있는지 살펴보시면 일반적인 예외를 어떻게 분류하고 있는지 알 수 있습니다. 실제로 스프링에서 분류하는 방식이 자바 개발자들 사이에서도 어느정도 통일되는 분류 방식이기도 합니다.

예외에 대한 테스트도 부족해보이네요 :) 의미있는 예외를 발생시키면 좋을 듯 합니다 :)

2021-06-25 17:15 UTC, itdar commented
> 코멘트 작성해두었습니다 :)
> 확인 부탁드려요.

안녕하세요 용근님!
 예외처리 클래스와 메서드를 정리하고, 즐겨찾기 관련해서 예외가 뭐가 있을까 보다보니, 로그인된 유저만 즐겨찾기를 보도록 하는 것이 필요할 것 같아서 해당 내용까지 추가했습니다.
재리뷰 부탁드립니다. 감사합니다!!

2021-06-27 00:13 UTC, kingbbode approved these changes
잘 반영해주셨네요 :)
작성된 코멘트도 확인 부탁드립니다.
수고 많으셨습니다.

2021-06-27 00:13 UTC, kingbbode commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    private Member member;
양방향 관계로 작성하신 배경이 궁금합니다 :)

회원이라는 도메인은 여러 도메인을 아우르는 공통되는 도메인으로 사용되는 경우가 많은데요. 이런 경우에는 회원 도메인과의 결합을 최소화하여 회원 도메인의 복잡도를 작게 관리할 수 있습니다 :)

2021-06-27 00:13 UTC, merged

2021-06-27 03:27 UTC, itdar commented
> 코멘트 작성해두었습니다 :)
> 확인 부탁드려요.

리뷰 감사드립니다!
코멘트 해주신 내용은 반영해서 4단계 리뷰 요청 드리겠습니다!