[step2] 경로 조회 리뷰 요청 드립니다~!
next-step/atdd-subway-service pull request #203
Opened 2021-06-25 15:59 UTC by prodo-developer

안녕하세요! 우아한 테크캠프 pro 2기 백성락 입니다.
이번 경로조회는 요구 사항 파악부터 비지니스 분리 및 다익스트라 방식에대해 적용하는데 시간이 오래걸렸고
난이도가 많이 어려진걸 느꼈고, 예상치 못한 에러에서 동기들과 함께 풀어감으로써 한층 성장 할 수 있게 되었습니다.

2차 미션도 꼼꼼한 피드백 주시면 감사하겠습니다!

2021-06-26 21:00 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-06-26 21:00 UTC, kingbbode commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +public class PathFinder {
PathFinder 는 경로를 찾기 위해 구성되었고, `jgrapht` 라는 라이브러리를 통해 구현이 되고 있습니다.

라이브러리, 알고리즘이나 구현의 방식은 얼마든지 변경될 수 있을텐데요. 현재의 `PathFinder` 는 `jgrapht` 라는 라이브러리와 강한 결합을 가지고 있기때문에 변경되기 쉽지 않을 것 같네요 :)

인터페이스와 구현체를 분리하여 구현의 변경에 용이한 구조를 취해보는 것은 어떨까요?

2021-06-27 04:55 UTC, prodo-developer commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +public class PathFinder {
말씀하신대로 PathFinder에 많은 역할이 분담 되어 있어서,
JgrpahtFinder의 구현체를와  PathFinder로  인터페이스를 나눴습니다.

2021-06-27 14:15 UTC, kingbbode approved these changes
잘 반영해주셨네요 :)
머지하겠습니다!

2021-06-27 14:15 UTC, merged