[Step 2] 인수테스트 기반 TDD
next-step/atdd-subway-service pull request #21
Opened 2021-01-05 16:46 UTC by jaenyeong

안녕하세요~

해당 미션 2번째 스텝 제출 드립니다.
다소 늦은 시간에 제출하게 되었네요 ㅠ

피드백 부탁드립니다!!

그럼 오늘도 좋은하루 되시길 바랍니다 ㅎㅎ
감사합니다

2021-01-06 11:57 UTC, kyucumber requested changes
안녕하세요

2단계 미션 잘 구현해주셨습니다.

코멘트 몇가지 남겨두었으니 확인 부탁드릴게요

2021-01-06 11:57 UTC, kyucumber commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
핵심 도메인인 `Line`과 `Section` 내부에 외부 라이브러리(jgrapht)에 존재하는 의존성이 추가되었군요.

`Line`과 `Section` 등 도메인 내부의 외부 라이브러리 의존성을 제거하고 `PathService` 등에서 `LineService` 등을 이용해 `Sections`를 조회하거나 하는 식으로 사용하면 어떨까요?

아니면 `Consumer`를 아래와 같이 활용해도 외부 라이브러리 의존성을 제거할 수 있지 않을까요?
예시로 작성한거라 컴파일 에러가 발생할 수 있습니다.

```java
        new Consumer<Section>() {
            public void accept(Section section) {

                final Station upStation = section.getUpStation();
                final Station downStation = section.getDownStation();
                graph.addVertex(upStation);
                graph.addVertex(downStation);
                graph.setEdgeWeight(graph.addEdge(upStation, downStation), section.getDistance());
            }
        };
```

```java
    private void addToPathGraph(final Consumer<Section> consumer) {
        sections.forEach(consumer);
    }
```

아래 남긴 추가적인 내용은 개인적인 의견이니 참고만 부탁드립니다.

graph와 같은 참조가 `PathFinder` -> `Line` -> `Section`과 같이 여러 흐름을 타고 전달되어 addVertex 등이 호출되고 있습니다.
이런 사이드 이펙트를 유발하는 부분이 많아지면 많아질수록 버그를 찾기가 힘들어져서 개인적으로는 지양하고 최대한 불변을 유지할 수 있도록 개발을 진행하는게 좋은 것 같습니다.

2021-01-06 11:57 UTC, kyucumber commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private PathFinder(final List<Line> subwayLines) {
`PathFinder`에서는 `Line`을 받아 다른 값을 사용하지 않고 하위의 `sections`를 forEach를 이용해 바로 순회하고 있습니다.

`Line`이 아닌 `List<Section>` 을 받는건 어떨까요?

2021-01-06 11:57 UTC, kyucumber commented on src/main/java/nextstep/subway/path/dto/PathFinderResponse.java
> +        return stations;
크게 중요한 부분은 아니지만 `List`의 참조가 노출되니 아래와 같이 반환하면 어떨까요?

```suggestion
        return Collections.unmodifiableList(stations);
```

2021-01-06 11:57 UTC, kyucumber commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +class PathFinderTest extends AcceptanceTest {
이런 경우 `PathFinder`에 대한 단위 테스트만 작성해주셔도 좋을 것 같아요

2021-01-06 13:15 UTC, jaenyeong commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
좋은 말씀 이신 것 같습니다! 저 또한 해당 의견에 동의하구요!
제가 가장 기본적인걸 놓치고 있었네요! 리뷰 감사합니다

2021-01-06 13:17 UTC, jaenyeong commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private PathFinder(final List<Line> subwayLines) {
이 또한 좋은 의견이신것 같네요!
아무생각 없이 LineRepository로 findAll 메서드를 통해 쉽게 받아와 처리하려 했었네요..
``` List<Line> ```가 필요한게 아니니 말씀대로 수정하도록 하겠습니다 ㅎㅎ

2021-01-06 13:25 UTC, jaenyeong commented on src/main/java/nextstep/subway/path/dto/PathFinderResponse.java
> +        return stations;
아 dto 객체기 때문에 리뷰 주신대로 변경하는게 맞는 것 같습니다!!

2021-01-06 13:28 UTC, jaenyeong commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +class PathFinderTest extends AcceptanceTest {
제가 이해를 잘못해서 그런데 말씀 주신게 DisplayName 애노테이션에 속성을 얘기하시는 건가요?
``` @DisplayName("PathFinder 단위 테스트") ``` 이렇게 작성하라고 권하신건지요??

2021-01-06 14:23 UTC, kyucumber commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +class PathFinderTest extends AcceptanceTest {
제가 조금 헷갈리게 남겨두었네요 ㅠㅠ

`class PathFinderTest extends AcceptanceTest`

`PathFinderTest`는 단위테스트로 `AcceptanceTest`를 상속할 필요가 없지 않을까요?

2021-01-06 14:31 UTC, kyucumber requested changes
피드백 잘 반영해주셨습니다.

코멘트 몇개 남겨두었으니 확인 부탁드릴게요

다음 요청 주시면 바로 머지하도록 하겠습니다.

2021-01-06 14:31 UTC, kyucumber commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        final PathFinder pathFinder = PathFinder.of(sectionRepository.findAll());
기존에 Cascade를 이용해 `Line`에서 Section의 라이프사이클을 모두 관리했던 것으로 기억하고 있습니다.

조금 비효율적일 수 있지만 `SectionRepository`를 이용하는게 아니라 `Line.findAll()` 이후 flatMap 등으로 `Section` 정보를 모두 가져오는건 어떨까요?

지하철 노선이라는 도메인 특성 상 `Line`이 엄청나게 많아지진 않을 것 같아서 쿼리가 조금 비효율적으로 나가더라도 `Section`의 라이프사이클을 `Line`에서만 관리하게 하는게 조금 더 나을 것 같아요.

이 부분은 개인적인 의견이라 참고만 해주시면 될 것 같습니다~

2021-01-06 14:31 UTC, kyucumber commented
```
제가 이해를 잘못해서 그런데 말씀 주신게 DisplayName 애노테이션에 속성을 얘기하시는 건가요?
@DisplayName("PathFinder 단위 테스트") 이렇게 작성하라고 권하신건지요??
```

요건 위에 코멘트 남겼습니다~

2021-01-06 23:12 UTC, jaenyeong commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        final PathFinder pathFinder = PathFinder.of(sectionRepository.findAll());
아 처음에 지금 말씀 주신것 그대로 구현했었습니다. PathFinder 단위 테스트도 Section 객체를 생성하는 방법이 아닌
기존 ``` List<Line> ```에서 flatMap을 사용하여 작성하였었습니다.
하지만 Line과 Sections에서 getSections 메서드를  구현하게 되는데
이게 디미터의 법칙을 어기는 것도 아니고 의존성 방향 자체도 제 생각엔 올바른 방향이라고 생각되긴 하나 
내부적인 메서드 체인이라고 생각이 되어 SectionRepository를 사용하는 방법을 선택하게 되었습니다.

JPA를 실무에서 사용해본적은 없어 이와 같은 방법으로 구현한다면 어떠한 문제가 있을지 모르겠으나 
객체지향적인 관점에선 이렇게 구현하는 게 나은 것이 아닌가라는 생각이었습니다.
혹시 Line 에서만 관리하는 게 낫다는 것이 어떤 면에서 낫다는 점인지 조금 더 자세히 설명을 주실 수 있을까요??

2021-01-07 00:30 UTC, kyucumber commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        final PathFinder pathFinder = PathFinder.of(sectionRepository.findAll());
`SectionRepository`에 들어가 있지는 않지만 `Section` 생성 또한 `SectionRepository`를 이용해 수행할 수 있습니다.

`Line`에서 수행되는 validation 등이 누락될 수 있으니 그런 부분을 차단하기 위해서 말씀드린거고 현재 상황에서는 조회만 수행되고 있어 크게 상관은 없을 것 같네요

2021-01-07 00:31 UTC, kyucumber approved these changes
2단계 미션 진행하시느라 고생 많으셨습니다.

다음 단계 진행을 위해 머지할게요

2021-01-07 00:31 UTC, merged