Step3 - 인증을 통한 기능 구현
next-step/atdd-subway-service pull request #216
Opened 2021-06-27 06:01 UTC by ybh89

안녕하세요. 윤병현입니다. 
코드리뷰 부탁드립니다. 
감사합니다!

2021-06-27 23:41 UTC, kang-hyungu requested changes
병현님 구현하신 내용 확인했어요
몇 가지 피드백 남겼습니다. 수정하시고 리뷰 재요청주세요
궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요

2021-06-27 23:41 UTC, kang-hyungu commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        Favorite favorite = findFavoriteById(favoriteId);
jpa를 사용하고 있고 favorite과 member가 매핑 되어 있는 걸 활용해보면 어떨까요

2021-06-27 23:41 UTC, kang-hyungu commented on src/main/java/nextstep/subway/favorite/ui/FavoriteController.java
> +    public ResponseEntity createFavorite(@AuthenticationPrincipal LoginMember loginMember,
제네릭 타입은 꼭 작성해주세요.
이펙티브 자바 3판 아이템 26. 로 타입은 사용하지 말라 참고하세요

2021-06-27 23:41 UTC, kang-hyungu commented on src/main/java/nextstep/subway/member/domain/FavoriteGroup.java
> +package nextstep.subway.member.domain;
즐겨찾기인데 왜 멤버 패키지에 있나요?
어디 있는지 찾을 때 헷갈리지 않을까요?

2021-06-27 23:41 UTC, kang-hyungu commented on src/main/java/nextstep/subway/member/domain/FavoriteGroup.java
> +    public FavoriteGroup() {
```suggestion
    protected FavoriteGroup() {
```

2021-06-27 23:41 UTC, kang-hyungu commented on src/test/java/nextstep/subway/auth/acceptance/AuthAcceptanceTest.java
> +        Map<String, String> params = new HashMap<>();
map 대신 TokenRequest를 사용하는걸 추천합니다.

2021-06-27 23:41 UTC, kang-hyungu commented on src/test/java/nextstep/subway/auth/acceptance/AuthAcceptanceTest.java
> +        ExtractableResponse<Response> response = RestAssured
RestAssured를 사용한 http get, post, put, delete 메서드 호출이 반복적으로 나오고 있네요.
AcceptanceTest에 중복된 호출을 미리 정의해두고 각 인수테스트에서 사용하면 코드량을 줄일 수 있지 않을까요?

2021-06-27 23:41 UTC, kang-hyungu commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTest.java
> +    public void 아이디가같은즐겨찾기_등록_확인() throws Exception {
이 테스트는 어떤걸 검증하려는 걸까요?

2021-06-27 23:41 UTC, kang-hyungu commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTest.java
> +    public void 깉은즐겨찾기_등록_확인() throws Exception {
위 테스트와 어떤 차이가 있는 걸까요?

2021-06-28 04:58 UTC, ybh89 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        Favorite favorite = findFavoriteById(favoriteId);
일단 수정은 했는데, 제가 피드백의 의도를 정확히 파악한것인지 모르겠습니다.

일단 저는 member와 favorite이 매핑되어 있는 것을 활용하라고 하셔서
favorite을 repository를 통해 찾지 않고
member에서 찾도록 변경하였습니다,

혹시 member.removeFavorite을 하지말고 repository.delete()를 사용하라는 말씀이신지 헤깔리네요😂

2021-06-29 02:51 UTC, kang-hyungu commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        Favorite favorite = findFavoriteById(favoriteId);
이전에 작성하신 방식은 db 관점으로 생각해서 favorite 데이터를 조회한 것이었죠
jpa를 사용하고 있으니 객체지향적으로 코드를 작성하자는 이야기였습니다.
favorite 객체가 member와 연결되어 있는 상태이니 수정하신 코드처럼 작성하시면 됩니다.

2021-06-29 02:57 UTC, kang-hyungu approved these changes
병현님 피드백 반영하신 내용 확인했습니다.
다음 미션 진행해주시면 됩니다.
pr은 머지 처리할게요. 수고하셨습니다~!

2021-06-29 02:57 UTC, kang-hyungu commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTest.java
> +        assertThat(사용자.getFavorites()).containsExactly(favorite1);
favorite2, favorite3 객체는 생성만 하고 사용자와 아무런 관계를 갖고 있지 않고 있네요.
의도한 테스트대로 한 번만 등록되는지 보려면 사용자 객체에 favorite2, favorite3 객체를 추가해봐야되지 않나요?

2021-06-29 02:57 UTC, merged

2021-06-29 06:21 UTC, ybh89 commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTest.java
> +        assertThat(사용자.getFavorites()).containsExactly(favorite1);
음.. Favorite 생성자에서 받은 사용자객체에 자신(Favorite)을 추가하고 있는 구조여서 따로 추가하지 않았습니다,

생성자에서 추가하지 않고 테스트코드에서 추가하도록 변경하는게 좋을까요?