Step4 - [ 요금 조회 ] 리뷰 요청드립니다.
next-step/atdd-subway-service pull request #228
Opened 2021-06-27 18:50 UTC by jhh992000

안녕하세요. 경준님
제가 지난주에 다른 기관의 강의를 수강하느라 이번 ATDD 미션부터 조금씩 밀리게 되었습니다.
없는 시간에 짬짬이 시간을 쪼개어 미션을 진행해보았는데 역시나 역부족이었네요. 😭
예전부터 꼭 듣고싶었던 강의라서.. 부득이하게 지난주 공백이 생기게 되었습니다.
다시 힘을 내어서 이번주부터는 nextstep 교육에 집중하도록 하겠습니다. 🔥
마지막 4단계 요금조회 기능을 구현이 완료되어 리뷰를 요청드립니다.
그럼 마지막 단계 리뷰도 잘 부탁드리겠습니다. 🙏
즐거운 한주 되시고요~!

2021-06-28 15:58 UTC, slamdunk7575 commented
- 이전에 제가 놓친 부분이 있는데요. 현재 LineController, StationController 등 컨트롤러 내에 예외처리 핸들러가 중복되어 구현되어 있는데요.
우리는 중복이 싫으니 `ControllerAdvice`를 만들어 별도로 예외처리를 관리해보면 좋을 것 같아요. 
`@RestControllerAdvice`를 활용해보세요. Service 단에서 발생하는 예외들도 같이 관리될 수 있을 것 같네요 :)


- 아래는 변경을 위한 피드백은 아니니 참고만 해주세요~!
경로를 찾기 위해 현재 우리는 `다익스트라(Dijkstra) 알고리즘`을 사용하고 있는데요.
알고리즘이나 라이브러리는 나중에 쉽게 변경될 수 있기 때문에 
인터페이스를 만들어 PathService 에서 구체적인 경로 찾기의 구현은 모르도록 하고 
jgrapht 을 사용한 Finder를 만들어 분리해보면 더 좋을것 같습니다.

2021-06-28 16:05 UTC, slamdunk7575 requested changes
요금 조회 잘 구현해주셨네요 👍 
개선해보면 좋을 부분에 코멘트 남겨드렸습니다.
조금만 더 힘내주세요~ 화이팅 입니다!

2021-06-28 19:05 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/path/ui/PathController.java
제가 지난 번에 놓친 부분이 있었네요. File changes에 잡히지 않아 여기에 남겨드립니다. 🙏 
`LineController, StationController` 등 컨트롤러 내에 예외처리 핸들러가 중복되어 있는데요.
우리는 중복이 싫으니 `ControllerAdvice`를 만들어 별도로 예외처리를 관리해보면 좋을 것 같아요. 
`@RestControllerAdvice`를 활용해보세요. Service 단에서 발생하는 예외들도 같이 관리될 수 있을 것 같네요 :)

2021-06-29 04:26 UTC, jhh992000 commented on src/main/java/nextstep/subway/path/domain/FareCalculator.java
> +    }
enum에 interface를 상속해서 사용하는 방법도 있다는것을 알게 되었네요. 감사합니다. 🙏

2021-06-29 04:33 UTC, jhh992000 commented on src/main/java/nextstep/subway/path/ui/PathController.java
메일로 날아온 피드백에는 한가지가 더 있었는데 요긴 없네요. (경로찾기 추상화 관련해서 말씀주신것)
그것도 한번 적용해보았습니다. 추상화만 잘 해놓으면 나중에 기능을 변경하거나 확장하기에 용이할것 같습니다. 👍

조금이라도 부족한부분이 있는것 같다면 거침없이 말씀해주시면 좋을것 같습니다.. 🙏
제가 부족한 부분을 알게만 해주시면 그만큼 저는 성장한다고 믿습니다~!

2021-06-29 04:34 UTC, jhh992000 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private int surcharge = 0;
`@AttributeOverride` 애노테이션에 대해서 알게해주셨습니다. 감사합니다. 🙏

2021-06-29 04:35 UTC, jhh992000 commented on frontend/src/views/line/components/LineCreateButton.vue
> +        </div>
vue를 잘 모르지만 그냥 슬쩍한번 추가해보았습니다.

2021-06-29 04:36 UTC, jhh992000 commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +        지하철_최단_경로에_요금이_포함됨(response, 3150);
결과확인부분에 가독성이 떨어진다는 점을 알게되었습니다.
다음부터는 결과값 확인에도 좀 식별하기 좋게 하는 노력을 해야겠습니다.

2021-06-29 04:37 UTC, jhh992000 commented on src/test/java/nextstep/subway/path/domain/FareCalculatorTest.java
> +    }
간단하게 셋트로 구성했을때 요금계산테스트 코드를 하나 추가해보았습니다.

2021-06-29 12:54 UTC, slamdunk7575 approved these changes
미션 진행하면서 피드백도 적극적으로 반영해주시고 많은 고민을 하셨기에 
좋은 결과가 나온거 같습니다. 

제가 드렸던 피드백들이 앞으로 훈희님께 조금이라도 도움이 되었으면 좋겠네요!

그동안 고생 많으셨습니다. 감사합니다. 🙇
남은 미션도 꾸준히 진행하시고 끝까지 완주하시길 응원하겠습니다! 🎉

2021-06-29 12:54 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    }
피드백 반영 잘해주셨네요 👍 

크게 중요한 부분은 아니지만 아래와 같이 역 설명 주석이 있다면 
나중에 훈희님과 동료 개발자분들이 다시 코드를 파악할때  좋을것 같아요 :)

```java
    /**            거리 6                  거리 20
     * 교대역   --- *2호선* ---   강남역   --- *2호선* ---   잠실역 
     * |                        |
     * *3호선*                   *신분당선*
     거리 3                    거리 12
     * |                        |
     * 남부터미널역  --- *3호선* --- 양재역
     *                거리 2
     */
```

2021-06-29 12:54 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/path/domain/impl/ShortestPathFinder.java
> +public class ShortestPathFinder implements PathFinder {
오히려 혼란을 드릴것 같아 삭제했었는데 반영해보셨네요 👍 🥇

2021-06-29 12:54 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/path/domain/DistanceSurchargeCalculator.java
> +    },
`Enum` 으로 잘 분리해주셨네요 👍

2021-06-29 12:55 UTC, merged