[3단계 - 인증을 통한 기능 구현] 리뷰요청 드립니다~
next-step/atdd-subway-service pull request #250
Opened 2021-07-01 11:39 UTC by byunghakjang1230

토큰 인증을 처음해봤는데 덕분에 JWT를 공부해볼 수 있었습니다. 개인적으로 잼있었네요~👏
(해당 내용 학습하고 이해하고 테스트 해보느라 시간이 좀 걸렸네요..ㅜㅜ)
그리고 미션 내용과 별개로 지난 미션 끝내고 계속 마음에 남아있던 경로조회 클래스에 대한 지하철 관련 클래스의 의존성을 제거해 보았습니다. 인터페이스를 이렇게 사용해본적도 처음인 것 같은데 올바른 방법으로 했는지 잘 모르겠네요..ㅠㅠ(이 내용도 확인 부탁드려도 되겠지요..??😵)
지난번 처럼 꼼꼼한 리뷰 부탁드립니다!👍

2021-07-01 14:15 UTC, wheejuni requested changes
대단히 수고 많으셨습니다 👍 전반적으로 설계도 깔끔하고 특별히 피드백 드릴 부분이 많지 않았네요.
아주 간단한 피드백 세 가지 드립니다. 확인 및 반영 부탁드릴게요.

2021-07-01 14:15 UTC, wheejuni commented on src/main/java/nextstep/subway/auth/infrastructure/JwtTokenProvider.java
> +                .setSigningKey(secretKey)
저도 확실하게는 모르겠지만 그냥 여쭤봅니다. 이거 혹시 `Jwts.parser().setSigningkey()` 의 결과물을 스프링 빈으로 관리할 순 없을까요? 어차피 같은 객체를 모두 사용해도 상관없을 것 같아서요.

2021-07-01 14:15 UTC, wheejuni commented on src/main/java/nextstep/subway/auth/infrastructure/JwtTokenProvider.java
> +                    .before(new Date());
`java.util.Date` 는 이제 점점 사용하지 않는 추세로 가고 있습니다.
대체할만한 클래스엔 무엇이 있을까요? 한번 찾아보시는 것도 추천합니다.

2021-07-01 14:15 UTC, wheejuni commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        return FavoriteResponse.of(favoriteRepository.save(new Favorite(member, sourceStation, targetStation)));
같은 `Favorite` 이 이미 존재한다면 어떻게 되나요?

2021-07-02 04:08 UTC, byunghakjang1230 commented on src/main/java/nextstep/subway/auth/infrastructure/JwtTokenProvider.java
> +                .setSigningKey(secretKey)
기존에 있던 `AuthenticationPrincipalConfig`에 추가를 했더니 여러 방법으로 해봐도 계속 오류가 나서 안되는줄 알았는데 순환참조 오류였네요.(`service`가 `jwtProvider`를 호출하고 `jwtProvider`가 또 `config`를 호출하고 `config`가 또 `sevice`를 호출하는...)
그래서 `JwtTokenConfig` 클래스를 따로 만들어서 주입받을 인터페이스를 빈으로 등록을 하고, `JwtTokenProvider`에서 생성자 주입을 통해 `JwtParser`를 받도록 수정하였습니다.👌물론 오류없이 잘 동작합니다!

2021-07-02 04:50 UTC, byunghakjang1230 commented on src/main/java/nextstep/subway/auth/infrastructure/JwtTokenProvider.java
> +                    .before(new Date());
코멘트를 보고 찾아보았는데 `Date`, `Calendar`에 대한 문제를 지적하는 내용을 많이 보게 되었습니다. 불변 객체가 아니어서 시스템 운영상 문제가 생길 소지도 있고, 애매한 상수선언 외 다양한 이유들로 개발 단계에서도 많은 문제가 발생하는것 같더라구요.
해당 코드는 `JDK 8`부터 포함된 `LocalDateTime`을 사용하였습니다. 그런데 `getExpiration()`가 반환하는 타입이 `Date`타입이여서 완전히 뺄수는 없었네요..일시 정보를 생성하는 단계에서는 `LocalDateTime`을 사용하고 파라미터로 주입할 때에만 타입 변환을 위해 `Date`를 사용하였습니다.ㅜㅜ

2021-07-02 04:51 UTC, byunghakjang1230 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        return FavoriteResponse.of(favoriteRepository.save(new Favorite(member, sourceStation, targetStation)));
해당 부분을 놓친것 같네요.😓출발역과 도착역이 이미 동일하게 등록된 경우에 예외가 발생하도록 수정하였습니다~

2021-07-03 12:01 UTC, wheejuni approved these changes
수고 많으셨습니다. 👍

2021-07-03 12:01 UTC, merged