[Mission5. 인수 테스트 기반 TDD] 1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #272
Opened 2021-07-04 18:11 UTC by gregolee

안녕하세요. 박이슬 리뷰어님! 🙇 
이번 인수 테스트 기반 TDD를 진행하시게 되어 반갑습니다 ❗ 
부족한 점이 많겠지만, 많은 부분을 보완할 수 있도록 좋은 조언 부탁드립니다!!!! 😄 
좋은 하루 되세요!! ☀️ 

- [x] 4.구현
    - [x] 4-1.인수테스트 리팩터링
        - [x] 4-1-1.`LineAcceptanceTest`
        - [x] 4-1-2.`LineSectionAcceptanceTest`
    - [x] 4-2.지하철 노선 생성
    - [x] 4-3.지하철 노선 생성 실패
    - [x] 4-4.지하철 노선 목록 조회
    - [x] 4-5.지하철 노선 조회
    - [x] 4-6.지하철 노선 수정
    - [x] 4-7.지하철 노선 삭제 
    - [x] 4-8.지하철 구간 등록 
    - [x] 4-9.지하철 구간 등록 실패
    - [x] 4-10.지하철 구간 삭제

2021-07-05 13:09 UTC, parkeeseul requested changes
안녕하세요 재영님! 인수 테스트 기반 TDD 미션을 함께 하게 된 박이슬 입니다! 😄 
첫 번째 단계 잘 진행해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다!
함께 이번 미션 잘 풀어나가보아요! 화이팅 입니다 🔥

2021-07-05 13:09 UTC, parkeeseul commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +	}
한번에 너무 많은 개념이 들어가있지는 않나 고민해보면 좋을 것 같아요! 🤔 
![스크린샷 2021-07-05 오후 9 56 50](https://user-images.githubusercontent.com/48339310/124474788-e9802d80-dddb-11eb-9b33-42073209127b.png)
강의 자료에 있는 예시를 보면
등록 -> 조회(등록에 대한 확인) -> 삭제 ->  확인조회(삭제에 대한 확인) 
처럼 자연스러운 흐름으로  등록, 삭제, 조회에 대한 인수 테스트에 대한 시나리오가 작성되었습니다
`지하철 노선에 여러개의 역을 순서 상관 없이 등록한다`, `지하철 노선에 이미 등록되어있는 역을 등록한다.` 등과 같은 특정 상황에 대한 인수테스트는 따로 분리해주는 것이 좀 더 자연스러운 흐름일 것 같은데 재영님의 생각은 어떠신가요? 😄 

또한 해당 인수테스트와 중복되는 인수 테스트들이 존재하는데 중복으로 작성해주신 이유가 있으신가요?

2021-07-06 23:39 UTC, gregolee commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +	}
계산을 위임하긴 했지만 객체로 전달하는 것이 도메인의 역할의 마무리라고 이해하도록 하겠습니다! 😄 👍 
조언 감사합니다!! 👍 🙇

2021-07-06 23:40 UTC, gregolee commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	}
직관적으로 `==`를 작성하는 것이 나은 것인가 `equals()`메서드로 하는 것인가 헷갈렸는데,
조언 주신대로 메서드명을 작성하여 보여주도록 하겠습니다! 👍

2021-07-06 23:46 UTC, gregolee commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +	}
사실 어떻게 작성해야될지 몰라서 하나의 흐름으로 작성했습니다.
"지하철 구간을 관리"라는 시나리오는 다소 추상적인 내용으로 특정 시나리오를 표출하기엔 부족함이 있었습니다.
따라서 말씀하신대로 특정 상황을 구성하도록 하겠습니다! 😄 
조언 감사합니다!! 👍 🙇

2021-07-07 00:58 UTC, gregolee commented
안녕하세요. 박이슬 리뷰어님! 🙇
덕분에 인수테스트 작성하는 내용에 대한 감이 '조금'이라도 잡힌것 같아 다행인것 같습니다 😄 👍 🙇 
코멘트 주셨던 부분 반영하여 리뷰 재요청 드립니다 ❗ 
좋은 하루 되세요!! ☀️

2021-07-07 13:29 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
다음 단계 진행해주세요! 
날씨가 많이 덥네요! 건강 유의하시고 미션 화이팅 입니다! 🔥

2021-07-07 13:29 UTC, merged