[Step1] 인수 테스트 기반 리팩터링 리뷰 요청드립니다.
next-step/atdd-subway-service pull request #3
Opened 2020-12-29 05:21 UTC by ccf05017

안녕하세요, 우아한테크캠프 Pro 수강생 조범진입니다 :)

Step1 인수 테스트 기반 리팩터링 과제를 아래와 같이 수행했습니다.
- 기존 인수테스트 대신 시나리오 기반의 인수테스트로 변경
- 지하철 노선의 도메인 로직을 서비스에서 도메인 로직으로 이동

지하철 노선의 도메인 로직을 옮기는 과정에서 Line 오브젝트가 과도하게 복잡해졌고, 이를 해결하기 위해 클래스를 분리했습니다.
현재 Line 내의 Sections를 조회하는 기능은 모두 LineExplorer가 담당하도록 구현했습니다.
Line에서 Sections의 추가, 삭제, 조회를 모두 수행하면 Line 오브젝트의 책임이 지나치게 크다고 생각했기 때문입니다.

추가, 삭제는 남기고 조회만 이동시킨 이유는 추가, 삭제의 경우 Line 내부의 Sections 컬렉션에 사이드 이펙트를 발생시키기 때문에
다른 오브젝트로 분리해서 처리하면 사이드 이펙트 추적이 어렵다고 생각되서 조회만 따로 추출했습니다.

더불어 Section 추가 기능의 경우 상태에 따른 동작이 많이 나눠진다고 생각되어 따로 메서드 추출을 진행했습니다.
Sections 제거 기능의 경우 기존 서비스 레이어에 있던 도메인 로직도 충분히 가독성이 좋다고 생각되어 별도의 변경을 진행하지 않았습니다.

관련해서 미숙한 점이나 고치면 좋을 점들에 대한 많은 피드백 부탁드립니다.
잘 부탁드립니다 :) 감사합니다.

2020-12-29 14:40 UTC, seogi89 requested changes
안녕하세요 😄 5주차 미션 리뷰어를 맡은 이재석입니다.
벌써 5주차 미션을 시작하시다니 대단하시네요 👏 

리펙토링 잘 진행해주셨습니다.
몇가지 궁금한점과 수정했으면 하는 부분이 있어 코멘트 남겨 놓았으니 확인 부탁드릴게요.

앞으로 과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 편하게 코멘트 또는 DM 남겨주세요.

범진님과 함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 코드 기대하며 기다리고 있을게요. 🙇

2020-12-29 14:40 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
불가능한 이유가 무엇일까요 🤔

2020-12-29 14:40 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +                .filter(it -> it.getUpStation() == station)
getter 를 사용하기보다는 Section 에 Message 를 전달하여 값을 구해보는건 어떤가요?

2020-12-29 14:40 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/LineSectionExplorer.java
> +public class LineSectionExplorer {
전체적으로 `default` 생성자를 사용한 이유가 궁금하네요 🤔

2020-12-29 14:40 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Section.java
>          this.distance -= newDistance;
distance  도 객체로 포장한다면
0 보다 작은 거리가 발생하는것을 확인하는 책임을 적절히 나눠줄 수 있을 것 같아요.

2020-12-29 14:40 UTC, seogi89 commented on src/main/java/nextstep/subway/station/application/StationService.java
> +        return stationRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("존재하지 않는 역입니다."));
구지 확인해야 할 필요가 있을까요?
성능상 큰 이점이 있을것 같지는 않아요.

2020-12-29 14:40 UTC, seogi89 commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        지하철_노선_생성됨(createResponse2);
중복을 제거 할 수 있을 것 같아요.

2020-12-29 22:39 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return sections.size() == originalSize + 1;
왜냐면..! 몰랐기 때문입니다 ㅜ
좋은 정보 공유 감사합니다.

2020-12-29 23:24 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/application/LineService.java
>          lineRepository.deleteById(id);
생각해보니 이 기능이 있는 걸 인수테스트 때 이미 발견했는데, 제가 대충 대응한 면이 있는 것 같네요 ㅜ
도메인에서 정의한 에러를 내보내고 싶다는 생각에 그냥 기존 기능 재활용하는 방향으로 진행했는데,
해당 에러를 try/catch로 덮는 게 더 좋은 것 같습니다. 
조언 감사합니다 :)

2020-12-29 23:28 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
본래는 `sections.size() <= 1` 구문이었는데 해당 메서드의 제거 결과를 반환하기 위해 위에 선언한 originalSize 변수와 겹쳐서 중복을 제거하기 위해 해당 변수를 사용해서 변경하도록 만들었습니다.
변경되면서 약간 의미가 잘 드러나지 않는 코드가 된 것 같네요 ㅜ
혹은 1이라는 매직 넘버에 의미를 부여하는 방향으로 개선해도 의도를 좀 더 드러낼 수도 있을 것 같네요

그 외 그냥 이 불변식 구문 자체가 왜 필요한지에 대한 말씀이셨다면, 지난번 과제와 이어지는 내용이고 지난번 과제의 제거 기능 관련 요구사항이 있었어서 이번에도 유지된다 생각해서 남겨놨습니다 :)

2020-12-29 23:29 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +                .filter(it -> it.getUpStation() == station)
나중에 해야지 하고 그냥 넘겨버렸네요 ㅜ
확인 감사합니다.

2020-12-29 23:36 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/LineSectionExplorer.java
> +public class LineSectionExplorer {
음.. 제가 어떤 의도로 말씀주신 건지 잘 이해를 못하겠습니다 ㅜ

제가 추측한 리뷰어님의 의도는
1. 굳이 메서드에서 파라미터를 안 받고 인자 한개밖에 없는데 굳이 생성자로 한 이유가 무엇인가?
2. 생성자 접근 제한을 기본 접근 권한으로 둔 이유는 무엇인가?
로 이해했습니다.

첫번째로 메서드 파라미터로 받지 않고 생성자로 처리한 이유는 처리할 대상이 List 콜렉션이기 때문에 만약을 대비해서 사이드 이펙트가 없도록 탐색 기능들을 수행하기 전에 공통적으로 해당 콜렉션에 대한 방어적 복사를 진행하고 싶었습니다.
메서드마다 파라미터를 받고 방어적 복사를 해도 되지만 그렇게 되면 반복적인 코드가 너무 많다고 생각되서 생성자에서 수행하도록 기능을 구현했습니다.

두번째로 접근 제한을 기본 접근 권한으로 둔 이유는 다른 레이어에서 해당 오브젝트를 직접 사용하지 못하도록 하기 위해 막아놨습니다. 해당 오브젝트의 기능은 Line과 밀접하게 관련된 내용인데 Line 책임이 너무 커져서 분리한 오브젝트로 Line에 대한 인지 없이 다른 클라이언트 코드에서 직접 사용하면 맥락적으로 이해가 힘들지 않을까 생각했습니다. 이 외에도 sections 콜렉션을 주력으로 사용하게 되는데, 이를 외부 클라이언트 코드에서 직접 사용하게 하면 Line.getSections()를 필연적으로 사용하게 될 것이라 불필요한 getter 사용을 줄이기 위해서 감춘 부분도 있습니다.
결론적으로 의도한 바는 Line 탐색도 Line의 하부 기능이기 때문에 세부사항은 LineSectionExplorer에 있지만, 실제 기능을 사용하기 위해서는 Line을 통해서만 사용할 수 있도록 만들고 싶어서 해당 LineSectoinExplorer의 생성자 접근 권한을 제한했습니다 :)

2020-12-29 23:38 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Section.java
>          this.distance -= newDistance;
요 부분은 검토가 부족한채로 그냥 넘겼네요.. ㅎㅎ ㅜ
LineService, Line에만 집중하면서 놓친 것 같습니다. 조언 감사합니다.

2020-12-29 23:42 UTC, ccf05017 commented on src/main/java/nextstep/subway/station/application/StationService.java
> +        return stationRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("존재하지 않는 역입니다."));
이 부분은 성능보다 초기에 정의한 인수테스트 조건을 충족시키기 위해 추가한 부분입니다.

사용자가 실수로 역 ID를 빼먹고 LineSection을 추가하는 요청을 보낼 때를 구현하면서 ID가 null일 경우 그대로 리포지토리에 null 전달하는 에러가 있어서 급하게 막은 구문입니다.

최종적으로는 DTO null 여부는 컨트롤러에서 해야된다 생각해서 컨트롤러에 해당 기능이 추가될 예정이었습니다...만... 그냥 홀라당 이렇게 남아 있었네요 ㅜ 이 부분도 수정해놓겠습니다

2020-12-29 23:43 UTC, ccf05017 commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +        지하철_노선_생성됨(createResponse2);
조언 감사합니다 이 부분도 메서드 추출 진행하겠습니다 :)

2020-12-30 02:15 UTC, ccf05017 commented
안녕하세요, 우아한테크캠프 Pro 수강생 조범진입니다.

요청주신 리뷰사항 반영과 구현의도에 대한 답변 남겨놨습니다 ㅎㅎ

진행과정 중 getter를 제거하는 부분과 Distance를 래핑하는 과정에서 새로운 객체를 발견했고,
해당 객체들에 대한 구현과 테스트가 추가됐습니다.

그 외 추가로 더 수정할만한 사항이나 미흡한 부분에 대해 피드백 주시면 감사하겠습니다 :)

2020-12-30 04:09 UTC, seogi89 approved these changes
피드백 빠르게 잘 반영해주셨네요 :) 
추가로 소소한 팁과 코멘트남겨놓았으니 다음 미션과 함께 고민해보면 좋을 것 같아요

이어서 다음 미션 진행해주세요.

2020-12-30 04:09 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return this.getSections().add(new Section(this, upStation, downStation, distance));
`sections.add(...)`

2020-12-30 04:09 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Line.java
>              sections.add(new Section(this, newUpStation, newDownStation, newDistance));
디미터의 법칙 위반하셨네요.

https://johngrib.github.io/wiki/law-of-demeter/

2020-12-30 04:09 UTC, seogi89 commented on src/main/java/nextstep/subway/station/ui/StationController.java
> +    public ResponseEntity<StationResponse> createStation(@Validated @RequestBody StationRequest stationRequest) {
👍

2020-12-30 04:09 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Distance.java
>              throw new InvalidDistanceValueException("거리는 음수가 될 수 없습니다.");
0이 될수도 없을 것 같아요.

2020-12-30 04:09 UTC, seogi89 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +        return new Distance(this.distance - thatDistance.distance);
소소하지만
```
if(that.distance == 0) {
    return this
}
return new Distance(this.distance - that.distance)
```

2020-12-30 04:09 UTC, merged

2020-12-30 05:03 UTC, ccf05017 commented on README.md
> +            - 지하철 역 등록됨~~~~
요즘 마우스 없이 키보드만으로 해보는 연습을 하고 있는데 가끔 가다가 어느 화면에 포커스 맞춰졌는지 모르고 열심히 단축키 누를 때가 있습니다 ㅜㅜㅜㅜ

확인 감사합니다 ㅎㅎ

2020-12-30 05:03 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return this.getSections().add(new Section(this, upStation, downStation, distance));
으 감사합니다 다 걷어냈다 생각했는데 하나씩 뭔가 빠지네요 ㅜ

2020-12-30 05:05 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
>              sections.add(new Section(this, newUpStation, newDownStation, newDistance));
확인감사합니다.
디미터 외에도 distance를 래핑한만큼 거기서 처리해야되는데 너무 로우값으로 처리가 되고 있는 것 같네요
다음 과제 진행 때 함께 반영하겠습니다 :)

2020-12-30 05:06 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Distance.java
>              throw new InvalidDistanceValueException("거리는 음수가 될 수 없습니다.");
음.. 그러네요 상식적으로 아예 붙어있는 역이란 존재할 수 없을 것 같아요.
반영해놓겠습니다 :)

2020-12-30 05:06 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +        return new Distance(this.distance - thatDistance.distance);
오.. 감사합니다
제 테스트 케이스가 부족했네요 ㅜ

2020-12-30 05:20 UTC, ccf05017 commented on src/main/java/nextstep/subway/line/domain/Line.java
>              sections.add(new Section(this, newUpStation, newDownStation, newDistance));
음.. 다시 확인하니 이 부분은 이전 코드 부분을 보신 것 같습니다.
제 커밋이 제대로 반영이 안되서 보이셨던 걸까요 ?_?

현재 해당 부분은 Section 쪽의 별도 메서드로 책임을 이관해서
```java
sections.add(Section.mergeByTwoSections(upSection.get(), downSection.get()));
```
으로 변경되어 있습니다 :)