Step4 : 요금 조회
next-step/atdd-subway-service pull request #333
Opened 2021-11-29 17:03 UTC by tyranotyrano

안녕하세요😊 5주차 인수 테스트 기반 TDD 미션 진행자 최영진입니다.
4단계 요금조회 미션 리뷰 요청 드리겠습니다!
4단계 진행 중 궁금한 내용은 아래에 정리하였습니다.

---

Q. 3단계 리뷰 중 PathService 도 테스트가 가능한 구조로 바꾸려고 시도하다 결국 구현하지 못했습니다.😅 제가 생각했던 방법은 PathService 에서 생성자 주입으로 PathFinder Bean 객체를 받아서 처리하면 될 것이라고 생각했는데 DijkstraShortestPathAlgorithm 에서 사용되는 DijkstraShortestPath 객체를 Bean 객체로 만들 수 없어 PathService 와 PathFinder 의 의존성을 결국 해결하지 못하였습니다. 이와 관련되서 좀더 힌트를 얻을 수 있을까요?

2021-11-30 14:25 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨어요 💯 
도움이 될만한 코멘트 남겨두었으니 확인 부탁드릴게요 😄

2021-11-30 14:25 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/DiscountRateType.java
> +    private final int minAge;
```suggestion
    private static final String INVALID_AGE_ERROR_MESSAGE = "나이 정보가 유효하지 않습니다.";
    
    private final int minAge;
```

클래스 변수와 인스턴스 변수 사이에 공백을 추가하면 가독성이 상승합니다!

2021-11-30 14:25 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/application/LineService.java
> +@Transactional
저는 개인적으로 클래스 레벨에 Transactional을 사용하는 것을 선호하지 않습니다 
트랜잭션은 굉장히 비용이 큰 작업이고, 불필요한 트랜잭션으로 성능이 낮아지는 문제도 있지만 더 큰 문제는 의도되지 않은 트랜잭션으로 인해 데드락이 발생할 수 있다 라는 것이 생각입니다 
실제 현업에서 대규모 트래픽을 처리하기 위해 데드락이 발생하지 않도록 설계하는 것이 굉장히 중요한데요 
개발하는 과정에서도 이 기능에 데드락이 발생할 요소가 있을까? 트랜잭션을 꼭 잡아야 가능한 기능일까? 구조를 변경하여 락이 필요 없는 구조로 바꿀 수 없을까? 에 대해 끊임없이 고민하게 되는데, 이러한 고민을 하는 시점이 저는 메서드에 Transactional 처리를 하는 시점에 가장 많이 하는 것 같습니다

또한 클래스마다 트랜잭션과 격리레벨이 정해지는 것이 아닌 기능(메서드)단위로 처리되기 때문에 클래스에 적용하여 공통으로 처리할 필요가 있을까? 라는 의문이 들었습니다 ㅎㅎ

지금도 `findAll`에서 해당 @Transactional이 어떠한 장점이 있을지 고민해보아요 :)

2021-11-30 14:25 UTC, jaeyeonling commented on src/test/java/nextstep/subway/fare/calculator/FareCalculatorTest.java
> +    void beforeEach() {
Q. 지하철 도메인 처럼 테스트를 하기위해 setUp() 단계에서 많은 픽스처들이 필요한 경우, 픽스처를 만드느라 코드가 지저분해지는 느낌을 많이 받았습니다. 혹시 이렇게 많은 픽스처가 필요한 경우 이 픽스처들을 깔끔하게 관리(?) 할 수 있는 방법이 있을까요? 생각나는 방법은 해당 테스트 클래스를 위한 별도 픽스처 팩토리 클래스를 만들면 어떨가 싶은데, 오히려 봐야하는 클래스가 늘어나는 건 아닐까 고민이됩니다.
A. 말씀하신 부분은 저도 고민하고 있는 문제로 테스트를 위한 픽스처가 많아질수록 고민이 많아지는 것 같습니다 T.T
해당 부분은 어쩔 수 없는 부분이라 생각이 되는데요!
픽스처 팩토리 클래스 분리, sql로 분리하는 방법 등 많은 방법이 있지만 각 케이스마다 장/단점이 존재하고 차이가 미비하여 베스트 프렉티스가 존재하지 않기 때문에 각 케이스를 사용해보고 취향에 맞게 선택해주시면 될 것 같습니다 :)

2021-11-30 14:29 UTC, tyranotyrano commented on src/main/java/nextstep/subway/fare/domain/DiscountRateType.java
> +    private final int minAge;
구현에 집중하다보니 이런 디테일을 놓쳤네요 ㅎㅎ 잡아주셔서 감사합니다!!👍

2021-11-30 14:35 UTC, tyranotyrano commented on src/main/java/nextstep/subway/line/application/LineService.java
> +@Transactional
평소에 @Transactional 을 사용하면서 데드락이나 성능에대해 크게 고민을 해보지 않은 것 같습니다 ㅎㅎ 
이번 기회에 트랜잭션에 대해 깊게 공부를 해봐야겠네요! 피드백 감사합니다!

2021-12-01 10:54 UTC, jaeyeonling approved these changes
마지막까지 미션 잘 진행해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 다음 미션도 화이팅입니다!!

2021-12-01 10:54 UTC, merged