1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #334
Opened 2021-11-30 10:54 UTC by jerry92k

안녕하세요, 혜린님!
인수 테스트 기반 TDD 미션을 수행하게 된 김지희 입니다.

이번 미션 리뷰 잘 부탁드립니다. 

감사합니다.🙂

2021-11-30 15:42 UTC, hhlyn0328 requested changes
안녕하세요 
인수테스트 기반 TDD 리뷰어 홍혜린입니다! 

1단계 인수 테스트 기반 리팩터링을 잘 진행해주셨네요 👍 
요구사항중에 누락된 부분이 있는 것 같아 코멘트 드렸습니다 
참고하시어 수정 후 재 요청 부탁드려요 🙏 

그럼, 이번 미션 잘 부탁드립니다 🙇

2021-11-30 15:42 UTC, hhlyn0328 commented on README.md
> +Feature: 지하철 구간 관련 기능
요구사항 정의를 잘 해주셨네요 👍

2021-11-30 15:42 UTC, hhlyn0328 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +		while (downStation != null) {
객체지향 생활체조는 언급이 따로 없어도 모든 미션에서 기본적으로 지켜야한다고 보시면 될 것 같아요 
`규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.`
위의 규칙을 지켜, 메서드의 책임을 최소화 해볼까요?

2021-11-30 15:42 UTC, hhlyn0328 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +			.anyMatch(it -> it == upStation);
object 비교는 == 보다는 equals를 사용해주세요

2021-11-30 15:42 UTC, hhlyn0328 commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +	}
요구사항에 맞게, 도메인 로직에 대한 단위테스트 작성 부탁드립니다 🙏

2021-11-30 15:42 UTC, hhlyn0328 commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +    void manageLineSection(){
시나리오를 기반으로 복합적인 인수테스트를 잘 작성해주셨네요 👍

2021-11-30 15:58 UTC, jerry92k commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +	}
removeStation의 예외 케이스 테스트를 1)구간이 없거나 2)하나만 존재하는 경우로 분리하는 것을 말씀하시는게 맞을까요~? 제가 이해한 것이 맞는지 다시 여쭤봅니다😅

2021-12-01 09:58 UTC, hhlyn0328 approved these changes
리뷰 반영을 잘 해주셨네요 👍 
다음 단계 진행을 위해 바로 머지하겠습니다! 🙇🙇

2021-12-01 09:58 UTC, merged