1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #335
Opened 2021-11-30 12:21 UTC by wangkdk

안녕하세요 리뷰어님!
1단계 인수 테스트 기반 리팩터링 리뷰 요청 드립니다.

감사합니다!

2021-12-01 10:52 UTC, jaeyeonling requested changes
안녕하세요 이번 미션을 같이 진행할 김재연입니다 :)
요구사항에 맞게 잘 구현해주셨습니다 👍 
코멘트 남겨두었으니 확인 부탁드려요 :)

2021-12-01 10:52 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    public ResponseEntity addSection(@PathVariable Long lineId, @RequestBody SectionRequest sectionRequest) {
ResponseEntity에 대한 Row타입을 사용하면 어떠한 문제가 있을지 고민 후 제네릭을 사용해보아요

2021-12-01 10:52 UTC, jaeyeonling commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +    Line line = new Line();
```suggestion
    private Line line = new Line();
```

접근제어자를 생략한 것은 의도된 내용일까요?

2021-12-01 10:52 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(IllegalArgumentException::new);
IllegalArgumentException로 예외 상황에 대한 내용을 전달할 수 있을지 고민해보아요

2021-12-01 10:52 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Station> getStations() {
해당 메서드에서 하는 예외처리들이 조회 시점에 해야할 예외처리들일지 고민해보면 좋겠습니다 :)

2021-12-01 10:52 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Section extractSectionByContainsUpStation(Station downStation) {
```suggestion
    private Section extractSectionByContainsUpStation(Station station) {
```

해당 메서드의 시그니처로 봤을 때 무조건 downStation만 올 수 있는게 아닌 상황에서 downStation과 같은 네이밍을 사용한다면 어떠한 문제가 있을지 고민해보아요

2021-12-01 10:52 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean addUpStationOfBetween(Section section) {
해당 메서드 내에선 특정 기능을 조회하며 값을 변경하는 역할을 하는데요
CQS 원칙에 대해 고민 후 어떠한 문제가 있을지 고민해보아요

2021-12-01 10:52 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            .filter(it -> it.getDownStation() == station)
== 으로 비교하는건 의도된 내용일까요?

2021-12-01 10:52 UTC, jaeyeonling commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +        assertThatThrownBy(() -> sections.addSection(
단위테스트에는 하나의 assertion만 작성하는 것이 좋은데요.
테스트가 실패할 경우 이전 테스트 결과로 인한 전파가 발생했는지 단독적인 이슈인지를 직접 확인해봐야 하기 때문입니다.
그리고 테스트당 개념 하나만을 테스트해야 한다는 원칙도 위배되는 경우가 발생할 우려도 있습니다.
만약 여러 테스트가 필요한 경우라면 jUnit5에서 추가된 assertAll을 활용해주세요!

2021-12-01 11:34 UTC, wangkdk commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    public ResponseEntity addSection(@PathVariable Long lineId, @RequestBody SectionRequest sectionRequest) {
제네릭을 사용하면 컴파일러를 통해서 런타임시 일어날 수 있는 예외를 미리 예방할 수 있다고 생각합니다!
음.. 그런데 body 의 내용이 없는 경우에는 어떤 타입이 적절할까요? Object 를 사용하는 것이 좋을까요?

2021-12-01 11:35 UTC, wangkdk commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +    Line line = new Line();
아닙니다 실수입니다 수정하겠습니다!

2021-12-01 11:55 UTC, wangkdk commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Section extractSectionByContainsUpStation(Station downStation) {
실제 메서드는 downStation 이라는 논리적인 부분까지 처리하지는 못하는데, 네이밍으로 인해서 메서드 기능 자체에 대한 오해가 생길듯 합니다.

2021-12-01 12:01 UTC, wangkdk commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            .filter(it -> it.getDownStation() == station)
기존 레거시 코드였었는데, JPA 를 사용하기 때문에 == 비교를 해도 무리가 없다고 판단했었습니다.
조금 더 안전하게 equals 로 수정하겠습니다!

2021-12-01 12:04 UTC, wangkdk commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +        assertThatThrownBy(() -> sections.addSection(
네 성공과 실패 메서드를 분리하겠습니다!

2021-12-01 13:45 UTC, wangkdk commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean addUpStationOfBetween(Section section) {
메서드가 두가지 역할을 하다보니 의미가 불분명해지고 복잡해지기 때문에
가독성이 떨어지고, 디버깅에 어려움을 겪을 수 있다고 생각합니다.

2021-12-01 13:58 UTC, wangkdk commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Station> getStations() {
제가 제대로 이해한 것인지는 모르겠지만, extract 메서드들 부분이라면 cud 로직 에서 이미 제대로 데이터가 반영되어있을 것이기 때문에 해당 예외가 발생할 가능성은 (있다면 db에 직접 접근해서 데이터를 넣은 케이스) 없지만, stream 사용시 get 메서드를 사용하는 것보다 throw 를 사용하는 것이 더 좋다고 생각을하여 orElseThrow 로 처리를 하였습니다.
또한 요구 사항이 늘어나게 되면 Sections 안에서 범용적으로 사용될 수도 있는 메서드 종류라 판단되어 예외처리가 되어있는편이 안전하다고 생각이 들었습니다. 
이 부분은 리뷰어님의 의견을 듣고 싶습니다!

2021-12-01 13:59 UTC, wangkdk commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(IllegalArgumentException::new);
네 해당 예외 내용 추가하겠습니다!

2021-12-02 11:02 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
질문의 답변 남겨두었으니 확인 부탁드리고 다음 단계 진행해주세요 😄

2021-12-02 11:02 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Station> getStations() {
stream의 예외처리인 것을 제가 놓쳤군요 혼란을 드려 죄송합니다 😢 
stream의 예외처리라 지금의 상태를 유지해주셔도 좋을 것 같습니다!!

`또한 요구 사항이 늘어나게 되면 Sections 안에서 범용적으로 사용될 수도 있는 메서드 종류라 판단되어 예외처리가 되어있는편이 안전하다고 생각이 들었습니다.` 
stream이 아니라는 가정에서 위에 대한 답변을 드리자면, 저는 조회 시점에 예외처리하는 것을 선호하지는 않습니다.
등록이 되는 과정에서 해당 예외처리가 되는 것이 맞다고 생각하고, 불필요한 예외처리의 경우 가독성이 떨어지거나 의도하지 않게 해당 케이스가 존재할 수 있다는 의미로 보여질 수 있기 때문입니다 ㅎㅎ 
물론 상황에 따라 다른 판단은 있을 수는 있을 것 같아요 😄

2021-12-02 11:02 UTC, merged

2021-12-02 11:45 UTC, wangkdk commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Station> getStations() {
답변 감사합니다!
말씀하신 대로 의도와는 다르게 코드를 해석할 여지가 있을 것 같네요. 👍