Step4 - 요금 조회
next-step/atdd-subway-service pull request #337
Opened 2021-11-30 17:30 UTC by devyonghee

안녕하세요 민호님!!
드디어 마지막 단계네요 😆

이번 요구사항은 특히 어려웠던 것 같아요 😰😰😭
값 객체를 활용해보려고 노력했는데 잘 나눈 건지 모르겠네요 😅
마지막까지도 잘 부탁드리겠습니다!!🙇‍♂️🙇‍♂️🙇‍♂️

2021-12-02 15:28 UTC, 5minho requested changes
안녕하세요 용희님!
리뷰가 늦어 죄송합니다!!
4단계 역시 잘해주셨습니다👍
코드도 잘 읽히고 객체들이 자기 역할과 책임을 잘 지키고 있는거 같아 좋았습니다!
조금 더 개선됐으면 좋아보이는 것들 코멘트 달았는데요
확인 부탁드립니다!

2021-12-02 15:28 UTC, 5minho commented on src/test/java/nextstep/subway/path/domain/FareDiscountPolicyTest.java
> +    @ParameterizedTest(name = "[{index}] {0} 나이일 경우 2150원의 할인 금액은 {1}")
이 테스트를
* @DisplayName(청소년은 운임에서 350원을 공제한 금액의 20%할인 해준다)
* @DisplayName(어린이은 운임에서 350원을 공제한 금액의 50%할인 해준다)

이렇게 두개의 테스트로 쪼개보면 어떨까요?
요구사항이 명확하게 파악되는 장점이 있을거 같아요.

2021-12-02 15:28 UTC, 5minho commented on src/test/java/nextstep/subway/path/domain/FareDistancePolicyTest.java
> +    @ParameterizedTest(name = "[{index}] {0} 거리만큼 이동하면 요금은 {1}")
마찬가지로
* 이용가리가 10km초과∼50km까지 이면 5km마다 100원이 추가되어야 한다.
* 이용가리가 50km초과 시이면 8km마다 100원이 추가되어야 한다.

이렇게 테스트를 분리해보면 어떨까요?

2021-12-02 15:28 UTC, 5minho commented on src/test/java/nextstep/subway/common/domain/AgeCategoryTest.java
> +package nextstep.subway.common.domain;
전체적으로 테스트를 꼼꼼하게 잘해주시는거 좋네요 👍

2021-12-02 15:32 UTC, devyonghee commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +    public Sections sections() {
작업하다가 잘못들어간 것 같습니다!! 수정하겠습니다 👍

2021-12-02 15:34 UTC, devyonghee commented on src/test/java/nextstep/subway/path/domain/FareDiscountPolicyTest.java
> +    @ParameterizedTest(name = "[{index}] {0} 나이일 경우 2150원의 할인 금액은 {1}")
넵!! 구분하도록 하겠습니다!!👍

2021-12-02 15:34 UTC, devyonghee commented on src/test/java/nextstep/subway/path/domain/FareDistancePolicyTest.java
> +    @ParameterizedTest(name = "[{index}] {0} 거리만큼 이동하면 요금은 {1}")
넵 이 부분도 테스트를 구분해서 명확하게 수정하겠습니다!👍

2021-12-02 15:35 UTC, devyonghee commented on src/main/java/nextstep/subway/path/application/PathService.java
> +            path.sections());
넵!! 내부에서 사용하는 객체를 숨기도록 하겠습니다!!👍

2021-12-03 11:51 UTC, 5minho approved these changes
안녕하세요 용희님!
피드백 반영해주신거 확인했습니다~
이번 미션 정말 고생많으셨구요
마지막 미션까지 화이팅입니다!!

2021-12-03 11:51 UTC, merged