1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #356
Opened 2021-12-04 05:59 UTC by wooobo

광현님 안녕하세요~

인수 테스트 기반 TDD 미션 함께 하게 된 강태화입니다.

이번 미션에서 `LineService` 리팩토링을 시작하면서  `mock` 테스트를 거치면서 진행해보았는데 안정적으로 리팩토링 할 수 있어서 좋은 인사이트를 얻을 수 있었습니다~

1. `LineServiceTest` "mock" 테스트 진행
2. `Sections`  "@Embeddable"로 분리
3. `Distance` "@Embeddable"로 분리
4. `LineRepositoryTest`,`StationRepositoryTest` 테스트 추가 
등등 미션을 진행하면서 궁금한 점이 있었습니다. 

# 궁금한점 
`LineService.addLineStation` , `LineService.removeLineStation` 이런 메소드들은 진짜로 추가되었는지 삭제되었는지 확인하기가 `mock`테스트에서는 확인하기가 힘들다는걸 느꼈는데 이부분은 `인수테스트` 나 `Repository` 테스트로 진행해야하는 것인지 궁금합니다. 

---
꼼꼼하게 진행한다고 하였지만 부족한 부분이 많은꺼라 생각됩니다!
부족하지만 리뷰 부탁드리겠습니다~

감사합니다 :smile:

2021-12-05 04:57 UTC, nokchax requested changes
안녕하세요, 태화님! 인수테스트 기반 TDD주차 리뷰어 김광현입니다 🙇‍♂️ 
첫번째 과제 잘 진행해 주셨습니다. 커밋로그도 그렇고, 코드에서 꼼꼼함이 묻어나왔던거 같아요 💯 
몇가지 코멘트 남겼는데요, 확인후 재요청 부탁드립니다 🙏

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/common/exception/DatabaseException.java
> +public class DatabaseException extends RuntimeException {
👍

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        validateDuplicateName(request.getName());
이 로직은 동시요청에 의해서 뚫릴 수있는 검증 방법 같아요.
DB에서 반환하는 유니크 제약이 더 확실한 방법이지 않을까요?

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        line.addSection(addSection);
line.addSection() 내부에서 Section 객체를 생성하는건 어떨까요?

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public boolean sameNameAndColor(Line line) {
boolean 형일때 함수명은 is, has 등과 같은 이름으로 시작하는게 어울릴거 같아요

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            .orElse(null);
null을 반환하는 것은 안티패턴이라고 볼 수 있는데요.
null을 반환하면서 Objects.isNull(~~) 과 같은 null체크 코드도 많이 보입니다.
아무런 역할을 하지 않는 DummySection 을 만들고 someSection.isDummy() 와 같은 식으로 로직을 구현해보면 어떨까요?

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean isMatchedUpStationAndDownStationInSections(Section section) {
함수명이 지나치게 긴 것 같아요.
긴 함수명은 오히려 가독성을 해칩니다. 핵심적인 것만 표현해 보면 어떨까요?

2021-12-05 04:57 UTC, nokchax commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    public ResponseEntity<Void> updateLine(@PathVariable Long id,
👍

2021-12-05 04:57 UTC, nokchax commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +@DisplayName("지하철 노선 관리 기능")
테스트도 전반적으로 꼼꼼히 잘 하셨네요 💯

2021-12-05 04:57 UTC, nokchax commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +@DisplayName("지하철 노선 관리 기능")
https://github.com/next-step/atdd-subway-service/pull/356#issue-795043852
넵, 실제 상황을 테스트해보고 싶다면 mock으로는 할수 없죠, 말씀 주셨듯 인수테스트나 service layer 테스트로 진행 해야 할거 같아요. repository 레이어 테스트라면 jpa에 대한 테스트가 되는것 아닐까요?

2021-12-05 09:26 UTC, wooobo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        validateDuplicateName(request.getName());
`RestResponseEntityExceptionHandler`에서 공통으로 관리 할지 생각해보았는데, 
메시지를 별도로 줄려니 `Controller`별로 만들어 보았습니다.

이부분 어떻게 생각하실지 궁급합니다ㅜ 
```
# LineController

   @ExceptionHandler(value = {DataIntegrityViolationException.class})
    protected ResponseEntity<ErrorResponse> handleLineNameDuplicateConflict() {
        return ResponseEntity.badRequest()
            .body(ErrorResponse.of(ErrorCode.LINE_NAME_DUPLICATE_DATA));
    }
```

2021-12-05 09:27 UTC, wooobo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        line.addSection(addSection);
생성자를 간소화 시킬려다 보니까, 외부에서 불필요한 코드가 더 생긴것 같습니다ㅜ 
내부로 이동시키는것이 더 나아 보입니다 :+1:

2021-12-05 09:27 UTC, wooobo commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public boolean sameNameAndColor(Line line) {
isSameNameAndColor 으로 변경해보았습니다.

2021-12-05 09:29 UTC, wooobo commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            .orElse(null);
`객체에게 묻는다` 지켰었어야 했는데 어떻게 할지 많이 고민한 부분인데, 별도의 객체를 만들 생각을 못했었네요ㅜ
말씀 하신 패턴으로 수정해보니 확실히 좀 더 코드가 안정감이 느껴집니다 :+1:

2021-12-05 09:29 UTC, wooobo commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean isMatchedUpStationAndDownStationInSections(Section section) {
함축할려다 보니 오히려 독이 되었네요, `isAddAblePositionInSections` 으로 수정해보았습니다.

2021-12-05 09:30 UTC, wooobo commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +@DisplayName("지하철 노선 관리 기능")
그러고보니 `repository`레이어는 JPA 테스트네요!
답변감사합니다! :smile:

2021-12-05 09:34 UTC, wooobo commented on src/main/java/nextstep/subway/common/exception/ErrorCode.java
> +    SECTION_EXIST(400, "이미 등록된 구간 입니다."),
예외 처리 개선하면서
`ErrorCode` , `ErrorResponse`를 추가해보았습니다!

2021-12-06 09:03 UTC, nokchax commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        validateDuplicateName(request.getName());
구현하신 것 처럼 컨트롤러별로 처리해도 됩니다.
하나 문제인점은 현재는 service layer에서 Line에 대한 예외만 던지기 때문에 문제되지는 않지만, 
여러 entity 중복에 대한 예외도 발셍 하게 되면, 에러메세지가 오히려 혼란을 가중시킬수는 있을거 같습니다.

API 응답에서 에러내용을 어느정도까지 친절하게 보여줄지에 따라 다른거 같아요.
에러의 내용을 숨기고 싶다면, 하나의 익셉션 핸들링으로 처리해줘도 될 것 같습니다 :)

그건 그렇고 API 응답이니 RestControllerAdvice를 사용해보는건 어떨까요?

2021-12-06 09:08 UTC, nokchax approved these changes
안녕하세요, 태화님! 피드백 잘 적용해 주셔서 추가적으로 코멘트 드릴게 없네요 👏👏 
이번 단계는 이만 머지할게요, 다음 단계 진행해주세요 :)

2021-12-06 09:08 UTC, nokchax commented on src/main/java/nextstep/subway/common/exception/InvalidParameterException.java
> +    private final ErrorCode errorCode;
👍  깔끔하니 보기 좋습니다

2021-12-06 09:08 UTC, merged

2021-12-06 09:17 UTC, wooobo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        validateDuplicateName(request.getName());
답변 감사합니다 :smile: 
컨트롤러에서 핸들링하더라도 다른 entity를 사용하는 경우가 있으면 동일하게 단점이 발생하니.. 좀 더 나은 패턴을 적용하거나 공통적으로 exception을 잡는게 좋을것 같네요~
고민해보겠습니다 감사합니다 :smile:

2021-12-06 09:18 UTC, wooobo commented on src/main/java/nextstep/subway/common/exception/InvalidParameterException.java
> +    private final ErrorCode errorCode;
감사합니다 부지런히 다음 단계 진행하겠습니다 :+1: