2단계 - 경로 조회 기능
next-step/atdd-subway-service pull request #366
Opened 2021-12-05 12:01 UTC by y2o2u2n

안녕하세요, 리뷰어님 :)

우선 주어진 요청/응답 포맷을 본 후 Happy 케이스에 대한 인수 테스트를 작성했고

그 다음 도메인에 대한 테스트 작성 후 실제 구현을 거쳐 이것을 서비스 레이어에 사용하도록 변경하는 순서로 개발을 진행했습니다.

그리고 이후에 인수 테스트에 에러 케이스에 대한 내용도 추가했습니다.

직전 PR에 댓글 남겨주셨던 것들도 수정했으니 참고 부탁드립니다!

리뷰 잘 부탁드립니다 (_ _)

2021-12-06 06:03 UTC, kang-hyungu requested changes
준석님 몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청주세요

2021-12-06 06:03 UTC, kang-hyungu commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +	void acceptanceCriteria() {
메서드는 한 가지 일만 처리해야 합니다.
테스트 코드에서도 이 규칙은 동일하게 적용됩니다.
테스트 하나에서 모든 인수 케이스를 작성해버리면 그 조건을 협업하는 개발자가 파악하기 어렵습니다.
테스트 목적에 따라 메서드를 적절하게 나눠주세요.

---

클린코드 157p

테스트 코드는 실제 코드 못지 않게 중요하다. 테스트 코드는 이류 시민이 아니다.
테스트 코드는 사고와 설계와 주의가 필요하다.
실제 코드 못지 않게 깨끗하게 짜야한다.

테스트는 유연성, 유지보수성, 재사용성을 제공한다. 테스트 케이스가 있으면 변경이 쉬워지기 때문이다.
따라서 테스트 코드가 지저분하면 코드를 변경하는 능력이 떨어지며 코드 구조를 개선하는 능력도 떨어진다.
테스트 코드가 지저분할수록 실제 코드도 지저분해진다.
결국 테스트 코드를 잃어버리고 실제 코드도 망가진다.

2021-12-06 11:04 UTC, y2o2u2n commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +	@ExceptionHandler(CanNotFindPathException.class)
넵 예외 처리만 담당하는 별도의 클래스를 두겠습니다 :)

2021-12-06 11:12 UTC, y2o2u2n commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +	void acceptanceCriteria() {
강의 내용 중 인수 테스트 작성시 시나리오로 검증하는 것이 많은 코드를 만들어내는 것보다 좋은 경우가 있을 수 있다고 해서
실패하는 케이스들도 추가해보았던 건데요,
생각해보니 실패하는 케이스들은 별도로 분리를 하는 것도 괜찮을 것 같다는 생각이 드네요 :)

2021-12-06 12:50 UTC, y2o2u2n commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
>  public class LineAcceptanceTest extends AcceptanceTest {
넵 반복되는 코드를 AcceptanceTest 로 올리는 것이 훨씬 깔끔해보이네요 :)

2021-12-06 12:56 UTC, y2o2u2n commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public List<Section> getSectionList() {
```
    public Sections getSections() {
        return sections;
    }
```

바로 위 코드에서 `getSections`을 사용하고 있어서 이렇게 이름을 지었었는데요,
이 메서드를 제거하고 사용하는 쪽에서 값을 꺼내서 사용하도록 변경하겠습니다 :)

2021-12-06 12:57 UTC, y2o2u2n commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return sections.getStations().getValues();
https://github.com/next-step/atdd-subway-service/pull/366/files/0701347d057c734954e3fa8da6fb3869596c67a8#r762982670

위와 동일하게 변경하겠습니다 :)

2021-12-07 07:04 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
>  public class LineAcceptanceTest extends AcceptanceTest {
네 다른 인수 테스트는 의미 있는 네이밍을 작성해주셨는데 라인 인수 테스트만 그대로여서 남긴 피드백이었습니다.
미션에 해당되지 않더라도 전체 코드를 깔끔하게 유지하는 걸 추천합니다.

2021-12-07 07:13 UTC, kang-hyungu approved these changes
준석님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리할게요. 추가로 남긴 피드백은 다음 미션 진행하면서 적용해주세요.

2021-12-07 07:13 UTC, kang-hyungu commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +		StationResponse 교대역 = 지하철역_등록되어_있음("교대역").as(StationResponse.class);
값을 셋팅하는 부분을 메서드로 추출하면 다른 테스트와의 중복을 줄일 수 있겠네요

2021-12-07 07:13 UTC, merged

2021-12-07 07:53 UTC, y2o2u2n commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +		StationResponse 교대역 = 지하철역_등록되어_있음("교대역").as(StationResponse.class);
이 부분은 강의 중 하나의 메서드 내에서 주어진 조건이 다 보이는 것이 상황에 따라서는 좋을 수도 있다는 내용을 보고
`setUp`을 활용하지 않은 부분이기는 합니다.
정답은 없겠지만 이 인수 테스트의 경우에는 추출하는 것도 괜찮아 보이네요!