1단계 [인수 테스트 기반 리팩터링] - 코드리뷰 요청드립니다.
next-step/atdd-subway-service pull request #381
Opened 2021-12-07 06:00 UTC by codingknowjam

안녕하세요
이번 미션은 생각보다 시간이 오래걸렸던 것 같습니다.
기존의 작성 된 인수테스트를 기반으로 TDD를 통한 단위테스트를 하면서 코드를 작성하다보니 어렵더라구요 ㅠ
여태까지 학습해왔던 것을 되뇌이면서 리팩터링을 진행해봤습니다.
좋은 피드백 기다리고 있겠습니다.
항상 고생이 많으십니다. 화이팅!

2021-12-07 13:29 UTC, nokchax requested changes
안녕하세요, 상우님! 인수테스트 기반 TDD 주차 리뷰어 김광현입니다 :)
첫번째 과제 잘 진행해 주셨습니다. 단위 테스트도 꼼꼼히 추가하셨네요 👍 
코멘트 남겼는데요, 확인후 재요청 부탁드립니다 🙇‍♂️

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/application/LineService.java
> +	private StationService stationService;
final 붙이는걸 깜빡하셨네요

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/application/LineService.java
> +	public LineService(LineRepository lineRepository, StationService stationService) {
이번 우태캠 프로 과정내에서는 indent를 4space로 적용해주세요 :)

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Section.java
> +            throw new IllegalArgumentException("역과 역 사이의 거리보다 좁은 거리를 입력해주세요");
적절한 예외사용 👍

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +				.orElse(finalCurrentSection);
함수로 추출할 수 있지 않을까요?

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +			.filter(section -> section.getDownStation().equals(addSection.getDownStation()))
getter사용 대신 message를 보내서 동일한 객체인지 물어보도록 하는건 어떨까요?

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private Station getUpStation(Optional<Section> optionalSection) {
optional을 인자로 받는것, optional을 리턴하는 것 optional.ifPresent(), optional.get() 모두 안티 패턴입니다!
이를 사용하지 말고 구현해보도록 해보세요 :)
추가적으로 null을 리턴하는 것도 안티 패턴입니다!

2021-12-07 13:29 UTC, nokchax commented on src/main/java/nextstep/subway/line/dto/LineRequest.java
> +    // }
사용하지 않는 코드는 제거해주세요

2021-12-07 13:29 UTC, nokchax commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +class SectionsTest {
단위 테스트 추가 👍

2021-12-08 04:15 UTC, codingknowjam commented on src/main/java/nextstep/subway/line/domain/Section.java
> +
여기 제 로컬 코드상에서는 indent4인데 왜이렇게 보이는지 모르겠네요 ㅠㅠ

2021-12-08 12:44 UTC, nokchax approved these changes
안녕하세요, 상우님!
피드백 잘 적용해 주셨네요, 남긴 코멘트는 참고 혹은 다음 단계에서 반영해보세요 :)
이번 단계는 이만 머지하겠습니다. 🙇‍♂️

2021-12-08 12:44 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Section.java
> +		if (this.distance <= section.getDistance()) {
distance를 객체로 추출하고 distance에 위임할수 있을거 같아요
아래의 this.distance -= section.getDistance(); 도 마찬가지입니다

2021-12-08 12:44 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +			.noneMatch(section -> section.getDownStation().equals(firstSection.getUpStation()));
section 내부에 새로 생성한 비교 함수를 사용할수 있겠네요

2021-12-08 12:44 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +		}
```suggestion
		if (!isUpdateDownStation(addSection)) {
		    return;
		}
		
	        sections.stream()
			.filter(section -> section.equalsDownStation(addSection))
			.findFirst()
			.orElseThrow(() -> new IllegalArgumentException("구간이 존재하지 않습니다."))
			.updateDownStation(addSection);
```

2021-12-08 12:44 UTC, nokchax commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +		}
test내의 print문은 삭제해주세요

2021-12-08 12:44 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private boolean isUpdateUpStation(Section addSection) {
isUpdatableUpStation() 이 더 어울리는 네이밍 같아요

2021-12-08 12:44 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Sections.java
>  	}
이런 방식도 가능해요

```java
private static final Section DUMMY_SECTION = new Section();
...
public boolean isDummy() {
  return this == DUMMY_SECTION;
}
```
위와 같이 선언을 하고 아래와 같이 로직을 구현하는 것도 방법일 것 같습니다 :)
```java
if (!upLineStation.isDummy() && !downLineStation.isDummy()) {
```
```java

private Section findUpSection(Station station) {
    return sections.stream()
                              .filter(section -> section.isEualsUpStation(station))
                              .findFirst()
                              .orElse(Section.DUMMY_SECTION);
}
```

2021-12-08 12:44 UTC, merged