3단계 - 인증을 통한 기능 구현
next-step/atdd-subway-service pull request #418
Opened 2021-12-10 11:37 UTC by wooobo

안녕하세요 광현님!

3단계 PR 요청드립니다~

## 진행한 부분 
1. `Oauth` 로 회원 관리 로직을 리팩토링 하고 테스트를 진행하면서, 재밌게 진행했습니다.

2. `Favorite` 도메인은 연관관계를 맺지 않는 형태로 구현했습니다.
`Member` -> `Favorites` 에서 
```
@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST, orphanRemoval = true)
    @JoinColumn(name = "member_id", updatable = false, nullable = false)
    private List<Favorite> favorites = new ArrayList<>();
```
의 형태로 `Member` 도메인을 통해 관리 될 수 있게 해보았습니다. 

3. `Favorite`가 약한 연관관계를 이루어져있다보니, 맵핑하는 로직을 일급컬렉션 `MemberFavoriteCollection`으로 분리 시켰습니다.

4. `ErrorCode` 를 인터페이스로 만들고 패키지별로 `ErrorCode` 하도록 분리 했습니다. 

생각보다 이번 미션에서 다루어야 되는 내용들이 많았어서 어떻게 할지 헤매는 부분이 많았지만..(이번 미션 쉽지 않았네요^^;;)
하나하나 짚어가며 진행해보았습니다.

리뷰 부탁드리겠습니다~! :smile:

감사합니다.

2021-12-10 13:42 UTC, nokchax requested changes
안녕하세요, 태화님 :)
이번에도 역시 잘 진행해주셨네요 👍 
구현도 잘 하시고, 테스트 코드도 꼼꼼하게 잘 짜주셨습니다.
질문하나 남겼는데, 답변 부탁드릴게요 🙇‍♂️

2021-12-10 13:42 UTC, nokchax commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    private Long stationSourceId;
station과의 연관관계를 맺지 않으신 이유가 있을까요?

2021-12-10 15:37 UTC, wooobo commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    private Long stationSourceId;
다시 코드를 보니 
```
public void saveFavorite(Long memberId, Long sourceId, Long targetId) {

```
에서 지하철역이 존재하는 station인지 검증을 해야 될 것 같아서 

[푸쉬 PR](https://github.com/wooobo/atdd-subway-service/pull/3) 해당코드 merge 하였습니다 ㅜ

2021-12-12 03:19 UTC, nokchax commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    private Long stationSourceId;
넵 태화님이 마지막 단계까지 생각하신 후 내린 결론이시라면, 이견없습니다 :)

2021-12-12 03:19 UTC, nokchax approved these changes
잘 구현 하셨어요 👍
머지하겠습니다. 다음 단계 진행해주세요 :)

2021-12-12 03:19 UTC, merged