🚀 1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #42
Opened 2021-01-09 08:01 UTC by himj131

안녕하세요, 김미진 입니다.
1단계 과제 제출합니다.
LineService에 있던 구간 등록 로직과 구간 역 제거 로직을 도메인 로직이라 생각해 
Line으로 이동 시켰고, 그에 해당하는 단위 테스트를 추가했습니다.

혹시 보완해야 할 부분이 있거나 잘못된 점 있으면 피드백 부탁드립니다. 
감사합니다 :)

2021-01-09 10:04 UTC, hongsii requested changes
안녕하세요~ 인수 테스트 기반 TDD 리뷰를 맡게 된 박시홍입니다.
비즈니스 로직을 도메인으로 잘 옮겨주셨네요! 👍 
추가로 피드백 남겼으니 확인하셔서 반영해주세요~!
잘 부탁드립니다 🙇‍♂️

2021-01-09 10:04 UTC, hongsii commented on src/test/java/nextstep/subway/line/domain/LineTest.java
> +        assertThat(stations).containsExactlyElementsOf(Arrays.asList(양재, 광교));
`containsExactly` 를 사용하면 리스트로 변환하지 않고 검증할 수 있습니다 :)

```suggestion
        assertThat(stations).containsExactly(양재, 광교);
```

2021-01-10 09:41 UTC, himj131 commented
피드백 주신대로 중복 로직을 메소드로 추출해 사용하고, Sections 란 일급 컬렉션을 만들어봤습니다 :)

2021-01-10 13:46 UTC, hongsii approved these changes
피드백 반영을 잘 해주셨네요! 💯 
간단한 피드백 남겼으니 다음 단계에서 함께 반영해주세요~!

2021-01-10 13:46 UTC, hongsii commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +public class Sections {
일급 컬렉션 👍

2021-01-10 13:46 UTC, hongsii commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            return Arrays.asList();
빈 리스트는 아래의 싱글턴 객체를 활용하는게 어떨까요? 

```suggestion
            return Collections.emptyList();
```

2021-01-10 13:46 UTC, hongsii commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            throw new RuntimeException();
이 예외의 의도가 무엇일까요? 의도가 드러날 수 있도록 바꿔보면 어떨까요?

2021-01-10 13:46 UTC, hongsii commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            sections.add(new Section(line, newUpStation, newDownStation, newDistance));
여기도 의도가 명확히 드러나도록 메서드로 추출해보면 어떨까요?

2021-01-10 13:46 UTC, merged