4단계 - 요금 조회
next-step/atdd-subway-service pull request #439
Opened 2021-12-11 16:52 UTC by SHINMJ

안녕하세요. 리뷰어님!

4단계 -요금 조회 리뷰 요청합니다!!!

기능 구현 뿐만 아니라 객체의 책임과 역할 도 계속적으로 고민하고 고려하면서 개발을 할 수 있게되었습니다..

결과는 잘모르겠지만 저는 이런 고민을 하게 되었다는 것이 엄청난 발전이라 리뷰어님께 너무 감사합니다!!

이번 단계도 잘 부탁드립니다!!!!

2021-12-12 03:55 UTC, leeyohan93 requested changes
4단계 미션도 잘 구현해주셨네요 👍 
미션을 마무리하기 이전에 조금 더 개선해보면 좋을 점에 대해서 코멘트 남겨두었습니다 !
미션동안 많은 개선을 해주셔서 코드가 이전보다 보기 정말 좋아진 것 같아요 😄 
마지막까지 화이팅해주세요! 🔥

2021-12-12 03:55 UTC, leeyohan93 commented on src/main/java/nextstep/subway/auth/domain/AuthenticationPrincipal.java
> +    boolean onlyLoginUser() default true;
@AuthenticationPrincipal 에 설정 값을 추갛여 비로그인 유저가 넘어올 수 있다는 것을 코드에 반영해주셨네요 ! 💯

2021-12-12 03:55 UTC, leeyohan93 commented on src/main/java/nextstep/subway/path/domain/AgeFarePolicy.java
> +            .orElseThrow(() -> new InvalidArgumentException("포함되는 정책이 없습니다."));
유저의 나이정보가 잘못되었다고 표현되는게 더 좋을 것 같아요 :)

2021-12-12 03:55 UTC, leeyohan93 commented on src/main/java/nextstep/subway/path/domain/AgeFarePolicy.java
> +public enum AgeFarePolicy {
나이 요금 정책에 대한 부분을 enum으로 구현해주셨네요 👍 
추가적으로 다형성과 인터페이스를 활용하는 방향으로 생각해볼 수도 있을 것 같아요!
예를 들어 FarePolicy라는 인터페이스를 만들고, 각 정책들에 맞게 인터페이스를 구현해주는 방식으로 구현할 수도 있겠네요 😄 

그렇다면 어떤 때에 enum을 사용하고, 인터페이스를 사용하는게 좋을까요 ?
저는 인터페이스를 사용하는 기준을 아래와 같이 두고 있습니다!
```text
1. 정책을 구현(계산)하는데 외부 의존성이 필요할 때
2. 정책마다 다른 구현(계산)이 필요할 때
```

지금의 요구사항에서는 enum으로 충분한 것 같으니 참고만 부탁드릴게요 🙏

2021-12-12 03:55 UTC, leeyohan93 commented on src/main/java/nextstep/subway/path/infrastructure/WeightedMultiStationGraph.java
> +    private Fare getAdditionalFare(GraphPath<Station, SectionEdge> path) {
해당 클래스에서 가까운 노선을 찾는 것과 운임요금을 부과하는 것 두가지의 기능을 수행하고 있네요 !
한 클래스당 하나의 책임을 수행하도록 개선해보는건 어떨까요 ? 🤔

2021-12-13 02:11 UTC, SHINMJ commented on src/main/java/nextstep/subway/path/infrastructure/WeightedMultiStationGraph.java
> +    private Fare getAdditionalFare(GraphPath<Station, SectionEdge> path) {
저도 계속 고민하고 있던 부분입니다!! 어디서 운임요금을 부과할 것인가!! 좀더 고민해보아야 겠습니다!!!

2021-12-13 16:25 UTC, leeyohan93 approved these changes
명진님 마지막까지 피드백을 반영하여 미션을 잘 마무리 해주셨네요 💯
여러 이야기를 나눌 수 있어서 정말 즐거운 시간이였습니다. 😄
소소한 코멘트들을 남겨놓았으니 확인부탁드리고, 다음 미션도 더 좋은 모습으로 완주하시리라 믿습니다.🔥
감사합니다.

2021-12-13 16:25 UTC, leeyohan93 commented on src/main/java/nextstep/subway/path/domain/Path.java
> +            .orElse(Fare.valueOf(0));
stream의 max를 이용해볼 수도 있겠네요 ! 그리고 Faire는 요금을 의미하는 값 객체이기 때문에 Comparable 인터페이스를 구현하는 것도 고민해볼 수 있을 것 같습니다 :)

```suggestion
        return includedLines.stream()
                .map(Line::getAdditionalFare)
                .max(Comparator.comparingInt(Fare::get))
                .orElse(Fare.valueOf(0));
```

2021-12-13 16:25 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/domain/Fare.java
> +    private Integer fare = FARE_MIN_NUMBER;
금액을 의미하는 Money 객체를 만들어볼 수도 있을 것 같아요

보통 금액을 다룰때는 BigInteger를 주로 많이 사용합니다 :)

그렇지만 지하철 요금이라 Integer로도 충분할 것 같기도 하네요 😄

2021-12-13 16:25 UTC, leeyohan93 commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private final Fare totalFare;
totalFare를 Path의 상태로 저장하고 있을 필요가 있을까요 ?
지금 현재 totalFare가 사용되는 곳은 getter 뿐이기 때문에 적합한 상태가 아닐 수도 있을 것 같네요 🤔 
만약 캐싱의 용도로 사용한다면 그에 대한 처리를 추가해주어도 좋을 것 같아요 :)

2021-12-13 16:25 UTC, merged