1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #441
Opened 2021-12-12 03:47 UTC by minseokLim

잘 부탁드립니다! 😄

2021-12-12 12:19 UTC, minsungryu requested changes
민석님 안녕하세요, 같이 미션 진행하게 되었네요! 반갑습니다 :)
1단계 잘 구현해주셨는데요, 몇 가지 코멘트를 남겼으니 확인해주시고
다시 리뷰 요청 부탁드릴게요~!

2021-12-12 12:19 UTC, minsungryu commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +    void 지하철_구간을_관리() {
요구사항에 맞게 테스트가 분리되는게 좋지 않을까요?

2021-12-12 13:22 UTC, minseokLim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(RuntimeException::new);
기존에 있던 함수를 private로 바꾸고 위치를 밑으로 이동시켜주기만 한거라서...^^; 수정하도록 하겠습니다.

2021-12-12 13:27 UTC, minseokLim commented on src/test/java/nextstep/subway/line/domain/LineTest.java
> +            .isInstanceOf(RuntimeException.class);
이전 미션 3에서는 커스텀 익셉션을 사용하였으나, 미션에서는 오버엔지니어링인 감이 없지 않아 있다는 피드백을 받은 적이 있어서...^^; 사실 저도 커스텀 익셉션을 선호합니다! 수정하도록 하겠습니다.

2021-12-12 13:30 UTC, minseokLim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +            Objects.equals(name, station.name);
이 역시 제가 작성한게 아니라 option + command + L 로 스타일 잡다가 이렇게 되었네요^^;
사실 저는 엔티티에서 equals와 hashcode를 아예 재정의하지 않거나(어차피 영속화되면 동일한 객체가 되므로) 하더라도 id를 제외한 비즈니스 키를 통해서 하는 편입니다. 저는 이 경우에는 아예 재정의하지 않는 게 가장 좋아보이는데 의견 부탁드립니다.

2021-12-12 13:31 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
넵!

2021-12-12 13:31 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +                .ifPresent(it -> it.divideBy(section));
넵!

2021-12-12 13:34 UTC, minseokLim commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +    void 지하철_구간을_관리() {
강의내용에 따르면, 인수테스트는 비용이 많이 발생하기 때문에 최대한 시나리오 기반으로 작성하고 통합하여 중복을 줄이고, 예외상황에 대한 검증은 단위테스트에서 한다로 이해했거든요. 물론 항상 그게 정답일 수는 없겠지만 이런 식으로도 할 수 있다~라고 강의에서 들어서요. 분리한다면 어떻게 분리를 하면 좋을까요?

2021-12-12 13:35 UTC, minseokLim commented on src/test/java/nextstep/subway/line/domain/SectionTest.java
> +@DataJpaTest
듣고보니 그렇군요!^^;

2021-12-12 14:15 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
근데 생각해보니까 여기선 그럴 필요가 없겠는데요? Section 생성자에서 line을 받다보니 이미 Section은 line과 연결되어있습니다. 구간 삭제 시에만 양방향에 대해 고려해주면 될 것 같습니다.

2021-12-12 14:40 UTC, minseokLim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +            Objects.equals(name, station.name);
일단 저는 아예 재정의하지 않는 쪽으로 변경하도록 하겠습니다^^;

2021-12-12 14:50 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
Section 생성자에 line이 포함되어있기 때문에 이미 연결되어있습니다. 구간 삭제 시에만 신경써주면 될 것 같습니다.

2021-12-12 14:53 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
근데 사실 삭제도 orphanRemoval = true 이 있어서 따로 코드가 없어도 되지 않을까요? 싶습니다만 일단 반영해보도록 하겠습니다.

2021-12-13 10:05 UTC, minsungryu approved these changes
민석님 안녕하세요, 1단계 잘 구현해주신 것 같습니다!
몇 가지 코멘트를 남겼는데요
한 번 확인해주시고 다음 단계 진행해주시면 좋을 것 같습니다~!

2021-12-13 10:05 UTC, merged

2021-12-13 10:16 UTC, minseokLim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +            Objects.equals(name, station.name);
영속화 이전에 발생할 수 있는 문제 때문인가보군요. 수정하도록 하겠습니다!

2021-12-13 10:34 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
Section에 생성자가 기본생성자와 line이 포함된 2개의 생성자만 존재합니다. 보통 JPA Entity의 기본생성자는 protected로 선언하고 나머지 생성자를 통해 객체를 생성하는데, line이 포함된 생성자를 통해서만 객체를 생성한다고 생각했습니다. 물론 나중에 추가적인 다른 생성자가 생성될 가능성도 없진 않지만, 그렇다고 Section 엔티티에 line필드에 대한 setter 함수를 생성하는 건 옳지 않은 선택이라고 생각했습니다. 어렵네요...; 민성님 말씀도 맞는 얘기 같긴 한데 그렇다고 entity에 setter를 만들고 싶진 않고... dafault (package private) 접근제어자를 가진 setter를 만들어서 해결하도록 하겠습니다.

2021-12-13 10:52 UTC, minseokLim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +            Objects.equals(name, station.name);
id를 이용해 equals와 hashcode를 재정의하게되면, SectionTest를 DataJpaTest로 바꿔야합니다. jpa를 안써서 id가 전부 null이거든요... 제대로된 비교가 되질 않습니다. 이런 부작용도 있으니 일단 재정의하지 않는 것으로 하겠습니다^^;;;

2021-12-13 10:59 UTC, minseokLim commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +    void 지하철_구간을_관리() {
강의에서도 이렇게 통합하는 게 반드시 정답이다라고 하진 않았습니다. 말씀하신 부작용에 저도 충분히 공감합니다. 비용이 많이 발생하는 인수테스트를 이런 식으로 통합하는 경우도 있다~라고 경험한 데에 의의를 두지 않으면 되지 않을까 싶습니다. 미션의 요구사항이 'LineSectionAcceptanceTest 리팩터링 - 인수테스트 통합' 이었음을 이해해주시면 감사하겠습니다^^;

2021-12-14 09:41 UTC, minsungryu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
저는 생성자와는 관계없이 이 메서드가 public으로 외부에 공개된 인터페이스인 점, JPA 양방향 연관관계 사이에서 객체 그래프가 데이터와 일치하지 않을 경우가 생길 여지가 있어서 말씀을 드렸던건데요,
무분별한 setter는 문제지만 엔티티는 가변 객체라서 상태를 변경해주는 메서드가 있다고 해서 잘못된 건 아닐 것 같습니다ㅎㅎ
또한 앞서 말씀드린대로 양방향 연관관계 편의 메서드와 장단점, 주의할점에 대해 알아보시면 좋을 것 같습니다.

2021-12-14 09:43 UTC, minsungryu commented on src/main/java/nextstep/subway/station/domain/Station.java
> +            Objects.equals(name, station.name);
넵, 재정의 하실 때는 기본키를 권장드려요. 비즈니스 키는 상황에 따라 바뀌기 때문에 일반적으로 추천드리진 않는 것 같습니다.
말씀하신대로 id를 제외한 비즈니스키(역 이름)로 구현하게 되면 같은 이름의 역(환승역 또는 제3의 역)으로 인해 문제가 생길 수 있스빈다.
DataJpaTest가 아니더라도 단위 테스트에서 id를 직접 지정해주는 방식으로도 문제를 해결할 수 있을 것 같네요.

2021-12-14 10:22 UTC, minseokLim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +            Objects.equals(name, station.name);
id를 직접 지정해주면 됐네요. 제가 생각이 짧았습니다. 수정하는 게 낫겠네요ㅋ 수정하도록 하겠습니다.

2021-12-14 10:23 UTC, minseokLim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(final Section section) {
넵! 감사합니다 😄