2단계 - 경로 조회 기능
next-step/atdd-subway-service pull request #456
Opened 2021-12-13 13:43 UTC by sungdukim

안녕하세요 현구님,

`Outside In` 방식으로 경로 조회 기능 구현해보았습니다.

이번 미션도 잘부탁드리겠습니다!

2021-12-14 01:27 UTC, kang-hyungu requested changes
성두님 몇 가지 간단한 피드백 남겼습니다.
수정해보시고 리뷰 재요청주세요

2021-12-14 01:27 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
>  package nextstep.subway.line.acceptance;
테스트가 깨지는 부분 확인해주세요

![image](https://user-images.githubusercontent.com/15669435/145914431-af93da1f-2775-426c-a8dd-8662b9d7aac1.png)

2021-12-14 01:27 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
>      public static ExtractableResponse<Response> 지하철_노선_생성_요청(LineRequest params) {
http를 호출하기 위한 rest assured 코드가 인수 테스트 클래스마다 중복해서 나타나고 있네요
중복을 제거할 방법 없을까요?

2021-12-14 01:27 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
>  package nextstep.subway.line.acceptance;
클린코드 25p

의미 있게 구분하라
컴파일러나 인터프리터만 통과하려는 생각으로 코드를 구현하는 프로그래머는 스스로 문제를 일으킨다.
예를 들어, 동일한 범위 안에서 다른 두 개념에 같은 이름을 사용하지 못한다.
...

컴파일러를 통과할지라도 연속된 숫자를 덧붙이거나 불용어(noise word)를 추가하는 방식은 적절하지 못하다.
이름이 달라야 한다면 의미도 달라져야 한다.

연속적인 숫자를 덧붙인 이름(a1, a2 ... aN)은 의도적인 이름과 정반대다.
이런 이름은 그릇된 정보를 제공하는 이름도 아니며, 아무런 정보를 제공하지 못하는 이름일 뿐이다.
저자 의도가 전혀 드러나지 않는다.

2021-12-14 01:27 UTC, kang-hyungu commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +        graph = new WeightedMultigraph(DefaultWeightedEdge.class);
제네릭 타입을 표시해주세요
DijkstraShortestPath 객체도 같이 챙겨주세요

2021-12-14 11:13 UTC, sungdukim commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
>  package nextstep.subway.line.acceptance;
제 로컬에서 자바8로 실행하고 있는데 테스트 잘 동작하고 있어서 이 부분은 제외하고 진행하겠습니다.

2021-12-15 05:55 UTC, kang-hyungu approved these changes
성두님 피드백 반영 잘해주셨습니다.
pr은 머지 처리하겠습니다. 다음 미션 진행해주세요.

2021-12-15 05:55 UTC, kang-hyungu commented on src/test/java/nextstep/subway/utils/RestAssuredUtil.java
> +    public static ExtractableResponse<Response> jsonPost(final Object params, final String path) {
메서드명에서 json은 제외해도 되지 않나요?
메서드 내부에서 어떻게 처리하는지 메서드명으로 표현할 필요는 없습니다.

2021-12-15 05:55 UTC, merged