Step2 - 경로 조회 기능
next-step/atdd-subway-service pull request #476
Opened 2021-12-15 16:10 UTC by Junhong-Kim

안녕하세요.
경로 조회 기능 코드리뷰 요청드립니다!
감사합니다. ☺️

2021-12-16 14:17 UTC, minsungryu requested changes
준홍님 안녕하세요!
2단계도 잘 구현해주신 것 같습니다 👍 
비교적 간단한 내용이지만 몇 가지 궁금한 점이 있어서 코멘트를 남겼는데요
확인해주시고 다시 리뷰 요청 부탁드릴게요 :)

2021-12-16 14:17 UTC, minsungryu commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    @DisplayName("출발역과 도착역의 최단 경로 조회2")
비슷한 테스트가 두 개 있는데 어떤 의도로 분리하신건지 알 수 있을까요?
노선이 변경되는 경우(환승)를 고려하신 것일거라 지레 짐작해봤는데요, 만약 그렇다면 테스트 이름에 명시해주셔도 좋지 않을까요?ㅎ

2021-12-16 14:17 UTC, minsungryu commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    @DisplayName("존재하지 않은 출발역이나 도착역을 조회 할 경우 최단 경로 조회를 실패한다.")
구분이 모호할 수는 있겠지만 가급적이면 인수 테스트는 시나리오 기반으로 작성하고
예외 케이스는 단위 테스트를 통해 검증해보는 것도 좋지 않을까요?
(물론 인수 시나리오에 실패 케이스가 명시되어 있을 수도 있긴 하지만요)

2021-12-16 16:18 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/map/domain/Map.java
> +public class Map {
앗.. 다른 클래스명과 중복되어 혼돈될 수 있다는 점을 생각하지 못했네요! 😅
클래스명 변경했습니다.

2021-12-16 16:19 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    @DisplayName("출발역과 도착역의 최단 경로 조회2")
넵, 환승을 고려해서 테스트를 따로 작성했습니다. 😊
테스트 이름 수정했습니다!

2021-12-16 16:19 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    @DisplayName("존재하지 않은 출발역이나 도착역을 조회 할 경우 최단 경로 조회를 실패한다.")
예외 케이스 단위 테스트 추가했습니다.
감사합니다! 👍

2021-12-17 04:22 UTC, minsungryu approved these changes
준홍님, 2단계 구현 멋지게 잘 해주셨네요 👍 
피드백 잘 반영해주셔서 감사합니다.
다음 단계에도 잘 부탁드릴게요~ PR은 merge 하겠습니다!

2021-12-17 04:22 UTC, merged