2단계 - 경로 조회 기능
next-step/atdd-subway-service pull request #494
Opened 2021-12-18 12:22 UTC by daehyun0

안녕하세요 민호님!
2단계 리뷰 요청드립니다 :)
자바와 백엔드 모두에 익숙하지 않아서, 부족한 부분이 있다면 작은거라도 부담없이 알려주시면 감사하겠습니다 👍  :D

**eca827d80ee8ac06d8127b99445da78a221f6dcd** 커밋의 경우에 민호님이 알려주신 경우를 토대로 테스트를 추가했는데요.
Section의 생성자에 Line이 있어서 무조건 값이 있다 라고만 생각하고, 다른 경우를 생각하지 못했었어요.
만약에 저와 같은 실수를 하시는 분이 있다면 LineTest.addSection_otherLineSection_failed의 시나리오를 TDD로 구현을 요청해주시면 더 이해하기 쉽지 않을까 조심스럽게 제안드립니다.

주말에 수고가 많으십니다. 감사합니다!

2021-12-19 13:44 UTC, 5minho requested changes
안녕하세요 대현님!
2단계 미션 진행해주시느라 고생많으셨습니다!
몇가지 더 개선해보면 좋을점 코멘트로 남겼는데요
확인부탁드려요~

2021-12-19 13:44 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
비정상적인 상황 같은데 그냥 return 하기보다는 예외를 던지는게 좋을거 같습니다!

2021-12-19 13:44 UTC, 5minho commented on src/main/java/nextstep/subway/path/application/PathService.java
> +		Sections sections = new Sections(sectionRepository.findAllByUpStationIdOrDownStationId(
source 와 target 이랑 연결된 구간들만 있으면 될까요?
전 구간이 필요하지 않을까요?

2021-12-19 13:44 UTC, 5minho commented on src/main/java/nextstep/subway/path/application/PathService.java
> +		GraphPath<Station, DefaultWeightedEdge> graphPath = pathFinder.findShortestPath(sourceStation, targetStation,
우리가 제어할 수 없는 외부 라이브러리를 domain 바깥으로 꺼내는것 보다는 PathFinder 내에서만 사용하고 (외부 라이브러리의 영향도를 PathFinder 로 제한하고) 외부에 반환할 때는 우리 도메인 객체로 변환해서 반환하는겉 어떨까요?

2021-12-19 13:44 UTC, 5minho commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +			throw Exceptions.SOURCE_AND_TARGET_EQUAL.getException();
예외의 메시지로 source, target 의 id 같은 정보를 넘길 수 있다면 트러블슈팅에 도움이 될텐데 그게 좀 아쉽네요.

2021-12-19 13:45 UTC, 5minho commented
> 만약에 저와 같은 실수를 하시는 분이 있다면 LineTest.addSection_otherLineSection_failed의 시나리오를 TDD로 구현을 요청해주시면 더 이해하기 쉽지 않을까 조심스럽게 제안드립니다.

네 대현님 엄청 좋은생각이네요 👍  제안 감사합니다!!!!

2021-12-19 15:52 UTC, daehyun0 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +		GraphPath<Station, DefaultWeightedEdge> graphPath = pathFinder.findShortestPath(sourceStation, targetStation,
사실은 Section들을 검색하고 pathFinder 안에서 해당 섹션들의 Line을 가져다가 다시 Line의 섹션들을 가져오는 일을 했는데..  
생각해보니 애초에 도메인에서 그런 작업들을 하는게 이상하네요..! 
N+1 문제를 겪어보지는 못했지만 발생할 것 같고.. 해서 @Query를 이용해서 LineRepository에 해당 메소드를 추가했습니다.

2021-12-19 16:25 UTC, daehyun0 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +		Sections sections = new Sections(sectionRepository.findAllByUpStationIdOrDownStationId(
Sections만 얻어다가 PathFinder안에서 Entity의 getSections를 이용해서 가져오고 있었는데요
PathFinder에서 직접 레포에 접근하지는 않지만 어쨌든 레이어를 침범한다는 점 때문에 PathService.SectionRepository에서 가져오도록 수정했습니다! 감사합니다!

2021-12-19 17:01 UTC, daehyun0 commented
말씀해주신걸 들으면 백번 맞는 말인데, 만들고 있다보면 무슨생각인지 놓치게 되네요.
리뷰 감사합니다! :D

2021-12-20 13:54 UTC, 5minho commented on src/main/java/nextstep/subway/path/application/PathService.java
> +		Sections sections = new Sections(sectionRepository.findAllByUpStationIdOrDownStationId(
![image](https://user-images.githubusercontent.com/20471248/146777248-29cec3d5-d573-4eda-a453-9aac77203d07.png)

헉 대현님 제가 전 구간이 필요하다고 했던 이유는 source 와 target 이 연결된 구간들만 있으면 정확하게 최단거리를 구할 수 없어보였기 때문이에요!
위와 같은 상황에서 S1 에서 S5 로 가는 최단 경로는 S1 -> S2 -> S3 -> S5 인데 위와 같은 방법으로 하면 S2 -> S3 구간이 포함이 안될 수도 있기 때문에 위와 같은 피드백을 드린거였습니다.

`lineReposirtory.findAll()` 메서드로 전 노선의 구간이 필요할거 같아요! 

혹시 제가 잘못 생각하고 있는거라면 언제든지 DM 주세요~

2021-12-20 14:19 UTC, 5minho approved these changes
안녕하세요 대현님!
피드백 수정해주신거 확인했습니다!
좀 더 수정해보면 좋을 것들 코멘트로 남겼는데요.
다음 미션 진행하시면서 수정해도 괜찮을거 같습니다!
이번 단계는 이만 머지하겠습니다~ 고생하셨습니다!

2021-12-20 14:19 UTC, 5minho commented on src/main/java/nextstep/subway/path/domain/FindShortestPathResult.java
> +public class FindShortestPathResult {
제가 https://github.com/next-step/atdd-subway-service/pull/494#discussion_r771950473 이렇게 피드백을 드렸었는데

수정해주신 것도 결국 FindShortestPathResult 에서 외부라이브러리를 사용하기 때문에 외부라이브러리의 사용을 PathFinder 내로 제한하지 못한거 같아요

제 생각에는 `GraphPath<Station, DefaultWeightedEdge>` 를 PathFinder 바깥으로 꺼내는것 보디 
FindShortestPathResult 내에 최단 경로를 구성하는 Station 리스트와 최단 경로 값 정도 들고 있으면 될거 같습니다.
`FindShortestPathResult` 는 최단 경로 결과의 유효성 체크정도 해주고요 

* 최단 경로는 1 이상이어야 한다.
* 최단 경로를 구성하는 역들의 개수는 2 이상이어햐 한다.

2021-12-20 14:19 UTC, 5minho commented on src/main/java/nextstep/subway/common/exception/CustomExceptionBase.java
> +	}
캐시되어 있는 Exception 들에 대해서 내부 메시지를 바꿔주게 되면, 예외를 던질때 만약 메시지를 세팅해주지 않으면 이전에 세팅되어 있던 메시지가 나오거나 하지 않을까요? 🤔

예외 핸들링이 이번 미션의 주요 주제가 아니므로 이 문제를 해결하기 위해 너무 많은 시간을 쏟지 않으셔도 되세요.
그리고 앞으로 개발을 할 때 에외를 캐시 할 때는 이런 문제점이 있다 정도만 얻어가도 좋을거 같아요.

2021-12-20 14:19 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/SectionRepository.java
> +	@Query(value = "SELECT DISTINCT se FROM Section se INNER JOIN Line l ON se.line.id = l.id INNER JOIN Station st ON st.id = se.upStation.id OR st.id = se.downStation.id WHERE st.id = :sourceId OR st.
https://github.com/next-step/atdd-subway-service/pull/494#discussion_r772382187
확인 부탁드립니다!

2021-12-20 14:23 UTC, merged

2021-12-20 16:28 UTC, daehyun0 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +		Sections sections = new Sections(sectionRepository.findAllByUpStationIdOrDownStationId(
앗 제가 완전히 이해를 잘못하고 있었네요!! S2-> S5 사이에 노선과 구간을 추가한 테스트를 추가했습니다!