Step1 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #523
Opened 2022-06-01 11:36 UTC by KangSeongHyo

안녕하세요~!!

1단계 - 인수테스트 기반 리팩터링 리뷰 부탁드립니다

감사합니다~!!

---
저 질문이 하나 있습니다~!! 

테스트 중에 Mock 관련된 빈객체 추가해서 Size 보는 요상한(?) 테스트가 있던데 
미션 내용에는 관련된 부분이 따로 없어서 이번 단계에서 처리하는게 아닌가 싶어서
테스트가 있어 오류 안나도록만 처리했습니다.
혹시 이번 단계에서 처리해야 해야하는 부분이라면 전달해주시면 처리하겠습니다~!!

2022-06-02 15:45 UTC, chae-yh requested changes
성효님 안녕하세요! 인수테스트 기반 TDD 리뷰를 맡은 채영훈 입니다! 리뷰가 늦어 죄송합니다...
코드는 전체적으로 잘 리팩터링 해주셨습니다 👍 
다만 조금 더 고민해주시면 좋을만한 내용들이 있어 코멘트 드렸으니 확인 부탁드립니다.

잘 부탁드립니다! 감사합니다 : )

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
> -        List<Station> stations = getStations(line);
service layer의 로직이 많이 사라졌네요 👍

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        List<StationResponse> stations = persistLine.getStations()
해당 StationResponse를 list로 만들어주는 것은 LineResponse 안에서 해줘도 좋지 않을까요...? 아래의 메서드에서도 반복적으로 나오고 있네요!

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
>          List<Line> persistLines = lineRepository.findAll();
이 메서드는 데이터 조회만 하는 메서드인데 트랙잭션 처리를 할 필요가 있을까요...?

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
>          return lineRepository.findById(id).orElseThrow(RuntimeException::new);
단순히 Runtime Exception보다는 구체적인 익셉션과 메시지를 전달해주어도 좋을 것 같습니다!

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/exception/SectionCreateException.java
> +public class SectionCreateException extends RuntimeException{
혹시 IllegalStateException 과 같이 이미 존재하는 익셉션에 메시지로 내용을 구체화하는 방법과 비교하여 익셉션을 정의하는 것은 어떤 장점이 있을까요...?

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/collections/Sections.java
> +public class Sections {
일급 컬렉션으로 잘 분리해주셨습니다 👍

2022-06-02 15:45 UTC, chae-yh commented on src/test/java/nextstep/subway/line/domain/collections/SectionsTest.java
> +class SectionsTest {
단위 테스트 좋습니다 👍

2022-06-02 15:45 UTC, chae-yh commented on src/test/java/study/unit/MockitoExtensionTest.java
> +                .thenReturn(Lists.newArrayList(new Line("신분당선", "color", new Station("정자"), new Station("판교"), 10)));
질문 주신 내용 여기에서 답변드립니다!

저 질문이 하나 있습니다~!!

```
테스트 중에 Mock 관련된 빈객체 추가해서 Size 보는 요상한(?) 테스트가 있던데
미션 내용에는 관련된 부분이 따로 없어서 이번 단계에서 처리하는게 아닌가 싶어서
테스트가 있어 오류 안나도록만 처리했습니다.
혹시 이번 단계에서 처리해야 해야하는 부분이라면 전달해주시면 처리하겠습니다~!!
```

혹시 이 부분에 대한 말씀이시면, Mock을 만드는 여러가지 방법에 대해 샘플 형식으로 보여주는 것 같습니다! 그래서 이정도로 작성해주셔도 좋을 것 같습니다 👍

2022-06-02 15:45 UTC, chae-yh commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +     * Feature: 지하철 노선 관련 기능
강의에서 나온 인수테스트 통합 형태로 작성해보는 것은 어떨까요...?
이 경우 when-then이 반복적으로 자주 나오는데, 이 때 Dynamic Test 를 사용해보는 것도 좋을 것 같습니다 : )
https://tecoble.techcourse.co.kr/post/2020-07-31-dynamic-test/

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/collections/Sections.java
> +    public Station findDepartStation() {
Sections 클래스에서만 쓰는데 private 로 선언해도 되지 않을까요...?

2022-06-02 15:45 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/collections/Sections.java
> +        return stations.stream().anyMatch(it -> it.equals(station));
it는 어떤 의미일까요...? 축약어를 사용하지 않는 방향으로 작성해봐도 좋을 것 같습니다!

2022-06-03 08:31 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        List<StationResponse> stations = persistLine.getStations()
아 넵넵 변경했습니다~!!

2022-06-03 08:41 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/line/domain/collections/Sections.java
> +    public Station findDepartStation() {
앗..  이부분은 한다면서 깜박했었네요
수정했습니다~!!

2022-06-03 09:02 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/line/application/LineService.java
>          List<Line> persistLines = lineRepository.findAll();
아 트랜잭션 설정을 잊고 있었네요..
해당부분 수정했습니다.~!!

2022-06-03 09:03 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/line/application/LineService.java
>          return lineRepository.findById(id).orElseThrow(RuntimeException::new);
이것도 수정한다면서 깜박했네요 변경했습니다~!! 

이부분은 단순조회 여서 IllegalArgumentException 으로 처리했는데 
어떻게 보시는 지 궁금합니다~!!

2022-06-03 09:07 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/line/exception/SectionCreateException.java
> +public class SectionCreateException extends RuntimeException{
개인적으로 운영 중 오류 발생시  로그 확인할때 익셉션 명칭이 더 먼저 눈에 들어와서
커스텀 익셉션 으로 할때 좀 더 어느 비즈니스 로직에서 오류가 났겠구나 라는 직관적인게 장점이 아닌가 싶습니다~!!
 
그렇지만 항상 고민이 되는 부분은 관련된 제공되어있는 익셉션이 있을때 
어느걸 써야할지 선택에 시간을 쓰게 되는데 
리뷰어님은 어느기준으로 하시는지 궁금합니다~

2022-06-03 09:10 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/line/domain/collections/Sections.java
> +        return stations.stream().anyMatch(it -> it.equals(station));
아 이거는 ㅎㅎ 지적해주실 것 같아서 기존 로직 그대로 두었는데
it 이 원래는 station으로 하려고 했었는데
위에 또 파라미터가 station이라서 명칭이 겹쳐 
어떤 이름을 쓰는게 좋을지 난감하더라구요
리뷰어님은 이런경우 어떻게 쓰시는지 궁금합니다.
(일단 stationn 으로 변경해보았습니다.)

2022-06-03 11:39 UTC, KangSeongHyo commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +     * Feature: 지하철 노선 관련 기능
오 TestFactory 라는 것도 있군요 해당 부분을 사용해서 변경해보았습니다~!!

그런데 아직 인수테스트 통합 관련 강의가 진행되지 않아서
강의 나온 인수테스트 통합 형태로 작성해보는 부분이 잘 모르겠는데 어떤 부분인가요?

지난 미션 중에 통합에 대한 내용이 있어서
개인적으로 생각한 부분은 인수테스트 통합이 유저 시나리오 형태로 테스트 해라가 아닌가
싶어서 일단 조금 더 수정해보았습니다.~

2022-06-04 10:33 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
>          List<Line> persistLines = lineRepository.findAll();
@Transactional(readOnly = true) 옵션을 주어도 좋을 것 같습니다!

2022-06-04 10:35 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
>          return lineRepository.findById(id).orElseThrow(RuntimeException::new);
익셉션이 상태를 잘 표현하네요 좋습니다 👍

2022-06-04 10:37 UTC, chae-yh commented on src/main/java/nextstep/subway/line/exception/SectionCreateException.java
> +public class SectionCreateException extends RuntimeException{
보통은 IllegalStateException 나 IllegalArgumentException 를 많이쓰고, 제공된 익셉션은 비교적 명확하게 오류 상태를 표현하기 때문에 선택하는 것에 크게 이슈는 없었던 것 같습니다!

2022-06-04 10:40 UTC, chae-yh commented on src/test/java/nextstep/subway/line/acceptance/LineAcceptanceTest.java
> +     * Feature: 지하철 노선 관련 기능
강의에 나온 행태로, 시나리오 기반으로 테스트를 작성해보면 어떨까.. 하여 여쭤봤던 부분입니다!
```
Feature: 지하철 구간 관련 기능

  Background 
    Given 지하철역 등록되어 있음
    And 지하철 노선 등록되어 있음
    And 지하철 노선에 지하철역 등록되어 있음

  Scenario: 지하철 구간을 관리
    When 지하철 구간 등록 요청
    Then 지하철 구간 등록됨
    When 지하철 노선에 등록된 역 목록 조회 요청
    Then 등록한 지하철 구간이 반영된 역 목록이 조회됨
    When 지하철 구간 삭제 요청
    Then 지하철 구간 삭제됨
    When 지하철 노선에 등록된 역 목록 조회 요청
    Then 삭제한 지하철 구간이 반영된 역 목록이 조회됨
```

2022-06-04 10:43 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/collections/Sections.java
> +        return stations.stream().anyMatch(it -> it.equals(station));
음.. 사실 저라면 여기에 `stations.contains(station)` 으로 사용해서 station의 변수를 두개이상 만들지 않을 것 같습니다!
개인적으로 의견은 input parmeter인 station을 candidateStation 등으로 바꿔도 좋을 것 같습니다 : )

2022-06-04 10:50 UTC, chae-yh approved these changes
성효님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 
조금 생각해보시면 좋을만한 내용들은 추가로 코멘트 드렸으나, 이번 스텝을 이정도로 merge 해도 될 것 같습니다!

다음 미션 진행 부탁드립니다! 감사합니다 : )

2022-06-04 12:21 UTC, merged