인수테스트 기반 TDD 4단계 : 요금조회 PR 요청 드립니다. :)
next-step/atdd-subway-service pull request #550
Opened 2022-06-10 15:03 UTC by ssonsh

안녕하세요 동휘님 :) 벌써 이번 미션 마지막 단계 PR이네요!

3단계 미션에서 말씀주셨던 사항들 먼저 반영하고 4단계에서 요구하는 사항들에 대해 진행해보았습니다.
이번 과정에서 Inside Out, Outside In 과 같은 접근 방법에 대해 조금 더 명확하게 알게 되었고 이런 방법들을
ATDD와 TDD 로 접근하면서 조금씩 감을 잡아가고 있는 것 같다는 생각이 들면서도
여전히 어렵더군요 ㅎㅎ 

이번 단계 피드백도 잘 부탁드립니다. :)

2022-06-10 17:18 UTC, dhmin5693 requested changes
미션 잘 수행해주셨네요 😄

다만 마지막 미션이니만큼 조금 더 생각해볼만한 여지를 남겨두었어요.
확인 후 재요청 부탁드립니다. 🙏

2022-06-10 17:18 UTC, dhmin5693 commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        if (Objects.isNull(credentials)) {
저는 `Objects.isNull`을 권장하지 않는 편입니다.
Object.isNull이나 == null 비교나 가독성 차이가 크지 않다고 생각하거든요.

이 메소드의 javadoc을 확인해볼까요?
```
API Note:
This method exists to be used as a java.util.function.Predicate, filter(Objects::isNull)
```
`Predicate` 를 위해서 만들었다고 쓰여있네요.

-----

위랑은 별개로, 여긴 보안상 허점이 될 가능성이 있습니다.
만약 회원만 사용 가능한 기능이 있다 해도 인증값을 null로 전달하면 무조건 비회원으로 넘어가게 됩니다.

`AuthenticationPrincipal` 에 required 와 같은 필드를 두어서 회원 전용 여부를 표기하면 어떨까요?

2022-06-10 17:18 UTC, dhmin5693 commented on src/main/java/nextstep/subway/fare/calculator/FareCalculator.java
> +public class FareCalculator {
static 메소드만 활용하는 클래스는 생성하지 못하도록 처리해주세요.

2022-06-10 17:18 UTC, dhmin5693 commented on src/main/java/nextstep/subway/fare/calculator/FareCalculator.java
> +    public static int calculate(Lines lines, Path path) {
`StringUtils.isEmpty()` 처럼 간단한 로직이 아니라 지금처럼 복잡한 로직을 서비스 메소드에서 의존하고 있으면 단위 테스트가 어려워지는 문제가 있어요.

요금은 그 자체로 도메인 객체화 할 수 있는 요소라고 생각이 듭니다.
인터페이스를 활용해서 다형성을 구현하면 enum도 최소화할 수 있을 것 같아요.
리팩토링 해보시는걸 추천드립니다.

2022-06-10 17:18 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Fare.java
> +public class Fare {
이름에서 `추가 요금`의 느낌이 나면 더 좋지 않을까요?

2022-06-10 17:18 UTC, dhmin5693 commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        if (loginMember.isLogin()) {
`loginMember.isLogin()` 이라는 구문이 살짝 어색해보여요.
`LoginMember`는 로그인 한 사용자만 사용할 수 있을법한 이름이거든요.
현재 상황에선 비로그인 사용자도 `LoginMember`를 사용하고 있습니다.

2022-06-11 01:48 UTC, ssonsh commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        if (Objects.isNull(credentials)) {
Objects.isNull, Objects.nonNull 에 대한 부분이 그저 객체의 null 체킹용도로 사용될 수 있구나로 접근했는데
사실 사용의 용도가 Predicate 를 위해 만들어졌다는 것을 이번 피드백을 통해 알게되었네요.
실제로 어떤 역할을 하는 녀석인지 들여다 봤으면 충분히 알 수 있었는데 스스로가 조금 아쉽다고 느껴집니다 ㅎ

말씀주신대로 == null != null 과 가독성에 차이는 없다고 생각됩니다. :)

2022-06-11 01:50 UTC, ssonsh commented on src/main/java/nextstep/subway/fare/calculator/FareCalculator.java
> +public class FareCalculator {
한번더 꼼꼼히 봤으면 챙길 수 있었던 부분일 것 같은데 스스로가 아쉽습니다 ㅠ 
포인트 잘 잡아주셔서 감사합니다. :)

2022-06-11 01:55 UTC, ssonsh commented on src/main/java/nextstep/subway/line/domain/Fare.java
> +public class Fare {
개인적으론 Line 노선의 Fare 라고 해서 노선의 요금이면 충분히 의미전달이 되겠구나 했지만
사실 추가 요금의 개념으로 명확히 명명하는게 더 나은 방향이라 생각됩니다! :)

2022-06-11 01:58 UTC, ssonsh commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        if (loginMember.isLogin()) {
너무 단순하게 생각하고 작업한 내용이었다 싶습니다. 
조금 더 고민하여 로그인한 사용자와 그렇지 않은 사용자를 구분하는 개념을 고민해보겠습니다.
말그대로 LoginMember는 로그인한 회원이라는 의미를 가지고 있는데 이것 자체가 로그인하지 않은 사용자를 판단하는 것이 맞는지도 고민스럽군요!

2022-06-11 02:01 UTC, ssonsh commented on src/main/java/nextstep/subway/fare/calculator/FareCalculator.java
> +    public static int calculate(Lines lines, Path path) {
연령별 요금은 인터페이스를 활용해서 다형성을 구현 << 이 포인트를 가지고 조금 더 고민하여 리팩토링을 진행해보겠습니다!

2022-06-11 08:27 UTC, ssonsh commented on src/main/java/nextstep/subway/fare/calculator/FareCalculator.java
> +    public static int calculate(Lines lines, Path path) {
DiscountPolicy 라는 인터페이스를 구성하고 
Non(할인없음), Free(공짜), Children(어린이), Teenager(청소년) 4가지의 할인정책을 구현해보았습니다.

구현된 DiscountPolicy는 ServiceMember(Guest or Login) 가 가질 수 있도록 구성해보았습니다. :)

구성의 방향성이 동휘님의 방향과 일치하는지는 다시한번 피드백을 통해 이뤄져야 할 것 같습니다. :)
개인적으론 이렇게 구성하고 진행해보니 과거 코드가 왜 저렇게 작성하였을까? 라는 생각이 들었습니다 ㅎ

2022-06-11 08:29 UTC, ssonsh commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        if (loginMember.isLogin()) {
서비스를 사용하는 사용자라는 관점에서 ServiceMember 인터페이스를 구성하였고
이를 구현한 기존 로그인된 사용자를 의미하는 LoginMember와 로그인되지 않은 사용자를 의미하는 GuestMember 두가지로 구현체를 생성하였습니다. 

이후 Authentication 과정에서 인증이 필요한지 여부(required = true or false) 에 따라서 LoginMember를 반환하거나
GuestMember를 반환하는 처리로 변경해보았습니다. :)

2022-06-11 08:32 UTC, ssonsh commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        if (Objects.isNull(credentials)) {
API의 권한에 대해 AuthenticationPrincipal 이 필요하지만 required 옵션을 두어 반드시 토큰인증이 필요한지
혹은, 토큰인증은 필요없는지를 구분하도록 하였습니다.
- 하단 피드백주신 사항에 의해 LoginMember와 GuestMember 두가지 구현체로 구성하였는데 
- 인증 여부에 따라서 처리될 수 있도록 AuthenticationPrincialArgumentResolver의 resolveArgument 메소드를 변경하였습니다.

2022-06-11 11:42 UTC, dhmin5693 approved these changes
피드백 잘 반영해주셨네요 😄

요금 정책을 다형성으로 구현하셨으면 했는데 제 의도를 자세히 설명하지 않은 것 같아 걱정했었습니다.
다행히도 기우가 되었군요.

미션을 너무 잘 수행해주셔서 이걸로 마무리해도 될 것 같습니다.
더 이상 미션과는 관계없지만 약간 개선했으면 하는 부분에 코멘트를 남겨두었어요.
나중에 천천히 확인해주세요 😄

이걸로 미션의 절반 이상이 마무리되었는데요,
마지막까지 얼마 남지 않은 만큼 조금만 더 힘내시기 바랍니다. 💪
그 동안 수고 많으셨습니다.

2022-06-11 11:42 UTC, dhmin5693 commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private static int ZERO_FARE = 0;
상수는 final 을 붙여주는게 좋지 않을까요?

2022-06-11 11:42 UTC, dhmin5693 commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private int lineFare;
필드가 한번 생성되면 변화하지 않아서 final로 불변을 보장해줘도 좋을 것 같습니다.

2022-06-11 11:42 UTC, dhmin5693 commented on src/main/java/nextstep/subway/auth/domain/GuestMember.java
> +        return new NonDiscountPolicy();
`DiscountPolicy`를 상속하는 모든 인스턴스는 싱글턴으로 만들어두고 가져오면 성능상 이점을 가질 수 있겠네요.

2022-06-11 11:42 UTC, dhmin5693 commented on src/main/java/nextstep/subway/auth/domain/ServiceMember.java
> +public interface ServiceMember {
다형성 구현 💯 
getter 상속이 조금 미묘하긴 한데, 큰 상관 없을 것도 같네요.

2022-06-11 11:42 UTC, dhmin5693 commented on src/main/java/nextstep/subway/policy/DiscountPolicy.java
> +public interface DiscountPolicy {
다형성 구현 💯
이렇게 구현하셨으면 하는 마음으로 피드백을 남겼는데, 잘 작성해주셨네요. 😄

2022-06-11 11:42 UTC, dhmin5693 commented on src/test/java/nextstep/subway/fare/domain/FareTest.java
> +class FareTest {
`AdditionalFareTest` 가 더 적절하지 않을까요?

2022-06-11 11:43 UTC, merged

2022-06-11 12:46 UTC, ssonsh commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private static int ZERO_FARE = 0;
상수임에도 final을 안붙였네요 ㅠㅠ 좀더 꼼꼼히 챙기겠습니닷!

2022-06-11 12:47 UTC, ssonsh commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private int lineFare;
불변하는 필드에 대한 final 키워드 붙이기!! 이 부분도 의식적으로 접근하겠습니다 :)

2022-06-11 12:48 UTC, ssonsh commented on src/main/java/nextstep/subway/auth/domain/GuestMember.java
> +        return new NonDiscountPolicy();
:) 이 부분은 미쳐 생각하지 못했는데 싱글턴으로 구성함으로써 성능상 이점을 가져갈 수 있음을 충분히 인지하였습니다 !

2022-06-11 12:48 UTC, ssonsh commented on src/main/java/nextstep/subway/policy/DiscountPolicy.java
> +public interface DiscountPolicy {
이렇게 구현하고 보니 다형성을 이렇게 활용하는 것이였는데 왜 미쳐 생각하지 못했을까! 라는 생각이 들었습니다 ㅎ

2022-06-11 12:49 UTC, ssonsh commented on src/test/java/nextstep/subway/fare/domain/FareTest.java
> +class FareTest {
Fare -> AdditionalFare 로 변경하는 과정에서 리네임을 챙기지 못하였던 부분인 것 같습니다 ㅠ