[Step1] 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #556
Opened 2022-06-11 08:57 UTC by soob-forest

안녕하세요.
인수 테스트 기반 리팩터링 과제 첫 번째 PR입니다.

이미 작성되어 있는 인수테스트를 기반으로, 리팩토링을 하니 걱정없이 안정적으로 리팩토링을 할 수 있어서, 인수테스트가 중요하다라는 것을 느끼게 되었습니다ㅎㅎ

잘 부탁 드립니다.

2022-06-11 13:24 UTC, seok-2-o requested changes
안녕하세요 😄 인수테스트 기반 TDD 미션 리뷰어를 맡은 이재석입니다.

첫번쨰 미션 잘 진행해주셨네요.
전반적으로 getter 사용이 많고 코드가 복잡한것 같아요.
몇가지 고민거리 남겨드렸으니 리펙토링해보면 좋을 것 같아요.

앞으로 과정 진행하면서 저와 의견이 다르거나 궁금한점 있으면 편하게 코멘트 또는 DM 남겨주세요.

수배님과 함께 할 수 있게 되어 무척 기쁜 마음입니다. :)
모쪼록 다음 코드도 기대하며 기다리고 있을게요. 🙇

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                new Line(request.getName(), request.getColor(), upStation, downStation, request.getDistance()));
동일한 인자(Station) 를 받는 생성자에 빌더를 적용하면 가독성을 향상시키고 휴먼 에러를 방지할 수 있어요.

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/application/LineService.java
>                  .collect(Collectors.toList());
LineResponse 안에서 수행해도 괜찮을 것 같아요.

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/application/LineService.java
>                              .collect(Collectors.toList());
37라인과 중복인것 같은데 어떻게 생각하시나요?

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                    .filter(it -> it.getDownStation() == section.getDownStation())
getter를 사용하지 않고 수행할 수는 없을까요?

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            sections.add(new Section(upLineStation.get().getLine(), newUpStation, newDownStation, newDistance));
upLineStation.get() 이 반복적으로 사용되고 있어요

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
이번 과정에서는 들어쓰기를 1번으로 제한하고 있어요.

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.

2022-06-11 13:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        while (downStation != null) {
105 랑니과 동일한 코드가 맞을까요?

2022-06-12 09:20 UTC, soob-forest commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                new Line(request.getName(), request.getColor(), upStation, downStation, request.getDistance()));
빌더 패턴 적용했습니다.

2022-06-12 09:21 UTC, soob-forest commented on src/main/java/nextstep/subway/line/application/LineService.java
>                  .collect(Collectors.toList());
from 메서드를 만들어 Line 객체만으로 Response 객체를 만들도록 변경했습니다.

2022-06-12 09:21 UTC, soob-forest commented on src/main/java/nextstep/subway/line/application/LineService.java
>                              .collect(Collectors.toList());
바로 위 리뷰와 함께 변경했습니다.

2022-06-12 09:23 UTC, soob-forest commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                    .filter(it -> it.getDownStation() == section.getDownStation())
Section에게  해당 로직의 책임이 있다고 생각해, Section의 메서드로 이동시켰습니다.

2022-06-12 09:23 UTC, soob-forest commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            sections.add(new Section(upLineStation.get().getLine(), newUpStation, newDownStation, newDistance));
메서드로 추출해, 중복을 제거했습니다.

2022-06-12 09:24 UTC, soob-forest commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
들어쓰기를 1번 만 하도록 변경했습니다.

2022-06-12 09:25 UTC, soob-forest commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        while (downStation != null) {
while문을 반복하는 것은 동일한데, while문에서 nextLineStation을 찾는 로직은 다릅니다.

2022-06-12 09:27 UTC, soob-forest commented
인수테스트를 이용해, 서비스에 있는 로직을 도메인으로 옮기는데에만 집중해서, 
전반적으로 getter 사용이 많은 등 객체지향적이지 않은 코드들이 있었던 것 같습니다.
전체적으로 코드를 리팩토링 하여 다시 리뷰 요청 드립니다.

2022-06-13 02:58 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요 👍 
소소한 고민거리 몇가지 남겨놓았으니 다음 미션과 함꼐 고민해보면 좋을 것 같습니다.

2022-06-13 02:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                        .downStation(downStation)
빌더패턴을 통해서 상행과 하행을 명확하게 구분할수 있게 되었네요 💯

2022-06-13 02:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                )
```suggestion
                .map(LineResponse::from)
```

2022-06-13 02:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Line.java
>      public Line(String name, String color, Station upStation, Station downStation, int distance) {
색션을 주인받도록 변경하면 어떤가요?

2022-06-13 02:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(Station upStation, Station downStation, int distance) {
여기도 색션을 주입받으면 어떤가요?

2022-06-13 02:58 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Line.java
>      public void update(Line line) {
line 을 주입받아서 불필요하게 빌더를 사용하게 된 것 같아요
DTO 에서 바로 입력받으면 더 이해하기 좋을 것 같아요.

2022-06-13 02:58 UTC, merged