Step4
next-step/atdd-subway-service pull request #56
Opened 2021-01-10 20:09 UTC by tearight

안녕하세요. 드디어 마지막 스텝입니다. 😂

이번 미션은 진행하면 할수록 너무 잘 만들어진 미션이라고 생각이 듭니다.
요구사항 하나하나 마다 엄청나게 많은 고민거리를 안겨주네요.

변경사항이 너무 많아서 주요 변경점을 간단히 설명드리겠습니다.
1. Path의 길이(Distance), 노선별 요금(Fare)은 Vertex(Station) 를 연결해주는 Edge 를 커스텀화(LineEdge) 하여 이를 통해 얻어옴.
2. 요금(Fare) Wrapper 클래스 사용.
3. 새로운 인증객체인 OptionalLoginMember 추가, 로그인/비로그인 둘다 이 객체로 변환 가능하며 상태를 알 수 있음.

이번 스텝도 질문드리고 싶은게 있는데요, 답변해주시면 정말정말 감사드리겠습니다! 🙇🏻‍♂️
혼자 해결할려고 최대한 구글링을 해봤는데 제가 검색실력이 부족한 탓인지 확실한 답변을 찾지 못했습니다. 😭
아마 현업에서도 의견이 갈릴 것 같은데 리뷰어님의 사용 예나 개인적인 의견을 말씀해주시면 정말 큰 도움이 될 것 같습니다!
### _**Q. DTO 에서도 원시값 포장을 해야 하는가 ?**_

예) distance 를 랩핑해놓은 객체가 있습니다. PathResponse(DTO) 에서도 distance(int형) 를 사용합니다.
PathResponse 에서 distance(int형) 를 래핑한 객체로 교체해야 하는지 궁금합니다.

제 생각은 반반인 것 같습니다. 제가 생각하는 각각의 이유는 이렇습니다.
### **[DTO 에서도 Wrapping 한 객체를 사용하여야 한다.]**
1. 실제 API 호출에서 로직에 닿기 전에 요청을 DTO 로 변환하는 작업을 하는데, 이때 값에 대한 유효성 검사를 할 수 있다. 따라서 요청의 유효성 검사 타이밍이 명확하다.
2. 인수테스트, MVC 테스트 등에서 DTO 객체를 사용시 테스트케이스가 잘못 된 경우를 바로 알 수 있다. (장점이자 단점이 될 듯)
3. 값의 타입이 명확하고 해당 타입을 참조하는 곳이 원시값보다 한정적이므로 DTO의 사용목적을 빠르게 이해할 수 있다.
4. 그렇지 않으면 DTO 에서 원시값으로 변환해야 하므로 Wrapper 클래스의 원시값이 공개되어야 하고, 이는 Wrapper 클래스의 잘못된 사용으로 이어질 수 있다.

### **[DTO 에서는 Wrapping 한 객체를 사용할 필요가 없다.]**
1. DTO 는 클라이언트와의 통신 프로토콜이므로 래핑할수록 실제 통신에서 사용하는 데이터를 유추하기 어려워진다.
2. Wrapper 클래스가 변경되면 이를 참조하고 있는 DTO 도 변경이 된다. 그러면 실제 통신 프로토콜도 변경될 가능성이 있는데,
프로젝트 내부에서는 이를 알아차리기가 어려워진다.
3. DTO 는 요구사항에 의해 가장 먼저 변경되는 클래스이다. 실제 상황에서는 같은 타입이더라도 다양한 요구사항이 존재하는데, Wrapper 클래스는 이에 영향을 받으면 안된다. 둘의 결합을 최대한 제거해야 한다.
(예: 특정 API 에 한해 노선을 등록할 때 입력받는 Distance 는 10 이상이어야 한다.)

2021-01-11 07:56 UTC, young891221 commented
질문 주신 'DTO 에서도 원시값 포장을 해야 하는가'에 대한 답변으로는... 결론적으로 둘 다 맞는 의견 같습니다.
개인적으로 저는 코딩하신 방식처럼 원시값으로 dto를 받고 랩핑 객체는 내부 도메인에서 사용합니다. 그렇게 하는 이유는 보통은 json이나 특정 타입을 지정해 주어 파싱해야 하는데 원시값이 그 부분에서 유리하기 때문입니다. validation은 기본적인 것을 어노테이션으로 처리해 주고 내부에서 더 자세한 validation처리를 랩핑 객체에서 처리해 주는게 가장 이상적인것 같네요ㅎ

2021-01-11 07:58 UTC, young891221 approved these changes
안녕하세요!
미션 자체가 난이도가 꽤 있는데 상당히 잘 풀어주셨네요 👍 
거의 실제 업무와 비슷하다는 인식입니다. 몇 가지 개선할 수 있는 점들을 코멘트 드렸습니다.
확인 부탁드립니다:)

2021-01-11 07:58 UTC, young891221 commented on src/main/java/nextstep/subway/path/domain/Path.java
> +		if (pathDistance.isGreaterThan(DISTANCE_50KM)) {
순서가 중요한 로직인데 제약사항이 없는 부분이 살짝 아쉽네요. enum으로 명시할 수도 있지만, 가볍게 주석처리만 해도 괜찮을것 같습니다.

2021-01-11 07:58 UTC, young891221 commented on src/main/java/nextstep/subway/auth/domain/OptionalLoginMemberPrincipal.java
> +public @interface OptionalLoginMemberPrincipal {
`LoginMemberPrincipal`와 `OptionalLoginMemberPrincipal`를 명시하기 위해 resolver를 2개를 쓰고 있습니다.
명확한 부분은 좋지만 거의 비슷한 로직을 2개를 분리하여 사용하는것 같습니다. `OptionalLoginMemberPrincipal`로 통일하되 `mustLogin`과 같은 true/false value를 넣어서 한곳에서 몰아서 처리하면서 그 의미를 살려가면 어떨까요?

2021-01-11 07:59 UTC, young891221 requested changes
안녕하세요!
미션 자체가 난이도가 꽤 있는데 상당히 잘 풀어주셨네요 👍
거의 실제 업무와 비슷하다는 인식입니다. 몇 가지 개선할 수 있는 점들을 코멘트 드렸습니다.
확인 부탁드립니다:)

2021-01-11 14:58 UTC, tearight commented on src/main/java/nextstep/subway/auth/domain/OptionalLoginMemberPrincipal.java
> +public @interface OptionalLoginMemberPrincipal {
그게 좀 더 직관적인 구조가 될 것 같습니다. 적용해보도록 하겠습니다. 🙂

2021-01-11 15:15 UTC, tearight commented
> 질문 주신 'DTO 에서도 원시값 포장을 해야 하는가'에 대한 답변으로는... 결론적으로 둘 다 맞는 의견 같습니다. 그리고 장단점을 정확하게 잘 써주셨네요 👍

감사합니다! 계속 이런 디테일에 신경이 쓰였었는데 덕분에 어느정도 해소가 된 것 같습니다. 결국 팀의 컨벤션에 달린 문제같네요ㅎㅎ.
생각하다보니 아이디어가 떠올랐는데 Request DTO 는 Getter 의 리턴타입을 Wrapper 로 하는 것도 나쁘진 않을 것 같습니다.
양쪽의 장점을 다 가져갈려면 아래와 같이 하면 될 것 같습니다!
1. Request DTO: getter 의 리턴타입을 Wrapper 로 사용
2. Response DTO: 생성자 또는 정적 팩토리 메소드의 인자를 Wrapper 로 사용

2021-01-12 00:55 UTC, young891221 approved these changes
리뷰 반영 감사합니다!
매우 잘 해주셔서 수월하게 진행된 느낌이네요ㅎ
고생하셨습니다. 머지할게요~!

2021-01-12 00:55 UTC, merged