Step2 - 경로 조회 기능
next-step/atdd-subway-service pull request #567
Opened 2022-06-12 08:32 UTC by geunhwanlee

안녕하세요😀

이번 미션에서 `PathService`는 stubbing을 통한 격리테스트를 진행했고
`PathFinder`는 외부 라이브러리를 활용한 단위테스트를 진행하였습니다

격리테스트는 내부 구현이 변경되면 테스트코드를 계속 변경해 주어야 하는 불편함이 있었고
테스트 대상의 협력객체를 외부에서 주입받는 형태로 구현해야 테스트가 가능했습니다.
반면 테스트 대상의 협력객체들에 영향을 받지 않는 장점이 있는 것 같습니다.

그럼 많은 피드백 부탁드립니다🙇🏻‍♂️

2022-06-13 08:19 UTC, joojimin requested changes
안녕하세요~ 근환님! 미션 진행 고생하셨습니다!
몇가지 피드백드렸는데 확인해보시고 리뷰 재요청 부탁드려요~!

2022-06-13 08:19 UTC, joojimin commented on README.md
> +- 출발역과 도착역이 존재하지 않는 역인 경우 조회할 수 없다
요구사항 정리 잘해주셨습니다!
추가로 이번 미션이 인수테스트 기반 TDD인 만큼 인수테스트 조건도 명시해주면 더 좋을 것 같아요!

2022-06-13 08:19 UTC, joojimin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    private final StationService stationService;
구조적으로 같은 계층 레벨을 가지는 *Service들끼리 주입받는건 후에 순환참조 문제를 일으킬 수 있습니다!
해당 부분도 한번 생각해주시면 좋을 거 같아요!

2022-06-13 08:19 UTC, joojimin commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +public class PathFinder {
관심사를 적절히 나눠주신 것 같아요!!! 훌륭하십니다 💯

2022-06-13 08:19 UTC, joojimin commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +    @ExceptionHandler(ErrorCodeException.class)
Path 도메인에 국한되어 쓰일 Exception이 아니라 글로벌적으로 쓰일 Exception 같아요! 
따로 클래스를 분리하여 전역에서 쓰일 수 있게하면 어떨까요?

2022-06-13 08:19 UTC, joojimin commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +    @MockBean
Mock 객체 활용 👍

2022-06-13 12:38 UTC, geunhwanlee commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +    @ExceptionHandler(ErrorCodeException.class)
넵 좋은 생각인 것 같습니다!👍🏻

2022-06-13 12:55 UTC, geunhwanlee commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    private final StationService stationService;
넵! Service 간에 참조하게 되면 그러한 문제가 생길 수 있을 것 같습니다!

궁금한것이 있습니다!🤔
서비스 레이어에서 담당하는 로직을 다른 서비스에서 활용할 경우도 생길 수 있을텐데
그런 경우에 지민님은 어떻게 처리하시는 지 궁금합니다!🙏

2022-06-14 09:09 UTC, joojimin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    private final StationService stationService;
궁금한것이 있습니다!🤔
서비스 레이어에서 담당하는 로직을 다른 서비스에서 활용할 경우도 생길 수 있을텐데
그런 경우에 지민님은 어떻게 처리하시는 지 궁금합니다!🙏
=> 음 이건 어떻게 레이어를 설계하느냐에 따라 다를거 같아요! 제가 하는 방식은 그냥 한가지 예로 들어주세요!
`서비스 레이어에서 담당하는 로직을 다른 서비스에서 활용할 경우` 는 Component(구성요소)로 다시 추출하여 새로운 관심사 클래스를 만드는 편입니다! 해당 구성요소를 쓰이는 서비스 계층마다 주입시켜서 같은 로직을 활용하게 구성하고 있어요!

추가적으로 Service 레이어의 역할이 어디까지 부여받았는가도 중요할 것 같은데요!
`하나의 트랜잭션을 담당 + 각 응답들을 적절한 도메인들로 DTO 변환하여 전달` 이런 식으로 저는 활용하고 있긴한데 이렇게 되면 서비스 레이어에서 담당하는 로직은 거의 없고 각 구성요소들만 주입받아 호출하는 식이 되어 계층별 구분을 명확하게 하고있습니다!

먼가 장황하게 설명만드려서... 도움이 되셧으면 좋겟습니다

2022-06-14 09:10 UTC, joojimin approved these changes
피드백 반영 고생하셨습니다!
질문의 대답은 코멘트로 달아놨습니다 ㅎㅎㅎ
혹시 더 궁금하시거나 다른 질문사항 있으시면 언제든 DM 혹은 qna 채널로 문의주세요!
다음미션 진행 부탁드립니다~

2022-06-14 09:10 UTC, merged