Step1 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #573
Opened 2022-06-12 14:58 UTC by yulmucha

안녕하세요.
리뷰 요청드립니다.
감사합니다.

2022-06-13 15:58 UTC, enemfk777 requested changes
안녕하세요 율님 :)
인수 테스트 기반 TDD 미션을 함께하게 된 리뷰어 강태엽입니다 🙇‍♂️

1단계 잘 수행해주셨네요 :)
몇가지 코멘트 드렸으니 한 번 슥 보시고 반영 or 의견 부탁드려요!!

그럼 이번 미션동안 잘부탁드려요 화이팅!! 💪

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/application/LineService.java
>          return LineResponse.of(persistLine, stations);
이부분을 LineResponse에서 책임지고 만들어내는건 어떨까요?
service 내의 중복로직이 많이 제거될 것 같네요 :)

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/application/LineService.java
>      public LineResponse findLineResponseById(Long id) {
조회용 메서드는 읽기전용 트랜잭션 설정을 해주는건 어떨까요?

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.findById(id).orElseThrow(NoSuchElementException::new);
private 메서드로 분리해주신 findLineById 를 사용할 수 있을것같아요 :)

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(NoSuchElementException::new);
체이닝 메서드는 한줄로 쓰기보단 .마다 줄바꿈을 하면 가독성이 높아질 것 같아요 :)

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public Station lastUpStation() {
production 코드에서 sections 내부에서만 쓰이는 메서드여서 접근제한자가 public 일 이유가 없어보입니다 :)

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
> 규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.

객체지향 생활체조 원칙을 지켜보시는건 어떨까요? :)

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Station downStation = lastUpStation();
메서드명은 upstation인데 변수명이 downstation인건 언뜻 코드를 읽을 때 혼동을 줄 수 있을 것 같습니다

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        boolean isDownStationExisted = stations.stream().anyMatch(it -> it == downStation);
sections에 station이 포함되는지만 확인하면 되는 로직으로 보이는데, 불필요한 정렬이들어가고 있네요 :)
section 스스로가 특정 station을 포함하고 있는지 반환할 수 있게 하면 어떨까요?

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                .filter(it -> it.getUpStation() == section.getUpStation())
이부분도 section이 section을 파라미터로 전달받아 upstation이 같은 section인지, downstation이 같은 section인지 반환해볼 수 있을 것 같아요 :)

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                    it.updateUpStation(section.getDownStation(), section.getDistance());
updateUpstation의 파라미터로 section을 전달 받는게 좀더 깔끔한 코드가 될 수 있을것 같습니다

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +        Member member = memberRepository.findById(id).orElseThrow(NoSuchElementException::new);
적절한 exception 설정 👍

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Section.java
>          if (this.distance <= newDistance) {
> 규칙 3: 모든 원시값과 문자열을 포장한다.

Distance는 0 보다 커야한다는 비즈니스 요구 사항이 있는 것 같은데 
객체로 포장해서 책임을 부여하는건 어떨까요?

2022-06-13 15:58 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            int newDistance = downSection.get().getDistance() + upSection.get().getDistance();
두 section을 합치는게 sections의 책임일까요?
필요한 데이터는 모두 section이 가지고 있는데, section 스스로 책임질수 있게 리팩토링해보시는건 어떨까요?

2022-06-14 00:52 UTC, yulmucha commented on src/main/java/nextstep/subway/line/application/LineService.java
>          return LineResponse.of(persistLine, stations);
결국 `Line`으로 만드는 거라 `LineResponse.of()` 파라미터에 `Line`만 남겨도 충분한 걸 놓쳤네요! 😅

2022-06-14 02:19 UTC, yulmucha commented on src/main/java/nextstep/subway/line/application/LineService.java
>      public LineResponse findLineResponseById(Long id) {
기본적으로 서비스에 `@Transactional(readOnly = true)`로 해 놓고, 쓰기 메서드에만 `@Transactional`을 붙이는 방식으로 수정했습니다.
조회만 할 때는 변경 감지를 위한 추가 작업을 하지 않아서 불필요한 메모리 사용을 방지할 수 있네요.

2022-06-14 02:39 UTC, yulmucha commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(NoSuchElementException::new);
로직 옮기는 데만 급급했네요. 😅 동의하며 평소에는 실천하고 있습니다.

2022-06-14 02:47 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public Station lastUpStation() {
나중에라도 충분히 외부에서 사용될 만한 정보가 아닌가 싶어서 고민하다가 `public`으로 두었지만,
말씀을 듣고 보니, 실제로 사용될 때 `public`으로 바꿔도 될 건데 당장 읽는 사람에게 혼란만 주는 것 같네요.

2022-06-14 03:34 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Station downStation = lastUpStation();
동의합니다.
리팩터링 전의 이름인 `findUpStation`보다는 낫다고 생각했지만, 나중에 다시 읽을 때 한번은 저 스스로도 이해하는 데 시간이 좀 걸리더라고요.

2022-06-14 04:02 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public Station lastUpStation() {
다만, 메서드가 테스트할 필요성이 있으면서 조회용이라 외부에서 사용해도 문제가 발생할 여지가 없다면 `public`이어도 괜찮지 않을까 싶습니다.

2022-06-14 07:07 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        boolean isDownStationExisted = stations.stream().anyMatch(it -> it == downStation);
앗 여기도 옮기는 데에만 정신이 팔렸었네요.

2022-06-14 07:38 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            int newDistance = downSection.get().getDistance() + upSection.get().getDistance();
`Section`에 `merge()` 메서드를 만들었습니다.
처음엔 `static`으로 만들어서 두 `Section`을 받아야 하나 싶었어요.
하지만 그렇게 되면 비록 메서드는 `Section`에 존재하지만 `Section` object가 스스로 책임진다고 할 수 있을까.. 외부에서 getter로 데이터를 받아 조작하는 것과 비슷하지 않은가.. 개체 간의 상호 작용이 아닌 것 같다는 생각이 들어서 non-static으로 만들었습니다.

2022-06-14 08:02 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                    it.updateUpStation(section.getDownStation(), section.getDistance());
`Section`에 `updateUpStationAndDistanceFor(Section)` 메서드를 만들긴 했는데 `public`이라 좀 찜찜하네요.
`Sections`의 `rearrangeElementsFor()` 메서드 안에서는 조건에 따라 알맞게 사용되고 있지만, 이게 `Sections`와는 별개로 `Section`에 있는 `public` 메서드니까 충분히 잘못 사용될 수 있지 않나 싶어서요.
그래서 `updateUpStationAndDistanceFor()` 안에 검증하는 조건문 하나 더 넣어 보았습니다.
너무 과한 걱정일까요..

2022-06-14 08:05 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Station downStation = lastUpStation();
혼동이 없도록 첫 번째 `Section`을 찾도록 바꾸었습니다.

2022-06-14 12:02 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Section.java
>          if (this.distance <= newDistance) {
wrapper class `Distance`를 만들어 사용해 보았습니다

2022-06-14 17:09 UTC, enemfk777 approved these changes
안녕하세요 율님 :)

많은 피드백이었는데 잘 반영해 주셨네요!!
몇 가지 고민해 볼 사항을 추가로 코멘트 드렸으니 확인 부탁드립니다!

그럼 다음 단계 진행을 위해 이만 머지하겠습니다!!

2022-06-14 17:09 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (elements.isEmpty()) {
elements가 비어있을 땐 exception을 발생시키면 어떨까요?
비즈니스 요구사항 상 elements가 비어있는 sections는 존재 할 수 없을 것 같아요

2022-06-14 17:09 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (hasValidStation(section)) {
조건이 반대로 되어있는 것 같습니다 :)

2022-06-14 17:09 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                    return;
람다로 표현해도 될 것 같아요 :)

2022-06-14 17:09 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (elements.size() <= 1) {
매직넘버는 상수화 시켜보는건 어떨까요?

2022-06-14 17:09 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +        value += distanceNew.value;
Distance 연산에서 새로운 Distance 객체를 반환하도록 해서
기존 객체를 불변으로 만들어 보시는건 어떨까요?

2022-06-14 17:09 UTC, merged

2022-06-15 05:07 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (hasValidStation(section)) {
❗️이름을 반대로 지었네요.

2022-06-15 05:33 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (elements.size() <= 1) {
이 경우에는 좀 애매하네요.
`size()`와 함께 `1` 자체가 그 의미를 충분히 나타내고 있어서 `ONE` 등으로 바꾸는 게 큰 의미가 없지 않을까 싶기도 하고..
`elements.size() > 1` 을 하나의 함수 `isPossibleToRemove()` 등으로 바꿀 순 있을 것 같습니다.

2022-06-15 16:19 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (elements.size() <= 1) {
ONE이 아닌 MINIMUM_SECTION_SIZE 등의 비즈니스 요구사항을 나타낼수 있는 이름으로 명명하면 의미가 있을 것 같아요 :)

2022-06-16 00:25 UTC, yulmucha commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (elements.size() <= 1) {
그 생각을 못했네요 ㅎㅎ.. 감사합니다!!