Step4 - 요금 조회
next-step/atdd-subway-service pull request #579
Opened 2022-06-13 13:06 UTC by limwoobin

안녕하세요 4단계 리뷰요청드립니다
요구사항에 맞게 최대한 다형성을 고려해서 작성해보려했는데
의도한만큼 잘 되었는지 모르겠네요ㅠ 이 부분에 개별 기능이 크지않아
enum 에 Function, BiFunction 으로 바로 로직을 넣을까도 고민했지만 개별 클래스로 빼서 작업했습니다
뭔가 요금계산에 대한 추가기능이 들어왔을때를 고려해보면 다형성을 이용해 클래스를 따로 만들어 로직을 처리하는게
더 유연하게 대처할 수 있지 않을까 싶어서 그랬습니다
1. 연령별 운임요금 계산
2. 거리별 추가요금 계산방법

위 두가지 case 는 얼마든지 추가 case 가 발생할 여지가 있고 계산방법에도 기능이 추가될 여지가 있다고 판단되었습니다.
예를들면 마일리지 적립이 포함된다던가, 운임요금 할인에 대해 특정 직업군에게 넓혀진다던가 하는 여지를 남겨두었습니다.
그래서 다형성을 이용해 enum 내에서 factory method 용도로 처리했습니다
변하거나 추가되지 않는다는 가정이 있었다면 그냥 enum 에서 바로 처리했을것같은데 그래서 이런 관점으로 개발했다는 점에 대해
리뷰어님 의견이 궁금해서 이렇게 남깁니다

리뷰로 의견 주시면 감사하겠습니다!

2022-06-14 07:15 UTC, shared-moon requested changes
우빈님 안녕하세요!
4단계 미션 잘 진행 해 주셨네요 :)
몇가지 코멘트를 남겨 두었는데, 확인 후 다시 리뷰 요청 부탁드릴게요!
화이팅입니다 :)

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +public class Fare {
오 .. 제가 영어가 짧아서 그런 걸 수도 있는데 보통 요금은 Price로 많이 표현하지 않나요? ㅎㅎ Fare 사전에 쳐보고 왔네요 😭

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/impl/OldFarePolicy.java
> +    public int calculate() {
엇 요구사항에 노인 무료 라는 정책이 있었나요 ?

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +public class Fare {
아 예시로 제시하신 코드가 Fare라는 표현을 쓰고 있었군요 ?

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +        Fare totalFare = fareByAge.plus(fareByDistance);
최종 요금 계산이 (운임요금 - 공제금액) * 0.5 이런 식으로 되어야 할 것 같아요! 지금은 기본요금 할인 + 거리 금액이 들어가는 로직으로 보이네요

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    public static Fare of(Path path, LoginMember loginMember) {
이 부분은 따로 Factory를 만들어서 제공하는게 어떨까 했는데, 따로 Fare를 다른곳에서 유의미하게 쓰진 않는군요. 그렇다면 Calculator 클래스 정도를 만들어서 결과만 제공해줘도 괜찮지 않을까 싶어요!

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/AgeFareType.java
> +            .filter(type -> type.predicate.test(age))
predicate.test 라고 하니 너무 범용적인 의미인 것 같아요! enum에 나이 판단하는 메서드를 오버라이딩 하는 방식으로 제공해 보는 건 어떨까요 ?

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/impl/AdultFarePolicy.java
> +public class AdultFarePolicy implements AgePolicy {
Policy 사용하신게 고민의 흔적이 보여서 굉장히 좋은 시도라고 생각합니다 :)
하지만 싱글톤을 사용하는 근본적인 이유를 조금 더 생각 해 보시면 약간 더 심플한 구조를 만들 수 있을 것 같아요!

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/distance/DistanceFareType.java
> +    BASIC(distance -> distance <= 10, BasicDistancePolicy.getInstance()),
AgeFareType에도 남겨두었지만, Predicate 활용 하신 것 굉장히 좋은 시도라고 생각합니다!
하지만 predicate 라는 범용적인 표현이 되어야 하는 것, 그리고 ENUM 선언부에서 해당 람다식이 무엇을 하기 위함인지 나타낼 수 없다는 것 (익명 함수) 등의 단점이 있을 것 같아요!

물론 크게 복잡한 내용이 아니라 클래스 이름과 같이 미루어 볼때 이해가 어려운 부분은 아니라고 생각 하는데요 ( 아마 이런 이유로 이런 방식을 선택 하셨을 거라 생각하구요 )
조금 더 직관적으로 표현 할 수 있는 방법이 있을 것 같아서 코멘트 남겨봐요 :)

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/distance/impl/BasicDistancePolicy.java
> +    private BasicDistancePolicy() {
이쪽도 마찬가지로! 정말 좋은 시도라고 생각하지만, 더 심플한 방법이 있을 것 같아요!
어쩌다보니 뭔가 되게 고심하신 부분을 전면 부정하는 식의 워딩이 되어서 마음아프네요 .. ㅜ
하지만 결코 잘못 했다 라는 뉘앙스는 아니라는 점 알아주시면 감사하겠습니다 :)

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(Line.of(request.getName(), request.getColor(), upStation, downStation, request.getDistance(), 0));
추가 운임요금을 넣을 방법이 없는걸까요 ?

2022-06-14 07:15 UTC, shared-moon commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    void 연령에_맞는_회원생성_후_로그인(int age) {
요거는 private하게 하고 맨 밑으로 내리는게 어떨까요 ?

2022-06-14 07:15 UTC, shared-moon commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPaths(@AuthenticationPrincipal LoginMember loginMember, @RequestParam Long source, @RequestParam Long target) {
미션 내용에 로그인 사용자의 경우는 할인을 해주는 조건이 있는데, 비 로그인 사용자의 경우는 할인 없이 이용 가능해야 할 것 같아요!

2022-06-14 07:22 UTC, shared-moon commented
고민하신 변경에 대한 처리에 대한 답변을 살짝 남겨볼게요!
말씀하신 부분은 대게 개방폐쇄원칙에 부합 하는가 아닌가에 대한 얘기일 것 같은데요!
제 나름대로, 이 부분에 대해서는 `변화에 유연하되 현재의 정책을 직관적으로 표현 할 수 있는 정도`로 마무리를 지으면 될 것 같습니다.

사실 변화에 유연하게 대처를 하려고 추상화를 하다보면, 무한 굴레에 빠지게 되거든요 이렇게 하면, 이렇게 바뀌면 이게 이랬다 저러면 ..? 이런 고민이 시작되면 끝이 없기때문에 최대한 현재 정책에는 맞춰서 만드는게 좋다고 생각하구요.

개인적으로는 추상화는 처음부터 고려하지 않는 게 좋다고 생각합니다. 변화에 유연하게 대응한다는 게 반드시 추상화 레이어를 고려해라 라는 뜻은 아니라고 생각해요. 추상화 하게 될 일이 생겼을 때 얼마나 적은 변화만으로 바뀐 요구사항을 수용할 수 있느냐 가 더 중점이라고 생각 하거든요.

변화를 예상하고 추상화를 하면, 1. 가독성이 떨어집니다. 이건 추상화를 하면 어쩔 수 없는 부분이죠. 2. 변화가 반드시 일어나지는 않습니다. 비즈니스 요구사항이 바뀐다는 건, 고객의 니즈가 변화한다는 얘기죠. 결국 바뀌느냐 마느냐의 주도권은 고객에게 있지 개발자에게 있지가 않습니다. 열 길 물속은 알아도 한 길 사람 속은 모른다고 하죠. 절대 예상 할 수 없는 부분을 예상하려 하는건 득보다 실이 많을 수 밖에 없습니다.

그리고 제가 예상한 방향으로 요구사항이 변하지 않으면, 오히려 변경이 훨씬 어려워지는 경우도 있습니다. 해서 저는 추상화는 무조건 바텀업이 되어야 한다고 생각해요. 인터페이스를 먼저 만들어 설계하고 거기에 끼워 맞추는게 아니라, 역할분리가 잘 된 클래스를 만들어 명시적으로 기능을 바라볼 수 있게 하고, 비슷하지만 약간은 다른 추가적인 요구사항이 들어왔을 때, 유지보수 측면에서 이득을 얻기 위해 추상화를 고려하는 방향이 맞다고 생각합니다.

질문에 대한 답이 되었을 지 모르겠네요! 남은 미션도 화이팅 하세요 :)

2022-06-14 08:08 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +public class Fare {
넵 맞습니다 ㅎㅎ

2022-06-14 08:08 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/age/impl/OldFarePolicy.java
> +    public int calculate() {
http://www.seoulmetro.co.kr/kr/page.do?menuIdx=354
예제로 나와있는 참고사항을 고려해서 추가했습니다!

2022-06-14 08:09 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +        Fare totalFare = fareByAge.plus(fareByDistance);
제가 계산방식에 있어 놓쳤군요 감사합니다

2022-06-14 08:10 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    public static Fare of(Path path, LoginMember loginMember) {
요금계산을 위한 Caculator 클래스를 별도로 만들어 역할을 분리하는것으로 이해해도될까요??

2022-06-14 08:18 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/age/AgeFareType.java
> +            .filter(type -> type.predicate.test(age))
한번 적용해보겠습니다! test 라는 이름이 명시적이지 않네요 ㅎㅎ

2022-06-14 08:19 UTC, limwoobin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(Line.of(request.getName(), request.getColor(), upStation, downStation, request.getDistance(), 0));
모든 노선이 추가운임요금을 받지는 않으니
defautl 는 0 으로하고 추가로 받을 수 있게끔 처리해보겠습니다

2022-06-14 08:35 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/age/impl/AdultFarePolicy.java
> +public class AdultFarePolicy implements AgePolicy {
enum 의 predicate 로 factory 역할을 해서 해당 인스턴스를 리턴하는방식으로 적용하였습니다
다만 해당 객체는 요금계산의 역할이라 계속 인스턴스로 생성될요 없이 싱글톤으로 적용해서
올려놓는게 성능상 이점이 된다고 판단해서 적용하였습니다. 
더 심플한 구조는 고민해보겠습니다! 그런데 근본적인 이유는 저도 공부해봐야겠네요 제가 사용한 이유가 잘못사용하고 있는게 아닐까 해서요 ㅎㅎ

2022-06-14 12:19 UTC, limwoobin commented
안녕하세요 선흠님 주신 피드백보고 반영해보았습니다
말씀해주신 p

> 고민하신 변경에 대한 처리에 대한 답변을 살짝 남겨볼게요! 말씀하신 부분은 대게 개방폐쇄원칙에 부합 하는가 아닌가에 대한 얘기일 것 같은데요! 제 나름대로, 이 부분에 대해서는 `변화에 유연하되 현재의 정책을 직관적으로 표현 할 수 있는 정도`로 마무리를 지으면 될 것 같습니다.
> 
> 사실 변화에 유연하게 대처를 하려고 추상화를 하다보면, 무한 굴레에 빠지게 되거든요 이렇게 하면, 이렇게 바뀌면 이게 이랬다 저러면 ..? 이런 고민이 시작되면 끝이 없기때문에 최대한 현재 정책에는 맞춰서 만드는게 좋다고 생각하구요.
> 
> 개인적으로는 추상화는 처음부터 고려하지 않는 게 좋다고 생각합니다. 변화에 유연하게 대응한다는 게 반드시 추상화 레이어를 고려해라 라는 뜻은 아니라고 생각해요. 추상화 하게 될 일이 생겼을 때 얼마나 적은 변화만으로 바뀐 요구사항을 수용할 수 있느냐 가 더 중점이라고 생각 하거든요.
> 
> 변화를 예상하고 추상화를 하면, 1. 가독성이 떨어집니다. 이건 추상화를 하면 어쩔 수 없는 부분이죠. 2. 변화가 반드시 일어나지는 않습니다. 비즈니스 요구사항이 바뀐다는 건, 고객의 니즈가 변화한다는 얘기죠. 결국 바뀌느냐 마느냐의 주도권은 고객에게 있지 개발자에게 있지가 않습니다. 열 길 물속은 알아도 한 길 사람 속은 모른다고 하죠. 절대 예상 할 수 없는 부분을 예상하려 하는건 득보다 실이 많을 수 밖에 없습니다.
> 
> 그리고 제가 예상한 방향으로 요구사항이 변하지 않으면, 오히려 변경이 훨씬 어려워지는 경우도 있습니다. 해서 저는 추상화는 무조건 바텀업이 되어야 한다고 생각해요. 인터페이스를 먼저 만들어 설계하고 거기에 끼워 맞추는게 아니라, 역할분리가 잘 된 클래스를 만들어 명시적으로 기능을 바라볼 수 있게 하고, 비슷하지만 약간은 다른 추가적인 요구사항이 들어왔을 때, 유지보수 측면에서 이득을 얻기 위해 추상화를 고려하는 방향이 맞다고 생각합니다.
> 
> 질문에 대한 답이 되었을 지 모르겠네요! 남은 미션도 화이팅 하세요 :)

답변감사합니다!!

2022-06-15 10:02 UTC, shared-moon requested changes
우빈님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
코멘트를 몇 개 남겨 두었는데, 마지막 미션이니 만큼 한 번만 더 보면 좋을 것 같아요!
확인 후 다시 리뷰 요청 부탁드릴게요! 🔥

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public static Fare of(Path path, Customer customer) {
Calculator로 옮기시면서 메서드 명은 of 말고 다른게 좀 더 좋을 것 같아요!

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null || !jwtTokenProvider.validateToken(credentials)) {
null은 애초에 인증정보가 없으니 비로그인이 맞지만, credentials가 있는데 유효하지 않은건 로그인 실패를 줘야하지 않나 싶네요! jwt면 expiredAt으로 유효기간 설정이 가능할거라서요?

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +        LoginMember loginMember = (LoginMember) customer;
요금 계산하는 로직이 약간 복잡해 보이네요! 사실 distance와 age로만 계산이 되는 값인데 복잡해지는 이유는 어떤게 있을까요?

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/AgeFareType.java
> +            .filter(type -> type.agePolicy.includeAge(age))
오 Policy 안으로 넣으셨군요 ?

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/impl/AdultFarePolicy.java
> +public class AdultFarePolicy implements AgePolicy {
이유는 알고 계신게 맞습니다! 질문을 드렸던 이유는, 새로운 인스턴스를 계속 생성하지 않는다 라는 관점에서 봤을 때, enum은 이미 싱글톤이고 각 enum 별 policy를 만들게 되는 현재 구조에서 policy 라는 부수적인 개념을 만들 이유가 있을까? 라는 의미로 질문을 드렸었어요!

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/impl/ChildFarePolicy.java
> +    public int discountRate() {
위의 0.5가 빠져야 되는 게 아닐까요 ?

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/impl/OldFarePolicy.java
> +    public int calculate() {
👍

2022-06-15 10:02 UTC, shared-moon commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(Line.of(request.getName(), request.getColor(), upStation, downStation, request.getDistance()));
request로 추가요금을 받을 수 있게 하면 안되는걸까요 ?

2022-06-15 10:07 UTC, shared-moon commented
질문 주신 내용 여기에 따로 답변 할게요! 말씀드렸던 부분은 현재 enum 정의하신것과 Policy들을 따로 만들어 두신게 용도가 완벽히 일치하고 있는 것 같아서 말씀드렸어요! enum의 메서드 오버라이딩을 통해서 충분히 구현 가능 해 보여서요 :)
전략 패턴을 사용하는 것도 충분히 좋은 방법이긴 하지만, 메서드 뎁스가 깊어짐으로 인해 사용성이 저하되고 enum을 확인 해 봤을 때 한 눈에 안 보이는 것 같아서 그걸 enum이 책임을 갖는다면 더 심플해지지 않을까 해서 말씀드렸습니다!

아 물론, enum에 별도의 로직을 넣는 걸 안 좋아하시는 분도 계셔서 약간 취향 차이일 수도 있긴 한데, 한번 enum에만 정의해서 사용해보시는 것도 해보는 게 어떨까요 ? :)

2022-06-15 11:03 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public static Fare of(Path path, Customer customer) {
넵 좀 더 계산을 명확히 표현할 수 있는 방식으로 변경해보겠습니다!

2022-06-15 11:03 UTC, limwoobin commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null || !jwtTokenProvider.validateToken(credentials)) {
맞습니다! 기존 jwt 가 넘어온 경우에 대해서는 토큰에 대한 검증을 진행하되 토큰이 없는 경우엔
비회원으로 인지하도록 변경하겠습니다

2022-06-15 11:05 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +        LoginMember loginMember = (LoginMember) customer;
> 질문 주신 내용 여기에 따로 답변 할게요! 말씀드렸던 부분은 현재 enum 정의하신것과 Policy들을 따로 만들어 두신게 용도가 완벽히 일치하고 있는 것 같아서 말씀드렸어요! enum의 메서드 오버라이딩을 통해서 충분히 구현 가능 해 보여서요 :) 전략 패턴을 사용하는 것도 충분히 좋은 방법이긴 하지만, 메서드 뎁스가 깊어짐으로 인해 사용성이 저하되고 enum을 확인 해 봤을 때 한 눈에 안 보이는 것 같아서 그걸 enum이 책임을 갖는다면 더 심플해지지 않을까 해서 말씀드렸습니다!
> 
> 아 물론, enum에 별도의 로직을 넣는 걸 안 좋아하시는 분도 계셔서 약간 취향 차이일 수도 있긴 한데, 한번 enum에만 정의해서 사용해보시는 것도 해보는 게 어떨까요 ? :)

저도 처음 이 부분을 enum 에서 처리할지 별도 클래스를 만들어 처리할지 고민하다가 후자를 택했습니다!
다만 이 경우엔 리뷰어님 말씀대로 enum 으로도 심플하게 사용해보면서 양쪽을 모두 경험해보면  좀 더 확실하게 공부가 될것같아요! 이번 팩토리로 생성했던 예제는 싹 날리고 의견주신방향으로 한번 수정해보겠습니다!

2022-06-15 11:06 UTC, limwoobin commented
저도 처음 이 부분을 enum 에서 처리할지 별도 클래스를 만들어 처리할지 고민하다가 후자를 택했습니다!
다만 이 경우엔 리뷰어님 말씀대로 enum 으로도 심플하게 사용해보면서 양쪽을 모두 경험해보면 좀 더 확실하게 공부가 될것같아요! 이번 팩토리로 생성했던 예제는 싹 날리고 의견주신방향으로 한번 수정해보겠습니다!

2022-06-15 11:25 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/age/AgeFareType.java
> +            .filter(type -> type.agePolicy.includeAge(age))
policy 안으로 넣었지만 이번에 모두 enum 안에서 처리해보려고해서 다시 제거하려합니다!

2022-06-15 11:25 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +        LoginMember loginMember = (LoginMember) customer;
method extract 로 각각의 역할에 맞게 요금조회하는 부분을 분리해보겠습니다

2022-06-15 11:25 UTC, limwoobin commented
안녕하세요 선흠님 리뷰주신 내용보고 이번엔 인터페이스 하위의 각 클래스에서 기능을 담당하던 구조를 제거하고
enum 안에서 간소화해서 표현해봤습니다. Predicate 도 좀 더 직관적인 표현이 될 수 있도록 상속받아 새로 구현했는데 말씀하신 의도대로 잘 구현했는지는 모르겠네요 ㅎㅎ 우선 이번 과제에서 느낀게 참 많네요
제일 와닿았던 부분은 
`추상화는 무조건 바텀업이 되어야 한다고 생각해요. 인터페이스를 먼저 만들어 설계하고 거기에 끼워 맞추는게 아니라, 역할분리가 잘 된 클래스를 만들어 명시적으로 기능을 바라볼 수 있게 한다`  이와 같은 리뷰를 주셨었는데
이 부분이 굉장히 도움이 많이 되었습니다. 제가 고민하고 있던 부분들에 대해 좋은 답이 된것같아서요 ㅎㅎ
추후 코드작성시 많은 도움이 될것같네요
감사합니다!

2022-06-15 14:53 UTC, shared-moon approved these changes
우빈님 안녕하세요!
피드백 잘 반영 해 주셨네요 :)
이번 미션은 이만 머지 하도록 하겠습니다!
앞으로 남은 미션도 힘내서 끝까지 완주하시기 바랄게요 🔥 
정말 고생 많으셨어요!

2022-06-15 14:53 UTC, shared-moon commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        jwtTokenProvider.validateToken(credentials);
👍

2022-06-15 14:53 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public static Fare calculate(Path path, Customer customer) {
👍

2022-06-15 14:53 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +        Fare totalFare = distanceFare.plus(new Fare(customer.DEFAULT_FARE));
👍

2022-06-15 14:53 UTC, shared-moon commented on src/main/java/nextstep/subway/fare/domain/age/AgeFareType.java
> +    OLD(age -> age >= 65, fare -> new Fare(0)),
요거 혹시나 해서 리뷰 남겨봐요! Enum의 각 요소들은 그 자체로 Enum Class를 상속받은 별도의 클래스이기 때문에 메서드를 오버라이딩 할 수 있어요!

enum 클래스에 `abstract boolean checkAge();` 이렇게 선언 하면

OLD {
@Override
public boolean checkAge() {
// TODO
}
}

이런식으로 ..! 람다를 건내주는것보다 메서드가 더 읽기 좋을 것 같아서 말씀드려봤어요 :)

2022-06-15 14:53 UTC, merged

2022-06-15 15:24 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/age/AgeFareType.java
> +    OLD(age -> age >= 65, fare -> new Fare(0)),
아 ㅇㅣ부분을 놓쳤습니다ㅠㅜㅜ
java8 이라고 이런케이스에 람다를 쓴다는 그런 습관이 저도모르게 나왔습니다
마지막리뷰인데 놓쳐서 너무아쉽네요.. 그래도 계속 꼼꼼하게 리뷰쥬셔서 정말 감사드립니다
고생하셨습니다 선흠님!