Step1 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #580
Opened 2022-06-13 13:24 UTC by yong2ss

안녕하세요 리뷰어님 :)

인수테스트 기반으로 리팩토링을 하다보니 확실히
초기에 시간은 더 소요되지만, 리팩토링으로 인한 소스 변경에도 기능 요구사항이 안전하게 보호받는 것 같네요..!

Step1 - 인수 테스트 기반 리팩터링
리뷰 부탁드립니다!

2022-06-13 17:47 UTC, dhmin5693 requested changes
안녕하세요. ATDD + TDD 미션을 함께할 민동휘라고 합니다.
반갑습니다. 👋

첫 번째 미션이라 가급적 빨리 merge하고 싶지만 확인이 필요한 부분이 있어서 부득이하게 코멘트를 남겼습니다.
확인 후 다시 요청 부탁드릴게요. 🙏

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Line.java
>      public Line() {
JPA entity의 기본 생성자는 protected로 해주세요.
https://stackoverflow.com/questions/6033905/create-the-perfect-jpa-entity

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Section.java
>      public Section() {
여기도 마찬가지로 기본 생성자는 protected로 변경해주세요!

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public List<StationResponse> getStationResponses() {
참조의 방향이 잘못되었습니다.

Layered Architecture 에서는 상위 레이어에서 하위 레이어를 참조하며, 한 방향으로 흐르도록 작성되어야 합니다.
`StationResponse`는 presentation layer로, 최상위에 위치합니다.
반면 `Line`은 최하위에 위치한 persistence layer입니다.

controller에서 service는 참조해도 그 반대로는 하지 않는다는걸 생각해보면 이해하기 쉽습니다.

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            if (!nextLineStation.isPresent()) {
1 depth를 유지해주세요.

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void addSection(Line line, Station upStation, Station downStation, int distance) {
메소드가 너무 길어요.
10라인까진 안되더라도 최대한 분리해주세요.

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void addSection(Line line, Station upStation, Station downStation, int distance) {
굉장히 복잡한 메소드임에도 검증이 되어 있지 않습니다.
또한 이번 미션은 ATDD + TDD를 경험하는게 목적입니다.
테스트를 작성하시는건 어떨까요?

테스트는 검증 뿐만 아니라 코드가 어떠한 일을 하는지 추측하게 쉽게 만드는 이정표의 역할도 합니다.
getter 등 굉장히 간단한 로직을 제외하고 public으로 공개가 된 모든 메소드의 테스트를 작성해주세요.

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        boolean isDownStationExisted = isDownStationExisted(downStation);
여기서 참조한 두 개의 메소드 내부에서 getStations()을 참조하고 있습니다.
getStation() 은 정렬 로직을 수행하기 때문에 굉장히 느린 편이에요.

성능 최적화를 해보면 어떨까요?

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        } else if (isDownStationExisted) {
85번째 줄 이전까지는 역 포함 여부에 따라 오류를 내고 있습니다.
1. 상행 포함/하행 포함 - 오류
2. 상행/하행 전부 미포함 - 오류

그렇다면 85번째 줄까지 도달하였을 때 상, 하행 중 하나만 포함이 되는 상태가 되겠죠.
상행이 포함된다면 85번째 줄의 if에 걸려 86번째 줄의 로직을 수행할거에요.
90번째 줄은 else if로 되어 있지만 사실상 else를 수행하고 있다고 보여집니다.

이번 미션에서도 else는 사용하지 않는 것을 권장드립니다.

2022-06-13 17:47 UTC, dhmin5693 commented on src/test/java/nextstep/subway/line/acceptance/LineStationScenarioTest.java
> +    @DisplayName("지하철 구간 관련 기능 시나리오 테스트")
실패하면 400 오류를 내는 케이스도 작성이 되어야 합니다.

2022-06-13 17:47 UTC, dhmin5693 commented on src/test/java/nextstep/subway/line/domain/DistanceUnitTest.java
> +    @Test
`DisplayName`에 원인과 결과가 명확하도록 설명하는 문구를 작성해주세요.

2022-06-13 17:47 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            return Arrays.asList();
```suggestion
            return Collections.emptyList();
```
이렇게 하면 의도를 더 잘 드러낼 수 있지 않을까요?
asList()는 매개변수로 배열을 받는데, 입력하지 않은 경우 빈 배열을 생성하기 때문에 메모리 낭비가 됩니다.

2022-06-14 14:44 UTC, yong2ss commented
안녕하세요 리뷰어님 :)
다시 보니 수정할 수 있는 부분이 많네요...!
리뷰해주신 내용 기반으로 리팩토링 진행하였습니다!

2022-06-14 14:46 UTC, yong2ss commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        boolean isDownStationExisted = isDownStationExisted(downStation);
이 부분이 조금 헷갈려서 그런데, getStations을 한번만 참조하는 방법 말고
혹시 성능 개선을 위해서 생각해두신 다른 방법이 있을까요?

2022-06-14 15:35 UTC, dhmin5693 approved these changes
피드백 잘 반영해주셨네요 👍 
다음 단계 진행을 위해 1단계는 마무리하도록 하겠습니다.

몇 가지 코멘트를 더 남겨두었어요.
이번 미션에 굉장히 중요한 부분이니 꼭 확인 부탁드리고, 다음 미션 전에 반영해주세요.

수고하셨습니다.

2022-06-14 15:35 UTC, dhmin5693 commented on src/test/java/nextstep/subway/line/domain/SectionsUnitTest.java
> +    }
이번 미션은 ATDD와 TDD가 혼합된 미션이에요.

TDD의 장점이 무엇일까요?
테스트 시나리오를 먼저 작성해보고 그 시나리오부터 코드를 도출해내는게 TDD입니다.
그 결과 실제 사용 시나리오 기반으로 도출해 냈기 때문에 코드가 조금 더 짜임새있게 구성이 됩니다.

하지만 TDD를 완벽하게 수행하는건 굉장히 어려운 일입니다.
그래서 TDD 미션 중에 테스트를 먼저 작성하는건 권장하고 있지는 않아요.

다만, 테스트 자체는 조금 더 다양한 시나리오를 고려해주셨으면 합니다.
TDD가 아니더라도 테스트는 시나리오 기반이 되어야 합니다.
`@DisplayName`에 given-when-then처럼 명확한 전제와 결과가 나타나 있어야 그 코드를 검증했다고 할 수 있습니다.

이 테스트를 예시로 들어보겠습니다.
**새로운 구간을 추가한다.** 라는 설명이 쓰여 있지만, 정용님께서 이 테스트를 작성하셨을 때 실제로 기대하셨던 바는 `(예외에 걸리지 않는 조건일 때) Sections에 새로운 구간을 추가할 수 있다`가 아닐까요?

그럼 이 테스트는 성공 시나리오를 검증한게 됩니다.
성공 시나리오가 있으면 실패 시나리오도 있어야 완벽히 검증했다고 할 수 있을거에요.
어떤 매개변수를 사용하면 예외가 발생한다던가... 하는 시나리오가 많을겁니다.
실제로 테스트를 많이 작성하게 된다면 실패 시나리오가 더 많은 경우가 일상적입니다.

인텔리제이를 활용하신다면 `Run Test with coverage` 기능을 활용해보시기 바랍니다.
어디가 검증되지 않았는지를 한 눈에 파악하기 쉽습니다.

말이 길어졌는데요, 결론을 요약해서 말씀드리겠습니다.

```plain text
1. 테스트는 시나리오 기반으로 작성해주세요.
2. 무엇을 더 검증해야 하는지를 더 고려해주세요.
    - 실패 케이스, 엣지 케이스(예를 들어 0 이하에서 오류가 나는 메소드는 0 값을 검증) 등 
```

2022-06-14 15:35 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Station nextSectionDownStation(List<Station> stations, Station downStation) {
잘 분리해주셨네요 😄

여기서도 코멘트를 남겨보자면, 매개변수로 콜렉션을 넘기고 그 메소드에서 콜렉션에 무언가를 하는 방식은 코드 추적에 어려움을 가미하는 요소가 됩니다.

이해를 돕기 위해 극단적인 예를 들어보자면 `List<String> strs`가 있다고 하겠습니다.
그리고 같은 메소드 내에 strs를 매개변수로 받는 10개의 메소드가 있습니다.
어떤 메소드는 strs에 add를 하고 있고 어떤 메소드는 단순히 확인만 하고 있습니다.
심지어 어떤 메소드는 remove로 제거도 하고 있다면 어떨까요?
`List`의 데이터 변화가 어디서 일어나는지 확인해보려면 10개의 메소드를 전부 확인해보아야 할거에요.

실제로 이 메소드에서 `stations`가 하는 일은 로직의 끝부분에서 구한 `nextStation` 을 추가하는 것입니다.
그렇다면 이 `List`, 메소드 바깥에 있어도 괜찮지 않을까요?

2022-06-14 15:35 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Section> getSections() {
안쓰는 메소드는 삭제해주세요.

2022-06-14 15:35 UTC, dhmin5693 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        while (Objects.nonNull(downStation)) {
취향을 타는 부분이지만 저는 `Objects.nonNull`은 가독성에 큰 도움이 안된다고 생각하여 쓰지 않는 편이에요.
게다가 이 메소드는 나온 목적이 따로 있습니다.
API 문서에는 이렇게 기재되어 있어요.

```
API Note:
This method exists to be used as a java.util.function.Predicate, filter(Objects::nonNull)
```

스트림 등 체이닝 연산을 할 때 사용되는 `Predicate`를 위해 존재한다고 하네요.

2022-06-14 15:36 UTC, merged