🚀 1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #602
Opened 2022-06-14 17:36 UTC by 14km

안녕하세요 :) 

잘부탁드립니다. ( _ _)

2022-06-15 12:42 UTC, seokhongkim requested changes
민태님 안녕하세요.
인수 테스트 기반 TDD 미션을 함께 진행할 리뷰어 김석홍입니다. 만나서 반갑습니다. 😀 

1단계 미션 잘 진행해주셨습니다.
코드에 코멘트를 조금 남겼으니 확인 부탁드립니다. 🙏

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/advice/GlobalRestControllerAdvice.java
> +public class GlobalRestControllerAdvice {
예외 처리를 위한 어드바이스 사용 좋습니다. 👍

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(NoSuchElementException::new);
적절한 예외로 변경하신 것 좋습니다. 👍

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.findById(id).orElseThrow(NoSuchElementException::new);
`findLineById` 의 로직과 중복되는 것으로 보이네요!

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void addSection(Section section) {
민태님은 메소드 배치를 어떤 순서로 하시나요?

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private void validate(Section section) {
메소드의 이름이 너무 범용적인 것 같습니다!

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public boolean isNextUpSection(Station station) {
`isNextUpSection` 과 `isNextDownSection` 의 메소드명이 행위를 잘 설명해주지 못하는 것 같습니다.
하행 구간이 존재하는지, 상행 구간이 존재하는지 확인하는 메소드일까요?

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/common/Messages.java
> +    public static final String NOT_FOUND_REMOVE_STATION = "[ERROR] 노선 삭제할 노선은 최소 1개이상 존재해야합니다.";
예외 변수명은 삭제할 역을 찾지 못했을 때 발생하는 것으로 읽히는데, 내용은 노선에 삭제 후 구간이 1개 이상 존재해야 한다는 내용이네요!

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            throw new IllegalArgumentException(NOT_FOUND_REMOVE_STATION);
인자로 들어온 값이 잘못된 것이 아니고, 현재 남은 구간의 상태가 삭제할 수 없는 상태이므로 더 적합한 다른 예외를 사용하실 수 있을 것 같습니다!

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean matchUpStation(Station station) {
`isNextUpSection`, `isNextDownSection` 과 동일한 구현으로 보이네요.

2022-06-15 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean isUpStationAndDownStation(Station station) {
구간의 상행역이자 하행역이면 이 역은 어떤 역일까요? 혹은 어떤 역이 아닐까요?

2022-06-15 12:42 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/domain/LineTest.java
> +    private Line 지하철_2호선;
실제 노선을 바탕으로 테스트를 작성해주셔서 읽고 이해하는데 더 수월했습니다. 👍

2022-06-15 14:40 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void addSection(Section section) {
관례상에 정적 변수는 최상위, public 메서드인지, private 메서드인지를 우선적으로 보고 public을 상위에 두는 것으로 보통 처리합니다 :)

추가로, 읽는 관례상에서 연관되어있는 메서드들이 있다면 사람 인지능력을 고려하여 배치하는 것 같습니다.

2022-06-15 14:44 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public boolean isNextUpSection(Station station) {
네, 존재하는지 확인하는 메서드인데요 hasNextUpSection로 변경해보았습니다 :)

2022-06-15 14:44 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public boolean isNextUpSection(Station station) {
혹시 생각하시는 조금 더 좋은 메서드 명칭이 있을까요?

2022-06-15 14:45 UTC, 14km commented on src/main/java/nextstep/subway/common/Messages.java
> +    public static final String NOT_FOUND_REMOVE_STATION = "[ERROR] 노선 삭제할 노선은 최소 1개이상 존재해야합니다.";
앗! 제가 수정하면서 제대로 메서드 명칭을 안바꾼것 같습니다 :)

2022-06-15 14:47 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            throw new IllegalArgumentException(NOT_FOUND_REMOVE_STATION);
음.. 요청하는 측면에서는 잘못된것일 수 있다고 생각했습니다.

\[삭제하려고! -> 삭제할게 없어 잘못된 인자야!\] 라고 형태라고 생각했습니다 :) 

관련해서 추천해주실 에러처리가 있을까요?

2022-06-15 14:51 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean matchUpStation(Station station) {
수정했습니다 :)

2022-06-15 14:54 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean isUpStationAndDownStation(Station station) {
관련해서 모호한 메서드 명칭 수정 완료했습니다. :)

2022-06-16 00:09 UTC, seokhongkim approved these changes
민태님, 1단계 미션 피드백 잘 반영해주셨습니다. 👍 
1단계 PR은 이만 머지하도록 하겠습니다.

코멘트를 조금 남겼는데, 2단계 미션을 진행하실 때 참고해보시면 좋겠습니다.
2단계 미션에서 뵙겠습니다. 😀

2022-06-16 00:09 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void addSection(Section section) {
public method 내부에서 사용하는 private method 가 위치상으로 멀리 떨어져 있다보니, public method 의 로직을 확인하기 위해 코드를 위 아래로 많이 이동하며 private method 를 찾아야 할 필요가 있네요.

클린 코드의 코드 순서와 관련된 내용을 참고하여 메소드 배치 순서를 고민해보시면 민태님에게 도움이 될 것 같습니다. :)

2022-06-16 00:09 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public boolean hasNextUpSection(Station station) {
이 메소드의 네이밍이 조금 헷갈렸던 것 같아요.
`hasNextUpSection` 이라서 다음 상행구간이 존재하는지 반환한다고 생각했는데, 구현은 `upStation` 이 일치하는 하행구간이 있는지 여부를 반환하네요!
`upStation` 이 같은 구간이 존재하는지 반환하는 메소드로도 변경할 수 있을 것 같습니다.

2022-06-16 00:09 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            throw new IllegalArgumentException(LEAST_ONE_MUST_EXIST_REMOVE_STATION);
`IllegalStateException` 을 사용해보시는 건 어떨까요?
`IllegalArgumentException` 의 경우 인자를 변경하면 성공할 수 있다는 내용을 내포하고 있다고 생각합니다.

예를 들면, http 요청에 대해서도 400번대 응답은 클라이언트 측에서 조치를 취할 수 있지만, 500번대 코드는 서버측 문제라는 것을 나타내는 것처럼 예외도 비슷한 역할을 한다고 생각합니다.

2022-06-16 00:09 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean hasUpStationAndDownStation(Station station) {
상행구간과 하행구간이 모두 존재하면 `종점이 아닌 역` 이지 않을까요?
메소드의 이름은 가능하면 구현이 아닌 행위를 서술하는 것이 더 좋다고 생각하고, 도메인의 언어로 설명되는것이 더 좋다고 생각합니다.

2022-06-16 00:09 UTC, merged

2022-06-16 14:43 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            throw new IllegalArgumentException(LEAST_ONE_MUST_EXIST_REMOVE_STATION);
오 좋은 의견 감사드립니다 ( \_ \_)

2022-06-16 14:48 UTC, 14km commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private boolean hasUpStationAndDownStation(Station station) {
:+1: 감사합니다 좋은 의견인것 같습니다.