Step4 요금조회
next-step/atdd-subway-service pull request #607
Opened 2022-06-15 13:48 UTC by cyr9210

안녕하세요.
인수테스트 기반 TDD 4단계 요금 조회 기능 리뷰 요청드립니다.
감사합니다.

2022-06-16 13:44 UTC, wooobo requested changes
안녕하세요 용락님!

개인적으로 요금조회 미션이 굉장히 어려운 미션이라고 생각하는데요
아주 잘 구현해주셨습니다!
고민하시면 좋을것 같은 부분들 코멘트 남겨드렸는데
확인해보시고 재요청 부탁드릴께요~ :pray:

2022-06-16 13:44 UTC, wooobo commented on src/main/java/nextstep/subway/path/application/SectionEdge.java
> +public class SectionEdge extends DefaultWeightedEdge {
상속 :+1:

2022-06-16 13:44 UTC, wooobo commented on src/main/java/nextstep/subway/auth/domain/LoginMember.java
> +    public DiscountType getDiscountType() {
`LoginMember` 도메인에서 `DiscountType`을 반환해주는게 개인적으로는 어색한것 같긴해요.
`AgeGroup` 혹은 그러한 `Enum` 혹은 `class`가 있으면 어떨까요?

개인적인 관점이며, 꼭 변경해야하는것은 아닙니다!

2022-06-16 13:44 UTC, wooobo commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Line(String name, String color, Station upStation, Station downStation, int distance, int addFee) {
메서드 : 동사
변수명 : 명사
의 관점을 보았을때, `additionalFee`는 어떤가요?

2022-06-16 13:44 UTC, wooobo commented on src/main/java/nextstep/subway/member/ui/MemberController.java
> +        loginMember.checkLoginUser();
해당 방법처럼 해도 되지만,
로그인 유저 정보가 잘못되었을때는 `@AuthenticationPrincipal` 을 통해  
`AuthorizationException` 과 같은 예외를 발생시키는 관점에 대해서는 어떻게 생각하시나요? :thinking: 
그렇게 된다면 `loginMember.checkLoginUser();` 코드가 반복적으로 발생하지 않을것 같아서요!

2022-06-16 13:44 UTC, wooobo commented on src/main/java/nextstep/subway/path/domain/Fee.java
> +public class Fee {
아주 잘구현해주셨네요!
메서도이름을 통해 의도를 잘 파악 할 수 있어서 이해하기 쉬웠습니다!

이번 요금 계산 미션에서 개인적으로 `개방-폐쇄 원칙 (OCP: Open-Closed Principle)` 을 활용해 보기 좋은 요구 사항이라고 생각하는데요!

현재 로직상 정책조건이 추가되면 `Fee` 의 변경을 지속적으로 해야해서 확장에는 닫혀있는 형태가 될수 있지 않을까 조심스럽게 생각해보았어요.

현재 구조에서 어려운 부분일수 있겠지만, 여건이 되신다면 변경에는 닫혀있고 확장에는 열려있는 `개방-폐쇄 원칙`을 고려해서 한번 리팩토링 도전을 해보셔도 좋고, 혹은 한번 고민만 해보셔도 충분히 좋을것 같아요!

#### 개방-폐쇄 원칙 (OCP: Open-Closed Principle)
> 소프트웨어 엔티티(클래스, 모듈, 함수 등)는 확장에 대해서는 열려 있어야 하지만 변경에 대해서는 닫혀 있어야 한다.

2022-06-16 13:44 UTC, wooobo commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    public void getFee_yesAddCharge_yesDiscount() {
`청소년`, `어린이` , `거리` 케이스별로 테스트를 만들어보는것도 좋은 훈련이 될거라고 생각해요!

2022-06-16 15:54 UTC, cyr9210 commented on src/main/java/nextstep/subway/path/domain/Fee.java
> +public class Fee {
네 관련내용 찾아보고 잘 생각해 보겠습니다!👍

2022-06-17 05:38 UTC, wooobo requested changes
피드백 빠르게 반영해주셨네요!

피드백 변영하면서 테스트 실패가 되고 있는것 같아서 
해당부분 코멘트 달아 드렸어요! 

확인부탁드려요! 🙏 🙏

2022-06-17 05:38 UTC, wooobo commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
![스크린샷 2022-06-17 오후 1 24 23](https://user-images.githubusercontent.com/12059592/174224574-33962008-30e6-4465-910c-c874692e55b3.png)

2022-06-17 05:38 UTC, wooobo commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
`null`을 리턴하도록 수정은 해주셨지만, 
아래 방법 또한 제안드리고 싶네요!

2022-06-17 05:38 UTC, wooobo commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
이전 피드백에서 설명이 다소 부족했던것 같아 죄송합니다!! 🙏 

`@AuthenticationPrincipal`을 사용하지만 같은 컨트롤러로 유입시키고 싶을때
아래처럼 해보면 좋을것 같아요.
그이유는 `null`이라는 것보다는 의미있는 객체를 리턴해주는게 좋다고 생각해요!

```
public @interface AuthenticationPrincipal {
    boolean required() default true;
```

```
#AuthenticationPrincipalArgumentResolver.java

AuthenticationPrincipal principal = parameter.getParameterAnnotation(AuthenticationPrincipal.class);

if (!principal.required() && credentials == null) {
    return new LoginMember();  혹은 new NoneLoginMember();
 }
```


```
# 로그인안되어있어도 허용해야하는 경우
@AuthenticationPrincipal(required=false)
```


2022-06-17 05:38 UTC, wooobo commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
피드백 반영하면서, 
`"로그인 하지 않은, 추가요금이 없는, 요금을 구한다."` 같은 테스트가 실패되는것 같아요!

2022-06-17 05:40 UTC, wooobo commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
혹시 궁금한 내용있으시면 DM주셔도 됩니다!

2022-06-17 11:07 UTC, cyr9210 commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
좋은 피드백 감사드립니다.
다만 말씀하신 테스트가 정상적으로 동작하여, 수정하지 않았는데 혹 실패한다면 말씀부탁드립니다.!

2022-06-17 11:23 UTC, wooobo commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        double discountPercent = loginMember.isLogin() ? loginMember.getDiscountPercent() : 0.0;
:100:

2022-06-17 11:23 UTC, wooobo commented on src/main/java/nextstep/subway/favorite/ui/FavoriteController.java
> +    public ResponseEntity<Void> delete(@AuthenticationPrincipal(required = false) LoginMember member,
:+1:

2022-06-17 11:23 UTC, wooobo commented on src/main/java/nextstep/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
> +        if (credentials == null) {
앗 실패하지 않네요! 제가 착오가 있었나봅니다! 
혼선을 드려 죄송합니다 :pray:

2022-06-17 11:26 UTC, wooobo approved these changes
피드백 고민해주셔서 감사합니다!

실패하는 테스트는 착오가 있었던것 같습니다 죄송합니다 :pray: 

힘든 미션이었을텐데 잘 완료해주셨네요 :+1: 
이만 `merge` 진행하도록 하겠습니다.

남은 미션도 응원하겠습니다 :smile:

2022-06-17 11:27 UTC, merged