4단계 - 요금 조회
next-step/atdd-subway-service pull request #609
Opened 2022-06-15 14:35 UTC by tyakamyz

안녕하세요 리뷰어님
 4단계 - 요금 조회 PR 드립니다 :)

노선별 추가 요금 부분은 조금 어려워서 
계속 번복하면서 코드를 작성 하다보니 커밋을 한번에 해버렸네요ㅜ
보실때 불편하실것 같아서 죄송합니다..ㅜ

계속 피드백 받았던 의존성 부분을 학습하면서 코드를 작성했는데 연습이 많이 필요할 것 같네요

그럼 마지막 리뷰도 잘 부탁드리겠습니다!

2022-06-16 05:53 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다 👍 
추가적인 코멘트 남겨두었으니 확인 부탁드릴게요!

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private Integer overFare;
overFare는 null을 허용하는 값일까요?

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/PathFinderGraph.java
> +    void addEdge(Section section, WeightedMultigraph<Station, SectionGraphEdge> graph, SectionGraphEdge sectionGraphEdge);
해당 인터페이스를 사용하는 클라이언트 입장에서 모든 메서드가 필요할지 고민해보아요!

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/member/domain/MemberAge.java
> +public class MemberAge {
`calculateDiscountFare`의 역할은 FareAgePolicy에게 넘겨줄 수 있을 것 같은데, 해당 클래스의 역할은 무엇일까요?

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
>              favoriteRepository.deleteById(id);
마땅한 위치가 없어 여기에 남겨두도록 하겠습니다~

https://github.com/next-step/atdd-subway-service/pull/570#discussion_r896765305

> Member가 여러개의 즐겨찾기를 저장할 수 있다고 생각해서
> memberId, sourceStationId, targetStationId 3개가 묶여야 중복되는 데이터가 없어서 인덱싱이 빠르게 동작할 것이라고 생각하였습니다

의 답변을 드리자면..!
3개의 컬럼을 인덱스로 잡아도 인덱스를 타겠지만, 지금의 구현에서는 memberId만 인덱스로 잡아도 동작할 것 같습니다 😄

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/path/domain/FareAgePolicy.java
> +    private final int max;
`Predicate`를 사용하여 인스턴스 변수를 줄이고 조건에 대한 확장성을 높일 수 있을 것 같네요 :)

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +        return new Path(path.getVertexList(), distance, Fare.of(Sections.of(path.getEdgeList()), new TotalDistance(distance), age).getFare());
한 라인에 너무 많은 코드가 있어 가독성이 떨어지는 것 같은데요.
중간변수를 추가하여 가독성을 높여보면 어떨까요?

2022-06-16 05:53 UTC, jaeyeonling commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AuthenticationPrincipal LoginMember loginMember, @RequestParam Long source, @RequestParam Long target) {
120라인이 넘을 경우 줄바꿈을 통해 가독성을 높여보아요 :)

2022-06-16 05:53 UTC, jaeyeonling commented on src/test/java/nextstep/subway/path/domain/FareTest.java
> +    void of() {
어떠한 테스트인지 파악할 수 있는 메서드명으로 변경 혹은 @DisplayName을 추가해보면 어떨까요?

2022-06-16 10:21 UTC, tyakamyz commented on src/main/java/nextstep/subway/line/domain/PathFinderGraph.java
> +    void addEdge(Section section, WeightedMultigraph<Station, SectionGraphEdge> graph, SectionGraphEdge sectionGraphEdge);
인터페이스로 선언하려면 조금 더 간결하게 정리해야될 것 같네요!

2022-06-16 10:22 UTC, tyakamyz commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private Integer overFare;
int 형으로 변경하겠습니다 :)

2022-06-16 10:30 UTC, tyakamyz commented on src/main/java/nextstep/subway/member/domain/MemberAge.java
> +public class MemberAge {
age 원시값을 포장하려는 목적과 Fare 도메인에서 FareAgePolicy에 대한 의존성을 줄이고 싶어서 클래스를 따로 생성하여 처리하였습니다!

2022-06-16 10:34 UTC, tyakamyz commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
>              favoriteRepository.deleteById(id);
답변 감사드립니다 :)
추가로 궁금한 점이 하나 생겨서 여쭤봅니다!
memberId가 중복될 수 있을 것 같은데 데이터가 많아졌을 경우에도 인덱스로 잡아도 무리가 없을까요?

2022-06-16 10:34 UTC, tyakamyz commented on src/main/java/nextstep/subway/path/domain/FareAgePolicy.java
> +    private final int max;
Predicate에 대해 학습하겠습니다 :)

2022-06-16 13:14 UTC, tyakamyz commented
피드백 모두 반영 완료했습니다!
확인 부탁드리겠습니다 :)

항상 꼼꼼하게 피드백 해주셔서 감사합니다
어떤 부분에 조금 더 신경 써서 코드를 작성해야 하는지 많이 느끼게 된 시간이었던 것 같습니다
감사합니다 :)

2022-06-17 07:57 UTC, jaeyeonling requested changes
피드백을 잘 반영해주셨습니다 👍 
질문의 답변 남겨두었으니 확인 부탁드리고, 확인해주시면 머지하도록 하겠습니다 😄

2022-06-17 07:57 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/PathFinderGraph.java
> +    void addEdgeAndWeight(List<Section> sections);
Path를 구하는 시점에 해당 값들을 추가할 수 있다면 메서드를 하나로 줄여볼 수 있겠네요 ㅎㅎ

2022-06-17 07:57 UTC, jaeyeonling commented on src/main/java/nextstep/subway/member/domain/MemberAge.java
> +public class MemberAge {
`age 원시값을 포장하려는 목적`은 어떠한 역할을 담당하기 때문이라고 생각이 드는데요.
그 역할이 `FareAgePolicy`와의 의존성을 줄이는 것이 맞을까요?
MemberAge -> FareAgePolicy 로 의존성이 끊어진 것이 아니기 때문에 아직도 의존성이 남아있다고 생각이 드는데 어떻게 생각하시나요?

2022-06-17 07:57 UTC, jaeyeonling commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
>              favoriteRepository.deleteById(id);
일반적으로 인덱스는 중복도가 낮은 값을 잡는 것이 원칙인데요.
memberId의 경우 중복이 될 수는 있어도 중복도가 낮기 때문에 카디널리티가 높아 인덱스로 잡기에 적합하다고 생각이 듭니다 😄

2022-06-17 07:57 UTC, jaeyeonling commented on src/main/java/nextstep/subway/path/domain/FareAgePolicy.java
> +    TEENAGER(13, 19, 350, 0.8),
```suggestion
    TEENAGER(age -> 13 <= age && age < 19, 350, 0.8),
```
 
취향차이지만..! 바로 조건을 넘겨줄 수도 있을 것 같습니다 ㅎㅎ

2022-06-17 09:20 UTC, tyakamyz commented
마지막 피드백 주신 내용들 모두 반영 완료했습니다 :)

2022-06-18 04:03 UTC, jaeyeonling approved these changes
미션을 잘 진행해주셨어요 👍 
수 많은 코멘트 반영하시느라 고생 많으셨습니다!
마지막까지 힘내주시고, 좋은 소식으로 다시 뵙겠습니다 😄

2022-06-18 04:03 UTC, merged