Step2 - 경로 조회 기능
next-step/atdd-subway-service pull request #610
Opened 2022-06-15 16:41 UTC by kmmin78

안녕하세요, 석홍님! 🙇‍♂️

5주차 2단계 - 경로 조회 기능 리팩터링 PR 드립니다.

외부 라이브러리와 그래프 자료구조를 활용해서 최단 경로를 구하는 과정이 흥미로웠습니다.

이번 리뷰도 잘 부탁드립니다! 😊

2022-06-16 13:47 UTC, seokhongkim requested changes
민성님, 2단계 미션 잘 구현해주셨습니다. 👍 

작은 커밋을 유지하고, 인수 테스트를 먼저 작성하신 점이 특히 좋았습니다.
리뷰를 위해 커밋 단위로 보니 코드 파악이 수월했습니다.

이번 코드는 피드백 드릴 부분이 많지 않아서, 코멘트를 조금만 남겼습니다.
확인 부탁드립니다. 🙏

2022-06-16 13:47 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/PathNavigator.java
> +        checkSourceEqualToTarget(sourceStation, targetStation);
출발역과 도착역이 동일한지 여부는 경로를 처음 조회할 때 바로 검증할 수 있을 것 같아요.
이를 통해 성능상의 이점도 가져올 수 있을 것 같습니다.

밸리데이션을 어느 곳에서 할 지(`PathService` or `PathNavigator` or 두 곳 모두)도 고민해보시면 도움이 될 것 같아요!

2022-06-16 13:47 UTC, seokhongkim commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
>  public class PathAcceptanceTest extends AcceptanceTest {
꼼꼼한 통합 테스트 작성 좋습니다. 👍

2022-06-16 13:47 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/PathNavigator.java
> +public class PathNavigator {
`PathNavigator` 에서 몇 가지 비즈니스 로직을 가지고 있으니, 단위 테스트도 추가로 작성해보는 건 어떨까요?

2022-06-16 13:47 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/exceptions/SourceAndTargetSameException.java
> +public class SourceAndTargetSameException extends RuntimeException {
상황별로 커스텀한 예외를 만들어서 사용하신 것 좋습니다. 👍

2022-06-16 13:50 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +    @ExceptionHandler({SourceAndTargetSameException.class, SourceNotConnectedWithTargetException.class,
혹시 모르신다면, 예외 처리를 어드바이스를 통해 하는 방법도 학습하고 적용해보셔도 좋을 것 같습니다. :)
이미 알고 계신다면, 어드바이스로 하는 것과 컨트롤러 내부에 `ExceptionHandler` 를 위치하는 것 사이의 장단점을 알고 선택하셨을거라고 생각하여 넘어가셔도 괜찮습니다.

2022-06-18 17:26 UTC, kmmin78 commented on src/main/java/nextstep/subway/path/util/PathNavigator.java
> +        checkSourceEqualToTarget(sourceStation, targetStation);
만약 출발역과 도착역이 동일한지 여부를 앞 쪽에 추가한다면, Controller에서 할 것 같습니다.
source와 target의 id만으로도 validation을 할 수 있으니까요!
저는 PathController와 PathNavigator 두 곳에서 하겠습니다.

2022-06-18 17:30 UTC, kmmin78 commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +    @ExceptionHandler({SourceAndTargetSameException.class, SourceNotConnectedWithTargetException.class,
ControllerAdvice를 알고 있었지만, Path 관련 예외는 PathController에서 잡아야 겠다고 생각했었습니다.
그런데 전체 패키지를 살펴보니 StationController와 LineController에서도 중복이 되고 있네요.
전체 Exception을 Handling 하도록 옮겨놓겠습니다!

2022-06-19 08:40 UTC, seokhongkim approved these changes
민성님, 2단계 미션 피드백 잘 반영해주셨습니다! 👍 
2단계 PR은 이만 머지하도록 하겠습니다.

미션 진행하시며 고민하신 부분이나, 궁금한 점에 대해서는 PR에 코멘트 또는 슬랙 DM으로 편하게 남겨주세요.
그럼 3단계 미션에서 뵙겠습니다. 😀

2022-06-19 08:40 UTC, seokhongkim commented on src/main/java/nextstep/subway/GlobalExceptionHandler.java
> +    public ResponseEntity handleIllegalArgsException(final Exception e) {
어드바이스로 예외 처리하는 로직을 모으신 것 좋네요! 👍 
여러 예외 케이스를 다루는만큼 메소드 이름도 변경해볼 수 있을 것 같습니다.

2022-06-19 08:41 UTC, merged