4단계 - 요금조회
next-step/atdd-subway-service pull request #622
Opened 2022-06-16 14:35 UTC by tj3828

안녕하세요.ㅎㅎ
어느덧 마지막 단계네요.

이전 미션까지는 TDD를 하려고 노력하면서 커밋도 단위별로 구분하려고 노력해봤는데,
이번 미션에서는 로직이 조금 복잡해졌다고, 잘 못 지켰습니다 ㅜ,ㅜ

나이와 거리, 노선에 따른 추가요금을 계산하는 로직을 정책으로 잡고 인터페이스로 구분해보았는데,
잘 분리되고 확장성있게 설계했는지 잘 모르겠네요..

그래도.. 커밋에서는 들어나지 않지만..
인수테스트부터 고치면서 테스트 기반으로 로직을 수정해서 많이 배웠습니다.

3단게 피드백 주신 부분도 함께 커밋해두었습니다.
리뷰 잘 부탁드립니다~!

2022-06-17 08:23 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다 👍 
코멘트 남겨두었으니 확인 부탁드려요~

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +    AgeFarePolicyType(Class<? extends AgeFarePolicy> ageFarePolicy) {
```suggestion
    private final Class<? extends AgeFarePolicy> ageFarePolicy;
    
    AgeFarePolicyType(Class<? extends AgeFarePolicy> ageFarePolicy) {
```

공백을 추가하면 가독성이 올라갈 것 같아요!

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +    private static AgeFarePolicy getAgeFarePolicyInstance(AgeFarePolicyType type) {
상태를 가지지 않는 객체를 매번 생성할 필요가 있을까요?
성능의 문제도 있겠지만, 코드의 가독성이나 디버깅에도 문제가 있을 것 같은데 어떻게 생각하시나요?

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +    Teenager(TeenagerAgeFarePolicy.class);
```suggestion
    TEENAGER(TeenagerAgeFarePolicy.class);
```

enum의 경우 어퍼케이스로 작성해주는 것이 관례입니다 :)

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +        int lineFare = ageFarePolicy instanceof FreeAgeFarePolicy ? 0 : additionalLineFare;
instanceof가 사용된다면 다형성을 잘못 사용하고 있는게 아닐까? 의심해 볼 수 있을 것 같아요!

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/impl/AdultAgeFarePolicy.java
> +    public boolean isAge(int age) {
`isAge`라는 메서드명으로 봤을 때 해당 역할을 나타낼 수 있을지 고민해보아요.

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicy.java
> +    int middleDistance = 50;
인터페이스의 목적으로 봤을 때 세부적인 내용을 담은 값을 가지고 있는게 어색하게 느껴지네요!
인터페이스 역할에 맞게 제거해보면 어떨까요?

2022-06-17 08:23 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicyType.java
> +    OVER_50KM(LongDistanceFarePolicy.class);
10KM 50KM 등 거리에 대한 부분은 언제든 변경이 될 수 있을 것 같은데 이름으로 사용해도 괜찮을까요?
또한 거리에 대한 조건은 MiddleDistanceFarePolicy, LongDistanceFarePolicy 내부에 존재하기 때문에 매번 같이 신경써줘야 하는 문제도 있겠네요!

2022-06-17 11:06 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +    private static AgeFarePolicy getAgeFarePolicyInstance(AgeFarePolicyType type) {
싱글톤 객체로 만든다고 했는데, 여러가지 만지다가 날라간거 같습니다 ㅜㅜ

2022-06-17 11:06 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +    Teenager(TeenagerAgeFarePolicy.class);
😂

2022-06-17 11:07 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +        int lineFare = ageFarePolicy instanceof FreeAgeFarePolicy ? 0 : additionalLineFare;
인터페이스에 default 메소드를 활용하여 수정하곘습니다!

2022-06-17 11:11 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicy.java
> +    int middleDistance = 50;
사실 이 부분 짤 때,해당 변수들을 인터페이스에 담기에도 어색하고..
이걸 또 static 변수들을 위한 클래스로 만들기도 어색함이 있어서 고민이 있었습니다.

정책에 대한 변수이지만 다수의 정책 중 몇개의 정책만 다른 값을 사용하다보니 애매했습니다.

일단 모든 정책에서 공통으로 사용되는 변수는 enum클래스에 static 변수로 뽑고,
정책 클래스 내부에서만 로컬 변수로 쓰이는 것들만 클래스로 이동시켰는데,
뭔가.. 다 마음에 들지 않아서 다른 좋은 분리 방법이 있을까 궁금합니다..!

2022-06-17 11:13 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicyType.java
> +    OVER_50KM(LongDistanceFarePolicy.class);
정책에 명칭과 동일하게 명칭을 수정하고,
거리에 대한 조건은 enum 클래스에 static 변수로 뽑아보았습니다.

2022-06-17 11:23 UTC, tj3828 commented
피드백 주신 부분 반영하였습니다.
다만, 설계 방법 중 어느 것이 효율적일까 에 대한 질문이 있어 코멘트 남깁니다!

지금은 enum 클래스로 각 조건에 따라 구현체를 찾아갈 수 있도록 되어있지만,
한가지 선택지로 생각했던 방법은 enum 클래스에 각 조건(나이,거리)과 Function을 value로 사용하는 방법입니다.

정책에서는 각 조건에 맞게 요금을 계산하는 하나의 역할과 책임만 가지기 때문에 충분히 Function을 value로 사용하는 방법도 좋겠다고 생각했지만, 
정책이라는 자체가 확장성이 상당히 높은 비지니스 로직이라 생각하여 잘못하면 enum클래스가 가지는 책임이 너무 많아지고 가독성,확장성 모두 어려울 것 같다라는 생각에 인터페이스를 이용한 구현체 방법을 선택했습니다.

근데 말씀해주신 피드백과 개발했을 때 느꼈던 변수나 메소드의 위치에 대한 어색함 등을 생각해보니 Function을 value로 사용하는 방법을 선택할 걸 그랬나? 라고 생각도 드네요 ㅜㅜ

리뷰어님은 어떠한 방식이 효과적이라고 생각하는지, 혹은 두 방법 말고도 활용해 볼 지식이 있는지 여쭈어봅니다.

2022-06-17 11:24 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/age/impl/AdultAgeFarePolicy.java
> +    public boolean isAge(int age) {
확실히 무슨 역할인지 알 수가 없었네요 ㅜㅜ `includeAge`로 수정하였습니다.

2022-06-18 05:02 UTC, jaeyeonling requested changes
미션을 잘 진행해주셨습니다 👍 
질문의 답변과 추가적인 코멘트 남겨두었으니 확인 부탁드릴게요~

2022-06-18 05:02 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicyType.java
> +    Long(LongDistanceFarePolicy.getInstance());
https://github.com/next-step/atdd-subway-service/pull/622#discussion_r899875217 해당 코멘트를 확인해주세요~

2022-06-18 05:02 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicy.java
> +    default boolean isFreeAge() {
https://github.com/next-step/atdd-subway-service/pull/622#discussion_r899880429 와 연관이 되는 것 같은데요.
인터페이스의 목적으로 봤을 때 default 메서드는 사실 존재하면 안되는 기능이지만, 하위호완성을 위해 추가된 기능입니다.
그래서 새로 작성하는 코드에 default 메서드가 추가되는 것 또한 지양하는 것이 좋을 것 같습니다!

2022-06-18 05:02 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicy.java
> +    default boolean isFreeAge() {
이어서 https://github.com/next-step/atdd-subway-service/pull/622#discussion_r900019427 의 답변을 드리자면 크게 3가지 방법이 있을 것 같아요.

- 지금과 같이 하나의 클래스에서 모든 값을 가지고 있는다.
- 상수들을 중복으로 만든다.
- 추상 클래스로 만든다. 

각 방법마다 특징이 존재하는데, 탁종님이 중요하다고 생각되는 부분을 정해서 트레이드 오프 해보면 좋을 것 같습니다 :) 
각 방법에 대한 탁종님의 생각을 정리해보시고 추가로 얘기해보면 좋을 것 같아요 😄

2022-06-18 05:02 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/distance/impl/LongDistanceFarePolicy.java
> +        int middleAdditionalDistanceFare = new MiddleDistanceFarePolicy().calculate(50, ageFarePolicy);
MiddleDistanceFarePolicy는 싱글톤 객체인데, new 키워드를 통해 객체를 생성해도 괜찮을까요?

2022-06-18 05:02 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +public enum AgeFarePolicyType {
https://github.com/next-step/atdd-subway-service/pull/622#issuecomment-1158775185 의 답변은 여기 남기도록 하겠습니다!
enum은 상수면서 역할을 가질 수 있기 때문에 다형성을 가장 쉽게 사용할 수 있어서 enum을 많이 사용하는데요.
말씀해주신 것과 같이 지금은 enum보단 클래스로 분리하는 것이 더 좋은 방법이라고 생각됩니다.
다만 정책마다 연관성이 존재하기 때문에 지금의 구조에선 애매한 부분이 있을 수 있는 것 같아요.
지금과 같은 도메인은 책임 연쇄 패턴을 검색해보시면 아이디어를 얻으실 수 있을 것 같습니다.
해당 구조로 바꾸려면 많은 코드 수정이 필요할 것 같아서 꼭 코드를 수정하실 필요는 없고 이런 방법이 있구나 생각해주시면 됩니다 😄

2022-06-18 06:26 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/distance/impl/LongDistanceFarePolicy.java
> +        int middleAdditionalDistanceFare = new MiddleDistanceFarePolicy().calculate(50, ageFarePolicy);
엇 놓친 부분이었습니다.
아예 안전하도록 생성자를 Priavte으로 지정하여 테스트코드에서도 객체를 싱글톤으로 사용하도록 강제하였습니다!

2022-06-18 06:29 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicyType.java
> +public enum AgeFarePolicyType {
`책임 연쇄 패턴` 좋은 방법 공유 감사합니다!
공부해보곘습니다!

2022-06-18 07:20 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicy.java
> +    default boolean isFreeAge() {
정책에서 무료대상 나이인지 판별하는 것보다는 enum에서 타입으로 무료대상인지 구분하는 것이 좀 더 자연스러운 것 같아 enum type으로 구분되도록 바꿨습니다.

다만, 말씀해주신 default 메소드가 지양해야하는 이유에 대해서 와닿지가 않아서,, 잘 이해가 안갑니다 ㅜㅜ
말씀해주신 하위호환성을 위해 추가된 것과는 다르게 저는 중복코드를 없애기 위해서만 사용하여 default 메소드의 목적과는 다르지만..

default 메소드의 남용으로 생기는 문제가 무엇이 있을까를 생각해 보았을 때는 딱히 떠오르지가 않습니닷..
(사용하면 나타날 수 있는 리스크가 딱히 떠오르지 않아 지양 해야겠다는 생각이 머리에 심어지질 않네요..)

물론 default 메소드를 사용하는 인터페이스를 다중 상속하여 구현하면 중복 메소드 이름으로 인한 문제가 있긴 하지만, 이 또한 컴파일 시점에서 별다른 리스크 없이 해결할 수 있다고 생각하는데, 어떻게 생각하실까요..?

재연님이 말씀해주신 이유에는 분명 단점이 존재하기 때문에 말씀해주신 거라 생각하는데
구체적으로 어떤 단점이 있을지 떠오르질 않아서 여쭈어봅니닷!

2022-06-18 07:31 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicy.java
> +    default boolean isFreeAge() {
- 지금과 같이 하나의 클래스에서 모든 값을 가지고 있는다.
   - 장점 : 도메인에 관련된 설정값을 하나의 클래스에서 확인 할 수 있음. 하나의 클래스 수정만으로 전체 로직에 적용할 수 있음.
   - 단점 : enum이 본질적인 타입 의미와는 약간 거리가 있는 설정값을 포함하게 됨. 설정값이 많이질 수록 enum의 역할이 더 모호해질 수 있음.

- 상수들을 중복으로 만든다.
  - 장점 : 클래스마다 상수를 로컬변수로 가지고 있다면, 해당 클래스만 보았을 때 직관적으로 어떤 설정값이 적용되는지 한눈에 보기 좋고, 관리가 쉽다.
  - 단점 : 다른 클래스에서 중복으로 같이 사용되는 의미의 상수가 변경이 필요할 때, 해당 상수가 의미하는 바를 논리적으로 다른 클래스에서도 찾아 수정해줘야한다. 그만큼 리스크와 테스트 비용이 커진다.

- 추상 클래스로 만든다.
  - 장점 : 인터페이스에 상수나 default메소드를 사용하는 것보다 추상클래스로 구상함으로서 역할을 위임하는 개념으로 사용할 수 있다
  - 단점 : 클래스이기 때문에 다중상속이 불가능하다. 

이 코멘트를 적다보니 위에서 말씀해주신 interface에 변수와 default method를 추상클래스로 활용해보라고 의견주신건가? 생각이 드네요. 
맞다면.. 추상클래스로 바꾸는게 가장 맞을 것 같습니다. 다중상속은 `나이정책 <-> 어린이정책,청소년정책...` 관계에서 정말 확장할 요구사항이 없는지에 대한 확신이 없어서 추상클래스(단일상속)으로 사용하는게 머뭇거려지는데요.

제가 정리한 내용이 의도주신 부분이 맞는지,,, 혹은 제가 생각을 정리한 내용이 맞을까요..?

2022-06-18 07:33 UTC, tj3828 commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicyType.java
> +    Long(LongDistanceFarePolicy.getInstance());
말도안되는 핑계지만,, 주로 새벽에 하다보니 집중을 못해서 놓쳤습니닷.. 죄송합니당😭

2022-06-19 05:46 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicy.java
> +    default boolean isFreeAge() {
굉장히 잘 정리를 해주셨네요 💯💯 
첨언을 하자면, `상수들을 중복으로 만든다` 라는 의견을 가장 잘 나타낸 책으론 [엘레강트 오브젝트](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9791187497219)가 있는데요.
객체의 입장에서 봤을 땐 본인의 책임일 뿐이라 각 객체에 해당하는 값을 가지는게 맞다고 주장합니다 ㅎㅎ 
이 처럼 설계에 따라서 구현이 바뀔 수 있는 부분이기 때문에 정답이 있기보단, 탁종님이 생각하는 방식대로 구현해주시면 될 것 같은데요.

제 의견을 남기자면 지금과 같은 구조라면 인터페이스 보다는 상속을 사용하는 것이 적합하다고 생각합니다~
만약 다중상속으로 확장될 것을 고려한다면 인터페이스를 유지해주시고 중복된다고 생각하는 구현체를 만들어 조합하는 방식으로 구현해주셔도 괜찮을 것 같습니다 😄

2022-06-19 06:06 UTC, jaeyeonling approved these changes
코멘트를 잘 반영해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요~~
남은 미션 화이팅해주시고, 좋은 소식으로 다시 뵙겠습니다 😄

2022-06-19 06:06 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/distance/DistanceFarePolicyType.java
> +    Middle(MiddleDistanceFarePolicy.getInstance()),
```suggestion
    MIDDLE(MiddleDistanceFarePolicy.getInstance()),
```

해당 부분을 놓치셨네요 ㅎㅎ

2022-06-19 06:06 UTC, merged

2022-06-28 16:47 UTC, jaeyeonling commented on src/main/java/nextstep/subway/fare/domain/policy/age/AgeFarePolicy.java
> +    default boolean isFreeAge() {
해당 코멘트를 놓쳤었네요~
인터페이스의 특징으로 봤을 때 인터페이스에서 메서드를 가질 수 있다라는 것 자체가 인터페이스 스럽지 않다는 것이 가장 큰 단점일 것 같아요 ㅎㅎ