1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #680
Opened 2022-06-21 20:37 UTC by las139

안녕하세요 😃

[1단계 - 인수 테스트 기반 리팩터링] 미션에 대한 리뷰 요청드립니다.

앞으로 잘 부탁드립니다 🙏

2022-06-22 14:46 UTC, seokhongkim requested changes
성민님 안녕하세요!
인수 테스트 기반 TDD 미션을 함께 진행할 리뷰어 김석홍입니다. 만나서 반갑습니다. 😀 

1단계 미션 잘 구현해주셨습니다.
커밋도 작은 단위로 나눠서 작업해주셨고, 테스트 코드도 꼼꼼하게 잘 작성해주셨네요.

코드에 코멘트 조금 남겼으니 확인 부탁드립니다. 🙏

2022-06-22 14:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/NotFoundStationException.java
> +public class NotFoundStationException extends NotFoundException {
적절한 커스텀 예외를 추가해서 사용하신 것 좋습니다. 👍

2022-06-22 14:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(IllegalArgumentException::new);
예외에 대해서 한번 고민해볼 수 있을 것 같아요.
`id` 가 지켜야 할 규약을 위반해서 `IllegalArgument` 로 보는 것이 좋을지, 아니면 해당 `id` 의 엔티티가 없으므로 데이터가 없다는 정보를 주는 것이 좋을지에 대해 어떻게 생각하시나요?

2022-06-22 14:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +public class Distance {
값 객체로 포장하신 것 좋습니다. 👍 
mutable 객체로 구현하신 이유가 따로 있는지 궁금합니다. :)

2022-06-22 14:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public Optional<Section> findUpLineStation(Station station) {
저는 메소드 이름과 구현이 조금 헷갈렸습니다.
`findUpLineStation` 이라서 상행 구간을 조회한다고 생각했는데, `upStation` 이 일치하는 구간이라서 이 역의 하행 구간을 조회하는 것 같네요.
성민님께서 보시기에 괜찮다면 그냥 넘어가셔도 괜찮습니다. :)

2022-06-22 14:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Station getNextStation(Station downStation) {
인자로 들어온 값이 `downStation` 이어야 할까요? 특정 역의 다음 역을 조회하는 것 같아서요!

2022-06-22 14:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Optional<Section> nextSection = this.sections.stream()
하행 구간을 조회하는 `findUpLineStation` 과 동일한 구현으로 보이네요!

2022-06-22 14:46 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +public class SectionsTest {
단위 테스트 꼼꼼하게 작성해주신 것 좋습니다. 👍

2022-06-22 18:26 UTC, las139 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lineRepository.findById(id).orElseThrow(IllegalArgumentException::new);
NotFoundException 으로 처리하는게 맞는것같네요
NotFoundLineException 추가하여 반영하였습니다!

2022-06-22 18:34 UTC, las139 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public Optional<Section> findUpLineStation(Station station) {
헷갈릴만한 메서드명이라고 생각이 드네요..
메서드명 수정하였습니다!

2022-06-22 18:36 UTC, las139 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Station getNextStation(Station downStation) {
nextStation 이 좀 더 적절해보이네요

2022-06-22 18:42 UTC, las139 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +public class Distance {
제가 놓친 부분이네요...
불변객체로 수정하였습니다!

2022-06-23 01:36 UTC, las139 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Optional<Section> nextSection = this.sections.stream()
해당 메서드를 호출하는것으로 변경하여
중복코드를 제거했습니다

2022-06-23 09:38 UTC, seokhongkim approved these changes
성민님, 1단계 미션 피드백 잘 반영해주셨습니다. 👍 
이번 단계 PR은 이만 머지하도록 하겠습니다.
코멘트 남긴 내용은 다음 단계 미션 진행하실 때 참고 부탁드립니다!

2단계 미션에서 뵙겠습니다. 😀

2022-06-23 09:38 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/NotFoundLineException.java
> +public class NotFoundLineException extends NotFoundException {
커스텀한 예외를 사용하신 것과, 예외를 발생시킨 id 정보도 함께 남겨서 원인 파악이 용이하도록 작성하신 점 좋습니다. 👍 
checked exception 을 사용하신 이유도 있는지 궁금합니다. :)

2022-06-23 09:38 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        Optional<Section> nextSection = this.sections.stream()
인자로 받은 `nextStation` 의 다음 역을 찾기 때문에, 인자는 `station` 일수도 있겠다는 생각이 드네요!

2022-06-23 09:39 UTC, merged

2022-06-23 14:28 UTC, las139 commented on src/main/java/nextstep/subway/exception/NotFoundLineException.java
> +public class NotFoundLineException extends NotFoundException {
노선을 찾지 못하는 오류라고 생각해서 NotFoundException을 사용했는데
예외처리가 강제된다는 점이 있네요...
이 경우엔 RuntimeException 을 사용하는게 좋을까요?

2022-06-24 07:23 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/NotFoundLineException.java
> +public class NotFoundLineException extends NotFoundException {
checked exception 과 unchecked exception 각각의 장단점이 있기에, 그것을 이해하고 필요에 따라 선택하시면 괜찮을 것 같습니다.
저는 데이터가 존재하지 않을 수 있다는 예외의 경우, 대부분의 비즈니스 로직에서 발생할 수 있는 상황이며, 예외가 발생할 수 있다는 것을 알았을 때 취할 수 있는 방법이 별로 없을 것 같아서 unchecked exception 을 사용해도 괜찮을 것 같습니다!