3단계 - 인증을 통한 기능 구현
next-step/atdd-subway-service pull request #684
Opened 2022-06-22 15:39 UTC by Ttungga

안녕하세요 성현님.

3단계 미션 PR 리뷰 부탁드립니다.

지난 번 피드백을 보고
경로 조회 서비스 객체만 너무 뚱뚱한 걸 뒤늦게 깨달았습니다.
그래서 서비스 레이어는 서비스 레이어답게 하는 게 맞다는 생각에 도메인 객체를 생성하여 책임을 넘겼습니다.
"도메인 = 엔티티"가 아닌데.. 간단하게 구현할 수 있을 것 같아서 전체 프로젝트 구조의 통일성을 깨버렸네요..

그리고 이번 미션 중에 한가지 질문이 생겨서 여쭤봅니다.
어떤 서비스 클래스는 DTO 뿐만 아니라 도메인 객체를 반환하는 public 메서드를 가지고 있는데요.
이 때 컨트롤러 객체가 해당 서비스 객체를 통해 도메인을 획득할 수 있게 되는데..
이걸 어떻게든 막는게 좋을까요?
아니면 일종의 협업 컨벤션?으로 프레젠테이션 레이어에는 DTO만 넘기게 한다고 보는 게 좋을까요?

감사합니다.

2022-06-23 15:12 UTC, boorownie requested changes
안녕하세요! 벌써 3단계 미션 요청을 주셨군요~
특히 이번 미션을 보면 변경된 파일수가 많아보이네요!
이번에도 크게 피드백 드릴 부분은 없으나
한번 생각해보면 좋을 것 같아 해당 코드 로직에 코멘트를 남겼습니다 :)

2022-06-23 15:12 UTC, boorownie commented on src/test/java/nextstep/subway/path/domain/SubwayGraphTest.java
> +    final List<Section> sections = Arrays.asList(
테스트 클래스 마다 테스트 픽스쳐를 정의해주기 번거롭진 않으신가요?
이 부분을 재사용할 수 있는 방법은 없을까요?

2022-06-23 15:12 UTC, boorownie commented on src/test/java/nextstep/subway/GivenSubway.java
> +    public GivenSubway() {
공통으로 사용되는 객체를 재사용하기 위해 중복제거용 테스트 유틸 클래스를 만드셨군요 👍 
제가 만약 이러한 테스트 픽스쳐 객체를 만든다고 한다면 테스트의 환경(Context)를 구성하고 재사용한다는 관점에서
XXXFixture나 SubwayXXXContext라는 네이밍으로 픽스쳐를 만들 수도 있을 것 같습니다 :)

2022-06-23 15:12 UTC, boorownie commented on src/main/java/nextstep/subway/station/domain/Station.java
> +import javax.persistence.Id;
중요한 내용은 아니지만 컨벤션 기준이 달라졌나요?

2022-06-23 15:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/dto/PathResponse.java
> +    public static PathResponse of(final List<PathStationResponse> stations, final int distance) {
DTO 내부에서 DTO 클래스로 변환해주는 객체 위치시키기 👍

2022-06-23 15:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/domain/SubwayGraph.java
> +public class SubwayGraph {
상태와 행위가 한 클래스에 위치하여 응집도가 높아졌군요 👍

2022-06-23 15:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                stationService.findAllStations());
메서드 분리의 이유가 있을까요? 한줄을 메서드로 분리하신 것 같아서요 :)

2022-06-23 15:12 UTC, boorownie commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    private Station targetStation;
멤버와 역 객체에 직접참조를 통해 의존을 표현하셨군요.
참조의 종류로는 간접참조를 통해서도 의존을 맺을 수 있는데
구현하신 방법인 직접참조와 간접참조는 어떤 차이가 있고
지금의 상황에서는 어떤 방법이 더 효과적일까요?

2022-06-23 15:12 UTC, boorownie commented on src/main/java/nextstep/subway/path/domain/SubwayGraph.java
> +        return new Path(getStationsOfGraphPath(graphPath), getDistanceOfGraphPath(graphPath));
Path 생성자의 인자로 Sections(구간들)을 보내는건 어떨까요?
현재난 지하철역 목록과 거리 정보만 가지고 있지만
Sections는 내부에 모든 정보를 다 가지고 있어서 자체적으로 구현하기 좋을 것 같기도 해서요~

2022-06-23 15:30 UTC, Ttungga commented on src/main/java/nextstep/subway/station/domain/Station.java
> +import javax.persistence.Id;
어 그렇네요 😓  
단축키로 생성자를 추가하는 과정에서 변경된 것 같습니다..

2022-06-23 16:40 UTC, Ttungga commented on src/test/java/nextstep/subway/path/domain/SubwayGraphTest.java
> +    final List<Section> sections = Arrays.asList(
인수테스트에는 픽스처 클래스를 만들었는데 단위 테스트에서는 부족했네요..
해당 부분 추가하겠습니다.

2022-06-24 01:21 UTC, Ttungga commented on src/main/java/nextstep/subway/path/application/PathService.java
> +                stationService.findAllStations());
어 특별히 의도가 있었다기 보다는 무의식적으로 분리했네요..

질문을 보고 왜 그랬을까 생각을 해봤는데,
첫 번째로는 커스텀 라인브레이크 때문에 3줄로 보여서..가 있구요.
두 번째로는 제가 테스트 코드가 아닌 한 객체생성을 생성자를 통해서 하는 걸 선호하지 않네요.
개인적으로 메서드를 사용해야 가독성이 좋은 것 같습니다.

그리고 하나의 단위 기능으로 볼 수 있다는 생각도 드네요. 생성자에 변경이 생겼을 때 수정할 코드의 양이 줄어들기도 하구요.
반환값이 아니라 행위를 가지고 있고 로직 중간에 사용해야하는 객체의 생성은 메서드로 분리하는 게 좋다고 보입니다.

그래도 이런 나름의 이유를 먼저 가지고 분리를 했더라면 더 좋았겠다는 생각이 드네요. 사후약방문 느낌이.. 😓 
질문해주신 덕분에 고민해볼 기회를 가졌습니다. 감사합니다.

2022-06-25 15:06 UTC, Ttungga commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    private Station targetStation;
간접참조는 아래와 같은 장점이 있을 것 같네요. 혹시 틀리거나 부족한 내용이 있다면 말씀 부탁드립니다. 🙏 
1. 엔티티 간 결합도 감소
2. 순환참조 방지
3. 데이터 조회 시 연관관계 객체에 대한 로딩 설정 고려를 하지 않아도 됨

즐겨찾기는 식별자와 로그성 컬럼 외에 고유한 컬럼이 없고, 참조하는 테이블의 데이터를 조합함으로써 의미를 가지기 때문에,
참조하는 엔티티 조회가 거의 모든 경우 필요하다고 봅니다.

또한 사용자별로 데이터가 구분되기 때문에 대량의 데이터를 한번에 조회할 가능성이 적은 도메인이라고 생각합니다.

따라서 직접 참조를 통해 객체를 직접 다루는 것이 각각 조회하는 코드를 추가하는 것보다 더 낫다는 생각이 드네요.

2022-06-26 05:04 UTC, Ttungga commented on src/main/java/nextstep/subway/path/domain/SubwayGraph.java
> +        return new Path(getStationsOfGraphPath(graphPath), getDistanceOfGraphPath(graphPath));
말씀해주신 방법을 생각해보았는데요. 아래와 같은 이유로 현재 구조를 유지하는 게 더 낫지 않을까하는 판단이 들었습니다.
한번 확인 후 다시 피드백 부탁드려도 될까요?

1. Sections 클래스는 Line에 종속됨을 염두하고 구현한 클래스
2. 1번의 이유로 Sections가 가진 상행종점역 구하기, 하행종점역 구하기, 순서대로 역 정렬과 같은 주요 기능이 모든 구간이 하나의 노선에 있다는 전제를 가지고 있음
3. 따라서 여러 노선을 거칠 수 있는 최단경로에서 Sections의 주요 기능을 사용할 수 없음

위와 같은 이유로 현재 Sections를 그대로 최단 경로에 이용하는 것은 적합하지 않다고 생각했습니다.
여기에 최단 경로에 맞는 새로운 Sections를 생성하는 것과 현재 구조의 트레이드 오프를 고려해보았는데요.
최단 경로는 수정/삭제 등의 상태 변경이 필요하지 않고 단순히 계산된 최단 경로를 보여주는 것이 목적이기 때문에
현재 구조를 유지하는 것이 더 나은 방법이 아닐까 생각했습니다.

2022-06-26 05:09 UTC, Ttungga commented
안녕하세요 성현님.

이번 달 들어 장애를 2건.. 맞는 바람에 미션을 위한 시간을 확보하기가 쉽지 않네요..
응답이 늦어서 죄송합니다. 😞 

특히 이번은 남겨주신 질문에 대답하기 위해 여러 정보를 찾아보고 고민을 했어야 해서 시간이 좀 더 필요했습니다.
나름 공부하면서 의견을 만들어가는 기분에 성취감을 느낄 수 있었어요.
좋은 질문 주셔서 감사합니다.

이번에는 코드 수정은 적고, 질문에 대한 답변을 정리한 게 대부분이었는데요.
다시 한번 리뷰 부탁드리겠습니다.

감사합니다.

2022-06-26 10:53 UTC, gracefulBrown commented on src/main/java/nextstep/subway/path/domain/SubwayGraph.java
> +        return new Path(getStationsOfGraphPath(graphPath), getDistanceOfGraphPath(graphPath));
아 그러시군요 Sections가 특정 Line에 종속될 것을 염두하고 구현하셨다면 말씀대로 재사용이 애매할 것 같긴 합니다.

하지만 제가 코드를 봤을 때는 Sections의 기능이 특정 Line에 종속되지 않을 수 있다고 판단했어요.
2번에서 말씀해주신 기능을 수행하는 로직을 보면 Line정보에 의존적이기 보다는 구간(section)의 상행과 하행을 기준으로 동작하고 있고 이 기능들은 반드시 하나의 line일 필요는 없다고 보여집니다. 간선(두 갈래로 나뉘는 길)은 요구사항에서 부터 막혀있는 기능이고 Sections를 구성할 때 밸리데이션을 체크한다면 이 또한 가능해보입니다.

그리고 말씀해주신대로 또 하나의 Sections를 만드는건 비효율적일 것 같아요.

제가 드린 피드백을 바탕으로 많은 고민을 해보신게 코멘트로 느껴져서 좋았습니다!
열린 방향으로 고민해주셔서 감사합니다 👍

2022-06-26 10:55 UTC, boorownie commented on src/main/java/nextstep/subway/path/domain/SubwayGraph.java
> +        return new Path(getStationsOfGraphPath(graphPath), getDistanceOfGraphPath(graphPath));
아 그러시군요 Sections가 특정 Line에 종속될 것을 염두하고 구현하셨다면 말씀대로 재사용이 애매할 것 같긴 합니다.

하지만 제가 코드를 봤을 때는 Sections의 기능이 특정 Line에 종속되지 않을 수 있다고 판단했어요.
2번에서 말씀해주신 기능을 수행하는 로직을 보면 Line정보에 의존적이기 보다는 구간(section)의 상행과 하행을 기준으로 동작하고 있고 이 기능들은 반드시 하나의 line일 필요는 없다고 보여집니다. 간선(두 갈래로 나뉘는 길)은 요구사항에서 부터 막혀있는 기능이고 Sections를 구성할 때 밸리데이션을 체크한다면 이 또한 가능해보입니다.

그리고 말씀해주신대로 또 하나의 Sections를 만드는건 비효율적일 것 같아요.

제가 드린 피드백을 바탕으로 많은 고민을 해보신게 코멘트로 느껴져서 좋았습니다!
열린 방향으로 고민해주셔서 감사합니다 👍

2022-06-26 10:58 UTC, boorownie approved these changes
번거로운 픽스쳐 정리까지 확인했습니다! 💯 
개선된 내용을 통해 유지보수하기 좋은 테스트가 설계되어가고 있는 것 같네요!

답글 남겨주신 내용에 대해서는 추가적인 코멘트를 남겼습니다.
남겨주신 코멘트를 통해 깊은 고민을 하며 미션을 진행하고 있는게 느껴져서 좋앗습니다 👍 

다음 단계 미션도 빠이팅 입니다!!

2022-06-26 10:58 UTC, boorownie commented on src/test/java/nextstep/subway/utils/fixture/AcceptanceTestSubwayFixture.java
> +public class AcceptanceTestSubwayFixture {
네이밍부터 재사용이 가능한 픽스쳐임이 명확하네요 👍

2022-06-26 10:58 UTC, boorownie commented on src/test/java/nextstep/subway/utils/fixture/DomainLayerSubwayFixture.java
> +public class DomainLayerSubwayFixture {
👍

2022-06-26 10:58 UTC, merged