🚀 4단계 - 요금 조회
next-step/atdd-subway-service pull request #686
Opened 2022-06-22 16:41 UTC by 14km

안녕하세요!

4단계 요금조회 기능 추가했습니다. :)

2022-06-23 10:33 UTC, seokhongkim requested changes
민태님, 4단계 미션 잘 구현해주셨습니다. 👍 

이번 미션도 테스트와 요구사항을 꼼꼼하게 작성해주셨고, 작은 커밋 단위로 나눠서 작업해주신 점이 좋았습니다.
코멘트를 조금 남겼으니 확인 부탁드립니다. 🙏

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/domain/ChildDiscountPolicy.java
> +    public int discount(int price) {
할인 금액 계산하는 로직을 `CHILD`, `YOUTH` 에서 함수로 제공할 수도 있을 것 같네요!

hint: `enum abstract method` 를 이용해보면 어떨까요?

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/navigation/domain/Navigation.java
> +        DiscountPolicy discountPolicy = DiscountType.ofDiscountPolicy(loginMember.getAge());
네비게이션에서 금액을 계산하는 역할까지 모두 가지고 있네요.
경로를 계산하는 것과 요금을 계산하는 책임을 분리해보면 어떨까요?

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +            @AuthenticationPrincipal LoginMember loginMember,
로그인하지 않은 사용자도 사용할 수 있는 기능일 때 처리할 수 있도록 `@AuthenticationPrincipal` 에 `required` 와 같은 필드를 추가해보는 건 어떨까요?
이를 이용해서 로그인이 필수인데 로그인이 안 된 경우 적절한 예외를 발생시킬 수 있고, 로그인이 선택적인 경우 빈 객체를 이용해서 서비스를 제공할 수 있을 것 같습니다.

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/domain/DiscountType.java
> +    public static DiscountPolicy ofDiscountPolicy(Age age) {
할인 정책을 전략 패턴으로 관리하신 것 좋습니다.
다만, 이번 구현의 요금 계산 과정에서 다른 빈에 대한 의존이 없어서 `enum` 에서도 관리할 수 있을 것 같습니다.

또한 `XXXPolicy` 의 경우 매번 객체를 생성하지 않고, 빈으로 등록한 후 해당 빈을 이용하면 성능상의 이점을 얻을 수 있을 것 같습니다.

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/application/FareCalculatorService.java
> +    private static final int DEFAULT_DISTANCE = 10;
`기본 운임이 부과되는 최대 거리` 값인 것 같네요.
이름만 보고 위 내용을 유추할 수 있도록 고민해보시면 좋을 것 같아요!

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/application/FareCalculatorService.java
> +    private static final int MAX_DISTANCE = 50;
`50km` 를 넘어가는 경우 다른 요금 정책이 적용되는 것 같아요.
즉, 거리는 50보다 커질 수 있지 않을까요? 여기도 이름을 고민해보시면 좋겠습니다!

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/auth/domain/LoginMember.java
> +        return new LoginMember();
`GuestMember` 로 빈 객체를 사용하신다면, 하나의 객체를 싱글턴으로 놓고 재사용해보는 건 어떨까요?

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/auth/domain/Age.java
> +    private final static int MINIMUM_AGE_OF_CHILD = 6;
구체적인 이름 좋습니다. 👍

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/application/FareCalculatorService.java
> +    private static final int FIVE_KILOMETRE = 5;
5km 와 8km 는 어떤 의미를 가지고 있나요?
`xx 구간에서 추가 요금이 부과되는 단위` 정도의 의미를 가지도록 수정해보는 건 어떨까요?

이름으로 정확한 표현이 어렵다면, 주석을 통해 쉽게 어떤 값인지 이해할 수 있도록 주석을 남겨보시는 것도 좋은 방법일 것 같습니다!

2022-06-23 10:33 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/domain/DiscountPolicy.java
> +    int discount(int price);
`discount` 의 반환값은 `내야 할 요금` 인가요? `할인해주는 요금` 인가요?

2022-06-24 02:38 UTC, 14km commented on src/main/java/nextstep/subway/fare/domain/ChildDiscountPolicy.java
> +    public int discount(int price) {
오.. 감사합니다 :)

2022-06-24 02:45 UTC, 14km commented on src/main/java/nextstep/subway/navigation/domain/Navigation.java
> +        DiscountPolicy discountPolicy = DiscountType.ofDiscountPolicy(loginMember.getAge());
이부분은 고민은.. 저도 조금 해봤는데요! :)

관련해서 `findShortest`에 필수로 연관되어있는 행위가 무엇일까? 라는 생각이였습니다 ㅎㅎ

[요구조건은 경로를 찾는 행위에 요금이 함께 포함되어있다]

라는 생각으로 많이 생각해본것 같아요!

다만, 말씀해주신 것처럼 `findShortest` 메서드 내에서 많은 행위를 하는것으로 보여서.. 수정 해보겠습니다 :)

2022-06-25 15:06 UTC, 14km commented on src/main/java/nextstep/subway/fare/domain/ChildDiscountPolicy.java
> +    public int discount(int price) {
변경했습니다 :) 좋은 의견 감사드려요!

2022-06-25 15:14 UTC, 14km commented on src/main/java/nextstep/subway/fare/application/FareCalculatorService.java
> +    private static final int DEFAULT_DISTANCE = 10;
명칭 한번 변경해보았습니다 :)

2022-06-26 06:30 UTC, 14km commented on src/main/java/nextstep/subway/auth/domain/LoginMember.java
> +        return new LoginMember();
`LazyHolder Singleton` 방식으로 수정해보았습니다!

2022-06-26 06:39 UTC, 14km commented on src/main/java/nextstep/subway/fare/application/FareCalculatorService.java
> +    private static final int MAX_DISTANCE = 50;
명칭 수정 해보았습니다 :)

2022-06-26 06:46 UTC, 14km commented on src/main/java/nextstep/subway/fare/application/FareCalculatorService.java
> +    private static final int FIVE_KILOMETRE = 5;
설명이 많이 어렵네용 ㅠㅠ ㅎㅎ..

관련해서 주석으로 남겨보았습니다 :)

2022-06-26 06:50 UTC, 14km commented on src/main/java/nextstep/subway/fare/domain/DiscountPolicy.java
> +    int discount(int price);
discountFare 로 메서드 수정해보았습니다 :)

2022-06-26 08:08 UTC, 14km commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +            @AuthenticationPrincipal LoginMember loginMember,
![](https://user-images.githubusercontent.com/45898974/175805497-d68eb1b6-5695-4240-ae67-c3f34dc45ae6.png)

혹시 생각하시는 방향이 이런부분이 맞을까요? 추가는 해보았으나 생각하신 방향과 다르다면 말씀 부탁드립니다 :)

2022-06-26 08:45 UTC, 14km commented on src/main/java/nextstep/subway/navigation/domain/Navigation.java
> +        DiscountPolicy discountPolicy = DiscountType.ofDiscountPolicy(loginMember.getAge());
책임을 Service 단으로 변경했습니다 :)

2022-06-26 12:14 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +            @AuthenticationPrincipal LoginMember loginMember,
넵, 맞습니다. :)
인증을 요청하는 경우 주로 `required = true` 인 상황이 더 많을수도 있겠다는 생각이 드네요.
default 값에 따라 수정해야 할 곳이 어떻게 되는지 확인해보신 후 작업 진행하셔도 좋겠습니다!

2022-06-26 12:37 UTC, seokhongkim approved these changes
민태님, 4단계 미션 잘 마무리 해주셨습니다. 👍 
미션의 주요 학습 목적은 달성하셨다고 생각되어 4단계 PR 머지하도록 하겠습니다.
코멘트 남긴 내용은 참고만 부탁드립니다.

인수 테스트 기반 TDD 과정 진행하시느라 수고하셨습니다. 👏 
앞으로 남은 과정에서도 민태님의 학습과 성장이 있기를 응원하겠습니다!

2022-06-26 12:37 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/domain/DiscountType.java
> +            return new GeneralDiscountPolicy();
여기서 policy 를 반환하지 않고 `DiscountType` 을 반환한 후, `discountType.calculate()` 를 호출해도 괜찮을 것 같다는 생각이 드네요!

2022-06-26 12:37 UTC, seokhongkim commented on src/main/java/nextstep/subway/fare/domain/DiscountType.java
> +    private final int fare;
350원은 요금이 아니라, 차감(공제)금액이니 `deductionAmount` 같은 이름을 써도 괜찮겠네요!

2022-06-26 12:37 UTC, merged