Step4 - 요금조회
next-step/atdd-subway-service pull request #693
Opened 2022-06-23 18:27 UTC by kmmin78

안녕하세요, 석홍님! 🙇‍♂️

5주차 4단계 - 요금조회 구현 PR 드립니다.

이번 단계는 기존의 구조를 변경하다 보니 파일 변경이 많아졌네요. 🥲

마지막 리뷰도 잘 부탁드립니다! 😊

2022-06-24 11:43 UTC, seokhongkim requested changes
민성님, 4단계 미션 잘 구현해주셨습니다. 👍 
피드백 조금 남겼으니 확인 부탁드립니다. 🙏 

직접 고민해보시길 바라는 마음으로 자세한 내용을 안 남기기도 했는데, 고민이 너무 길어지신다면 슬랙 DM 으로 편하게 말씀 부탁드려요!

2022-06-24 11:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/auth/domain/LoginMember.java
> +        return new LoginMember();
비회원을 처리하기 위한 값이라면 싱글톤으로 만들어서 재사용해보는 것은 어떨까요?

2022-06-24 11:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +            , @AuthenticationPrincipal LoginMember loginMember) {
비회원도 사용할 수 있는 기능(경로 조회)과 비회원은 사용할 수 없는 기능(로그인, 회원 정보 수정 등)을 구분하기 위해 `AuthenticationPrincapal` 속성에 `required` 같은 값을 추가해보시면 좋을 것 같네요!

2022-06-24 11:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/ChargeCalculator.java
> +        final int deductionPrice = totalCharge - 350;
매직 넘버보다는 상수로 추출하고, 적절한 이름을 부여해주시면 좋을 것 같네요.

2022-06-24 11:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/ChargeCalculator.java
> +        if (13 <= age && age < 19) {
청소년, 어린이 요금 할인 정책을 처리할 수 있는 별도의 클래스로 분리해보면 어떨까요?
조금 더 추상화하면, 어떤 할인 정책을 적용할지 결정하고, 할인된 요금 또는 할인해줘야 하는 요금을 계산해줘도 좋을 것 같습니다.
그럼 요금을 계산하는 곳(`ChargeCalculator`)에서 적절할 할인 정책을 요청(할인 없음 - 기본, 청소년, 어린이)하여 할인 요금을 계산해볼 수 있을 것 같네요!

2022-06-24 11:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/types/ChargeType.java
> +    LESS_OR_EQUAL_TEN, BETWEEN_TEN_AND_FIFTY, MORE_OR_EQUAL_FIFTY;
10, 50 과 같은 값이 어떤 의미일까요?
기본운임 거리, 1단계 추가 요금 거리, 2단계 추가요금 거리 등으로 구분해볼 수도 있을 것 같네요!

2022-06-24 11:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/PathNavigator.java
> +        final int maxSurcharge = calculateMaxSurcharge(graphPath.getEdgeList());
최단 거리를 조회하는 곳에서 추가 요금이 얼마인지까지 함께 계산해주네요.
역할을 분리해보면 어떨까요?

2022-06-24 11:43 UTC, seokhongkim commented on src/test/java/nextstep/subway/path/util/ChargeCalculatorTest.java
> +public class ChargeCalculatorTest {
요금 계산에 대한 꼼꼼한 단위 테스트 좋습니다. 👍

2022-06-24 11:43 UTC, seokhongkim commented on src/test/java/study/unit/UnitTest.java
>  public class UnitTest {
이 테스트는 `Line` 테스트에서 같이 할 수도 있을 것 같은데, 따로 관리하시는 이유가 있을까요?

2022-06-24 16:48 UTC, kmmin78 commented on src/test/java/study/unit/UnitTest.java
>  public class UnitTest {
앗 이 코드는 기존에 작성되어 있던 코드인데요.
노선에 surcharge (추가요금) 속성을 추가하면서 노선 생성자가 바뀌게 되어 해당 테스트 코드가 깨지는 걸 막고자 수정하게 되었습니다.

2022-06-24 16:52 UTC, kmmin78 commented
꼼꼼한 리뷰 감사드립니다 🙂
덕분에 잊고 있었던 부분을 복습할 수 있었습니다! 👍

2022-06-25 02:12 UTC, seokhongkim requested changes
민성님, 4단계 피드백 잘 반영해주셨습니다. 👍 
로그인 필수 기능과 그렇지 않은 기능을 구분하기 위한 작업 잘 해주셨습니다.
요금 계산하는 코드도 이전보다 한층 이해하기 수월하게 리팩토링 해주셨네요.

조금 더 역할 분리가 가능할 것 같은 부분이 있어 코멘트 남겼습니다.
확인 부탁드립니다. 🙏

2022-06-25 02:12 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/ChargeCalculator.java
>          return DEFAULT_CHARGE + (int) ((Math.ceil((distance - 1) / 8) + 1) * 100);
[지하철 운임안내](http://www.seoulmetro.co.kr/kr/page.do?menuIdx=354)를 보니 요금 계산 로직을 수정하셔야 할 것 같아요.
기본거리 이하인 경우 1250원, 10km ~ 50km 구간에 대해서는 5km 마다 100원씩 가산, 50km 이상 구간에 대해서는 8km 마다 100원씩 가산이네요.
예를 들어 운행거리가 65km인 경우, 1250(10km) + 100 * 8(40km) + 100 * 2(15km) = 2250원이 되어야 합니다.

단계별로 요금을 계산하는 로직이 달라지는데, 여기에서 `if` 를 제거할 수 있는 방법도 고민해보시면 좋을 것 같아요!
hint: `ChargeType` 마다 조건이 달라지고 있으니, enum 에 abstract method 를 추가하고 타입별로 계산 로직을 구현해보면 어떨까요?

2022-06-25 02:12 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/ChargeCalculator.java
> +        final SalePolicy salePolicy = SalePolicy.getPolicyByAge(age);
`SalesPolicy` 에 따라 요금을 계산하는 로직이 달라지니 `if` 문을 제거하는 방법을 고민해보시면 좋을 것 같아요!
hint: `SalesPolicy` 마다 요금 계산 로직이 달라지니, enum 에 abstract method 를 추가하고 타입별로 계산 로직을 구현해보면 어떨까요?

2022-06-25 02:12 UTC, seokhongkim commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        if (!required && !jwtTokenProvider.validateToken(credentials)) {
`required` 가 false 라면 `credentials` 검증이 아예 불필요할 수도 있겠다는 생각이 드네요!

2022-06-26 12:19 UTC, kmmin78 commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        if (!required && !jwtTokenProvider.validateToken(credentials)) {
`required` 가 false 여도 `credentials`가 존재하면 로그인 정보를 가져오고, `credentials` 가 존재하지 않으면 빈 로그인 정보를 가져와야되기 때문에 검증하는 작업이 필요할 것 같습니다!

2022-06-26 12:21 UTC, seokhongkim commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        if (!required && !jwtTokenProvider.validateToken(credentials)) {
앗, 그렇네요!
제가 잘못 생각했습니다. 😅

2022-06-26 12:22 UTC, kmmin78 commented
석홍님, 이번 리뷰를 통해서도 덕분에 많이 배울 수 있었습니다. 👍
enum을 통해 역할 분리를 더 잘게 쪼갤 수 있다는 걸 항상 염두에 둬야겠습니다. 🙂

2022-06-26 13:27 UTC, seokhongkim requested changes
민성님, 4단계 피드백 잘 반영해주셨습니다! 👍 

요금 계산 로직 관련하여 수정이 필요한 부분이 보여 코멘트 남겼습니다.
확인 부탁드립니다. 🙏

2022-06-26 13:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/SalePolicy.java
> +        return totalCharge - (int) Math.round(deductionPrice * YOUTH.getDiscountRate());
청소년, 어린이 할인 금액 계산 로직을 다시 확인해보시면 좋겠습니다.
* 현재 로직: 총 금액 - (총 금액 - 350원) * 할인율
기본 요금 1250원일 때, 청소년의 기본 요금 = 1250 - (1250 - 350) * 0.2 = 1250 - 180 = 1070원
* [운임 안내](http://www.seoulmetro.co.kr/kr/page.do?menuIdx=354)에 따른 로직: (총 금액 - 350원) * (1 - 할인율)
기본 요금 1250원일 때, 청소년의 기본 요금 = (1250 - 350) * (1 - 0.2) = 900 * 0.8 = 720원

2022-06-26 13:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/types/ChargeType.java
> +public enum ChargeType {
`ChargeType` 과 `SalePolicy` 에 대한 단위 테스트도 작성해보시면 도움이 될 것 같습니다!
또는, `ChargeCalculator` 에서 청소년, 어린이 할인 요금에 대한 테스트를 추가해보셔도 좋겠습니다.

2022-06-26 13:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/path/util/ChargeCalculator.java
> +    private static int calculateYouthCharge(final int totalCharge, final int deductionPrice) {
이 부분은 `SalePolicy` 내부로 이동하면서 더 이상 사용하지 않는 코드로 보이네요!

2022-06-26 13:40 UTC, kmmin78 commented on src/main/java/nextstep/subway/path/util/SalePolicy.java
> +        return totalCharge - (int) Math.round(deductionPrice * YOUTH.getDiscountRate());
운임 안내를 더 꼼꼼히 살펴봤어야 했는데 그렇지 못했습니다. 🙇‍♂️
알려주셔서 감사합니다! 🙂

2022-06-26 13:58 UTC, kmmin78 commented
구현에 오류가 생각보다 많았네요 🥲
새로운 객체가 생기면 항상 단위테스트를 작성하는 습관을 들여야 겠습니다.
좋은 리뷰 감사합니다! 🙂

2022-06-27 11:38 UTC, seokhongkim approved these changes
민성님 4단계 미션 잘 마무리해주셨습니다. 👍 
미션을 통해 학습해야 할 목표는 달성하신 것으로 보여 PR은 머지하도록 하겠습니다.
추가로 이야기 나누고 싶은 부분이 있으시다면 슬랙 DM 으로 편하게 말씀해주세요 😀 

남은 교육 기간에도 많이 학습하시고 성장하실 수 있기를 응원하겠습니다. 💪 
인수 테스트 기반 TDD 미션 진행하는 동안 수고 많으셨습니다!

2022-06-27 11:38 UTC, merged