Step2 - 경로 조회 기능
next-step/atdd-subway-service pull request #694
Opened 2022-06-23 18:35 UTC by bestsilver

안녕하세요 영훈님!
1단계에서 리뷰 해주셨던 내용들과 함께 2단계 미션 진행해보았습니다!
꼼꼼하게 리뷰 해주신 덕분에 제가 많이 배울 수 있었던 것 같아요!
정말 감사합니다!🙇‍♀️

그럼 이번에도 리뷰 부탁드립니다!

2022-06-25 01:40 UTC, chae-yh requested changes
고은님 안녕하세요! 리뷰가 늦어져 죄송합니다...
경로 조회 기능 전체적으로 잘 작성해주셨네요 👍 다만 구조적인 부분과 테스트 관련하여 조금만 더 고민해주시면 좋을만한 내용이 있어 코멘트 드렸으니 확인부탁드립니다!

감사합니다 : )

2022-06-25 01:40 UTC, chae-yh commented on docs/STEP2_README.md
> +## 🚀 요구사항
요구사항에 대한 단순 내용 추가보다는 실제 어떤 것들을 구현해야하고, 실제 구현했는지를 표현해보면 어떨까요...?

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Station> getStations() {
역을 순서대로 노출할 때 필요할 것 같은데 혹시 단순히 station을 가져오는 것으로 변경하신 이유가 있을까요...?

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +        return lines.stream().anyMatch(line -> line.getStations().contains(station));
line 에서 모든 station을 가져오지 않고(getter 사용), line 에 해당 station을 가지고 있는지 메시지를 전달해볼 수 있지 않을까요...?

2022-06-25 01:40 UTC, chae-yh commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +        Collections.sort(stationIds);
서버에서 순서대로 정렬된 값이 return이 되어야 하지 않을까요...?

2022-06-25 01:40 UTC, chae-yh commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
>  public class PathAcceptanceTest extends AcceptanceTest {
최단경로 조회 인수테스트 좋습니다 👍

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/path/application/PathService.java
> +public class PathService {
최단 경로 조회에 대한 인수테스트는 잘 작성되었습니다 👍 
해당 domain, service(의존 객체에 대해 Mocking을 한 단위테스트)에 대해서 구체적으로 단위테스트를 작성해보는 것은 어떨까요...?

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +                //지하철역 설정
아주 중요한 주석이 아니라면 삭제하는 것도 좋을 것 같습니다! 코드를 읽었을 때 이미 자연스레 해당 의미를 확인할 수 있었습니다 : )

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +public class PathFinder {
이 부분은 의견여쭤보고 싶습니다!
우선 PathFinder를 잘 만들어주셨습니다 👍 그런데 lines 와 조금 역할이 섞여 있는 것 같습니다.
해당 클래스에서 최단 경로를 찾지 않고, lines에서 findPath를 해서 Path 혹은 GraphPath<Station, DefaultWeightedEdge>의 일급컬렉션을 return 할 수 있지 않을까요...?

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/path/dto/PathResponse.java
> +        List<StationResponse> stationResponses = stationList.stream().map(StationResponse::of).collect(Collectors.toList());
```suggestion
        List<StationResponse> stationResponses = stationList.stream()
        .map(StationResponse::of)
        .collect(Collectors.toList());
```
이렇게 개행해주셔도 좋을 것 같습니다!

2022-06-25 01:40 UTC, chae-yh commented on src/main/java/nextstep/subway/station/application/StationService.java
> +                .map(StationResponse::of)
여기도 파라미터가 한개인데 from이 조금 더 어울리지 않을까요...? : )

2022-06-25 01:40 UTC, chae-yh commented on src/test/java/nextstep/subway/line/acceptance/LineSectionTotalAcceptanceTest.java
> +public class LineSectionTotalAcceptanceTest extends AcceptanceTest {
구간에 대한 인수테스트를 시나리오 형태로 잘 작성해주셨습니다. Dynamic Test도 잘 작성해주셔서 가독성이 좋네요 👍 
다만, 인수테스트와 통합테스트는 다른 개념입니다! 관련하여 잘 정리해둔 글이 있어 첨부드립니다!
https://tecoble.techcourse.co.kr/post/2021-05-25-unit-test-vs-integration-test-vs-acceptance-test/

2022-06-25 16:40 UTC, bestsilver commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +public class PathFinder {
Lines는 PathFinder의 멤버변수를 랩핑하기 위해서 만든 일급 컬랙션으로만 생각했었네요..!
그리고 PathFinder class에 findPath가 있어야 더 직관성이 있어보였습니다!

하지만 저도 lines와의 역할이 조금 섞여 있다는 것에는 동의합니다!
그래서 이번에 Lines로 findPath를 한번 옮겨보았습니다

2022-06-25 16:41 UTC, bestsilver commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +        Collections.sort(stationIds);
제가 이전 리뷰의 의도를 잘못 파악하고 수정했네요ㅠㅠ
다시 롤백했습니다!

2022-06-25 16:42 UTC, bestsilver commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public List<Station> getStations() {
제가 이전 리뷰의 의도를 잘못 파악하고 수정했네요ㅠㅠ
다시 롤백했습니다!

2022-06-25 16:43 UTC, bestsilver commented
안녕하세요! 영훈님!
즐거운 주말 보내고 계신가요?! 😃
말씀해주신 사항들 다시 한번 수정해보았습니다!

그럼 편하실때 리뷰 해주시면 감사하겠습니다!

2022-06-26 07:30 UTC, chae-yh approved these changes
고은님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 조금 더 고민해주시면 좋을만한 내용이 있어 코멘트 드렸으나 현재 step의 목표는 달성한 것으로 생각되어 merge하겠습니다!

다음 step 진행 부탁드립니다 : )

2022-06-26 07:30 UTC, chae-yh commented on src/test/java/nextstep/subway/line/domain/LinesTest.java
> +public class LinesTest {
도메인에 대한 단위 테스트 좋습니다 👍 
메서드명에 한글 사용 / @Displayname에 한글 사용
의 케이스가 섞여 있는데 통일해서 작성해주셔도 좋을 것 같습니다 : )

2022-06-26 07:30 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return LineResponse.from(persistLine);
static factory method 에서 of 와 from의 구분 기준은 어떤 것일까요...?

2022-06-26 07:30 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +    List<Line> lines;
접근 제한자를 안주신 이유가 있을까요..?

2022-06-26 07:30 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +public class Lines {
일급컬렉션 분리 좋습니다 👍

2022-06-26 07:30 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private static final int DELETABLE_SIZE = 1;
상수 추출도 좋습니다 👍

2022-06-26 07:30 UTC, chae-yh commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +    }
출발지와 도착역이 연결되어 있지 않을 때의 테스트 케이스도 추가해보면 어떨까요...?

2022-06-26 07:30 UTC, chae-yh commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +public class PathServiceTest {
피드백 반영 좋습니다 👍 Path에 대해 외부 라이브러리를 사용하는 pathFinder에 대한 도메인 단위 테스트도 추가해보면 어떨까요...?

2022-06-26 07:30 UTC, merged