STEP2: 경로 조회 기능 PR 입니다
next-step/atdd-subway-service pull request #698
Opened 2022-06-25 08:49 UTC by breezeunn

리뷰어님 안녕하세요 😄 
지난 PR 에서 코멘트 주신 재귀함수에 대한 변경과
이번 미션 내용을 반영해서 PR 생성하였습니다 😄 

이번 리뷰도 잘 부탁드립니다🙇‍♀️

2022-06-26 06:44 UTC, joojimin requested changes
안녕하세요~ 지은님!
미션 수행 고생하셨습니다!
몇가지 피드백남겼는데 확인 후 리뷰 재요청 부탁드려요!

2022-06-26 06:44 UTC, joojimin commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        while (hasPreviousSection(downStation)) {
피드백 반영 💯

2022-06-26 06:44 UTC, joojimin commented on src/test/java/nextstep/subway/path/domain/DijkstraPathFinderTest.java
> +@ExtendWith(SpringExtension.class)
테스트에서 SpringContext가 쓰이는 곳이 없어서 SpringExtension은 필요없을 것 같습니다!

2022-06-26 06:44 UTC, joojimin commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +@ExtendWith(SpringExtension.class)
`@ExtendWith(SpringExtension.class)`와 `@SpringBootTest`는 어떤 차이가 있을까요~?

2022-06-26 06:44 UTC, joojimin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +            throw new IllegalArgumentException("출발역과 도착역이 동일합니다.");
에러 메시지를 관리할 더 좋은방법은 없을까요~?

2022-06-26 06:44 UTC, joojimin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +@Transactional
@Transactional의 속성 중 read-only 속성을 적용해보면 어떻게될까요!

2022-06-26 10:35 UTC, breezeunn commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +            throw new IllegalArgumentException("출발역과 도착역이 동일합니다.");
에러메시지가 흩어져 있다 보니 Enum 을 이용하여 한 곳에 모아두는 방안을 고민해보았습니다 😄 
혹시 리뷰어님께서는 저와는 다른 아이디어를 생각하셨을지 여쭈어보아도 될까요?

2022-06-26 13:17 UTC, breezeunn commented on src/test/java/nextstep/subway/path/domain/DijkstraPathFinderTest.java
> +@ExtendWith(SpringExtension.class)
로직을 다시 확인하고 제거하였습니다 😢  코멘트 감사합니다 👍

2022-06-26 14:50 UTC, breezeunn commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +@ExtendWith(SpringExtension.class)
```@SpringBootTest``` 는 통합테스트를 할 때 사용되고, 
```@ExtendWith(SpringExtension.class)``` 는 JUnit 테스트를 하는 과정에서 Spring Boot 관련 기능이 사용될 때
주로 사용했었던 것 같습니다.  리뷰어님의 생각은 어떠실지 여쭈어보아도 될까요??

2022-06-26 14:53 UTC, breezeunn commented on src/main/java/nextstep/subway/path/application/PathService.java
> +@Transactional
조회 쿼리만 있다는 사실을 잠시 잊었던 것 같습니다😢 코멘트 남겨주셔서 감사합니다 👍

2022-06-27 15:08 UTC, joojimin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +            throw new IllegalArgumentException("출발역과 도착역이 동일합니다.");
저도 Enum 클래스로 관리하면 어떨까 생각했었습니다! ㅎㅎㅎ

2022-06-27 15:18 UTC, joojimin commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +@ExtendWith(SpringExtension.class)
Spring2.1부터는 ...Test(`@SpringBootTest, @DataJpaTest..등`) 안에 `@ExtendWith(SpringExtension.class)`가 포함된걸로 파악하고있어서 질문을 드렸는데요!

동작의 차이점에 대해서는 저도 한번 알아봐야할거같네요 😢

2022-06-27 15:18 UTC, joojimin approved these changes
피드백 반영 고생하셨습니다!!
다음미션 진행 부탁드려요~!

2022-06-27 15:18 UTC, merged