4단계 - 요금 조회 리뷰 요청
next-step/atdd-subway-service pull request #701
Opened 2022-06-25 21:43 UTC by Su-hub9

안녕하세요~! 재석님!😊
4단계 요금 조회 리뷰 요청 드립니다.

미션이 갈수록 난이도가 엄청 나네요..😱 구현하는 내내 쩔쩔 매면서 겨우 마쳤습니다...
그래도 덕분에 마지막 단계까지 잘 올 수 있었던 것 같습니다.
사실... 마지막 쯤에 거의 멘탈이 나간 상태로 진행해서 부족한 부분이 많을 듯 합니다😭

남은 리뷰도 유익한 의견 많이 부탁 드립니다~!🙇

2022-06-26 00:51 UTC, seok-2-o requested changes
요금 조회 미션 잘진행해주셨네요.
몇가지 수정하면 좋을 것 같은 부분들이 있어서 코멘트로 남겨놓았어요.
확인 부탁드릴게요 🙇 

즐거운 주말 되시길 바라요.

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/AgeType.java
> +        if (authMember instanceof LoginMember) {
[instanceof의 사용을 지양하자](https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/)

자바에서 instanceof 는 지양하는 패턴인데 비회원의 age 를 임의의 수로 고정하면 어떤까요?

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +    public static int distanceExtraFare(int distance) {
요금 계산이 잘못되고 있는것 같아요
요금 계산은 누적되는 형태로 55 키로미터를 진행한 경우에
`0~10 기본 요금11~50 중간 요금 51~55까지 장거리요금`을 부가해야 해요.

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private static int finalFare(Path path, DiscountPolicy discountPolicy) {
DistanceType 이 모든 계산을 책임지고 Fare 는 단순히 값에 대한 검증 0 원이상 등만 검증하는거 어떤가요?

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private static int finalFare(Path path, DiscountPolicy discountPolicy) {
요금이 Path를 알아야 할까요?

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/policy/DiscountPolicy.java
> +    default int atLeastBasicFare(int calculateFare, int basicFare) {
자바에 default 메소드는 언제 사용할까요?

>...(중략) ... 바로 "하위 호환성"때문이다. 예를 들어 설명하자면, 여러분들이 만약 오픈 소스코드를 만들었다고 가정하자. 그 오픈소스가 엄청 유명해져서 전 세계 사람들이 다 사용하고 있는데, 인터페이스에 새로운 메소드를 만들어야 하는 상황이 발생했다. 자칫 잘못하면 내가 만든 오픈소스를 사용한 사람들은 전부 오류가 발생하고 수정을 해야 하는 일이 발생할 수도 있다. 이럴 때 사용하는 것이 바로 default 메소드다. (자바의 신 2권)

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/AgeType.java
> +    public static DiscountPolicy getDiscountPolicy(AuthMember authMember) {
구지 DiscountPolicy 으로 변환하지 않고 할인을 계산할 수도 있을것같은데 분리해주신 이유가 있으신가요/

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/AgeType.java
> +    private final float discountRate;
어디에 사용되는 인자인가요?

2022-06-26 00:51 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/AgeType.java
> +            return new TeenagersDiscountPolicy();
매번 새로운 객체를 생성할 필요가 있을까요?

2022-06-27 15:39 UTC, Su-hub9 commented
정신 차리고 다시 코드를 봤더니 끔찍하기 그지 없더라구요..😱 대체 무슨 정신으로 구현 한 건지 모르겠습니다..😵 시간이 걸리더라도 좀 더 신중을 기했어야 했는데.. 엉망인 코드 보시면서 리뷰 주시느라 너무 고생하셨을 거 같아 죄송합니다..😭

요금 계산 부분은 제가 요구사항을 잘못 이해한 부분이라 로직 수정 했습니다. 계산 부분은 DistanceType 에서 모든 계산 부분의 책임을 가질 수는 있겠지만 제가 의도했던 역할은 거리 항목에 대한 부분이었어서 거리 초과에 대한 추가 운임만 계산하도록 했고, 경로에 대한 최종 요금 계산은 Path 객체로 이동 했습니다. 다른 좋은 의견 있으시다면 말씀 부탁 드립니다.😊

DiscountPolicy 부분에서는 다형성을 구현하고 싶었는데.. 변명이겠지만 멘탈이 나가서 처음 의도가 이상하게 꼬인 부분이 좀 있었습니다. (물론 지금도 많이 부족한 거 같지만요…)

나름대로 채워보려고 노력했지만 모자람이 많습니다.. 항상 감사합니다~!🙇

2022-06-27 23:53 UTC, seok-2-o requested changes
피드백 반영 잘해주셨어요.

아직도 객체간 응집성이 떨어지는 부분이 있어 관련된 부분과 몇가지 개선하면 좋을 것 같은 부분에
코멘트 남겨놓았습니다. 확인 후 리펙토링해주세요.

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/AgeType.java
> +        return IntStream.range(minAge, maxAge)
매번 새로운 스트림을 만들 필요가 있을까요. DiscountPolicy 처럼 만들어놓고 사용할 수도 있을 것 같네요.

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +    public static int distanceExtraFare(int distance) {
상수의 이름(enum)이 의미를 충분하게 전달하고 있지 않은 것 같아요.

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +    public int extraFare(int distance) {
요금의 계산을 책임진 객체가 거리를 감소시키는 행위도 해야할까요?

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +    public int extraFare(int distance) {
```java 
public int calculate(int distance) {
        int fee = 1250;
        if((distance -= 10)> 0) {
            fee += (int) (Math.ceil((distance - 1) / 5) + 1) * 100;
        }
        if((distance -= 40)> 0) {
            fee +=  (int) (Math.ceil((distance - 1) / 8) + 1) * 100;
        }
        return fee;
    }

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +        int extraFare = FareType.BASIC.getFare();
FareType 과 DistanceType 의 응집성이 떨어진다고 생각해요.

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/FareType.java
> +public enum FareType {
관심사가 다른 요금들을 하나의 클래스로 관리 할 필요가 있을까요?

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private int extraFare;
```suggestion
    private Fare extraFare;
```

Fare 클래스를 만들었으면 여기에도 적용해야 하지 않을까요?

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/domain/Path.java
> +        return Fare.from(discountPolicy.discount(calculateFare));
discountPolicy.discount(calculateFare) 가 Fare 를 응답할 수 있지 않을까요?

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +    public static int distanceExtraFare(int distance) {
해당 메소드에 대한 테스코드가 작성되지 않은 것 같아요.

2022-06-27 23:53 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/DistanceType.java
> +        int extraFare = FareType.BASIC.getFare();
메소드의 이름은 동사로 작성하는 것이 좋습니다.

2022-06-28 11:28 UTC, Su-hub9 commented
의견 주신 내용 반영하여 수정하고 누락된 테스트도 작성 하였습니다.

FareType 부분은 공통으로 사용되는 상수를 enum 으로 만들면 좋겠다는 의도이긴 했는데 관심사가 다른 부분은 미처 생각지 못했네요.. 해당 클래스는 제거하고 필요한 부분의 내부에서 선언하도록 수정 해봤는데 더 나은 방법이 있다면 좋은 의견 부탁 드리겠습니다.

부족한 부분이 많아 리뷰 하시는데 여러모로 번거롭게 해드리네요😭
다시 한번 좋은 리뷰 부탁 드립니다. 감사합니다.

2022-06-28 11:46 UTC, seok-2-o approved these changes
피드백 반영잘해주셨습니다.
마지막으로 소소한 고민거리 남겨드렸습니다. 확인부탁드릴게요.

다른 미션을 병행하지 않으셨다면 다소 촉박할 수 있지만 포기하지말고 미션 완주 하시길 바랄게요.
포비가 말씀하신것처럼 본인 성장을 위한 소중한 시간이 되셨으면 좋겠습니다.

이번 피드백을 마지막으로  저와의 미션은 마무리가 되네요 🙇 

저와 미션은 여기까지지만 앞으로 궁금한점이나 어려운점 있으면 편하게 DM 주세요 :)
좋은 개발자로 성장하는데 조금이나마 도움이 되었기를 바라봅니다.

감사드리며,
이재석 드림

2022-06-28 11:46 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    private final int fare;
```suggestion
   
     private final int fare;
```

2022-06-28 11:46 UTC, seok-2-o commented on src/main/java/nextstep/subway/fare/policy/KidsDiscountPolicy.java
> +        return Fare.from(Math.max(calculateFare(fare), calculateFare(BASIC_FARE)));
청소년: 운임에서 350원을 공제한 금액의 20%할인
어린이: 운임에서 350원을 공제한 금액의 50%할인

기본 금액과 계산된 금액의 할일가를 비교하는 이유가 무엇인가요?

2022-06-28 11:47 UTC, merged

2022-06-28 12:00 UTC, Su-hub9 commented on src/main/java/nextstep/subway/fare/policy/KidsDiscountPolicy.java
> +        return Fare.from(Math.max(calculateFare(fare), calculateFare(BASIC_FARE)));
테스트 작성할 때 할인된 금액인 기본 요금보다 적을 경우가 있지 않을까 생각 해서 추가한 부분 이었습니다. 테스트에 맞추려다 보니 전체 구조 상 발생하지 않을 케이스인 듯 하네요.. 잊지 않고 수정해 두겠습니다~!