Step3 - 인증을 통한 기능 구현
next-step/atdd-subway-service pull request #714
Opened 2022-06-26 23:32 UTC by bgc8214

안녕하세요 :)
step3 인증을 통한 기능구현 완료하여 리뷰 요청드립니다 🙇

2022-06-27 14:02 UTC, parkeeseul requested changes
3단계 잘 진행해 주셨네요! 👍 
몇가지 코멘트 남겨두었으니 확인 부탁드립니다 😄 
화이팅 입니다 🔥

2022-06-27 14:02 UTC, parkeeseul commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
> +        assertThat(favoriteTargets).contains(target);
assetAll 을 사용해보면 어떨까요? 😄 
```suggestion
        assertAll(() -> assertThat(favoriteSources).contains(source),
                () -> assertThat(favoriteTargets).contains(target));
```

2022-06-27 14:02 UTC, parkeeseul commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
>  public class FavoriteAcceptanceTest extends AcceptanceTest {
로그인을 하지 않은 상태에서 즐겨찾기 기능을 사용했을 경우의 테스트도 있으면 어떨까요? 😄

2022-06-27 14:02 UTC, parkeeseul commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +    private final StationService stationService;
개인적으로는 Service 보다는 repository를 의존하는 것이 더 좋다고 생각하는데요,
Service 에는 요구사항에 대한 기능을 구현하게 됩니다.
예를 들어 StationService 에는 `지하철 역을 생성할 수 있다`라는 요구사항에 대한 구현 부분인데요,
FavoriteService가 StationService를 의존하게 되면 만약 지하철역에 대한 요구사항이 수정되어 StationService 를 수정할 경우
FavoriteService에도 영향이 갈 수 있을 것 같아요.

이 부분은 저의 의견이니 수정 요청을 드리는 것은 아니고 한번 고민해 보시면 좋을 것 같아요 😄

2022-06-27 14:02 UTC, parkeeseul commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    private Member member;
객체를 직접 참조하는 방법과 ID로 참조하는 방식이 있는데요,
해당 부분은 member 를 직접 참조할 필요가 없을 것 같은데 어떻게 생각하시나요? 😄

2022-06-27 14:02 UTC, parkeeseul commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +    }
@Transactional(readOnly = true) 를 사용해 보면 어떨까요? 😄 
```suggestion
    @Transactional(readOnly = true)
    public Member findMemberOrThrow(Long id) {
        return memberRepository.findById(id).orElseThrow(IllegalArgumentException::new);
    }
```

2022-06-28 05:11 UTC, bgc8214 commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
> +        assertThat(favoriteTargets).contains(target);
몰랐던 건데, 이렇게 쓰니까 한번에 적용할 수 있어 편하네요! 수정하였습니다.

2022-06-28 05:12 UTC, bgc8214 commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
>  public class FavoriteAcceptanceTest extends AcceptanceTest {
이것도 추가하였습니다!

2022-06-28 05:20 UTC, bgc8214 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +    private final StationService stationService;
저는 Service를 일반적으로 많이 사용하는 편인데요... repository 로 단순 쿼리로만 할 수 있는 거를 쓰는 데는 좋은데, DB에서 가져온 후 서비스 적인 로직이 필요한 경우도  많다고 생각을 해요. ( 삭제를 해야 되는데... 그 전에 다른 것들의 처리가 필요하다던가 )
repository 를 통해서 가져온 후, 직접 그런 내용을 구현할 수 있지만, 다른 서비스에서 알고 있는 내용이고 거기서 책임을 지는 게 맞다고 생각해서, 해당 서비스의 메소드를 호출하는 게 좋다고 생각합니다.
의존 생기는 것은 분명히 존재하지만, 호출하는 서비스가 수정되는 경우에 대한 영향은 그게 올바른 동작이라면 호출하는 부분에서 그렇게 변견되는 것이 맞지 않을까? 라는 생각도 해요 ( 완전 개별적인 로직이라면 다르겠지만요 )

다만 순환참조같은 문제가 생기는 경우도 있어서, 항상 고민을 많이 하는 부분입니다. 😭

2022-06-28 05:20 UTC, bgc8214 commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    private Member member;
굳이 필요가 없네요! 변경하였습니다.

2022-06-28 05:20 UTC, bgc8214 commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +    }
find 부분에 대해서는 수정하였습니다.!

2022-06-29 08:54 UTC, parkeeseul approved these changes
리뷰가 많이 늦었는데 양해해 주셔서 감사합니다 🙏 
피드백 잘 반영해 주셨네요! 👍 
다음 미션 진행해 주세요!
마지막까지 화이팅 입니다 🔥

2022-06-29 08:54 UTC, merged