Feature/payment
next-step/atdd-subway-service pull request #72
Opened 2021-01-12 19:04 UTC by lazy-moon

4단계 - 요금 조회 과제 제출합니다.

4단계는 금방 끝낼 줄 알았는데, 숨겨진 고려할 항목들이 있었네요, 덕분에 머리좀 많이 굴렸습니다 ㅎㅎ

이번 리뷰도 잘 부탁드려요 !

2021-01-13 10:25 UTC, wbluke requested changes
4단계 요금 계산 구현까지 고생많으셨어요! 👍 
Enum으로 추상화 잘 해주셨네요 ㅎㅎ
마지막이라서 리팩토링 진행해보면 좋을 것 같아요 🙂

2021-01-13 10:25 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +    private boolean found = false;
필터링된 Line을 로컬 변수로 선언한 뒤에 바로 리턴하면 굳이 들고 있지 않아도 될 것 같아요 :)

2021-01-13 10:25 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +        if (prevFindLine == null || !prevFindLine.containsSection(departureId, destinationId)) {
이전에 찾은 Line을 기억하고 check하기 보다는, 필터 결과를 담는 컬렉션을 Set으로 두면 중복제거가 되지 않을까요? :)

2021-01-13 10:25 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +    public ThroughLineSelector(List<Line> lines, List<Long> stationIds) {
`List<Line>`에서 stationId를 기반으로 필터링을 하는거니 별도의 객체를 만들기보다는 Lines 일급컬렉션을 만들고 거기서 책임을 가져가는건 어떻게 생각하시나요? :)

2021-01-13 10:25 UTC, wbluke commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        ThroughLineSelector throughLineSelector = new ThroughLineSelector(lines, stationIds);
id 대신 Station 기반으로 변경하면 어떨까 고민해봐주세요 ㅎㅎ
앞선 과정에서 Station을 id 기반으로 한번 검색하기 때문에, 그 결과를 가지고 활용하면 Line, Section의 메서드에 Long값 보다 엔티티로 명시되어서 조금 더 명확하지 않을까 하는 생각이 드네요 :)

2021-01-13 10:25 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
> +            return DEFAULT_CHARGE;
Enum 추상화 좋네요! 👍  
구간이 추가된다면 if문도 계속 추가되어야할 것 같은데요, default 구간도 enum으로 만들어서 구간이 추가되어도 변경이 없도록 리팩토링해볼 수 있을까요? :)

2021-01-13 14:54 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/application/PathService.java
>                  .collect(Collectors.toMap(Station::getId, it -> it));
엥 그러네요 ㅋㅋ 미처 생각이 안났나봐요 감사합니다 :)

2021-01-13 15:02 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +    private boolean found = false;
요거는 살짝 혹시 find()를 중복해서 호출 할 일이 있지 않을까 해서 캐싱 개념으로 담아뒀던건데, 지금은 굳이 쓸모가 없긴 하네요 ㅎㅎ

2021-01-13 15:14 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +        if (prevFindLine == null || !prevFindLine.containsSection(departureId, destinationId)) {
아하, 요녀석은 사실 중복제거를 위해서라기보단 line을 찾는 작업을 최소화시키려고 나눠져있는 부분입니다. 출발 - 도착 역이 다른 노선일 수도 있지만, 같은 노선인 경우가 많을테니, 매번 어떤 라인인지까지 찾는게 낭비라고 생각이 돼서요!
예를 들면, lines에 1호선 - 9호선이 순서대로 등록되어 있다면 라인까지 찾으려면 1호선 - 8호선까지 둘러보는 낭비가 발생하는게 아닐까요 ?
코멘트를 달다 보니 그럴거면 그냥 Map으로 만들어두는게 좀 더 의미전달이 명확하지 않았을까 싶네요!
하지만 그렇다 한들 line -> section -> station으로 관계가 맺어져있는 지금 상황에서 station으로 line을 뽑아내려면 전체 Line.Sections를 순회하는 것 밖엔 방법이 없어보이는데, 어떻게 생각하시나요 ? :)

2021-01-13 15:15 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +        if (prevFindLine == null || !prevFindLine.containsSection(departureId, destinationId)) {
일단 요 부분은 놔두겠습니다!

2021-01-13 15:16 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +    public ThroughLineSelector(List<Line> lines, List<Long> stationIds) {
그쪽이 좀 더 의미전달이 잘 될거 같네요! 일단 한번 해볼게요 :)

2021-01-13 15:53 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/ThroughLineSelector.java
> +    public ThroughLineSelector(List<Line> lines, List<Long> stationIds) {
옮기는김에 살짝살짝 다른데도 손대봤어요 ㅎㅎ 깔끔해진거같네요 !

2021-01-13 15:56 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        ThroughLineSelector throughLineSelector = new ThroughLineSelector(lines, stationIds);
아하, 그게 더 나을것같네요 감사합니다 :)

2021-01-13 16:24 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
> +            return DEFAULT_CHARGE;
지금 상황에선 얘가 좀 더 직관적이라고 생각해서 그러긴 했는데 ㅎㅎ 바꿔보겠습니다 :)

2021-01-14 13:50 UTC, wbluke approved these changes
피드백 반영 감사합니다 👍 
enum에 대해서 간단한 코멘트 하나 남겼으니 참고해주세요 ㅎㅎ
길었던 지하철 미션 고생 많으셨어요! 남은 과정도 화이팅입니다 🙂

2021-01-14 13:50 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
> +        }
Enum의 생성자를 두가지로 두고 calculate를 오버라이딩하는 것보다 
DEFAULT(0, 0)처럼 같은 생성자로 생성하고 calulate 메소드에서 overDistance가 0보다 같거나 작은 경우에 기본요금을 리턴하도록 하는 구조는 어떨까요?

2021-01-14 13:50 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
>      private enum DistanceCharge {
저번에 말씀드릴까 하다가 안드리긴 했었는데, 클래스 내의 private 클래스로 두기보다 (외부에서 접근하는 것이 싫다면) 별도 패키지를 구성하고 패키지 접근제어자로 관리하면서 단위테스트를 하는게 더 좋을 것 같다는 생각이에요 :)

2021-01-14 13:50 UTC, wbluke commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +public class Lines {
일급컬렉션 잘 만들어주셨네요 👍

2021-01-14 13:50 UTC, merged

2021-01-14 13:59 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
>      private enum DistanceCharge {
아하, 그것도 좋은 생각인 것 같습니다 ㅎㅎ 하지만 제 개인적인 생각으로 이너클래스를 쓰는 경우는, 메서드만으로는 표현이 불편한 기능들( 메서드 스택 별로 동일한 참조가 필요하다던지 )을 묶기 위한 느낌이 더 강해서 package 범위로 오픈하는것과는 조금 다른 뉘앙스일 것 같아요! 온전히 그 클래스에서만 사용하는 기능들의 집합이 클래스 내부에 존재한다면, 그 클래스의 오픈 된 기능들을 테스트 했을 때 자연스레 검증이 되지 않을까 하는 의견입니다. public 메서드를 검증하는 것으로 거기서 참조하는 나머지 private 한 메서드들이 덩달아 검증이 되듯이 ㅎㅎ 
하지만 역시 이것도 상황에 따라 서로 다른 선택지가 있을 것 같아요 ! 의견 주신 내용은 참고하도록 하겠습니다. 감사합니다 :)

2021-01-14 14:02 UTC, wbluke commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
>      private enum DistanceCharge {
그렇네요 그것도 좋은 의견이네요 ㅎㅎ 말씀해주셔서 감사합니다 👍  저도 참고하겠습니다 :)

2021-01-14 14:05 UTC, lazy-moon commented on src/main/java/nextstep/subway/path/domain/PaymentCalculator.java
> +        }
그것도 나쁘진 않은 것 같아요! 저도 원래는 그런식으로 썼었는데 ( 생성자는 하나에 메서드는 다같이 오버라이드 혹은 동일한 녀석을 쓰는 ? ), 일단 0, 0은 당연히 쓰이지 않을 녀석이라고 알고 있는 값인데 굳이 넘겨주는 것과, enum 객체의 protected 한 메서드에 조건문이 들어가는 건 enum으로 얻을 수 있는 가독성에서의 이점을 잘 못살리는게 아닌가 하는 생각이 들어서 ㅎㅎ .. 이유를 설명하자면 이런거긴 하지만 사실 결론적으로는 그냥 개인적으로 볼 때 불편해서 그런게 크겠죠 ㅎㅎ 이건 좀 취향문제라고 생각합니다 ! 의견은 감사히 참고하도록 하겠습니다 :)