4단계 - 요금조회 PR
next-step/atdd-subway-service pull request #725
Opened 2022-06-29 18:25 UTC by kbh0581

안녕하세요 

최단거리에 노선의 요금을 추가하는 부분에서 
생각보다 오래 걸렸네요 ㅠㅠ...
요금조회 미션 리뷰 부탁드립니다.

2022-06-30 14:35 UTC, Junhong-Kim requested changes
4단계 미션 잘 구현해주셨습니다 👍
소소한 코멘트 남겼는데 확인하시고 다시 요청해주시면 감사드립니다!

2022-06-30 14:35 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        return LoginMember.memberLogin(member.getId(), member.getEmail(), member.getAge());
정적 팩터리 메서드에도 네이밍 컨벤션이 있어요 ☺️
참고할만한 [링크](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/) 공유드립니다.

2022-06-30 14:35 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/global/GlobalExceptionHandler.java
> +    @ExceptionHandler(DataIntegrityViolationException.class)
동일한 응답을 반환하는 예외는 다음과 같이 처리할 수도 있습니다.
```suggestion
    @ExceptionHandler({DataIntegrityViolationException.class, IllegalArgumentException.class})
```

2022-06-30 14:35 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        persistLine.changeFare(request.getFare());
`Line` 인스턴스 생성시 `Fare` 값을 할당해주면 될 것 같은데 따로 분리하신 이유가 있을까요?
되도록 인스턴스 생성과 동시에 초기화해서 완전한 값을 갖도록 하면 좋을 것 같아요.

2022-06-30 14:35 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/member/ui/MemberController.java
> +    private void authValidLoginMember(LoginMember loginMember) {
Controller에 비즈니스 로직을 두는 것보다는 객체에 메시지를 보내면 좋을 것 같아요.

2022-06-30 16:58 UTC, kbh0581 commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        return LoginMember.memberLogin(member.getId(), member.getEmail(), member.getAge());
참고하여 적절한 메서드 명으로 바꾸겠습니다!

2022-06-30 17:00 UTC, beng9re commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        persistLine.changeFare(request.getFare());
사실 생성자의 필드들이 너무 많아져서 분리를 진행 했었는데
빌더 패턴으로 해결하면 좋을꺼 같습니다

2022-07-01 09:57 UTC, Junhong-Kim requested changes
피드백 잘 반영해주셨네요 👍
소소한 코멘트 남겼는데 확인하시고 다시 요청해주시면 감사드립니다!

2022-07-01 09:57 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(request.toLine(upStation, downStation));
`Request` 객체는 요청 값을 받아 유효성 검사만하면 좋을 것 같아요.
인스턴스를 생성하는 책임은 해당 클래스에게 위임하여 인스턴스 생성에 대한 일관성이 있으면 좋을 것 같아요.

2022-07-01 15:45 UTC, kbh0581 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(request.toLine(upStation, downStation));
분리하도록 하겠습니다!

2022-07-02 07:24 UTC, Junhong-Kim requested changes
피드백 반영해주신 내용에 대해 코멘트 남겼습니다.
확인하신 후 다시 요청해주시면 감사드립니다. ☺️

2022-07-02 07:24 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    private Line requestToLine(LineRequest request, Station upStation, Station downStation) {
https://github.com/next-step/atdd-subway-service/pull/725#discussion_r911813325

`인스턴스를 생성하는 책임은 해당 클래스에게 위임`이라는 내용은 `Line` 클래스에 위임을 의미한 것이었습니다.
`Line` 클래스의 생성자 또는 정적 팩토리 메서드를 활용하면 될 것 같아요.
인스턴스 생성 책임을 한 곳에 두어 인스턴스 생성에 대한 일관성을 갖으면 좋을 것 같다는 내용이었습니다.
Service가 도메인 클래스의 인스턴스를 생성하는 책임을 갖는게 괜찮은 방법일지 고민하고 수정해보면 좋을 것 같아요.

2022-07-02 08:25 UTC, kbh0581 commented
준홍님 피드백 반영 완료 하였습니다. 

"인스턴스 생성 책임을 한 곳에 두어 인스턴스 생성에 대한 일관성을 좋겠다" 라는 의미가 와닿지가 않아서 

인스턴스 생성 책임의 일관성 갖게 생성하면 어떤 장점이 있을까 하는가에 대해서 
곰곰히 생각을 해보았는데요.
 
해당 인스턴스의 생성이 여러 부분에 산재가 되어 있다면 
해당 인스턴스의 필드가 추가 되거나 변경이 되었을때 직접 찾아가서 모두 바꿔줘야하지만 해당 클래스 부분만 바꾸면 되는 거의 장점이 있는거 같다고 개인적으로 생각이 드는데 제가 이해하는 부분이 맞을까요??

2022-07-03 09:04 UTC, Junhong-Kim commented
https://github.com/next-step/atdd-subway-service/pull/725#issuecomment-1172860343

엔티티 클래스 인스턴스 생성을 `Request` 클래스의 메서드 또는 `Service` 클래스의 메서드에서 할 수 있게된다면,
협업하는 다른 개발자 입장에서는 인스턴스 생성 시 `Request`를 사용해야 할지 `Service`를 사용해야 할지 고민될 것 같아요.

그래서 엔티티 클래스에 대한 인스턴스 생성은 항상 엔티티 클래스 생성자 또는 정적 팩토리를 사용하도록 해서,
인스턴스 생성 시 어떤 클래스를 이용해야 할지에 대한 고민을 줄일 수 있을 것 같습니다.

그리고 앞서 코멘트 드린 것처럼 `Request` 객체는 요청 값을 받아 유효성 검사에 대한 역할만 하고,
`Service`는 도메인 클래스들을 활용해서 메서드마다 하나의 기능을 제공하는 방향을 지향하면 좋을 것 같아요.
이에 대해 참고할만한 [링크](https://nesoy.github.io/articles/2018-04/why-close-to-domain)도 공유드립니다. ☺️

2022-07-03 09:11 UTC, Junhong-Kim approved these changes
피드백 잘 반영해주셨네요 👍
피드백 반영해주신 내용에 대해 소소한 코멘트 남겼으며 PR로 질문 남겨주신 사항은 코멘트로 답변드렸습니다.

리뷰 반영하시느라 정말 고생 많으셨어요!
이번 미션은 여기서 마무리하겠습니다.
다음 미션도 화이팅입니다! ☺️

2022-07-03 09:11 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public static Line of(LineRequest request, Station upStation, Station downStation) {
정적 팩토리 메서드 `of`가 `LineRequest`에 종속되게 되네요.
`LineRequest`를 사용하지 않고 upStation과 downStation 처럼 값을 넘겨받으면 좋을 것 같아요.

2022-07-03 09:11 UTC, merged