Step4 - 요금 조회
next-step/atdd-subway-service pull request #73
Opened 2021-01-13 02:58 UTC by PilhwanKim

코드 리뷰 미리 감사드립니다.

## TODO list

- 경로 조회 시 거리 기준 요금 정보 포함 테스트 작성
- 경로 조회 시 거리 기준 요금 정보 포함 코드 작성
- 노선별 추가 요금 정책 테스트 작성
- 노선별 추가 요금 정책 코드 작성
- 연령별 할인 정책 테스트 작성
- 연령별 할인 정책 코드 작성
- 연령별 할인 controller 단 적용
- 요금정보 전체 리펙토링

2021-01-13 06:24 UTC, seok-2-o requested changes
요금 조회 미션 잘 구현해주셨네요.

다만 거리에 비례한 요금 계산시 요구사항을 정확하게 반영하고 있지 않은 것같아요.
11km 를 이용한 경우 기본 이용거리인 10키로를 제외한 1키로에 대한 추가 요금이 100 원 발생하여
`1350원`이 계산 되어야 하며 (현재 로직에서는 1250 + 300 = `1550원`)
 52km 거리를 이동했을때에는
1250(0 ~ 10) + 800(10 ~ 50) + 100 (50 ~ 52) 로 각 구간별에 해당하는 
요금이 계산되어야 합니다.

추가적으로 요금 계산 관련하여 몇가지 코멘트 남겨놓았으니 확인 부탁드릴게요 🙆‍♂️

2021-01-13 06:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/application/fare/DistanceOverFarePolicy.java
> +    public int calculateOverFare(int distance) {
해당 메소드에 대한 테스트도 작성할 수 있을 것 같아요.

2021-01-13 06:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
> +        DistanceOverFarePolicy distanceFarePolicy = getDistanceFarePolicy(distance);
DistanceOverFarePolicy  를 외부에 노출할 필요가 있을까요?
`calculateOverFare(distance) ` 메소드 내부에서 전략을 선택하고 계산까지 진행해줄 수 있을 것 같아요.

2021-01-13 06:24 UTC, seok-2-o commented on src/test/java/nextstep/subway/path/application/fare/FareCalculatorTest.java
> +        int fare = new FareCalculator().calculateFare(path, loginMember);
calculateFare해당 클래스가 이동거리와, 추가 요금을 주입받는다면 테스트 하기 한결 간결해질 것 같아요.
객체간 의존성도 낮아질테구요.

2021-01-13 06:24 UTC, seok-2-o commented on src/test/java/nextstep/subway/path/application/fare/FareCalculatorTest.java
> +    void calculateAgeFare1() {
해당 부분도 거리 기반 요금을 계산하는 로직과 
공제 금액을 계산하는 로직을 분리한다면 테스트하기는 조금더 수월해질 것같아요.

2021-01-13 06:31 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/DistanceOverFarePolicy.java
> +    private final int max_distance;
헙!  python 을 쓰고 있어서 :( 바로 바꿀게요.

2021-01-13 06:32 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
> +    private static final int BASIC_FARE = 1250;
오호. 좋네요. 바로 적용!

2021-01-13 06:33 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
> +public class FareCalculator {
spring di 를 쉽게 하려고 썼습니다. 음.. 아래 보니깐 좀 더 나은 방식이 언급되어 있네요. 그 방향으로!

2021-01-13 06:33 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/DistanceOverFarePolicy.java
> +    public int calculateOverFare(int distance) {
원래 최초 버전이 이 메소드 였는데 리팩토링도 편의를 좀 더 생각해봤어야 했네요!

2021-01-13 06:34 UTC, PilhwanKim commented on src/test/java/nextstep/subway/path/application/fare/FareCalculatorTest.java
> +        int fare = new FareCalculator().calculateFare(path, loginMember);
오 그래서 싱글턴을 언급하셨던 거군요. 넵 바로 적용!

2021-01-13 06:35 UTC, PilhwanKim commented on src/test/java/nextstep/subway/path/application/fare/FareCalculatorTest.java
> +    void calculateAgeFare1() {
오 넵 좀 test 하기 빡세진다 생각했는데, 방법이 있었군요.

2021-01-14 06:46 UTC, seok-2-o approved these changes
피드백 반영 빠르게 잘 해주셨네요 👍 

저도 필환님 덕분에 지하철 요금 계산하는 로직은 잊지 못할 것 같아요.
어제 이야기 나눈 뒤로 저도 한번 계산기를 구현해보고 비교해보면 재미있을 것 같아 해당하는 코드 첨부 해놓았습니다.
모쪼록 여유가 되신다면 이번엔 리뷰어의 시각으로 리뷰 부탁드립니다.😄 

이번 피드백을 마지막으로 저와의 미션은 종료되었네요 😭 
좋은 개발자로 성장하는데 조금이나마 도움이 되길 바라봅니다.

미션은 종료되었지만 앞으로도 궁금한점이나 어려운점 있다면 편하게 연락주세요.

완주가 얼마 남지 않았습니다. 끝까지 멋진 모습으로 완주해주세요.🔥
응원하고 있겠습니다.

감사드리며, 
이재석 드림

2021-01-14 06:46 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/application/fare/policy/DistanceOverFarePolicy.java
>  public enum DistanceOverFarePolicy {
```java
    enum BillingStrategy {
        SHORT (distance -> 1250),
        MEDIUM(distance ->
                SHORT.expression.apply(Constants.SHORT_MAX_DISTANCE)
                + (int) (Math.ceil((distance - Constants.SHORT_MAX_DISTANCE - 1) / 5) + 1) * 100),
        LONG(distance ->
                MEDIUM.expression.apply(Constants.MEDIUM_MAX_DISTANCE)
                + (int) (Math.ceil((distance - Constants.MEDIUM_MAX_DISTANCE - 1) / 8) + 1) * 100);


        private static class Constants {
            public static final int SHORT_MAX_DISTANCE = 10;
            public static final int MEDIUM_MAX_DISTANCE = 50;
        }

        private final Function<Integer, Integer> expression;

        BillingStrategy(Function<Integer, Integer> expression) {
            this.expression = expression;
        }

        public static int calculate(int distance) {
            return find(distance).expression.apply(distance);
        }

        private static  BillingStrategy find(int distance) {
            if(distance <= Constants.SHORT_MAX_DISTANCE) {
                return SHORT;
            }
            if(distance <= Constants.MEDIUM_MAX_DISTANCE) {
                return MEDIUM;
            }
            return LONG;
        }
    }
```

ㅎㅎ 저도 어제 필환님 질문을 받고 한번 구현해봤는데요, 비교해보면 좋을 것 같아서 살포시 첨부해봅니다.

2021-01-14 06:46 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/application/fare/policy/DistanceOverFarePolicy.java
>  public enum DistanceOverFarePolicy {
```java
 public int calculate(int distance) {
        int fee = 1250;
        if((distance -= 10)> 0) {
            fee += (int) (Math.ceil((distance - 1) / 5) + 1) * 100;
        }
        if((distance -= 40)> 0) {
            fee +=  (int) (Math.ceil((distance - 1) / 8) + 1) * 100;
        }
        return fee;
    }
```

짧게는 위와 같이도 가능합니다.

2021-01-14 06:46 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
> +    private final DistanceOverFarePolicy distanceOverFarePolicy;
인스턴스 로 가지고 있어야 할 필요가 있을까요?
valueOf 는 calculateFare 메소드 내부로 캡슐화 해도 괜찮을 것 같아요.

2021-01-14 06:46 UTC, seok-2-o commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
>      public FareCalculator(int distance, List<Section> sections, LoginMember loginMember) {
`List<Section> sections` 말고 거리별 추가요금을 주입 받는건 어떻게 생각하시나요 ?
FareCalculator 객체가 Section을 알아야 할 필요가 있을까요?

2021-01-14 06:46 UTC, seok-2-o commented on src/test/java/nextstep/subway/path/application/fare/policy/DistanceOverFarePolicyTest.java
> +        int fare = DistanceOverFarePolicy.valueOf(distance).calculateFare(distance);
위에도 언급하였듯이 valueOf 를 호출하지 않고 바로 계산 하면 더 좋을 것 같아요.

2021-01-14 06:46 UTC, merged

2021-01-14 06:59 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
> +    private final DistanceOverFarePolicy distanceOverFarePolicy;
너무 저거에 집착했었던거 같네요. ㅎㅎ 실용적으로 접근하자!

2021-01-14 07:00 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/FareCalculator.java
>      public FareCalculator(int distance, List<Section> sections, LoginMember loginMember) {
section 리스트를 가장 큰 line 을 찾는 로직을 어디다 둘지 애매해서 놔뒀는데... 좀 더 고민해봐야겠네요.

2021-01-14 07:01 UTC, PilhwanKim commented on src/test/java/nextstep/subway/path/application/fare/policy/DistanceOverFarePolicyTest.java
> +        int fare = DistanceOverFarePolicy.valueOf(distance).calculateFare(distance);
큭... 통한의valueOf...

2021-01-14 07:01 UTC, PilhwanKim commented on src/main/java/nextstep/subway/path/application/fare/policy/DistanceOverFarePolicy.java
>  public enum DistanceOverFarePolicy {
오 ... `Function<Integer, Integer>` 을 쓰는 방법도 있겠군요.. 요거 기억해놨다가 나중에 써먹어야 겠습니다. 감사합니다. :)