[Step4] 요금 조회
next-step/atdd-subway-service pull request #737
Opened 2022-07-04 15:10 UTC by cold-pumpkin

안녕하세요 리뷰어님! 4단계 요금조회 미션 제출합니다.
더운데 건강 조심하셔요~
잘 부탁드립니다!

2022-07-05 14:37 UTC, parkeeseul requested changes
4단계 미션 잘 진행해 주셨녜요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 😄 
날씨가 많이 덥네요 건강 유의하시고 마지막까지 화이팅 입니다 🔥

2022-07-05 14:37 UTC, parkeeseul commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +    }
거리에 따라 달라지는 요금계산에 대한 테스트인데요,
비슷한 코드가 중복되네요, 중복을 제거해 주는 방법은 없을까요?

또한 구간별로 달라지는 계산방식에 대한 테스트가 한 테스트 안에 존재하고 있는데요,
만약 특정 구간에 대한 테스트가 실패했을 경우 어떠한 테스트에서 문제 발생했는지 파악하기 힘들고
한 테스트에서 여러 구간에 대한 개념을 독자가 이해해야 하는 어려움이 있을 것 같은데 어떻게 생각하시나요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +    }
`@MethodSource`를 사용하면 test method 실행 당 복잡한 인수 를 전달할 때 유용한대요 
한번 학습해 보셔도 좋을 것 같아요 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +    }
하나의 테스트 메서드에서 
3개의 노선에 대한 테스트를 진행해 주셨는데요,
어떠한 이유로 해당 테스트들이 모두 필요하다고 생각하셨나요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        }
로그인 하지 않은 사용자를 LogInMember 로 나타내는 것이 어색하다고 생각되는데
어떻게 생각하시나요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/auth/domain/AuthenticationPrincipal.java
> +    boolean required() default true;
👍

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/line/domain/AdditionalFare.java
> +    }
객체를 생성할 때마다  해당 검증이 필요할 것 같은데요,
기본 생성자에 해당 로직을 위치하면 어떨까요?
어떠한 차이가 있을까요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    }
다양한 생성자가 존재하는데요, 모두 필요한 생성자 일까요?
다양한 생성자가 필요하다면 주 생성자를 만들어 사용해보면 어떨까요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private final int additionalFare;
AdditionalFare 객체를 사용하지 않는 이유가 있을까요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/path/domain/Path.java
>      }
해당 메서드는 테스트 코드에서만 사용중인데 필요한 부분 일까요? 😄

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/path/domain/fare/DistanceFareCalculationPolicy.java
> +    private static final int ADDITIONAL_FARE_UNIT = 100;
개인적으로는 enum 으로 관리해도 좋을 것 같다는 생각이 드네요! 😄 
(수정해달라는 의미는 아닙니다 😄 )

2022-07-05 14:37 UTC, parkeeseul commented on src/main/java/nextstep/subway/path/dto/PathResponse.java
>      }
DTO에 비즈니스 로직이 포함되어 있네요 🤔 
serivce 나 도메인으로 옮겨볼 수는 없을까요?

2022-07-09 09:58 UTC, cold-pumpkin commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +    }
확실히 하나의 메서드 안에서 여러 케이스를 한번에 테스트 하려다보니 복잡해지는 것 같습니다..! 특히 서비스 내용에 대해 잘 알지 못하는 다름 개발자가 본다고 했을 때 이해하기 여러울 것 같아요.
케이스별로 메서드를 분리하는게 좋을 것 같습니다!

2022-07-09 09:59 UTC, cold-pumpkin commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +    }
이 메서드 역시 분리하는게 좋을 것 같습니다!

2022-07-09 10:13 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/line/domain/AdditionalFare.java
> +    }
여러 개의 정적 팩토리가 있더라도 결국 공통적으로 생성자를 호출하기 때문에, 생성자 안에 검증 로직을 넣어두는 것이 좋을 것 같습니다~!

2022-07-09 10:30 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    }
테스트 코드에서 케이스를 만들려다보니 생성자가 늘어났네요..! 
강의 중에 테스트를 위한 생성자를 추가하는 것은 괜찮다고 듣기는 했지만, 굳이 기존의 생성자를 사용해도 무방한데 마냥 추가하는 것은 좋지 않은 것 같아 조금 줄여보도록 하겠습니다~

2022-07-09 10:36 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private final int additionalFare;
앗 만들어두고 사용을 안했네요 ^^;

2022-07-09 10:39 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/path/domain/Path.java
>      }
역시 기존 메서드를 사용하면 되기 때문에 삭제해도 될 것 같습니다~

2022-07-09 10:43 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/path/domain/fare/DistanceFareCalculationPolicy.java
> +    private static final int ADDITIONAL_FARE_UNIT = 100;
넵 저도 이 부분에서 Enum으로 해도 좋지 않을까?하는 생각을 했었는데, 실행력(?)이 부족했네요 ^^;
확실히 Enum을 잘 활용하면 유지보수, 테스트 측면 등에서 훨씬 유용한 것 같아 필요한 경우 적극 활용하면 좋을 것 같습니다!

2022-07-09 13:33 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/path/dto/PathResponse.java
>      }
넵 비즈니스 로직은 서비스나 도메인 쪽으로 옮기는게 좋을 것 같습니다~

2022-07-09 13:45 UTC, cold-pumpkin commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        }
음 이 부분은  생각해봤는데, 어떤 방법이 좋을지 고민이 되네요..!
로그인 하지 않은 사용자도 서비스를 사용해야해서 예외를 발생시키면 안되고 빈 `LoginMember`를 리턴하는게 좋을 것 같다고 생각했는데, 리뷰어님 말씀처럼 어색한 면도 있는 것 같아요  🤔

하나 생각해본 방법은 
- 멤버를 나타내는 추상 클래스를 만들고 (ex. `Member`)
- 토큰 유효 여부에 따라 Member를 상속하는 다른 자식 클래스를 리턴 (ex. `LoginMember` / `GeneralMember` )

이런 방식인데.. 혹시 더 좋은 방법이 있을까요?

2022-07-09 14:30 UTC, parkeeseul commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> +    @DisplayName("첫번째 추가요금 구간 요금이 계산되어 조회된다.(미로그인)")
첫번째 추가요금 구간은 어떤 구간일까요? 😄 
`예) 10km 초과 ~ 50km 구간의 요금을 계산한다` 와 같이 구간에 대한 정보를 담아주면 어떨까요? 😄

2022-07-09 14:30 UTC, parkeeseul commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    }
주 생성자를 사용할때 어떠한 이점이 있는지 고민해 보셔도 좋을 것 같아요 😄

2022-07-09 14:43 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드리고
이만 머지 하겠습니다 😄 
그동안 많은 피드백 반영해 주시느라 정말 고생 많으셨습니다.
기간이 얼마 남지는 않았지만 남은 미션들도 꼭 완주하시길 바라요!
마지막까지 화이팅 입니다 🔥

2022-07-09 14:43 UTC, parkeeseul commented on src/main/java/nextstep/subway/auth/application/AuthService.java
> +        }
말씀해주신 방법 좋다고 생각합니다! 👍

2022-07-09 14:43 UTC, parkeeseul commented on src/main/java/nextstep/subway/path/service/PathService.java
>      }
코드가 중복되네요
중복을 제거해 보면 어떨까요? 😄

2022-07-09 14:43 UTC, merged