Step2 경로 조회 기능 리뷰 부탁드립니다!
next-step/atdd-subway-service pull request #768
Opened 2022-11-27 12:51 UTC by ilmare-cbk

안녕하세요 우테캠 Pro 5기 교육생 천보경입니다!
2단계 미션인 `경로 조회 기능` 리뷰 부탁드립니다.

지난 1단계 미션에서 피드백 주신 사항들도 반영했습니다.

https://github.com/next-step/atdd-subway-service/pull/757#discussion_r1032805729
해당 피드백에 대해서 Section을 생성하는 곳을 3곳으로 줄였습니다
`많은 곳에서 생성 책임을 가지고 있다면 어떤 단점이 있을까요!?` 라는 질문에는 제가 아직 명확한 답변을 찾지 못하였는데
힌트나 태경님의 생각도 같이 알 수 있을까요??

2022-11-27 15:22 UTC, ohtaeg commented
> 많은 곳에서 생성 책임을 가지고 있다면 어떤 단점이 있을까요!? 라는 질문에는 제가 아직 명확한 답변을 찾지 못하였는데
힌트나 태경님의 생각도 같이 알 수 있을까요??

우선, A라는 객체의 생성을 많은 곳에서 해준다는 것은 
1. 그만큼 내부 노출이 되어있다는 뜻으로써, 구현체 타입이 노출되어 구현 은닉을 할 수 없는 단점이 있는 것 같아요 :)
지금은 다형성을 이용하지 않지만 유연함을 발휘하기 위해서는 구체적인 타입을 숨기는 것부터가 시작이라고 생각합니다 ㅎㅎ
2. `강한 의존 관계`를 맺는 단점이 있는 것 같아요! 의존 관계는 보통 객체간 협력을 통해 기능을 수행하기 위해 맺어지는데요!
기능은 요구사항의 변화에 민감하다보니 요구사항이 변하면 기능도 변하게 됩니다 :)
반대로 기능과 무관한 것은 그 요구사항도 잘 변하지 않는데요!
기능이 변하면 기능을 사용하고 있는 객체에 영향이 가는 것은 맞지만, 저는 생성과 기능은 다르다고 생각합니다 😄 
그렇기에 구체적인 객체를 생성하는 곳이 많다는 것은 구체적인 객체 생성을 수정할 경우, 기능으로 인해 영향을 받는 것이 아닌
생성변경으로 인해 영향을 받는 다는 것은 그만큼 강한 의존 관계를 맺게 되는 것 같아요!
3. 객체 생성은 당연히 어느 곳에서나 이루어질 수 있다고 생각합니다.
참조 변수를 선언할 때도 생성할 수 있고, 생성자에서도 생성할 수 있으며 메소드 내에서도 생성할 수 있습니다.
다만 이러한 자유도는 "관리" 측면에서는 매우 불편하다고 생각합니다 :)

2022-11-27 16:02 UTC, ohtaeg requested changes
2단계 구현을 잘해주셨어요 👍 👍 테스트도 잘 작성해주셨어요 👍 
다음 미션을 진행하기전에 고민해보시면 좋을 포인트들이 있어 Request changes 하였습니다!
주신 질문에 대한 코멘트 및 소소한 피드백들을 드렸는데 확인해주시면 감사하겠습니다 :)
날씨가 많이 추워졌습니다 🥶 감기 조심하세요!!

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/exception/EmptyLineNameException.java
> +public class EmptyLineNameException extends DomainException {
각 예외 케이스마다 커스텀 익셉션 구현 👍

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/line/application/LineService.java
> +@Transactional(readOnly = true)
👍 👍

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/line/domain/LineColor.java
> +public class LineColor {
👍 👍

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            if (!nextStation.isPresent()) {
저는 솔직하게 실무에서는 반복문 내에 if문을 작성하곤 합니다 😂
아쉽지만 우테켐 과정에서는 depth 1(반복문 내부에 if문 허용 x)만 허용하기에
해당 부분을 리팩토링 해주시면 좋을 것 같아요 :)
힘드실 경우 현재 구조를 유지해주셔도 좋습니다!

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private final DijkstraShortestPath<Station, DefaultWeightedEdge> dijkstraShortestPath = new DijkstraShortestPath<>(graph);
PathFinder라는 도메인 객체를 별도로 만들어주셨네요 👍 
이 부분에 대해서 같이 고민해보면 좋을 포인트가 있는 것 같아요 :)

개인적으로 생각하길, 외부 라이브러리를 이용한 최단 경로 찾는 방법은 언제든지 바뀔 수 있는 점을 고려해보았을 때
만약 다른 최단경로알고리즘 라이브러리나 직접 구현할 경우 알고리즘 교체에 유연하지 않은 것 같아요!

이 부분을 해결하기 위해서 도메인 패키지에 인터페이스를 선언하고, 실제 구현체는 외부에서 주입받아 사용할 수도 있을 것 같아요
도메인 layer에서 외부 라이브러리 구현체에 직접 의존하는 것을 최소화하면 어떨까요?
보경님은 이 부분에 대해서는 어떻게 생각하시나요 :) ?

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    public static PathFinder from(List<Line> lines) {
PathFinder에서는 Line을 받고 있네요 :)
Line을 받음으로써 Line을 이용할 것 같지만 정작 Line을 사용하지 않고
Line의 Sections 혹은 getStation()을 통해 List\<Station>을 가져와 forEach를 이용해 
순회하고 있는 용도로만 사용하고 있는 것 같아요..!
Line이 아닌 Sections 혹은 List\<Section> 혹은 List\<Station>을 받는건 어떨까요?

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    public static PathFinder from(List<Line> lines) {
이전 생성 책임에 연장선으로 이번엔 PathFinder가 Line과 Section, Staion을 의존하고 있는 상태에서
Line의 의존성이 제거된다면 어떤 장점이 있는지 고민해보시면 좋을 것 같아요 😄

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/ControllerExceptionHandler.java
> +@ControllerAdvice
`@ControllerAdvice` 👍
아실수도 있지만 `@RestControllerAdvice`랑 어떤 차이가 있는지 알아보시는 것도 좋을 것 같아요 😄

2022-11-27 16:02 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private int distance;
수정을 위한 리뷰가 아닌 점 참고 부탁드리며,
현재 만들어주신 Path 도메인 객체의 책임은 무엇인지 의도를 공유해주실 수 있으실까용? 🙏
개인적으로 Path 도메인 객체는 현재는 DTO, VO 성 목적이 강해보여서 드린 질문이였어요!

최단 경로에 대한 결과를 가지고 있는 것은 매우 좋은 설계라고 생각하지만,
데이터만 보관하고 있는 도메인 객체는 도메인으로써의 역할을 잘 하고 있는지가 판단하기가 애매한 부분인 것 같아요..!

또한 해당 객체를 이용하여 내부나 외부에서 따로 별다른 연산이 보이지 않고
PathResponse와 크게 다른 것 같지 않아보이기에 이 부분을 같이 고민하면 좋을 것 같아 코멘트를 드리게 되었습니다 :)

보경님은 어떻게 생각하시는지 궁금하네요 😄

2022-11-27 16:02 UTC, ohtaeg commented on src/test/java/nextstep/subway/path/PathAcceptanceTest.java
> +    void findShortestPathWithException2() {
예외 상황에 대한 테스트도 꼼꼼하게 작성해주셨네요 💯 
![image](https://user-images.githubusercontent.com/20432323/204144722-1893dfc8-1ac4-489c-ab6d-73b131392064.png)

2022-11-27 16:10 UTC, ohtaeg commented
커밋들 하나하나 보았는데 정말 TDD로 개발하시려는 노력이 느껴지네요!
미리 테스트 케이스를 통해 명세를 작성한 상태에서 기능 구현이 하나하나 채워지면서 리팩토링 되는 과정이 인상깊네요 💯 👍 👍

2022-11-28 12:54 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private final DijkstraShortestPath<Station, DefaultWeightedEdge> dijkstraShortestPath = new DijkstraShortestPath<>(graph);
> > 많은 곳에서 생성 책임을 가지고 있다면 어떤 단점이 있을까요!? 라는 질문에는 제가 아직 명확한 답변을 찾지 못하였는데
> > 힌트나 태경님의 생각도 같이 알 수 있을까요??
> 
> 제 의견을 조심스럽게 공유드려봅니다 🙏 우선, A라는 객체의 생성을 많은 곳에서 해준다는 것은
> 
> 1. 그만큼 내부 노출이 되어있다는 뜻으로써, 구현체 타입이 노출되어 구현 은닉을 할 수 없는 단점이 있는 것 같아요 :)
>    지금은 다형성을 이용하지 않지만 유연함을 발휘하기 위해서는 구체적인 타입을 숨기는 것부터가 시작이라고 생각합니다 ㅎㅎ
> 2. `강한 의존 관계`를 맺는 단점이 있는 것 같아요! 의존 관계는 보통 객체간 협력을 통해 기능을 수행하기 위해 맺어지는데요!
>    기능은 요구사항의 변화에 민감하다보니 요구사항이 변하면 기능도 변하게 됩니다 :)
>    기능이 변하면 기능을 사용하고 있는 객체에 영향이 가는 것은 맞지만, 저는 생성과 기능은 다르다고 생각합니다 😄
>    그렇기에 객체 생성 로직을 수정할 경우, 기능으로 인해 영향을 받는 것이 아닌 생성으로 인해 영향을 받는 다는 것은
>    그만큼 매우 강한 의존 관계를 맺게 되는 것 같아요!
> 3. 객체 생성은 당연히 어느 곳에서나 이루어질 수 있다고 생각합니다.
>    참조 변수를 선언할 때도 생성할 수 있고, 생성자에서도 생성할 수 있으며 메소드 내에서도 생성할 수 있습니다.
>    다만 이러한 자유도는 "관리" 측면에서는 매우 불편하다고 생각합니다 :)
> 
> 읽어보시고 고민해보신 후 보경님이 내린 결론도 공유해주시면 감사하겠습니다 😄

아직 저의 내공이 많이 부족한 듯 싶습니다 ㅎㅎ
객체의 생성을 많은 곳에서 해준다는 것이 느낌적으로는 안좋을 것이다라고 느껴지는데
아직 말씀해주신 부분들에 대해서는 명확하게 이해를 하지 못한 상태입니다 ㅎㅎ
다만 관리적인 측면에서 객체의 생성이 여러곳에 흩어져있다면 생성에 대한 로직이 변경되었을 때 많은 부분이 영향 받을것이라는 것에는 이해되었습니다!!

적어주신 내용들은 제가 시간을 두고 계속 곱씹어보면서 이해해보도록 하겠습니다!
꼼꼼하게 답변 주셔서 진심으로 감사합니다 😄

2022-11-28 12:57 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    public static PathFinder from(List<Line> lines) {
불필요한 Line 모델을 참조하는 것보다는 명확하게 필요한 모델을 참조하여 PathFinder를 사용하는 곳에서는 불필요한 모델을 조회해오는 (의존하는) 부분들을 줄일 수 있을 것 같습니다! 혹시나 더 추가적인 조언이 있으시면 말씀주세요 ㅎㅎ

2022-11-28 12:58 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/ControllerExceptionHandler.java
> +@ControllerAdvice
ResponseBody를 통해 객체를 리턴하는 경우에는 @RestControllerAdvice를 사용하면 될 것 같습니다!!

2022-11-28 12:59 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private final DijkstraShortestPath<Station, DefaultWeightedEdge> dijkstraShortestPath = new DijkstraShortestPath<>(graph);
> PathFinder라는 도메인 객체를 별도로 만들어주셨네요 👍 이 부분에 대해서 같이 고민해보면 좋을 포인트가 있는 것 같아요 :)
> 
> 개인적으로 생각하길, 외부 라이브러리를 이용한 최단 경로 찾는 방법은 언제든지 바뀔 수 있는 점을 고려해보았을 때 만약 다른 최단경로알고리즘 라이브러리나 직접 구현할 경우 알고리즘 교체에 유연하지 않은 것 같아요!
> 
> 이 부분을 해결하기 위해서 도메인 패키지에 인터페이스를 선언하고, 실제 구현체는 외부에서 주입받아 사용할 수도 있을 것 같아요 도메인 layer에서 외부 라이브러리 구현체에 직접 의존하는 것을 최소화하면 어떨까요? 보경님은 이 부분에 대해서는 어떻게 생각하시나요 :) ?

이 부분에 대해서는 인터페이스를 통해 외부 라이브러리에 대한 직접적인 의존을 최소화 해볼 수 있을 것 같습니다.!
피드백 반영해서 수정해보았는데 부족한 점이 있으면 말씀주세요!!😄

2022-11-28 13:00 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            if (!nextStation.isPresent()) {
이 부분 depth1로 수정해보았습니다!

2022-11-28 13:03 UTC, ilmare-cbk commented on src/main/java/nextstep/subway/path/domain/Path.java
> +    private int distance;
맞습니다 현재 Path 모델은 단순히 vo의 성격이 강합니다
path 모델을 도입한 이유는 아래와 같은 메소드를 한 번만 호출해서 List<Station>과 distance를 가져올 수 있어 
불필요한 메소드 호출을 줄일 수 있지 않을까 하는 생각에 만들게 되었습니다!
`GraphPath<Station, DefaultWeightedEdge> path = dijkstraShortestPath.getPath(source, target);`

2022-11-28 13:04 UTC, ilmare-cbk commented
> 커밋들 하나하나 보았는데 정말 TDD로 개발하시려는 노력이 느껴지네요! 미리 테스트 케이스를 통해 명세를 작성한 상태에서 기능 구현이 하나하나 채워지면서 리팩토링 되는 과정이 인상깊네요 💯 👍 👍

신경쓴 부분을 이렇게 알아봐주셔서 너무 좋네요 ㅎㅎㅎ

2022-11-28 16:31 UTC, ohtaeg approved these changes
피드백 반영들을 잘해주셨어요 💯 
테스트도 꼼꼼하게 잘 작성해주셨어요 👍 👍 
다음 미션도 화이팅입니다 🔥

2022-11-28 16:31 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
>  public interface PathFinder {
인터페이스 추출 💯

2022-11-28 16:31 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/DijkstraShortestPathFinder.java
> +        if (path == null) {
라이브러리 내부에서 null이 반환되는 것도 놓치지 않고 꼼꼼하게 validation 💯 

```
protected final GraphPath<V, E> createEmptyPath(V source, V sink) {
    if (source.equals(sink)) {
        return new GraphWalk<>(
            graph, source, sink, Collections.singletonList(source), Collections.emptyList(), 0d);
    } else {
        return null;
    }
}
```

2022-11-28 16:31 UTC, ohtaeg commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            nextStation = findNextStation(currentStation);
리팩토링을 잘해주셨어요 👍 👍

2022-11-28 16:31 UTC, ohtaeg commented on src/main/java/nextstep/subway/path/domain/PathFinder.java
> +    private final DijkstraShortestPath<Station, DefaultWeightedEdge> dijkstraShortestPath = new DijkstraShortestPath<>(graph);
너무 잘해주셨네요 👍

2022-11-28 16:32 UTC, merged