1단계 - 인수 테스트 기반 리팩터링
next-step/atdd-subway-service pull request #792
Opened 2022-11-30 03:13 UTC by snh15978

안녕하세요 석홍님!

단위 테스트와 TDD 미션 잘 부탁드립니다 🙏

2022-11-30 13:51 UTC, seokhongkim requested changes
남현님 안녕하세요.
인수 테스트 기반 TDD 미션을 함께 할 리뷰어 김석홍입니다. 만나서 반갑습니다. 😀

1단계 미션 잘 진행해주셨습니다. 👍
서비스에 있는 로직을 도메인으로 잘 이동해주셨고, 그 과정에서 단위 테스트도 잘 작성해주셨네요.

코드를 보고 궁금한 점과 고민해보시면 좋을 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-30 13:51 UTC, seokhongkim commented on README.md
> +#### 기능 요구사항
요구사항 목록 작성 좋습니다. 👍

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +@Transactional(readOnly = true)
클래스에 설정하신 `@Transactional`의 readOnly 설정을 true 로 하신 이유가 있을까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            .orElseThrow(() -> new IllegalArgumentException("노선을 찾을 수 없습니다."));
요청으로 넘어온 id 가 무엇인지도 예외 메시지에 포함하시면 문제가 발생했을 때 원인 파악이 수월할 것 같습니다. :)

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +public class Distance {
거리 관리를 위한 값 객체 사용 좋습니다. 👍

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public Distance() {
기본 생성자를 사용할 일이 없다면 제거해보는 건 어떨까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public Distance(int distance) {
1. `from`을 사용하도록 하기 위해 이 생성자는 private 으로 관리해보면 어떨까요?
2. 거리는 항상 0보다 커야 할 것 같아요. 밸리데이션을 추가해보는 건 어떨까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public void modifyDistance(Distance otherDistance) {
이 메서드의 기능은 입력받은 거리를 현재 거리에서 뺀 거리를 계산하는 것 같아요. `minus` 또는 `subtract` 를 사용해도 괜찮지 않을까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +        this.distance = this.distance - otherDistance.getDistance();
`sum` 메서드와 같이, `Distance`를 불변으로 유지하기 위해 새로운 객체를 만들어서 반환해보는 것은 어떨까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +            throw new IllegalArgumentException("역과 역 사이의 거리보다 좁은 거리를 입력해주세요");
거리는 역, 구간을 직접적으로 사용하고 있지는 않으나, 예외 메시지에서 거리가 역, 구간에 의존적인 메시지를 만드는 것은 아닐까요? 이로 인해 구간에서 거리를 사용하고, 거리에서도 구간에 의존적인 메시지를 가지게 되며, 상호 참조하는 관계가 만들어지는 것 같기도 합니다. 🤔

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public Section(Station upStation, Station downStation, int distance) {
`Section`은 항상 `Line`이 있어야 하는 것은 아닐까요? :)

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public static Section merge(Optional<Section> upLineStation, Optional<Section> downLineStation) {
1. 각 인자는 `Section` 타입이니 `upSection`, `downSection` 을 사용해보는 건 어떨까요?
2. 메서드 내부에서 바로 get 으로 값을 꺼낸다는 것은 항상 존재해야 한다는 것 같아요. Optional 을 사용하신 이유가 있을까요?
3. 항상 두 개의 `Section`이 있어야 한다면, 현재 `Section`에서 병합해야 할 `Section`을 인자로 받을 수 있도록 인스턴스 메서드로 제공해보는 건 어떨까요? static method 를 사용하신 이유가 있을까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public boolean existDownStation() {
구현상 항상 downStation, upStation 을 가지고 있을 것으로 보이는데, 상행역 또는 하행역이 구간에 없는 경우가 있을까요?

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        return sortedStation();
남현님께서는 메서드를 어떤 순서로 배치하시나요? :)

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Optional<Section> removeUpSection(Station station) {
상행역이 일칠하는 구간을 찾는 것과 제거하는 두 가지 역할을 하다보니, 구현을 보기 전까지는 반환 값이 무엇을 나타내는지 바로 예상하기는 어려운 것 같네요. 🤔

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Section findPrevStation(Station station) {
1. `Prev`와 `Pre`가 모두 같은 내용을 나타낸다면, 하나의 용어로 통일해보시면 좋을 것 같습니다.
2. 메서드명과 반환 타입을 통해 구현을 보지 않고 무슨 기능인지 생각하기는 조금 어려웠네요. 앞 구간을 찾는다면 `findPrevSection`이 될 것 같은데, 하행역이 일치하는 구간을 찾는 것이니 `findSectionByDownStation`이 기능을 더 잘 설명해주는 것 같기도 합니다. :)

2022-11-30 13:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    @ExceptionHandler({DataIntegrityViolationException.class, IllegalArgumentException.class, IllegalStateException.class})
예외 핸들링 좋습니다. 👍

2022-11-30 13:51 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/acceptance/LineSectionAcceptanceTest.java
> +    Stream<DynamicNode> scenario() {
인수 테스트 통합 시나리오 좋습니다. 👍

2022-11-30 13:51 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/domain/DistanceTest.java
> +class DistanceTest {
꼼꼼한 단위 테스트 작성 좋습니다. 👍

2022-11-30 14:25 UTC, snh15978 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            .orElseThrow(() -> new IllegalArgumentException("노선을 찾을 수 없습니다."));
반영 완료요!

2022-11-30 14:36 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public Distance() {
`@Embeddable` 이 붙은경우 기본 생성자가 필수여서 접근제어자를 protected로 변경했습니다!

2022-11-30 14:36 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public Distance(int distance) {
반영완료요!

2022-11-30 14:37 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public void modifyDistance(Distance otherDistance) {
`subtract`로 변경했습니다.

2022-11-30 14:37 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +        this.distance = this.distance - otherDistance.getDistance();
반영완료요~

2022-11-30 14:37 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +            throw new IllegalArgumentException("역과 역 사이의 거리보다 좁은 거리를 입력해주세요");
`기존의 거리보다 좁은 거리를 입력해주세요.`로 변경했습니다.

2022-11-30 14:41 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public Section(Station upStation, Station downStation, int distance) {
해당 생성자 제거했습니다. 테스트코드 짜다가 잘못 만들어진걸 계속 쓰고 있었네요.ㅠㅠ

2022-11-30 15:01 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public static Section merge(Optional<Section> upLineStation, Optional<Section> downLineStation) {
1. 변경했습니다~
2. if 문에서 `isPresent()`로 체크를했는데 굳이 `Optional`로 넘길필요가 없었네요.
3. upSection에 downSection을 merge하는걸로 변경했습니다. service에 있던 로직을 그대로 메소드로 분리를 진행했고 해당 메소드는 section의 역할이다보니 그대로 옮기다가 static을 붙였었습니다. 말씀해주신대로 변경한게 훨씬 깔끔하고 보기 좋네요.

2022-11-30 15:06 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        return sortedStation();
요번엔 분리되는 메소드도 많아서 public 메소드들을 위로 올리고 private메소드는 아래에 배치를 하는식으로 진행을 했습니다.

2022-11-30 15:09 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Section findPrevStation(Station station) {
`Prev`로 통일했습니다. 메소드명을 좀 더 명확하게 작성하겠습니다

2022-11-30 15:19 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    private Optional<Section> removeUpSection(Station station) {
remove 메소드 분리했습니다.

2022-11-30 15:25 UTC, snh15978 commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public boolean existDownStation() {
말씀해주신대로 굳이 체크할필요가 없네요. 제거하겠습니다.

2022-11-30 15:36 UTC, snh15978 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +@Transactional(readOnly = true)
습관?적으로 `@Transactional(readOnly = true)`걸고 실제 `insert`, `update`가 일어나는곳에 `@Transactional`을 붙이고 있습니다. 해당내용 리뷰주신 이유 알 수 있을까요?

2022-12-01 10:51 UTC, seokhongkim approved these changes
남현님, 1단계 미션 코멘트 잘 반영해주셨습니다. 👍 
1단계 PR 머지하도록 하겠습니다.

남겨주신 질문과, 제 질문에 코멘트 남겨주신 내용에 대해 추가로 코멘트 남겼습니다.
코멘트 참고 부탁드립니다.

2단계 미션에서 뵙겠습니다. 😀

2022-12-01 10:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +@Transactional(readOnly = true)
readOnly 설정을 명시적으로 추가하셔서, 이렇게 관리하시는 이유가 있는지 궁금했습니다. :)

저는 클래스의 transactional 설정은 readOnly = false 를 사용하는데요. 이유는 아래와 같습니다.
* 클래스의 설정을 `readOnly = true` 로 하고, 메서드에서 `transactional(readOnly = false)` 오버라이드 하는 경우 메서드에 설정이 잘 되었음을 테스트에서 확인하기 어려움. 즉, 개발자 또는 리뷰어가 놓치는 상황이 발생할 수 있음.
    * 코드에서 데이터를 수정하는 작업이 발생하는지에 대한 검증은 단위테스트와 통합테스트를 통해 검증이 상대적으로 용이함. 그러나 트랜잭션 설정이 잘 되었는지에 대한 테스트는 상대적으로 어렵고 놓치기 쉬움.
* readOnly 설정을 DB replication 과 함께 사용하여 writer/reader 를 구분하는 목적으로 사용할 수 있는데, readOnly = true 가 기본인 경우 쓰기 요청이 읽기 DB로 전달되어 장애 상황이 발생할 수 있음. 반면, 읽기 전용으로 설정해야 하는 작업이 쓰기 DB로 전달되는 경우 부하는 늘어날 수 있으나 당장 장애 상황으로 이어지지는 않음.

이 내용도 참고해서 같이 고민해보셔도 도움이 될 것 같습니다.

2022-12-01 10:51 UTC, seokhongkim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        return sortedStation();
그렇군요! public 메서드가 상단에 있으면, 어떤 기능을 제공하는지 한 눈에 보기 쉽다는 장점이 있겠네요.

저는 개인적으로 public 메서드를 먼저 작성하고, 해당 메서드 내부에서 호출하는 private 메서드를 사용되는 순서대로 이어서 작성합니다.
오버로딩된 public 메서드가 존재하는 경우, 해당 메서드는 모아서 작성하고, 내부에서 호출하는 private 메서드를 사용되는 순서대로 이어서 작성합니다.
이렇게 이어서 작성했을 때, public 메서드 내부에서 사용하는 메서드를 가까운 곳에서 찾을 수 있고, 순서대로 찾아볼 수 있어서 구현된 코드를 읽기 위해 이동하는 시간을 줄일 수 있어 좋았습니다.

관련하여 클린 코드에 나온 내용을 참고해보셔도 좋을 것 같습니다. :)

2022-12-01 10:51 UTC, merged