[yeojiin(임정연)] - 2단계 경로 조회 기능
next-step/atdd-subway-service pull request #818
Opened 2022-12-02 12:55 UTC by yeojiin

안녕하세요. 우빈님~
익숙하지 않은 다익스트라 알고리즘을 사용하고, 모키토 테스트 케이스 방식 작성이 처음이라 시간이 꽤 오래 걸렸네요.😭
오류가 많이 나서 중간에 어려움이 있었지만 열심히 해봤습니다!
3번째 미션이 특히 어렵다고 하는데 더 걱정이 되네요🤣
이번 미션도 리뷰 잘 부탁드립니다!🙏
날이 갑자기 추워졌는데 감기 조심하세요~~🙇‍♀️

2022-12-03 03:47 UTC, limwoobin commented
<img width="633" alt="image" src="https://user-images.githubusercontent.com/28802545/205420979-bfba629c-9b48-4aa0-a6ae-55fdb899b3ac.png">
코드가 수정되면서 기존에 작성되어있던 테스트코드에서 실패가 떨어지는것같은데
같이 확인부탁드립니다 :)
+ 커밋 전이나 pr전에 전체 테스트를 돌리면 리팩토링한 로직이 
사이드 이펙트가 있는지를 확인할 수 있는 좋은 방법이기도 합니다 ㅎㅎ

2022-12-03 03:48 UTC, limwoobin commented
추가로 지금도 굉장히 미션을 잘 수행해주셔서 걱정하고 계시는 3단계 미션은
전혀 문제없이 잘 진행해주실거라고 생각됩니다 ㅎㅎ
충분히 잘 하실것같은데 전혀 걱정안하셔도 될것같아요 👍👍

2022-12-03 03:50 UTC, limwoobin requested changes
안녕하세요 정연님 2단계 미션 잘 수행해주셨네요! 👍👍👍 
테스트코드도 정말 꼼꼼하게 잘 작성해주셔서 크게 피드백드릴 부분이 없었습니다 ㅎㅎ
프로덕션코드쪽에 몇가지 코멘트를 남겨드렸으니 확인하시고 다시 요청주시면 될것같습니다!

추가로 미션을 진행하며 생기는 궁금증이나 의논하고 싶으신 점이 있으면
언제든 편하게 dm주셔도 좋습니다 화이팅입니다 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on README.md
> +## 🚀2단계 - 경로 조회 기능
요구사항 정리를 굉장히 꼼꼼히 작성해주셨네요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
advice를 적용해주셧군요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +    }
InternalServerException 는 모두 badRequest로 리턴하네요 
예외이름만 보았을때는 서버예외로 판단되는데요 이런 경우엔 잘못된 요청이라는 이름의 예외클래스이름을 사용해보는것도 좋을것같습니다
InternalServerException는 너무 포괄적인 이름이라 badRequest로 판단하기엔 애매할수도 있을것같아요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +    }
추가로 RuntimeException 시에 메시지를 같이 던지고있는데요
이때 RuntimeException을 던지지 않고 어떤 예외가 발생했는지 advice로 잡아서 httpstatus와 메시지를 같이
클라이언트에게 응답하면 보다 명확하게 인지될것같아요!

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +//        Line persistLine = lineRepository.save(request.toLine(upStation, downStation));
주석은 제거해주심 좋겟네요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private Color color;
모두 객체로 래핑해주셧군요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/line/domain/Section.java
>          }
advice를 이용해 예외에 대해 공통으로 처리할 수 있도록 작성해주셨는데요
여기는 그냥 RuntimeException으로 바로 리턴하는 이유가 있을까요??

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
지하철역에 대해 조회하고 없으면 예외를 리턴하는군요
조회 -> 예외발생까지의 책임은 StationService에서 가지는게 더 맞을것같은데 어떻게생각하시나요??

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +public class DijkstraPathFinder implements PathFinder {
클래스 이름이 와닿지가 않네요 ㅎㅎ 
해당 클래스를 사용하는 입장에선 어떤 알고리즘을 이용한 클래스인지 보다는 어떤 경로를 찾는지 (지하철 노선, 자전거...)가 더 중요한 정보가 아닐까 싶습니다 ㅎㅎ
추가로 인터페이스없이 PathFinder로 사용해도 괜찮을것같아요
애초에 subway-service 라는 프로젝트이니 노선찾기 이외엔 추가될 여지는 없을것같아서 의견드려봅니다 

+ 만약 네비게이션같은 서비스였다면 작성하신것처럼 다형성을 생각해 충분히 좋은 설계라고 생각되기도 하네요!

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +    private final DijkstraShortestPath<Station, DefaultWeightedEdge> dijkstraShortestPath = new DijkstraShortestPath<>(graph);
key를 객체로 쓰는건 저는 좀 지양하는 편인데요 ㅎㅎ
우선 객체의 동일성 보장이 애매하고 키 비교시에도 성능상 단점이 있다고 생각들어서요
어떻게 생각하시나요??

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +    }
조회시 Path 라는 이름의 VO와 같이 한번에 응답받으면 
경로조회에 대해 응집도가 더 생길것같은데 어떠신가요??

2022-12-03 03:50 UTC, limwoobin commented on src/main/java/nextstep/subway/station/application/StationService.java
> +        return stationRepository.findById(id).orElseThrow(() -> new RuntimeException(NOT_EXISTS_STATION));
여기도 액션별 줄개행이 있으면 좋겟네요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +                .hasMessageStartingWith(INVALID_OVER_SECTION_DISTANCE);
hasMessage로만 사용해도 될것같네요..!

2022-12-03 03:50 UTC, limwoobin commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +     */
위와같은 주석이 있으니 테스트코드 읽기에 굉장히 수월하네요 ㅎㅎ

2022-12-03 03:50 UTC, limwoobin commented on src/test/java/nextstep/subway/path/application/PathServiceTest.java
> +class PathServiceTest {
서비스 단위테스트 정말 잘 작성해주셧습니다!

2022-12-03 03:50 UTC, limwoobin commented on src/test/java/nextstep/subway/path/domain/PathFinderTest.java
> +class PathFinderTest {
단위테스트도 정말 훌륭하네요 ㅎㅎ

2022-12-03 13:35 UTC, yeojiin commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
이전 미션 때 적용해보면 좋을 것 같다고 해주셔서 함께 적용해봤습니다!☺️

2022-12-03 13:40 UTC, yeojiin commented on src/main/java/nextstep/subway/line/domain/Section.java
>          }
해당 부분은 제가 놓쳤습니다!🤣

2022-12-03 13:48 UTC, yeojiin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +public class DijkstraPathFinder implements PathFinder {
너무 과제 위주로 생각하다보니 클래스명까지 알고리즘 명으로 타고 간 거 같네요🤣
말씀해주신 대로 다른 기능이 추가 될 여지가 없기 때문에 PathFinder 하나로 가도 괜찮을 거 같습니다!
이후에 추가할 부분이 생기면 인터페이스로 분리하는 방향이 더 맞는 거 같네요~☺️

2022-12-03 14:08 UTC, yeojiin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +    private final DijkstraShortestPath<Station, DefaultWeightedEdge> dijkstraShortestPath = new DijkstraShortestPath<>(graph);
생각해보니 현업에서 키를 객체로 쓰는 경우는 드물었던 거 같네요.
다만, 궁금한 부분이 있는데 키를 Station의 id로 변경하기 위해 Long 타입으로 변경해보았습니다. 
그런데 그렇게 변경하면 같은 클래스 내에
```
 public List<Station> findAllStationsByStations(Station source, Station target) {
        GraphPath<Long, DefaultWeightedEdge> path = getShortestPath(source, target);
        return path.getVertexList();
    }
```
해당 부분이 `List<Long>` 으로 키값들만 반환해주게 될 텐데 결과적으로 필요한 `List<Station>` 을 리턴해 줄 때 어떤 방식으로 Station 객체들을 찾아오는 게 좋을까요?

현재는 전체 역을 조회 후 키값이 같은 정보를 세팅하게 되는 이중 for문을 사용하는 방식에 사고가 막혀있어서 피드백을 한 번 더 받고 수정하도록 하겠습니다!

2022-12-03 14:36 UTC, yeojiin commented on src/main/java/nextstep/subway/path/domain/DijkstraPathFinder.java
> +    }
넵! 중복된 부분도 한번에 관리할 수 있고 훨씬 더 좋은 방향인 거 같습니다!👍

2022-12-03 16:52 UTC, yeojiin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
코드 작성 시 해당 부분을 고려하다 수정했었는데 피드백이 나온 걸 보니 책임을 옮기는 게 더 맞는 거 같네요☺️

2022-12-03 17:00 UTC, yeojiin commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +    }
`InternalServerException`을 `DomainException`으로 수정 후 `ControllerExceptionHandler`부분을 수정했는데 
제가 의도하신 피드백대로 수정한 건지 확실치 않네요🤔

2022-12-03 17:07 UTC, yeojiin commented
> <img alt="image" width="633" src="https://user-images.githubusercontent.com/28802545/205420979-bfba629c-9b48-4aa0-a6ae-55fdb899b3ac.png">
> 
> 코드가 수정되면서 기존에 작성되어있던 테스트코드에서 실패가 떨어지는것같은데 같이 확인부탁드립니다 :) + 커밋 전이나 pr전에 전체 테스트를 돌리면 리팩토링한 로직이 사이드 이펙트가 있는지를 확인할 수 있는 좋은 방법이기도 합니다 ㅎㅎ

앗! study 부분을  빼고 돌렸네요😂 앞으론 전체 test를 돌려보는 습관을 기르겠습니다!

2022-12-04 03:10 UTC, limwoobin commented on src/main/java/nextstep/subway/path/dto/domain/PathFinder.java
> +package nextstep.subway.path.dto.domain;
Pathfinder의 위치는 dto/domain보다는 domain이 더 알맞지 않을까요??
경로찾기의 핵심 객체라고 생각되어서요 ㅎㅎ
추가로 dto/domain package는 어떤 패키지인지 감이 잘 안오기도하네요 ㅎㅎ

2022-12-04 03:10 UTC, limwoobin commented on src/main/java/nextstep/subway/path/vo/Path.java
> +    }
Path객체에서 굳이 GraphPath까지 알고있을 필요는 없지않을까 합니다..
PathFinder에서 getVertextList, getWeight로 값을 가져와 생성자로 넘겨주는건 어떻게생각하시나요??

2022-12-04 03:10 UTC, limwoobin commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +    }
DomainException인 이름은 뭔가 포괄적이기도 하네요
예외는 경우에따라 BadRequest, UnAuthrozation 등등 여러 경우가 발생할 수 있어서 보다 명시적인 이름을 나타내는게 좋긴 합니다
다음 미션에도 다른 예외가 추가될 수 있으니 한번 고민해보심 좋을듯 해요 ㅎㅎ

2022-12-04 03:11 UTC, limwoobin approved these changes
안녕하세요 정연님
2단계 피드백 모두 잘 반영해주셨네요 ㅎㅎ 👍 
주말임에도 미션하시느라 정말 고생 많으셨습니다!
몇가지 코멘트를 남겨드렷으니 다음미션 진행하면서 확인부탁드립니다

다음 미션도 화이팅입니다!

2022-12-04 03:11 UTC, merged