4단계 - 요금 조회 PR 요청 드립니다.
next-step/atdd-subway-service pull request #842
Opened 2022-12-04 15:22 UTC by crongcm

안녕하세요 용희님
피드백 주셨던 내용들 반영했는데
테스트 픽스쳐 구성 변경
서로 다른 도메인 간의 양방향 의존성 제거
이 두가지 부분이 제가 제대로 이해한게 맞는지  잘 모르겠습니다.
의도하신대로 변경 되었는지 확인 부탁드리겠습니다.

그리고 Mock 테스트에서 stubing을 given 항목에 when을 사용해서 given으로 모두 변경했는데
이렇게 사용하는게 맞을까요 ? 이 부분도 궁금합니다.

이번 미션은 난이도가 갑자기 급 상승한 느낌이네요..
개인적인 일정과 미션의 난이도로 구현이 많이 늦어졌습니다.

`SectionEdge`는 도저히 구현을 방법을 모르겠어서 참고 했습니다..

리뷰 잘 부탁드리겠습니다.
감사합니다.

2022-12-05 13:56 UTC, devyonghee requested changes
안녕하세요 창민님!
4단계 요금 조회 역시 잘 구현해주신 것 같아요 👍👍
어려운 단계였음에도 불구하고 깔끔하게 구현하시느라 고생 많으셨을 것 같습니다 🙇‍♂️

추가적으로 조금 더 고민해보시면 좋을 것 같은 부분들에 대해
소소한 코멘트들 남겨드렸는데 확인 한번만 부탁드리겠습니다. 🙇‍♂️
질문에 대한 답변도 코멘트와 함께 남겨드렸습니다! 🤔😆

이번 단계는 마지막 단계이다보니 우선은 request chagnes 로 남겨드리겠습니다. 🙏
마지막까지 파이팅입니다!!💪🚀

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/DistanceSurchargePolicy.java
> +    }
데코레이터 패턴을 이용해주신 것 같아요 👍👍
그런데 추상 클래스의 캡슐화가 깨지면서 결합도가 많이 생긴 것 같아 추상 클래스 수정이 어려워 질 것 같아요.🤔
역할이 과하게 추상화가 이루어진게 아닐까라는 생각이 드는데 
오히려 인터페이스를 바로 구현하시는 방향은 어떻게 생각하시나요??🤔🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    public static final int FIRST_SECTION_MAX_SURCHARGE = 800;
재사용을 고려해주셔서 상수를 선언해서 사용해주셨네요 👍👍
그런데 모든 상수가 사실 요금을 표현하고 있는데 `Fare` 가 아닌 `int` 원시 타입으로 이용해주신 이유가 있을까요??🤔

그리고 이 상수들이 `Fare` 에 위치하고 있는 것이 적절한지 고민해보시면 좋을 것 같아요. 
예를 들어 `BASIC_FARE` 같은 경우에는 `BasicFare` 에 위치하고 있는 방향이 응집도가 더 좋지 않을까 개인적으로 생각되는데 혹시 이 부분에 대해 어떻게 생각하시나요?? 🤔🤔

제가 참고한 자료 남겨드리도록 하겠습니다!
[퍼블릭 상수를 사용하지 마세요](https://github.com/hyejineee/Reading-and-Writing/blob/master/%EC%A0%95%EB%A6%AC/%EC%97%98%EB%A0%88%EA%B0%95%ED%8A%B8%20%EC%98%A4%EB%B8%8C%EC%A0%9D%ED%8A%B8.md#25-%ED%8D%BC%EB%B8%94%EB%A6%AD-%EC%83%81%EC%88%98%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%88%EC%84%B8%EC%9A%94)

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    }
이용 거리 초과에 따른 추가 요금 계산 되는 로직의 응집도가 떨어지는 것 같아요.
예를 들어 추가 요금이 변경되면 두 곳 모두 변경이 필요한 상태인데요. 

혹시 추가 요금 계산하는 공통 로직을 추상화 해보는 방향은 어떻게 생각하시나요?🤔🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    BASIC_SECTION(0, 10, 0, distance -> BASIC_SECTION_NO_SURCHARGE),
이 `enum` 클래스가 외부 패키지에서까지 사용될 필요가 없다고 생각되는데 
패키지 레벨에서의 캡슐화를 위해 접근제어자를 수정해보시는 방향은 어떻게 생각하시나요??🤔🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +            distance -> FIRST_SECTION_MAX_SURCHARGE + calculateSurchargeSecondSection(distance));
다양한 구간별을 `enum` 으로 케이스 정리를 잘해주신 것 같아요 👍👍👍

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/path/domain/Path.java
> +        farePolicy = MemberDiscountPolicy.of(farePolicy, loginMember);
이전에 코멘트 해드려서 아시겠지만
`path` 와 `fare` 도메인 영역이 양방향 의존성으로 생긴 것 같아요 🤔
혹시 이 부분을 수정해서 단방향으로 유지하는 방향은 어떠신가요??🤔🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/member/domain/Password.java
> +    public boolean isWrongPassword(String password) {
피드백을 수용해주셔서 감사합니다 🙇‍♂️

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private Fare surcharge;
`@Embedded` 설정이 누락된 것 같아요 😆

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/MemberDiscountPolicy.java
> +    }
이 부분 역시 내부적으로 양방향 의존성이 생긴 것 같아요.
접근제어를 통해 두 객체를 캡슐화를 시켜주거나 단방향을 유지해주는 방향은 어떻게 생각하시나요? 🤔🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/path/domain/Path.java
> +import nextstep.subway.fare.policy.MemberDiscountPolicy;
`path` 에게 요금 비즈니스 정책에 대해 너무 많고 강한 결합들이 추가된 것이 아닌가 라는 생각되는데  혹시 이부분에 대해서 어떻게 생각하시나요??🤔🤔
path 와 정책들을 활용하여 요금을 계산하는 또 다른 클래스에게 이러한 역할을 위임해주시는 방향은 어떠신가요?? 🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/path/domain/SectionEdge.java
> +    private final Section section;
외부 라이브러리를 확장하셔서 구간으로 구현을 해주셨네요 👍👍

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/MemberDiscount.java
> +    }
위와 동일하게 중복된 코드가 발생되는 것 같아요.
마찬가지로 추상화를 통해 중복이 제거되면 더 좋을 것 같아요 😆

2022-12-05 13:56 UTC, devyonghee commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTestFixture.java
> +    }
> 테스트 픽스쳐 구성 변경

테스트 픽스처를 별도로 분리해주셨네요 👍👍
그런데 제가 피드백을 드리고자 한 부분은 
생성자가 아닌 `Member.of("email@email.com", "password", 20)` 와 같이 중복적으로 사용되는 객체에 대해서 
메소드로 생성해놓고 재사용하는 방향에 대한 말씀이었습니다 😅
지금도 충분히 좋은 구조로 잘 작성해주셨고 개인적인 의견일 뿐이니 참고만 해주세요 🙇‍♂️

더 명확하게 예시 코드로 드리자면 해당 테스트 클래스 내부에 다음과 같은 메소드가 추가될 것 같습니다. 
```java 
private Member devyonghee() {
    return Member.of("devyonghee@gmail.com", "password", 20);
}
```

2022-12-05 13:56 UTC, devyonghee commented on src/test/java/nextstep/subway/favorite/service/FavoriteServiceTest.java
> +        given(stationService.findStationById(2L)).willReturn(arrivalStation);
> 그리고 Mock 테스트에서 stubing을 given 항목에 when을 사용해서 given으로 모두 변경했는데
이렇게 사용하는게 맞을까요 ? 이 부분도 궁금합니다.

테스트를 bdd 형식으로 잘 변경해주신 것 같습니다. 👍👍
개인적으로 두개 메소드의 동작은 동일하게 동작할텐데  
bdd 형식에서는 `given` 을 이용해주시는 방향이 더 명확하지 않을까 생각됩니다 🤔

2022-12-05 13:56 UTC, devyonghee commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> -        member.addFavorite(this);
> 서로 다른 도메인 간의 양방향 의존성 제거

서로 호출하고 있는 메소드만을 제거해주신 것 같은데 
아직 서로에 대한 의존성은 남아있는 것 같아요. 🤔🤔 

조금 더 명확하게 말씀을 드리자면 
현재 구조 상태에서는 `Member` 에서 `Favorite` 알지 못하도록 필드, 메서드 인자까지도 제거하면 단방향 의존성을 유지할 수 있을 것 같아요.

2022-12-05 14:19 UTC, crongcm commented on src/main/java/nextstep/subway/fare/policy/DistanceSurchargePolicy.java
> +    }
요금 정책을 중첩으로 처리하기 위해서 데코레이터 패턴을 사용했는데
구현하면서 결합도가 많이 생기는 느낌이 들긴 했습니다.
인터페이스를 바로 구현하는 방향으로 고민해보겠습니다.

2022-12-05 14:24 UTC, crongcm commented on src/main/java/nextstep/subway/fare/domain/Fare.java
> +    public static final int FIRST_SECTION_MAX_SURCHARGE = 800;
public으로 선언하여 다른 곳에서도 사용할 수 있을 수 있을까 생각하여 int로 선언했었습니다.
퍼블릭 상수는 사용하지 않도록 노력해보겠습니다.
말씀해주신 내용들 고민해보도록 하겠습니다.

2022-12-05 14:25 UTC, crongcm commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    }
응집도가 떨어지는 느낌이 들었는데 좀 더 고민해보겠습니다.

2022-12-05 14:30 UTC, crongcm commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTestFixture.java
> +    }
넵 의견 감사합니다

2022-12-05 16:29 UTC, crongcm commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    BASIC_SECTION(0, 10, 0, distance -> BASIC_SECTION_NO_SURCHARGE),
접근제어자에 대한 고민 아직 익숙치 않아서 놓치게 되네요..
변경하겠습니다 !

2022-12-05 18:46 UTC, crongcm commented
안녕하세요 용희님
응집도 의존성 .. 많이 어렵네요
추상화도 어렵고.. 음.. 최대한 고민해서 구현해봤는데 나아졌는지 모르겠네요..
피드백 최대한 적용하려고 노력했습니다.

많이 부족하네요.. 이번 리퀘스트에서 반영이 안된 부분이 있다면 조언 부탁드리겠습니다.

감사합니다 !

2022-12-06 16:48 UTC, devyonghee approved these changes
안녕하세요 창민님!!
마지막 단계까지 피드백 반영해주시느라 정말 고생 많으셨습니다 🙇‍♂️🙇‍♂️
요금 정책에 따라 계산하는 과정과 양방향 의존성에 대해서 어려움이 많으셨을 것 같아요 😅

그래도 창민님께서 코드를 잘 구현해주셔서 코드가 깔끔하게 유지된 것 같아요 👍👍👍
추가적으로도 아주 소소한 코멘트들 남겨드렸습니다!

인수 테스트 기반 TDD 진행하시느라 정말 고생 많으셨고
남은 미션도 잘 마무리 하셔서 꼭 좋은 결과 있으셨으면 좋겠습니다 😆👍

2022-12-06 16:48 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    }
추상화를 잘해주신 것 같아요!!👍

2022-12-06 16:48 UTC, devyonghee commented on src/main/java/nextstep/subway/member/domain/Member.java
> -    private Favorites favorites;
의존성을 잘 제거해주셔서 단방향이 된 것 같아요 👍👍👍

2022-12-06 16:48 UTC, devyonghee commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    private Long memberId;
직접 참조에서 간접 참조로 변경까지 해주셨네요 👍👍👍

2022-12-06 16:48 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/FarePolicy.java
> +    }
추상화를 제거해주시고 콘크리트 클래스로 활용해주셨군요 👍
코드의 의미가 더 명확해진 것 같아요😆

2022-12-06 16:48 UTC, devyonghee commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    SECOND_SECTION(51, Integer.MAX_VALUE, 8, 800, DistanceSurcharge::calculateSurcharge);
`FIRST_SECTION` 을 이용해서 나오는 가격인 800 원이라는 가격이 인라인으로 작성되어 있는데요.
`enum`에서는 먼저 선언한 요소에 대해서는 필드값을 활용할 수 있으니 
응집도를 위해 `FIRST_SECTION` 의 값을 통해서 가격을 계산하는 것도 좋은 방법이 될 수 있을 것 같아요🤔

2022-12-06 16:48 UTC, merged

2022-12-06 23:28 UTC, crongcm commented on src/main/java/nextstep/subway/fare/policy/DistanceSurcharge.java
> +    SECOND_SECTION(51, Integer.MAX_VALUE, 8, 800, DistanceSurcharge::calculateSurcharge);
해당 방법 고민해보겠습니다
감사합니다 !