Step4 요금조회PR 요청드립니다
next-step/atdd-subway-service pull request #857
Opened 2022-12-06 09:25 UTC by chunhodong

2022-12-06 16:16 UTC, heowc requested changes
안녕하세요~ 벌써 해당 미션에 마지막 단계이네요 🙇 

마지막 단계인 만큼 소소한(?) 피드백을 드려보았습니다.
궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/AgePolicy.java
> +    CHILD(6, 13, 350, 0.5),
0세 이상 ~ 6세 미만의 사람은 어떻게 처리 되나요 ? 🤔 
현재로는 예외가 발생하는데 그게 자연스러운 것인지 고민해보면 좋을 것 같아요 👍

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/DistancePolicy.java
> +    BASE(0, 10, distance -> distance / ( distance + 1 ) ),
추가 요금이 없다면, 아무 계산 없이 0을 반환해도 되지 않을까요?

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/DistanceFare.java
> +public class DistanceFare {
어떤 이유로 해당 클래스가 생겼는지 궁금합니다 🤔 
거리별 요금 정책에 대한 금액을 표시 하기 위함이라면, 기본 운임은 해당 클래스에서 가지고 있어야 하지 않을까 싶어서요~
또한, 노선별 추가 요금과 기본 운임을 더한 값을 전달 받는 것이 다소 어색한 것 같습니다 🤔 

어떻게 생각하시나요?

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +    public Line findMaxFareLineByStations(List<Station> stations) {
가장 비싼 노선별 추가 요금이라면 반환이 fare가 되는것이 더 자연스럽지 않을까요 ? 🤔

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/path/domain/PathResult.java
> +public class PathResult {
해당 클래스는 어떤 의미로 추가되었을까요 🤔

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        return new PathResponse(stations, distance, findFare(line, distance, age));
비지니스 로직이 서비스 레이어에 추가된 것 같아요~
이를 어떻게 하면 도메인 레이어로 옮길 수 있을까요?

조금 힌트를 드려보자면 jgrapht를 이용하면 경로에 대한 많은 정보를 얻을 수 있습니다. 
이를 한 객체에 모아 전달 받는다면, 그것을 도메인으로 만들 수 있지 않을까요? 🤔

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    private int findFare(Line line, int distance, int age) {
금액을 찾는 것이 아니라 계산하는 것이기 때문에 보다 의미 있는 네이밍이면 좋을 것 같습니다 🤔

2022-12-06 16:16 UTC, heowc commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findShortestPath(sourceId, targetId, loginMember.getAge()));
로그인한 사용자만 나이에 대한 운임 계산이 가능한데요~
이에 대한 예외처리가 누락된 것 같습니다. 확인 부탁드려요 🤔

2022-12-06 16:16 UTC, heowc commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> -        ExtractableResponse<Response> response = 최단_경로_조회_요청(강남역.getId(), 남부터미널역.getId());
하나의 테스트에 너무 많은 것을 테스트하고 있는 것 같습니다. 이를 분리해보는 것은 어떨까요 ? 🤔

2022-12-07 05:30 UTC, chunhodong commented on src/main/java/nextstep/subway/fare/domain/AgePolicy.java
> +    CHILD(6, 13, 350, 0.5),
일단 0에서 6세까지는 별도로 KIDS라는 enum을 추가한다음에 운임료는 0을반환하게했습니다

2022-12-07 05:30 UTC, chunhodong commented on src/main/java/nextstep/subway/fare/domain/DistancePolicy.java
> +    BASE(0, 10, distance -> distance / ( distance + 1 ) ),
맞습니다 오히려 더 눈에 잘읽히는거같아요 수정했습니다 :)

2022-12-07 05:32 UTC, chunhodong commented on src/main/java/nextstep/subway/fare/domain/DistanceFare.java
> +public class DistanceFare {
제가 완전 잘못생각한거같습니다 원철님 생각이 맞습니다..DistanceFare는 거리별 요금을 계산하기위해 추가했는데
기본요금은 다른 클래스에가있고...요금계산하는데 필요없는 파라미터를 받고있고..ㅎㅎ 
사실 이번 과제는 너무 급하게해서 아예 다시한다는 생각으로 만들어봤습니다ㅠㅠ

2022-12-07 05:33 UTC, chunhodong commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        return new PathResponse(stations, distance, findFare(line, distance, age));
거리정보를 가지고있는 ShortestPath클래스와 요금을계산하는 FareCalculator클래스를 만들어서 해결해봤습니다 :)

2022-12-07 05:34 UTC, chunhodong commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> -        ExtractableResponse<Response> response = 최단_경로_조회_요청(강남역.getId(), 남부터미널역.getId());
이 부분은 궁금한테 분리라는게 어떤걸 기준으로 분리해야되는지 어렵습니다ㅜㅜ 일단 저는 나이별로 구분했는데 다른 방법이 있을까요...??

2022-12-07 05:36 UTC, chunhodong commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    private int findFare(Line line, int distance, int age) {
수정했습니다 감사합니다 :)

2022-12-07 06:01 UTC, chunhodong commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findShortestPath(sourceId, targetId, loginMember.getAge()));
로그인안한경우 나이를 null값으로하고 성인요금으로 정책을 부여해서 할인해택을 못받게해봤습니다!

2022-12-07 06:06 UTC, heowc commented on src/test/java/nextstep/subway/path/acceptance/PathAcceptanceTest.java
> -        ExtractableResponse<Response> response = 최단_경로_조회_요청(강남역.getId(), 남부터미널역.getId());
테스트를 작성시 given/when/then으로 나눠볼 수 있을 것 같은데요.
이것들은 별도의 테스트 단위로 가져갈 수 있다면, 좋을 것 같습니다!

2022-12-07 13:02 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/DistanceFare.java
> +public class DistanceFare {
기존보디 훨씬 읽기 쉬워진 것 같습니다  👍

2022-12-07 13:37 UTC, heowc requested changes
머지하려고 했으나 아직 요구사항이 충족되지 않아 한번 확인 해주셨으면 해서 request changes 드렸습니다.

비로그인에 대한 검증을 한번더 확안해주셨으면 좋겠어요~

궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-12-07 13:37 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public FareCalculator(Lines lines, ShortestPath shortestPath, AgePolicy agePolicy) {
요금 계산기가 너무 많은 것을 참조하고 있는 것 같아요. 계산시에 필요한 정보만 넘긴다면 보다 간단해질 수 있을 것 같아요~ 👍

2022-12-07 13:37 UTC, heowc commented on src/main/java/nextstep/subway/path/domain/ShortestPath.java
> +public class ShortestPath {
경로를 의미하는 클래스를 만들어주셨네요 👍

2022-12-07 13:37 UTC, heowc commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findShortestPath(sourceId, targetId, loginMember.getAge()));
`@AuthenticationPrincipal LoginMember loginMember`는 항상 토큰이 있어야 가능한 부분인데 어떻게 해결하셨을까요?

2022-12-07 13:38 UTC, heowc commented on src/main/java/nextstep/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findShortestPath(sourceId, targetId, loginMember.getAge()));
관련해서 테스트도 추가해주시면 더 좋을 것 같습니다 👍

2022-12-07 16:08 UTC, chunhodong commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public FareCalculator(Lines lines, ShortestPath shortestPath, AgePolicy agePolicy) {
궁금한점이 있습니다! 피드백을 기반으로 생성자를
public FareCalculator(int lineFare, int distanceFare, AgePolicy agePolicy) 
이런식으로 바로 요금을 받아서 getCalculcate메소드에서 요금을 바로 이용할수 있게 수정해봤습니다.

그런데 위에 방식대로 수정하면 lineFare,distanceFare값을 만들기위해 
PathService의 findShortestPath메소드에서 lineFare와 distanceFare값을 구하기위한 로직이 들어가거든요
이걸 비즈니스로직으로 봐야할까요..?? 개념적인 부분에서 헷갈리는거같습니다ㅠ

2022-12-07 16:16 UTC, zerodkdj commented on src/main/java/nextstep/subway/path/domain/ShortestPath.java
> +public class ShortestPath {
피드백 받아서 수정했습니다 감사합니다^^
그리고 위에서 다른 피드백주신부분 테스트나누는 부분이랑 비회원부분 예외처리하는방법도 수정해봤습니다.

그런데 궁금한점이 비회원에대한 예외처리를 토큰값이 없을때는 나이대별 할인요금을 적용하지 않는 방식으로 했는데
맞는건가요?? 비로그인 검증이라고 하신부분이 예외반환하고 그걸 테스트해야되는지 아니면 제가 수정한 방식처럼
연령대별 할인요금을 아예적용안하는건지 헷갈립니다

2022-12-08 13:07 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public FareCalculator(Lines lines, ShortestPath shortestPath, AgePolicy agePolicy) {
제 짧은 생각으로 말씀을 드려보자면 어떠한 행위를 클래스를 만드는 것보다는 도메인 안에서 행위를 메소드로 만드는 것은 어떨까 싶습니다.
예를 들면, 지금은 계산하는 행위를 계산기(?)로 만들었지만, (지금 있는 클래스로 예를 들어보자면) ShortestPath에서 calculateFare 같은 메소드를 만드는 것입니다.

어떻게 생각하시나요 ?! 🤔

2022-12-08 13:09 UTC, heowc commented on src/main/java/nextstep/subway/path/domain/ShortestPath.java
> +public class ShortestPath {
> 그런데 궁금한점이 비회원에대한 예외처리를 토큰값이 없을때는 나이대별 할인요금을 적용하지 않는 방식으로 했는데
맞는건가요?? 

넵 맞습니당~

2022-12-08 13:11 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    public FareCalculator(Lines lines, ShortestPath shortestPath, AgePolicy agePolicy) {
지금은 `ShortestPath` 에서 참조하고 있는 것이 많으나 그걸 활용하지 않고 외부 객체? 값을 참조해서 라고 생각이 들어요.
보다 힌트를 들여보자면, `GraphPath`, `DefaultWeightedEdge` 등을 보다 활용해본다면 최단 거리에 대한 역들을 뿐만 아니라 지나간 구간들 호선들 역시 알 수 있습니다 👍

2022-12-08 13:16 UTC, heowc approved these changes
두번째 피드백까지 고생 많으셨습니다 👍 

이번 미션은 여기서 마무리하도록 하겠습니다.
미션을 통해 배움이 있으셨다면 다행입니다 🙏 

다음 미션을 진행해주세요~

2022-12-08 13:16 UTC, heowc commented on src/main/java/nextstep/subway/fare/domain/AgePolicy.java
> +            return ADULT;
빈 값일때 `ADULT` 보다는 `NONE` 같은 보다 명확한 타입을 두는건 어땠을까요!? 🤔

2022-12-08 13:16 UTC, merged