[yeojiin(임정연)] - 4단계 요금 조회
next-step/atdd-subway-service pull request #879
Opened 2022-12-09 04:47 UTC by yeojiin

안녕하세요~ 우빈님!
벌써 마지막 단계네요!
4단계 미션은 기존 걸 리펙토링 하는 부분도 까다롭고, 기능 구현 자체도 쉽지 않았던 거 같아요.😂
여러 케이스를 고려하다보니 만들었다가 뒤로 돌아가는 상황도 꽤나 빈번했던 것 같습니다.
특히, get를 추가하지 않아 reqeust 부분에서 값이 세팅이 안 되는 부분 때문에 꽤 오랜 시간 고생했네요😅
기본기를 더 탄탄히 공부해야겠어요!
그리고 exception부분은 피드백 주신대로 좀 더 간결히 정리해보았습니다!

이번 미션은 여려모로 쉽지않고, 남들보다 뒤쳐진다는 느낌을 계속 받게하는 미션이었는데
우빈님이 정말정말 꼼꼼히 피드백해주시고, 세세한 것도 놓치지 않고 잡아주셔서 정말 도움이 많이 됐습니다.
피드백을 받으며 반성도 많이 하고 정말 많이 배워갑니다.🙇‍♀️

날이 또 쌀쌀헤진다고 하니 감기 조심하시고, 독감과 함께 과제중인데 정말 아프네요😂
우빈님은 독감 걸리지 않게 건강 잘 챙기시길 바랍니다!
마지막 미션도 잘 부탁드려요~
정말 감사합니다!🙏

2022-12-10 02:16 UTC, limwoobin requested changes
안녕하세요 정연님
4단계 미션 잘 진행해주셨네요 👍👍
독감에 걸리셨다니 컨디션이 좋지않으실것같은데 와중에도 미션하느라 너무 고생많으십니다ㅠ

미션에 대해서는 몇가지 코멘트를 남겨놓았으니 다시 한번 확인부탁드립니다.
추가로 커밋로그가 한번에 다 딸려서 올라온것같네요 
이미 pr이 올라왔으니 어쩔수없지만 왜 같이올라왔는지 정도는 한번 보시면 좋을듯 합니다 ㅎㅎ
코멘트 확인하시고 다시 요청부탁드립니다 조금만 더 화이팅입니다!

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/AgeFarePolicy.java
> +    }
해당 예외가 발생할 케이스가 있을까요??
기본요금이 보장되어있는 상태라 없어도 되지않을까 싶습니다 ㅎㅎ

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/OverFarePolicy.java
> +public enum OverFarePolicy {
거리에 대한 운임이니 Distance 가 들어가는 이름을 쓰는건 어떨까요??

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/OverFarePolicy.java
> +    }
여기도 구간별 메소드를 따는것보다는 age를 계산했던것과 같이 이동거리 값을 주어서
계산하는건 어떨까요??

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private LineFare fare;
구간 추가요금에 대해서 객체로 래핑해주셧군요 ㅎㅎ 좋네요

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +public class Lines {
노선의 추가구간요금중 가장 비싼 요금을 찾으려는 목적으로 만드신걸까요??

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
구간은 노선을 가지고있으니 `Lines` 객체 없이 간단하게 바로 응답을 주어도 될것같기도 하네요 ㅎㅎ
추가로 노선은 구간을 가지고있는데 filter조건에서 또 필터링을 하신 이유가 있을까요??

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    private int minLineFare;
혹시 변수명이 minLineFare인 이유가 있을까요??
요구사항은 노선중 가장 높은 추가요금일텐데 이름이 맞지 않는것같아서요 ㅎㅎ

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        PathFinder pathFinder = PathFinder.from(sections.getSections());
노선은 Sections, Stations 모두 가지고있으니
구간목록을 던지는것보만 모든 노선을 던지는게 맞지 않을까요??

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/path/application/PathService.java
>      }
여기도 요금계산을 위해선 구간정보만 있음 될것같은데 개선에 대해 고민해보심이 좋겟네요 ㅎㅎ

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        PathFinder pathFinder = PathFinder.from(sections.getSections());
추가로 비회원인 경우 요금계산은 어떻게 되는걸까요??

2022-12-10 02:16 UTC, limwoobin commented on src/main/java/nextstep/subway/path/dto/PathResponse.java
>      }
Station객체를 response 객체로 컨버팅하는거는 method extract 혹은 변수로 한번 빼는건 어떨까요??
뎁스가 깊어지면 가독성에는 좋지않다고 생각되서요 ㅎㅎ

2022-12-10 02:16 UTC, limwoobin commented on src/test/java/nextstep/subway/auth/acceptance/AuthAcceptanceStepTest.java
> +}
액션에 대해 잘 분리해주셨네요 ㅎㅎ

2022-12-10 02:16 UTC, limwoobin commented on src/test/java/nextstep/subway/fare/domain/AgeFarePolicyTest.java
> +class AgeFarePolicyTest {
단위테스트 잘 작성해주셧네요 ㅎㅎ

2022-12-10 02:16 UTC, limwoobin commented on src/test/java/nextstep/subway/fare/domain/AgeFarePolicyTest.java
> +    void discount(int input, int expected) {
input 보다는 age가 더 좋을것같아요

2022-12-10 02:16 UTC, limwoobin commented on src/test/java/nextstep/subway/fare/domain/AgeFarePolicyTest.java
> +    @DisplayName("연령별 요금할인을 적용한다.")
DisplayName 은 추상적인것보단 명시적인게 좋다고 생각들어요 한눈에 어느기능을 검증하는건지 파악되는게 중요하다고 생각하기때문인데요 ㅎㅎ
예를들면 아래와 같은 방법은 어떨까요??
ex) `청소년이라면 요금에서 350원 공제 후 20% 할인된 가격이 계산되어야한다` 와 같은 방법입니다
한번 보시고 의견부탁드릴게요!

2022-12-11 23:23 UTC, yeojiin commented on src/main/java/nextstep/subway/fare/domain/AgeFarePolicy.java
> +    }
기본 요금이 보장 되어 있는 부분을 놓쳤네요😅

2022-12-11 23:26 UTC, yeojiin commented on src/main/java/nextstep/subway/fare/domain/OverFarePolicy.java
> +public enum OverFarePolicy {
상세 내용이 distance로 사용되는 부분이 훨씬 많은 거 같네요~ 수정했습니다!

2022-12-12 00:39 UTC, yeojiin commented on src/main/java/nextstep/subway/fare/domain/FareCalculator.java
> +    private int minLineFare;
기본요금으로 생각하고 만든 변수명이라 minLineFare로 지정했습나다! 해당 부분은 좀 더 명시적으로 baseFare로 변경하겠습니다!

2022-12-12 00:49 UTC, yeojiin commented on src/test/java/nextstep/subway/fare/domain/AgeFarePolicyTest.java
> +    @DisplayName("연령별 요금할인을 적용한다.")
명칭은 명시적인게 테스트에 훨씬 도움이 되는 거 같습니다! 
한가지 궁금한 부분은 제가 `@CsvSource` 를 이용해 테스트를 분리하지 않았는데 이 경우에는
ex)`청소년이라면 요금에서 350원을 공제 후 20% 할인된 금액이 발생하고, 어린이라면 요금에서 350원을 공제 후 50% 할인된 금액이 발생한다.`
와 같이 길게 작성해도 무방할까요?

2022-12-12 01:05 UTC, yeojiin commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +public class Lines {
넵 해당 부분을 다르게 리펙토링할 수 있을까요?

2022-12-12 04:19 UTC, yeojiin commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
다시 생각해보니 해당 구간들 중 가장 높은 금액을 찾으면 되기 때문에 필터 없이 찾아도 되겠네요!

2022-12-12 04:41 UTC, yeojiin commented on src/main/java/nextstep/subway/path/application/PathService.java
>      }
해당 부분 사고를 확장하는데 어려움이 있었습니다만 피드백주신대로 Lines 없이 리펙토링 해보았습니다. 객체 안에 객체가 있는데 사고의 범위가 넓어지는데 큰 도움이 되었습니다.🙏

2022-12-12 04:55 UTC, yeojiin commented on src/main/java/nextstep/subway/line/domain/Lines.java
> +public class Lines {
해당 부분은 `Sections`로 책임을 넘겼습니다!

2022-12-12 05:22 UTC, yeojiin commented on src/main/java/nextstep/subway/fare/domain/OverFarePolicy.java
> +    }
해당 부분도 수정했습니다! 같은 구조네요😂

2022-12-12 07:54 UTC, yeojiin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        PathFinder pathFinder = PathFinder.from(sections.getSections());
비회원의 경우에는 성인으로 간주하고 할인 없이 계산되도록 수정했습니다.

다만, PathFinder에서 구간이 아닌 전체 노선을 던지도록 리팩토링 해보았는데 그러면 `Sections`내부에서 `List<Section> sections`를 파라미터로 받아 Sections를 리턴해주는 방식으로 구현해야할 거 같은데 이 부분을 좀 더 간결히 정리할 수 있는 부분이 있을 까요?😥

2022-12-12 07:58 UTC, yeojiin commented on src/main/java/nextstep/subway/path/dto/PathResponse.java
>      }
가독성을 위해 메서드를  분리했습니다!

2022-12-12 08:00 UTC, yeojiin commented
> 안녕하세요 정연님 4단계 미션 잘 진행해주셨네요 👍👍 독감에 걸리셨다니 컨디션이 좋지않으실것같은데 와중에도 미션하느라 너무 고생많으십니다ㅠ
> 
> 미션에 대해서는 몇가지 코멘트를 남겨놓았으니 다시 한번 확인부탁드립니다. 추가로 커밋로그가 한번에 다 딸려서 올라온것같네요 이미 pr이 올라왔으니 어쩔수없지만 왜 같이올라왔는지 정도는 한번 보시면 좋을듯 합니다 ㅎㅎ 코멘트 확인하시고 다시 요청부탁드립니다 조금만 더 화이팅입니다!

step4로 작업을 했는데 PR요청시 conflict가 해결이 되지 않아 rebase 후 step4-1을 생성해 step4를 땡겨 PR요청을 했더니 커밋 로그가 한번에 올라간 것 같습니다.😢

2022-12-12 12:45 UTC, limwoobin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +        PathFinder pathFinder = PathFinder.from(sections.getSections());
@yeojiin 
Line목록을 던진 후 PathFinder내부에서 getSections()를 이용해 구간목록을 가져와 경로에 등록하는걸 말씀드렸어요
Line <-> Sections는 연관관계가 맺어져있어 Line만 있어도 lazy loading으로 가져오는걸 의도했습니다 ㅎㅎ
혹시라도 제 답변이 질문하신 의도와 다르다면 다시 말씀부탁드려요!
아니면  dm으로 주셔도 괜찮습니다 ㅎㅎ

2022-12-14 01:06 UTC, limwoobin commented on src/test/java/nextstep/subway/fare/domain/AgeFarePolicyTest.java
> +    @DisplayName("연령별 요금할인을 적용한다.")
의도만 잘 전달된다면 약간은 길어도 저는 그렇게 작성하는편이긴합니다!

2022-12-14 01:20 UTC, limwoobin approved these changes
안녕하세요 정연님
마지막 단계도 잘 수행해주셨습니다 👍👍👍
피드백 반영도 잘해주셧고 인수테스트, 도메인테스트도 모두 정말 꼼꼼하게 작성해주셧네요
커밋로그를 보니 TDD를 계속 의식해 고민하면서 작성하신것이 느껴졌습니다!

정말 고생많으셨습니다
남은 미션도 모두 잘 완주해내시길 기원하겠습니다 :)

2022-12-14 01:20 UTC, limwoobin commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        // Lines 조회 분리하지 않고, 구간에서 바로 Line 찾고 LineFare 찾기
주석은 제거해주셔도 좋을거같아요 ㅎㅎ

2022-12-14 01:20 UTC, limwoobin commented on src/main/java/nextstep/subway/member/ui/MemberController.java
> +    @PostMapping("")
`@PostMapping` 으로만 써도 되겟네요 ㅎㅎ

2022-12-14 01:20 UTC, limwoobin commented on src/main/java/nextstep/subway/path/application/PathService.java
> +    }
service에서 sections를 모두 추출하고 넣으시는군요 ㅎㅎ
제 의도는 lines 를 그대로 넘겨서 PathFinder내부에서 getSections를 사용해 구간을 가져오는방법으로 
말씀드렷엇습니다 ㅎㅎ
영속성컨텍스트를 이용한 방법을 제안드린거였는데 이 방법도 좋은방법으로 보여지네요 ㅎㅎ

2022-12-14 01:21 UTC, merged