Step3 - 인증을 통한 기능 구현
next-step/atdd-subway-service pull request #917
Opened 2022-12-21 16:08 UTC by iamsojung

안녕하세요!

2단계 리뷰하면서 빈에 대해 공부를 많이 하게 되었습니다.!
3단계도 리뷰 부탁드립니다

감사합니다!!🙇‍♂️

2022-12-22 09:28 UTC, seokhongkim requested changes
소정님 3단계 미션 잘 구현해주셨습니다. 👍 
인증이 실패했을 때 예외 처리하는 부분과 인수 테스트에서 검증하는 부분에 조금 수정할 필요가 있는 것으로 보여 코멘트 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-12-22 09:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +@Transactional(readOnly = true)
클래스에 설정한 트랜잭션의 readOnly 설정을 true 로 하신 이유가 있을까요?

2022-12-22 09:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        favoriteRepository.deleteById(favoriteId);
존재하지 않는 즐겨찾기를 삭제하려고 하거나, 다른 사용자의 즐겨찾기를 삭제하려고 하는 경우에 대한 방어로직도 추가해보시면 좋겠습니다. :)

2022-12-22 09:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/favorite/dto/FavoriteResponse.java
> +    public static List<FavoriteResponse> toList(List<Favorite> favorites) {
`FavoriteResponse.toList()`라는 메서드명만 봤을 때는 생성을 하거나 타입을 변경하는 메서드로 보이지는 않는 것 같아요.
기능을 잘 설명해줄 수 있는 이름으로 변경해보면 어떨까요?

2022-12-22 09:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/auth/application/AuthService.java
>  public class AuthService {
유효하지 않은 사용자일 때는 인증에 실패하도록 구현이 필요해 보이네요!

2022-12-22 09:28 UTC, seokhongkim commented on src/test/java/nextstep/subway/member/MemberAcceptanceTest.java
> +        assertThat(내_회원_정보_조회_응답.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
권한이 없는 경우라면 401 응답이 오는지 확인해봐야 할 것 같아요!

2022-12-22 09:28 UTC, seokhongkim commented on src/test/java/nextstep/subway/auth/acceptance/AuthAcceptanceTest.java
>  public class AuthAcceptanceTest extends AcceptanceTest {
꼼꼼한 인수테스트 작성 좋습니다. 👍 
`Favorite`, `AuthService`에 대한 단위 테스트도 만들어서 작은 단위의 동작에 대한 검증도 해보셔도 좋겠습니다. :)

2022-12-22 09:28 UTC, seokhongkim commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
>  public class FavoriteAcceptanceTest extends AcceptanceTest {
`favorite`, `member`도 인수 테스트 패키지를 `acceptance`로 옮기면 어떨까요?

2022-12-23 02:08 UTC, iamsojung commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
>  public class FavoriteAcceptanceTest extends AcceptanceTest {
넵!

2022-12-23 03:20 UTC, iamsojung commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +@Transactional(readOnly = true)
읽기 전용이라는 것을 명시적으로 알 수도 있고, 읽기 전용으로 하면 메모리 최적화에도 도움된다고 알고 있습니다..! 거의 습관적으로 쓰는 것 같습니다

2022-12-23 03:21 UTC, iamsojung commented
안녕하세요!

피드백 주신부분 수정했습니다.
확인 부탁드립니다.
감사합니다!

2022-12-23 03:21 UTC, iamsojung commented on src/test/java/nextstep/subway/auth/acceptance/AuthAcceptanceTest.java
>  public class AuthAcceptanceTest extends AcceptanceTest {
넵 만들었습니다.

2022-12-23 03:21 UTC, iamsojung commented on src/test/java/nextstep/subway/favorite/FavoriteAcceptanceTest.java
>  public class FavoriteAcceptanceTest extends AcceptanceTest {
옮겼습니다!

2022-12-23 03:22 UTC, iamsojung commented on src/test/java/nextstep/subway/member/MemberAcceptanceTest.java
> +        assertThat(내_회원_정보_조회_응답.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
로직 구현을 안해서 추가했습니다!!!

2022-12-23 03:22 UTC, iamsojung commented on src/main/java/nextstep/subway/favorite/dto/FavoriteResponse.java
> +    public static List<FavoriteResponse> toList(List<Favorite> favorites) {
이름이 항상 고민인 것 같습니다.. 혹시 석홍님만의 이름 짓는 방법?있으신가요..!

2022-12-23 11:26 UTC, seokhongkim commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +@Transactional(readOnly = true)
말씀하신 것처럼 읽기 전용을 적절하게 사용하면 성능상의 이점이 있습니다. :)
정답은 없지만, 저는 클래스의 transactional 설정은 readOnly = false 를 사용하는데요. 이유는 아래와 같습니다.

* 클래스의 설정을 `readOnly = true` 로 하고, 메서드에서 `transactional(readOnly = false)` 오버라이드 하는 경우 메서드에 설정이 잘 되었음을 테스트에서 확인하기 어렵습니다. 즉, 개발자 또는 리뷰어가 놓치는 상황이 발생할 수 있습니다.
  * 코드에서 데이터를 수정하는 작업이 발생하는지에 대한 검증은 단위테스트와 통합테스트를 통해 검증이 상대적으로 용이합니다. 그러나 트랜잭션 설정이 잘 되었는지에 대한 테스트는 상대적으로 어렵고 놓치기 쉽습니다.
* readOnly 설정을 DB replication 과 함께 사용하여 writer/reader 를 구분하는 목적으로 사용할 수 있는데, readOnly = true 가 기본인 경우 쓰기 요청이 읽기 DB로 전달되어 장애 상황이 발생할 수 있습니다. 반면, 읽기 전용으로 설정해야 하는 작업이 쓰기 DB로 전달되는 경우 부하는 늘어날 수 있으나 당장 장애 상황으로 이어지지는 않습니다.

위 내용도 한 번 같이 고민해보시면 도움이 될 것 같습니다. :)

2022-12-23 12:43 UTC, seokhongkim commented on src/main/java/nextstep/subway/favorite/dto/FavoriteResponse.java
> +    public static List<FavoriteResponse> toList(List<Favorite> favorites) {
저도 이름 짓는 게 항상 어렵더라구요. 😢 
개인적으로는 이름을 작성한 후 한글로 읽어본 후, 기능을 잘 설명하는지 고민해봅니다. (이름만 보고 무슨 기능을 하는지 예측이 되는지 확인)
이외에 비슷한 행위를 하는 메서드에는 주로 사용하는 이름(e.g., `compareTo`, `validate~`, `map`, `of`, `from`, `find~`, `get~`)이 생기기도 하더라구요. :)

2022-12-23 12:46 UTC, seokhongkim approved these changes
소정님, 3단계 미션 코멘트 잘 반영해주셨습니다. 👍 
3단계 PR도 머지하겠습니다.
코멘트 남긴 내용은 다음 단계 미션 진행하실 때 함께 고민해보셔도 좋겠습니다.
4단계 미션에서 뵙겠습니다. 😀

2022-12-23 12:46 UTC, seokhongkim commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +        return memberRepository.findById(id).orElseThrow(() -> new EntityNotFoundException("회원이 존재하지 않습니다"));
예외 메시지에 요청으로 들어온 값을 함께 포함하고 로그를 남기면 문제 상황이 발생했을 때 원인을 찾는데 도움이 될 것 같습니다. :)

2022-12-23 12:46 UTC, seokhongkim commented on src/test/java/nextstep/subway/favorite/domain/FavoriteTest.java
> +    void add_favorite() {
즐겨찾기 생성이 실패하는 경우(e.g., 출발역과 도착역이 같은 경우)도 테스트를 추가해보셔도 좋겠습니다.

2022-12-23 12:46 UTC, merged