Step3 : 인증을 통한 기능 구현
next-step/atdd-subway-service pull request #93
Opened 2021-01-17 08:39 UTC by nawhew

지난번 질문 답변이 많은 도움이 되었습니다!
이번 코드리뷰도 잘 부탁드립니다 :)

2021-01-17 14:51 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +    public Long addFavorite(Long id, FavoriteRequest favoriteRequest) {
크게 중요한 부분은 아니지만

member의 아이디인지 어떤 아이디인지 명확히 파라미터로 알 수 있으면 좋을것 같아요.

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +        this.memberRepository.flush();
flush 보다는 save를 호출하면 어떨까요?

`flush` 보다 `save`가 메소드의 목적에 더 맞는 키워드지 않을까 싶어요

```suggestion
        this.memberRepository.save(member);
```

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +                .findAny().orElseThrow(IllegalArgumentException::new);
FavoriteRepository가 아닌 Member를 이용해 Favorite을 관리하시려는거군요

Stream이 길어져 가독성이 조금 떨어지는 것 같은데 Member에 원하는 Favorite을 찾아올 수 있는 메소드를 만들거나 하면 어떨까요?

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +        member.deleteFavorite(favorite);
아이디를 넘겨서 member 내부에서 바로 즐겨찾기 삭제 및 예외처리를 진행하는건 어떨까요?

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
`Favorite`를 통해 `Member`를 조회하는 케이스는 없는 것 같아요, LAZY로 설정하면 어떨까요?

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    public Member getMember() {
file change에는 getMember를 사용하는곳이 확인되지 않는데 불필요하다면 삭제하면 어떨까요?

2021-01-17 14:51 UTC, kyucumber commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +                .findAny().orElseThrow(IllegalArgumentException::new);
Member 내부에서 지우려는 타겟 Favorite를 찾지 못한 경우 내 즐겨찾기가 아닌 다른 사람의 즐겨찾기를 지우려고 시도한 케이스일 것 같아요.

"다른 사람의 즐겨찾기는 삭제할 수 없습니다" 등 메세지를 따로 남겨주면 어떨까요?

2021-01-17 15:41 UTC, nawhew commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +                .findAny().orElseThrow(IllegalArgumentException::new);
Favorites로 로직을 이동시켰습니다!

2021-01-17 15:41 UTC, nawhew commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +        member.deleteFavorite(favorite);
Favorites로 로직을 이동시켰습니다.

2021-01-17 15:54 UTC, nawhew commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +    public Long addFavorite(Long id, FavoriteRequest favoriteRequest) {
넵 변경하였습니다~

2021-01-17 16:12 UTC, nawhew commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    public Member getMember() {
getter를 다 만들던 습관때문에 불필요한 메소드를 만들었습니다..
삭제하였습니다~

2021-01-17 16:12 UTC, nawhew commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +                .findAny().orElseThrow(IllegalArgumentException::new);
오류 메세지들을 추가하였습니다!

2021-01-17 16:13 UTC, nawhew commented on src/main/java/nextstep/subway/member/domain/Favorite.java
> +    @ManyToOne(cascade = CascadeType.PERSIST)
네 변경하였습니다

2021-01-17 16:28 UTC, nawhew commented on src/main/java/nextstep/subway/member/application/FavoriteService.java
> +        this.memberRepository.flush();
아직 JPA에 대한 이해가 부족하여
FavoriteServiceTest 부분에서 지연로딩으로 인해서 오류가 발생하여, 해당 테스트 쪽에 @Transactional을 사용하였는데,
이 과정에서 해당 부분을 save하니 값이 getFavorites()의 사이즈 체크 부분이 사이즈가 2가 나와서 flush로 변경하였었습니다...
해당 부분 및 테스트 부분을 수정하였습니다.

2021-01-18 13:07 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다~

다음 단계 진행을 위해 머지할게요

2021-01-18 13:07 UTC, merged