[ATDD2] Step3 인증을 통한 기능 구현 PR
next-step/atdd-subway-service pull request #95
Opened 2021-01-17 15:21 UTC by shk3029

안녕하세요~ 
저번 리뷰 피드백 반영 및 Step3 기능 구현하였습니다
코드 리뷰를 통해 많은 도움이 되네요!
이번에도 잘 부탁드립니다!
감사합니다!

2021-01-18 12:20 UTC, hongsii requested changes
3단계 요구사항 구현을 깔끔하게 잘 해주셨네요! 👍 
간단한 피드백 몇가지 남겼으니 확인하셔서 반영해주세요!

2021-01-18 12:20 UTC, hongsii commented on src/test/java/nextstep/subway/utils/AuthRestAssuredTestUtils.java
> +public class AuthRestAssuredTestUtils {
👍

2021-01-18 12:20 UTC, hongsii commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +@Transactional
`@Transactional(readOnly = true)` 사용 시 더티 체킹이 수행되지 않아 조금이나마 성능 향상이 가능합니다.
추가로 더티 체킹이 발생하지 않으므로 엔티티 핸들링 과정에서 실수로 발생할 수 있는 변경을 막을 수 있습니다.

그래서 저는 클래스 레벨에 `@Transactional(readOnly = true)` 을 사용해 기본적으론 읽기 전용 트랜잭션을 사용하고, 변경이 필요한 시점에만 명시적으로 `@Transactional` 을 붙여 줍니다.

``` java
@Transactional(readOnly = true) // 클래스 레벨 어노테이션 사용 시 기본적으로 모든 메서드에서 읽기 전용 트랜잭션 사용
public class MemberService {

    public MemberResponse findMember(Long id) {
        ...
    }

    @Transactional // 메서드 레벨 어노테이션이 있으면 클래스 레벨 어노테이션보다 우선 적용
    public MemberResponse createMember(MemberRequest request) {
        ...
    }
}
```

2021-01-18 16:37 UTC, shk3029 commented on src/main/java/nextstep/subway/advice/SubwayExceptionHandler.java
> +    }
아하 하나의 핸들러에 여러 개의 예외를 넣을 수 있군요!
`
 @ExceptionHandler(value = {SectionBadRequestException.class, MemberBadRequestException.class, FavoriteBadRequestException.class})
`
이렇게 하나로 처리하라는 뜻인가요?
상위 클래스로 묶는다는 뜻은 이 3개를 SubwayBadRequest로 묶어서 처리한다는 말씀이신가요?

2021-01-18 16:39 UTC, shk3029 commented on src/main/java/nextstep/subway/favorite/domain/Favorite.java
> +    public Favorite() {
오 네넵 JPA Entity 생성자 호출 시, 습관처럼 public 디폴트 생성자를 만들었는데 이부분도 앞으로 신경써보겠습니다
감사합니다!

2021-01-18 16:48 UTC, shk3029 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        return memberService.addFavorite(loginMember.getId(), request);
네 member에서 favorite을 관리하는 로직이 대부분이라 memberService에 구현했었습니다
설명을 듣고나니 FavoriteService에서는 대부분의 로직이 MemberService 비지니스 로직을 호출하게 되네요
Favorite 관련 로직을 FavoriteService로 이동하였습니다!
감사합니다!

2021-01-18 16:53 UTC, shk3029 commented on src/main/java/nextstep/subway/member/application/MemberService.java
> +@Transactional
오오 완전 꿀팁이네요!
서비스 클래스 자체에 @Transactional(readOnly = true) 로 걸어서 더티체킹을 방지한 후,
생성, 추가, 삭제와 같은 변경이 가능한 경우는 메소드 레벨에서 @Transactional로 제어하는거군요!
감사합니다!

2021-01-18 16:55 UTC, shk3029 commented on src/main/java/nextstep/subway/advice/SubwayExceptionHandler.java
> +    }
`
    @ExceptionHandler(value = {SectionBadRequestException.class, MemberBadRequestException.class, FavoriteBadRequestException.class})
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    ResponseEntity check(RuntimeException e) {
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
    }
`
이렇게 변경했습니다!

2021-01-19 10:13 UTC, hongsii approved these changes
피드백 반영을 깔끔하게 잘해주셨네요! 👍 
머지할게요. 다음 단계 진행해주세요~!

2021-01-19 10:13 UTC, hongsii commented on src/main/java/nextstep/subway/advice/SubwayExceptionHandler.java
> +    }
맞습니다! 지금은 3개밖에 없어서 괜찮지만, 예외가 계속 늘어난다면 하나의 핸들러에서 처리해야할 예외가 점점 많아집니다.
이러한 경우엔 말씀하신대로 상위 예외 클래스를 만들어서 해당 예외들에게 상속시켜 비대해진 핸들러를 축소할 수 있습니다.

2021-01-19 10:13 UTC, hongsii commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        member.removeFavorite(favorite);
여기도 합칠 수 있지 않을까요?

2021-01-19 10:13 UTC, merged

2021-01-19 11:37 UTC, shk3029 commented on src/main/java/nextstep/subway/advice/SubwayExceptionHandler.java
> +    }
아하 네넵~ 이해했습니다
감사합니다!

2021-01-19 11:40 UTC, shk3029 commented on src/main/java/nextstep/subway/favorite/application/FavoriteService.java
> +        member.removeFavorite(favorite);
엇 이부분도 합쳤었는데 커밋이 뒤로 밀렸었나봅니다!
    @Transactional
    public void deleteFavorite(LoginMember loginMember, Long id) {
        Member member = memberService.getMember(loginMember.getId());
        member.removeFavorite(getFavorite(id));
    }
이렇게 통합했었습니다!
꼼꼼하게 봐주셔서 감사합니다~!